### ISSUE TITLE
Can jsdom follow links ?

### ISSUE THREAD

**Issue by ericminio** [tmpvar/jsdom#1000]
Hi,

What is the config to tell jsdom to follow a link, execute the scripts of the new page and update the document content accordingly ?

Is there another way than doing a new jsdom.env by hand with the url of the link ?

Thx

**Comment by ericminio** [comment]
And, will you please point out the test that document how jsdom follow links if it exists ?

**Comment by domenic** [comment]
jsdom is more for single pages than for entire web browsing sessions. For the latter you may want to look into zombie.js, which is based on jsdom.

**Comment by ericminio** [comment]
Thank you for your quick answer
