### ISSUE TITLE
Byte-order-marks breaking browserify.

### ISSUE THREAD

**Issue by sterpe** [tmpvar/jsdom#1010]
There are extraneous byte-order marks at the beginning of lib/jsdom/browser/Window.js and lib/jsdom/browser/documentAdapter

Browserify's bom removal seems to catch the bom in documentAdapter but for some reason does not catch the bom in Window.js

https://github.com/substack/node-browserify/issues/1095

**Comment by domenic** [comment]
Fixed in 3.0.3.
