### ISSUE TITLE
isEqualNode crashes

### ISSUE THREAD

**Issue by jbblanchet** [tmpvar/jsdom#1015]
The following code crashes with `TypeError: Object [ undefined ] has no method 'item'` :

```javascript
var jsdom = require("jsdom");

jsdom.env({
    html: "<html><body><div class='test'></div><div class='test'></div></body></html>",
    scripts: ['http://code.jquery.com/jquery-2.1.3.min.js'],
    done:  function (err, window) {
        var $ = window.jQuery;
        var $elems = $(".test");
        console.log($elems[0].isEqualNode($elems[1]));
    }
});
```

I've tracked down the error to line 246 of jsdom\level3\core.js (mainly because my console says that the error happens on line 246 of that file! :bowtie:) where we access the properties of both node lists for comparison (onl and snl) using onl.item(i) instead of onl[i].

It seems like a rather simple problem to fix, but since this code has been there for 3 years, I find it surprising that I'm the first one to encounter the error, so I thought I'd ask to check if I was doing something wrong first.

**Comment by domenic** [comment]
I am pretty sure isEqualNode just does an === check and is either deprecated or already removed from specs. (I know Chrome is trying to remove it.) If it is here to stay then we should fix this bug but if not then we should just remove it from jsdom.

Good find, in any case.
________________________________

**Comment by jbblanchet** [comment]
You're think of isSameNode. From the W3 [doc](http://www.w3.org/TR/DOM-Level-3-Core/core.html#Node3-isEqualNode) about isEqualNode: "This method tests for equality of nodes, not sameness".

This is actually quite a useful method for unit testing, and is used by jasmine isEqual comparator when comparing nodes.

**Comment by domenic** [comment]
You're right that I am thinking of isSameNode. But let's not look at outdated specs. Here's the spec for isEqualNode: https://dom.spec.whatwg.org/#dom-node-isequalnode

(See Contributing.md for more information on specs.)

Anyway, good catch, will tag as a bug.

**Comment by jbblanchet** [comment]
Wow thanks! And here I was thinking this was a one line job! :stuck_out_tongue_winking_eye:
