### ISSUE TITLE
Browserify: fs.readFile is not a function (v 3.1.0)

### ISSUE THREAD

**Issue by davidebaldini** [tmpvar/jsdom#1018]
To support DOM in HTML5 web workers, I do:

`$ browserify -r /usr/local/lib/node_modules/jsdom/lib/jsdom.js:jsdom >jsdom_browserify.js`

In the HTML page:
```javascript
<script src='/src/lib/jsdom_browserify.js'></script>
<script>
    jsdom = require('jsdom');
    jsdom.env( ... );
</script>
```

On the browser (Iceweasel 31) console I get:
`TypeError: fs.readFile is not a function jsdom_browserify.js:49261`

jsdom version: 3.1.0

I read a `Domenic`'s post from [here] (https://github.com/tmpvar/jsdom/issues/245#issuecomment-58647477) dated Oct 10, 2014 stating "jsdom works in the browser with browserify now".

I guess he refers to jsdom version 1.0.1 or 1.0.2, released during that time.
Am I correct? Do newer jsdom releases work with browserify? Would an older version work on browsers?

**Comment by domenic** [comment]
To browserify jsdom, you need to have another project that does `require("jsdom")` and then browserify that. If you do that, it will properly respect [the `package.json` `"browser"` directives](https://github.com/tmpvar/jsdom/blob/fbcdc3a39e01bd65425c9cb862cfd7a332cd1328/package.json#L84-L88). Manually using the browserify CLI on a specific file inside jsdom will not work.

**Comment by davidebaldini** [comment]
Thank you domenic for clarification.
I encapsulated jsdom into a wrapper: (`jsdom_capsule.js`)

```javascript
(function () {

    var jsdom = require('jsdom');
    module.exports = jsdom;

}());
```

Then:
`browserify -r ./jsdom_capsule/lib/jsdom_capsule:jsdom_capsule >jsdom_browserify.js`

and in the HTML page:
```javascript
<script src='/src/lib/jsdom_browserify.js'></script>
<script>
    jsdomCapsule = require('jsdom_capsule');
    jsdomCapsule.env( ... );
</script>
```

But the browser's error console still yields:
`TypeError: fs.readFile is not a function      jsdom_browserify.js:122`

**Comment by domenic** [comment]
It's possible we've introduced a regression recently, but it seems unlikely, given how we are running tests on the browserified code every build. I'll try to look into this more. I assume you're using the latest version of browserify?

**Comment by davidebaldini** [comment]
Latest version, browserify 8.1.3.

The line referred to by my browser's error console is [pastebin here] (http://pastebin.mozilla.org/8567408) (highlighted).

**Comment by davidebaldini** [comment]
I stripped down the HTML part to the minimal, to no avail:

```javascript
<script src='/src/lib/jsdom_browserify.js'></script>
<script>
    jsdomCapsule = require('jsdom_capsule');
    jsdomCapsule.env(
        '<div></div>',
        function (errors, window) {
            console.log('message');
        }
    );
</script>
```
Produces: "*TypeError: fs.readFile is not a function*"
Maybe this is browserify not defining the function?

**Comment by davidebaldini** [comment]
This is not a regression.
I browserified and tested all the following versions of jsdom:
* 3.1.0
* 1.2.1
* 1.1.0
* 1.0.3

All them present the same exact error on browser's console: "*TypeError: fs.readFile is not a function*".
Browserify version 8.1.3 for all tests above.

### Test method:
The test method is the same as for my previous posts:
1) **jsdom_capsule.js:**
```javascript
(function () {

    var jsdom = require('jsdom');
    module.exports = jsdom;

}());
```

2) **Browserify:**
```
browserify -r ./jsdom_capsule/lib/jsdom_capsule:jsdom_capsule >jsdom_browserify.js
cp jsdom_browserify.js ${web}/src/lib/jsdom_browserify.js
```

3) **HTML code loaded on browser:**
```javascript
<script src='/src/lib/jsdom_browserify.js'></script>
<script>
    jsdomCapsule = require('jsdom_capsule');
    jsdomCapsule.env(
        '<div></div>',
        function (errors, window) {
            console.log('message');
        }
    );
</script>
```
No errors nor any stdout printed by `./browserify`.

**Comment by Sebmaster** [comment]
Ahh, looks like in our CI runs we include [browser-fs.js](https://github.com/tmpvar/jsdom/blob/master/test/browser-fs.js), which is why it works in our tests.

Can you try your html with:
```html
<script src='/src/lib/jsdom_browserify.js'></script>
<script>
    jsdomCapsule = require('jsdom_capsule');
    jsdomCapsule.env({
        html:  '<div></div>',
        done: function (errors, window) {
            console.log('message');
        }
    });
</script>
```

**Comment by davidebaldini** [comment]
Wow, thank you @Sebmaster, that works.
Your snippet also works w/o the need of `jsdom_capsule.js` wrapper; I can browserify and `<script src=` jsdom naked alone.

**Comment by domenic** [comment]
@Sebmaster we should probably add `"fs": "...browser-fs.js"` to package.json, don't you think?

**Comment by Sebmaster** [comment]
@domenic Not too sure about the automatic XHRs, but it's probably for the best.
