### ISSUE TITLE
How to get the http response status code?

### ISSUE THREAD

**Issue by rbabayoff** [tmpvar/jsdom#1021]
Thanks

**Comment by domenic** [comment]
I think you filed this on the wrong repo. This question has nothing to do with jsdom as far as I can tell.

**Comment by rbabayoff** [comment]
@domenic no I didn't. I'm using it to scrap data, and I'd like to know if I got a 3xx, 4xx or 5xx response. Rigth now, if I get a 500 response (server error), it doesn't fail, and jsdom parses it normally. I used phantomjs until now, and in onResourceReceived, I can see the http response code of my request. I would like to be able to do the same with jsdom. I can work on a PR that does that - create a new http response callback (using the info I get from the request package). and also provide an http error for done. There is no reason to parse the document if I got a 4XX or 5XX response, unless maybe if the user asked for it in config. What say you?

**Comment by Sebmaster** [comment]
You could probably get the response code by implementing a resourceLoader (which was added in #1008) yourself, since you can access the response object before it's processed by jsdom.

**Comment by domenic** [comment]
I think there's plenty of reason to process 4xx or 5xx responses. They still have DOMs!

If you want to filter certain responses, you'd be best off just doing the HTTP request yourself, checking any preconditions, and then if they are met you can feed them to `jsdom.jsdom`.

**Comment by rbabayoff** [comment]
The reason why I want to do it with jsdom, is that with jsdom, I can control what gets loaded (css, scripts, images, etc.), and @domenic, you are right, they still have DOMs, so the user can decide if he wants to process it or not. Let me know what you think and if I should work on a PR. Also, unrelated FYI, I packaged this for meteor, would you like me to create a PR for it, including updates to the README, and meteor tests in travis?

**Comment by domenic** [comment]
I don't think there's any PR needed. You can just write in your app code to use `request` to request the code, then check any preconditions, then pass to `jsdom.jsdom`.

On meteor, no, sorry, we don't support alternate package managers, whether they be bower or meteor. You're welcome to maintain a fork for that.

**Comment by rbabayoff** [comment]
ok, thanks
