### ISSUE TITLE
Contextify is breaking jsdom on node v0.12.0 and io v1.1.0

### ISSUE THREAD

**Issue by TheAlphaNerd** [tmpvar/jsdom#1022]
Appears to be the nan needs to be upgraded.  There is already a PR in the queue.

https://github.com/brianmcd/contextify/pull/154

**Comment by domenic** [comment]
Yes, this is a bug with contextify, not with jsdom.

**Comment by TheAlphaNerd** [comment]
Posted here as the module cannot be installed currently on 0.12 or io.

Breaks any stack relying on it. Indeed the problem exists with contextify,
but I would argue that jsdom is broken as long as this dep causes the stack
to explode
