### ISSUE TITLE
Error thrown in NodeJs 0.12.0

### ISSUE THREAD

**Issue by rgeraldporter** [tmpvar/jsdom#1024]
node_modules/requestify/node_modules/jquery/node_modules/jsdom/lib/jsdom/level1/core.js:418
    set nodeName() { throw new core.DOMException();},
                 ^
    SyntaxError: Unexpected token )

I got this error from using Requestify, which requires jQuery, which requires jsdom, after upgrading to NodeJS 0.12.0 - released a few days ago. I'm rolling back now to v0.10.36 but just thought you should have a heads up!

**Comment by domenic** [comment]
You appear to be using an old version of jquery (newer versions don't depend on jsdom) which depends on an old version of jsdom; this issue has since been fixed.

**Comment by avilaton** [comment]
But what causes the issue?

**Comment by KenanY** [comment]
@avilaton https://github.com/tmpvar/jsdom/pull/615?
