### ISSUE TITLE
submit event does not firing

### ISSUE THREAD

**Issue by wtfil** [tmpvar/jsdom#1026]
Hi!

I am trying to use `jsdom` for running client-side tests. Everything seems alright, but I found than events does not working as expected (not like in browsers)

`form` does not triggering the `submit` event when  the `click` event on `button` occurred.

```html
<form action="">
	<button type="submit"></button>
</form>
```
I've created small repo to reproduce it
https://github.com/wtfil/jsdom-submit-bug

**Comment by domenic** [comment]
@Joris-van-der-Wel thoughts? Not sure this fell under the purview of your changes but seems like you know the code pretty well by now :)

**Comment by Joris-van-der-Wel** [comment]
haha ;)

The test uses  `<button type="submit">`, however the type attribute for `<button>` is not implemented in jsdom.
A `<input type="submit">` should work however.

Implementing both `<button type="submit">` and `<button type="reset">` should not be that hard, submitting and resetting is already implemented.

**Comment by wtfil** [comment]
Thx for replay:)
I've checked `input[type=submit]` and it works pretty well!
These is not difference between `button` and `input` in my app, so I can easily switch to `input`. But I think, it would be nice to not depend on test environment :)

**Comment by domenic** [comment]
Agreed! Glad to hear this should be a pretty easy fix. Maybe I can do it soon. (And yet, whenever I say that, it never seems to happen :-/)

**Comment by marcandre** [comment]
I think this can be closed, as latest release seem to work fine.
