### ISSUE TITLE
Expired cookie is still present in document.cookie

### ISSUE THREAD

**Issue by rmurphey** [tmpvar/jsdom#1027]
jsdom version: 3.1.1

I ran into a bug that is alluded to in #310 and referenced in ScottHamper/Cookies#37 and jmeas/backbone.simple-auth#1: A cookie set with an expiration date in the past -- as [recommended on MDN](https://developer.mozilla.org/en-US/docs/Web/API/document.cookie#Removing_a_cookie) as the way to delete a cookie -- is still present in `document.cookie` inside jsdom. 

jsdom test case:

```js
var jsdom = require('jsdom');

jsdom.env('<p>expired cookie bug</p>', function (err, window) {
  var doc = window.document;

  function create(name, value, days) {
    var date = new Date();
    date.setTime(date.getTime() + (days * 24 * 60 * 60 * 1000));
    var expires = days ? ';expires=' + date.toGMTString() : '';

    var c = name + '=' +
      encodeURIComponent(value) +
      expires +
      ';path=/';

    doc.cookie = c;
  }

  // set a cookie that expires in 10 days
  create('testcookie1', '1', 10);
  console.log('unexpired cookie is present', !!doc.cookie.match('testcookie1=1'));

  // set a cookie that has already expired
  create('testcookie2', '', -1);
  console.log('expired cookie is present', !!doc.cookie.match('testcookie2'));
});
```

This results in the following output:

```
unexpired cookie is present true
expired cookie is present true
```

Here is a browser test case:

```js
var doc = window.document;

function create(name, value, days) {
  var date = new Date();
  date.setTime(date.getTime() + (days * 24 * 60 * 60 * 1000));
  var expires = days ? ';expires=' + date.toGMTString() : '';

  var c = name + '=' +
    encodeURIComponent(value) +
    expires +
    ';path=/';

  doc.cookie = c;
}

// set a cookie that expires in 10 days
create('testcookie1', '1', 10);
console.log('unexpired cookie is present', !!doc.cookie.match('testcookie1=1'));

// set a cookie that has already expired
create('testcookie2', '', -1);
console.log('expired cookie is present', !!doc.cookie.match('testcookie2'));
```

The output is as expected:

```
unexpired cookie is present true
expired cookie is present false
```

**Comment by inikulin** [comment]
Seems like jsdom's cookies mechanism doesn't meet [RFC 6265](http://tools.ietf.org/html/rfc6265). Maybe we should adopt https://github.com/goinstant/tough-cookie? I can take care of it somewhere around next week. /cc  @domenic @Sebmaster

**Comment by Sebmaster** [comment]
I had a look at though-cookie once already, but as far as I remember there was something else missing or not compliant, however I currently can't remember exactly what it was.

I'll take another look.

**Comment by inikulin** [comment]
We use it currently heavily in production and haven't encountered any problems on Alexa top 500 websites.

**Comment by inikulin** [comment]
I found test suite for the HTTP-state: https://github.com/abarth/http-state/tree/master/tests I'll try to run it against tough-cookie on weekend. If we will have something missing/broken I can take care of PR/fork.

**Comment by domenic** [comment]
Would love to farm out cookie handling to another module. Happy to take anyone's patches that does that :). Either that or we can keep patching our current implementation.

Also worth checking out: https://github.com/assaf/zombie/blob/master/src/cookies.js

**Comment by domenic** [comment]
Oh and feel free to create the module under github.com/jsdom, I can add you to it as a collaborator if you want. (You don't have to though.)

**Comment by inikulin** [comment]
@domenic I hope will be able to end up with the tough-cookie, without dealing with new module.
Here is the plan:
* [ ] Run IETF's http state tests against tough-cookie to figure out it's spec compliance state
* [ ] Fix falling tests (if we will have one)
* [ ] Issue the PR to the tough-cookie repo
* [ ] Delegate cookies handling to tough-cookie in jsdom. Move cookies getters/setters to the living/document.js(?). Optionally it would be nice to refactor resource loader into the separate module (browser/resource_loader.js)
* [ ] *Optionally:* If at that moment we will not have our PR to the tough-cookie merged we can consider to go with our own fork at jsdom org.

I hope I will be able to start tomorrow, I need to rollout pending updates to parse5 first.

**Comment by domenic** [comment]
Sounds like a lovely plan <3.

**Comment by inikulin** [comment]
Ooook, we have [71 failing tests](https://travis-ci.org/inikulin/tough-cookie/jobs/52413403) from the IETF's suite at the moment. Moreover IETF data [is a little bit obsolete](https://github.com/abarth/http-state/issues/10). I'll issue them a PR with the update tool once I finish fixing current failing tests. Seems like It will be a looong road :hammer:

**Comment by inikulin** [comment]
I've fixed all issues in tough cookie and issued them a PR (goinstant/tough-cookie#30). Now we can move to the jsdom part.

**Comment by inikulin** [comment]
@domenic I have a question. My first intention was to move `document.cookie` to Document interface to the `living/document.js`. Surpisingly, I haven't found `cookie` into the Document interface of the [Living  Standard](https://html.spec.whatwg.org/multipage/dom.html). According to the Living standard goals:
> This specification standardizes the DOM. It does so as follows: 
By consolidating DOM Level 3 Core [DOM3CORE], Element Traversal [ELEMENTTRAVERSAL], -  Selectors API Level 2 [SELECTORSAPI], the "DOM Event Architecture" and "Basic Event Interfaces" chapters of DOM Level 3 Events [DOM3EVENTS] (specific type of events do not belong in the base specification), and DOM Level 2 Traversal and Range [DOM2TR]

Meanwhile, `document.cookie` declared in the Document Object Model Level 2 HTML, therefore at the moment `cookie` is not a part of the Living Standard. 
So, should I keep `document.cookie` in `level2/html.js` to conform current specs state?

**Comment by domenic** [comment]
@inikulin cooke is in the HTML Standard now, which supplements the DOM Standard. We don't have a clear division between HTML and DOM in living/, and I'm not sure we want or need one. So living/document.js is fine, or maybe living-html/document.js

**Comment by inikulin** [comment]
Thank you fo the clarification, found them in the HTML Standard.

**Comment by rmurphey** [comment]
Thanks everyone!
