### ISSUE TITLE
Provide an official lightweight jsdom (without contextify)

### ISSUE THREAD

**Issue by jbe456** [tmpvar/jsdom#1035]
Sorry if this has already been treated (couldn't find anything from github search).

I need to use the jsdom.env feature but in my use cases, I don't need all jsdom features and in particular it works fine even if I remove the dependency of contextify (which on Windows require a few tricks to be installed, and I want to avoid that for anyone using my project).

If you look at the stat from nodejs about jsdom-nogyp (https://www.npmjs.com/package/jsdom-nogyp) there are still ~7000 downloads a month for this module, although the project hasn't been updated since 2 years (https://github.com/dexteryy/jsdom-nogyp). It seems like I'm not the only one looking for it (I agree though it represents 2.3% compared to jsdom node monthly download).

Has it been already considered/Could you consider to create and maintain an official lightweight version of jsdom with less features and without the Contextify dependency ?

**Comment by domenic** [comment]
The portion of the test suite that passes without contextify is extremely low. So, no, that isn't really something we're interested in maintaining.

However, as per #995, we'll be shipping a jsdom 4.0.0 soon (PR at #1001) which will be io.js-only and will not require Contextify. So, maybe that's your answer.
