### ISSUE TITLE
Font style shorthand doesn't get set

### ISSUE THREAD

**Issue by mprudhom** [tmpvar/jsdom#1042]
Try calling `style.setProperty("font", "12em monospace", null)` and observe that the style doesn't get set in the DOM. This is due to the shorthand parsing error at: https://github.com/chad3814/CSSStyleDeclaration/pull/25

There probably isn't much you can do about it without an upstream fix, but this issue will at least identify that the shortcoming exists.

**Comment by Sebmaster** [comment]
Since upstream is fixed, closed.
