### ISSUE TITLE
Document not initialized properly?

### ISSUE THREAD

**Issue by Sebmaster** [tmpvar/jsdom#1043]
https://github.com/tmpvar/jsdom/blob/2390f917749608deda0b5dabff959659eaf7e1c9/lib/jsdom/level1/core.js#L1498

Looks fishy. Node expects an ownerDocument and gets passed a string?

(Just noting that here, have not dug into it yet.)

**Comment by domenic** [comment]
Agreed, surprised this doesn't break everything horribly. I guess people don't look at `document.ownerDocument` very often (or anything related to it).
