### ISSUE TITLE
Use of const in strict mode

### ISSUE THREAD

**Issue by guyellis** [tmpvar/jsdom#1044]
Added comment to line causing this: https://github.com/tmpvar/jsdom/commit/6b0ec154eec87baeaa9629ac51e9b57b1ed4c84a

**Comment by domenic** [comment]
From the readme:

> Note that as of our 4.0.0 release, jsdom no longer works with Node.js™, and instead requires io.js. You are still welcome to install a release in the 3.x series if you are stuck on legacy technology like Node.js™.
