### ISSUE TITLE
Custom html tags  '_ownerDocument' of undefined

### ISSUE THREAD

**Issue by GianlucaGuarini** [tmpvar/jsdom#1045]
I got this issue by using a custom html tag:
```javascript
jsdom.env('<!doctype html><html><head></head><body><' + myComponent +'/></body></html>', function (errors, window) {
  global.document = window.document
  console.log(document.body.innerHTML) // <my-component></my-component>
})
```
```shell
/Users/gianlucaguarini/Sites/www/riotjs/node_modules/jsdom/lib/jsdom/level1/core.js:579
    if (!newChild._ownerDocument) newChild._ownerDocument = this._ownerDocumen
                 ^
TypeError: Cannot read property '_ownerDocument' of undefined
    at core.Node.insertBefore (/Users/gianlucaguarini/Sites/www/riotjs/node_modules/jsdom/lib/jsdom/level1/core.js:579:18)
    at core.Node.insertBefore (/Users/gianlucaguarini/Sites/www/riotjs/node_modules/jsdom/lib/jsdom/level2/events.js:326:32)
```

**Comment by Sebmaster** [comment]
@GianlucaGuarini Unrelated: There are no custom self-closing tags in HTML5, your document seems to be formatted improperly.

Also I can't reproduce, which version of node/iojs + jsdom are you using?

**Comment by GianlucaGuarini** [comment]
The issue appears on the performance tests of riotjs https://github.com/muut/riotjs/blob/master/test/performance/mem.js I am using node 0.12.0 with harmony flag enabled

**Comment by domenic** [comment]
Node 0.12.0 is not supported, *especially* not with the --harmony flag enabled. Only io.js is supported by jsdom.

**Comment by GianlucaGuarini** [comment]
I have tested iojs v1.0.2 as well and I got the same issue

**Comment by domenic** [comment]
OK. Can you produce a complete example file, I can run on my own computer, without any external dependencies, that reproduces this problem in io.js 1.4.1 and jsdom 4.0.1?

**Comment by domenic** [comment]
For example the OP does not contain a full example file since `myComponent` is an undefined variable (and you need `var jsdom = require("jsdom")`).

**Comment by GianlucaGuarini** [comment]
You can try it by yourself
```shell
$ git clone https://github.com/muut/riotjs.git
$ cd riotjs 
$ npm install && make perf
```

**Comment by domenic** [comment]
The point of producing an isolated example is to demonstrate that the bug lies in jsdom, not in third-party software like riotjs. If the bug cannot be reproduced without riotjs, it is a bug in riotjs, whereas if it can be reproduced using only jsdom, then that shows that it is a bug in jsdom. Right now it could be either.

**Comment by GianlucaGuarini** [comment]
You are right, the issue seems to be strictly related to riotjs. I am going to close this bug for now. It needs further investigation
