### ISSUE TITLE
incompatibility with Node.js as of version 4x

### ISSUE THREAD

**Issue by kris-o3** [tmpvar/jsdom#1047]
`Note that as of our 4.0.0 release, jsdom no longer works with Node.js™, and instead requires io.js. You are still welcome to install a release in the 3.x series if you are stuck on legacy technology like Node.js™.`

To be perfectly frank, to release this version in the wild, and to publish it on *npmjs.com* - the de facto source of information about community-contributed packages for Node - is grossly irresponsible in light of the incompatibility with Node.js

Those of us who use *Gulp* as a build system, and thus, rely on Node modules, which may in turn, rely on other Node modules, **including this one**, are now faced with a fatal error upon running `npm install` and attempting to use *Gulp*.

**Comment by domenic** [comment]
They are welcome to use the 3.x series.

**Comment by kris-o3** [comment]
how to easily *do* that isn't exactly obvious...  in my case, it was *gulp-packer* that was dependent upon it and now giving a fatal error.

adding:

`"jsdom": "3.1.2"`

to `devDependencies` in the same `package.json` used by Gulp does resolve this issue.

**Comment by Sebmaster** [comment]
That's a bug in the `packer` module for not using semver dependency specification for jsdom.

**Comment by tjwebb** [comment]
@kris-o3 Everyone is switching to https://github.com/cheeriojs/cheerio since @domenic is deciding to be obstinate about this.

**Comment by kris-o3** [comment]
@tjwebb ANOTHER fork of Node, based on jQuery?! just what we needed.

**Comment by kris-o3** [comment]
re: "a bug in the `packer` module"

from:
https://www.npmjs.com/package/jsdom 

**Dependents:**
`webjspell_http, io, ember-prerender, svg2path, blo, node-jquery, truffler, newman, launchjs, dhs, opengrapher, grunt-redo-ctc, blog-scraper, jui, inliner3, cloudvisio, fetch-image, linkedin-scraper, gulp-slang, grunt-jsdom-jquery, and 584 more.`

**Comment by Sebmaster** [comment]
@kris-o3 Went to the jsdom npm page just now, clicked the first dependant, which was sdom, going into it's [package.json](https://github.com/zaucy/node-sdom/blob/master/package.json) reveals: `"jsdom": "^1.0.0-pre.6"` => won't break because it won't get 4.0.0.

Packer's [package.json](https://github.com/evanw/packer/blob/master/package.json#L9) reveals `"jsdom": ">= 0.1.23"` => breaks because it gets jsdom v4.0.0.

That's why we have semver, exactly to avoid this kind of breakage.

**Comment by kris-o3** [comment]
okay -- how many of the other dependents were not this careful?

**Comment by tjwebb** [comment]
> @tjwebb ANOTHER fork of Node, based on jQuery?! just what we needed.

@kris-o3 nah it's just a replacement for jsdom.

**Comment by kris-o3** [comment]
ah, got it (read further in the README, which i should have done to begin with)...

980+ dependents. well that's certainly excellent.

**Comment by domenic** [comment]
In general I'm sure most of those dependents that relied on 0.1.x behavior were broken by the major changes from 0.x to 1.x... if not those then the major changes from 1.x to 2.x... if not _those_ then the major changes from 2.x to 3.x... I guess we could be seeing a tiny tail of dependents who are (a) not using semver version specifiers; and (b) were only broken by the 3.x to 4.x change, but not by any of the previous ones. But just like we didn't stick to 0.x API and instead forged forward with 1.x API, we're similarly going to keep going in the 4.x series, and eventually the 5.x series (probably as a result of #1039), and so on.

**Comment by kris-o3** [comment]
a helpful hint following your quite-severe advisory message to advice adding:

`"jsdom": "3.1.2"`

to package.json at the root level of a Gulp build configuration, or similar, would be surely more helpful than the advisory alone. strongly recommend doing this lest more suffer the time i wasted, needlessly.

**Comment by domenic** [comment]
That won't work, in general. If it did in your case, then that's an accident of your current run of npm. The only fix will be to change the package that's using invalid version specifiers, to stop doing that :-/.

**Comment by kris-o3** [comment]
"my current run of npm" -- oh, you mean `npm install` and Gulp?

**Comment by domenic** [comment]
Yeah, next `npm install` might produce different results. Or if you change your package.json (or if any of your dependencies does).

**Comment by kris-o3** [comment]
i've rm -rf'd node_modules and npm install'd at least a dozen times since i discovered this workaround with the same beneficial result each time.

**Comment by domenic** [comment]
Well, I hope it keeps working then! It's not guaranteed though, especially if any of your dependencies change. Maybe if you did an npm shrinkwrap or checked in your results into node_modules you'll be safe!

**Comment by kris-o3** [comment]
a fellow developer also just did the same and achieved this same, consistent result.

**Comment by krisgale** [comment]
hey @domenic creating a new gulpfile for a project today... noticed the warning/disclaimer at the top of the page on npmjs.org -- i'm sure i'm not the only person who appreciates this heads-up.
