### ISSUE TITLE
Virtual console at startup

### ISSUE THREAD

**Issue by domenic** [tmpvar/jsdom#1049]
Per the confusion in https://github.com/tmpvar/jsdom/pull/991#issuecomment-76561496, we should probably add some kind of option that allows setting up a virtual console at startup time. Not sure exactly what it would look like.

Alternately we could delay firing the console events for a tick?

**Comment by jeffcarp** [comment]
Instead of receiving a `virtualConsole`, could you build one yourself and pass it in as a config option?

```javascript
var myConsole = new (require('events').EventEmitter)();

myConsole.on("log", function (message) {
  console.log(message);
});

jsdom.env({
  virtualConsole: myConsole
}};
```

On a different note, would it be useful to skip a layer of abstraction and let you just pipe output to a writable stream?

```javascript
jsdom.env({
  sendOutputTo: process.stdout
}};
```

**Comment by domenic** [comment]
> Instead of receiving a virtualConsole, could you build one yourself and pass it in as a config option?

I think that was what I was envisioning in the OP, actually.

> On a different note, would it be useful to skip a layer of abstraction and let you pipe output to a writable stream?

Not really. The events are pretty important, especially given the upcoming #1039. And it's an easy enough adapter to write. I think it'd just be more code to support that kind of thing.

**Comment by domenic** [comment]
> var myConsole = new (require('events').EventEmitter)();

Although this isn't great; we'd want `jsdom.createVirtualConsole()` probably.
