### ISSUE TITLE
eventListener errors get swallowed

### ISSUE THREAD

**Issue by lovebear** [tmpvar/jsdom#1051]
The line I'm referring to is https://github.com/tmpvar/jsdom/blob/master/lib/jsdom/level2/events.js#L201

```javascript
var el = document.getElementById("test");
el.addEventListener("click", function(){
    console.log('clicked');
    throw('this gets caught, but i want to throw...');
    console.log('and this silently never gets run..');
}, false);


var e = document.createEvent('Event');
e.initEvent('click', true, true);
el.dispatchEvent(e);
```

**Comment by lovebear** [comment]
I should explain a bit further, when writing tests in node, it caused me a bit of confusion...

I would have `assert(...)` but that would get swallowed.But really what I want to do is have the test fail.

Also since it is an error but it gets caught, all resulting code stops which may make in a nightmare to actually rethrow on top of looking up document.error for these particular tests.

Maybe there should be an option to tell jsdom not to catch what I consider node errors, or just disable it for a particular event all together?

**Comment by domenic** [comment]
Yeah, right now there's this kind of strange process where things get put into `document.errors`.

The eventual plan here is that errors thrown by scripts in the page go to `window.onerror`. When that happens, you'll be be able to add a listener to `window.onerror` and forward those to your Node process. How does that sound?

**Comment by lovebear** [comment]
Sounds good
