### ISSUE TITLE
how to handle a singlepage app / waitingFor ajax content

### ISSUE THREAD

**Issue by SerkanSipahi** [tmpvar/jsdom#1057]
I know this( see below ) doesnt work but how can i handle a ajax content that will be loaded few second after the "done" callback?
```js

var jsdom = require("jsdom");

jsdom.env({
    url: "https://www.cu-camper.com/de/#YVR-01.06.2015-20.06.2015-2",
    scripts: ["http://code.jquery.com/jquery.js"],
    done: function (errors, window) {
        var $ = window.$;
        var timer = setInterval(function(){
            if($(".searchwrapper").length){
                $(".searchwrapper").each(function() {
                    console.log($(this).html());
                });
                clearInterval(timer);
            }    
        }, 1000);
    }
});
```

**Comment by domenic** [comment]
Why doesn't that code work? It seems like it should.

Does the content fire an events when it loads, that you could listen to?

**Comment by SerkanSipahi** [comment]
No, its doesnt work as i expect. 

``` <div class="searchwrapper"></div> ``` this is created dynamically. Also after the DOM is ready. How can i access this or waitFor selectors? my approach doesnt work because the "done callback" is called only once.

**Comment by domenic** [comment]
Well, how would you do so on a normal web page? jsdom doesn't give any new abilities (like "wait for selectors") that browsers don't have.

**Comment by SerkanSipahi** [comment]
i can do something like that but that doesnt work with jsdom:

```js
        var waitFor = setInterval(function(){
            if($(".searchwrapper").length){
                $(".searchwrapper").each(function() {
                    console.log($(this).html());
                });
                clearInterval(waitFor);
            }    
        }, 1000);
```


Browser doesnt have "wait for". I know that ! My question is, how do you handle ajax content or something like that some time later created(DOM)? Do you know what my problem is?

**Comment by domenic** [comment]
I do understand the problem, and was just trying to make sure you understood that jsdom doesn't do anything more than what browsers do :).

One thing I noticed from your OP is that you are not running with external scripts enabled, so it is unlikely the page is able to actually do any AJAX. You could try turning that on? See https://github.com/tmpvar/jsdom#flexibility

**Comment by SerkanSipahi** [comment]
##### response from server
```html
<body data-json="{..., ..., ..., ..., ..., ...., }">

</bod>
```

##### after domready( 1-2 sec. later ) i build with the json-data:

<body data-json="{..., ..., ..., ..., ..., ...., }">
      <div class="searchwrapper"></div>
      <div class="searchwrapper"></div>
      <div class="searchwrapper"></div>
      <div class="searchwrapper"></div>
</bod>

I dont use ajax ! i build after dom-ready dynamically html and append it on any/some dom node. I believe https://github.com/tmpvar/jsdom#flexibility is not what i want :(

**Comment by domenic** [comment]
OK. But it still uses JavaScript to move the data from `data-json` to the body, right? Without the options from that section turned on, jsdom will not execute the JavaScript. (Because https://github.com/tmpvar/jsdom#on-running-scripts-and-being-safe )

**Comment by SerkanSipahi** [comment]
Yes it use Javascript to move data from ```data-json```to body.

**Comment by SerkanSipahi** [comment]
i thought jsdom is like phantomjs but isnt so. I think its good for building/creating mock-nodes for testing any applications. Or is it a misunderstanding?!?

**Comment by domenic** [comment]
It isn't like PhantomJS, indeed, in that it isn't an actual instance of a very old version of Safari running in another process that you pipe messages to. Instead it's a new implementation of the relevant APIs, in JavaScript itself. I think it's pretty useful for testing, crawling, and anything else that needs a DOM. But it does need to be configured carefully.

**Comment by SerkanSipahi** [comment]
@domenic thanks for your information :)
