### ISSUE TITLE
error: "Set is not defined" when running example from README.md (v4.0.5)

### ISSUE THREAD

**Issue by jhudson8** [tmpvar/jsdom#1071]
It seems there is no reference for ```Set``` in /level2/html.js
https://github.com/tmpvar/jsdom/blob/master/lib/jsdom/level2/html.js#L405

I hit this error when running the example from the README.md
```
var jsdom = require("jsdom");
jsdom.env(
  '<p><a class="the-link" href="https://github.com/tmpvar/jsdom">jsdom!</a></p>',
  ["http://code.jquery.com/jquery.js"],
  function (errors, window) {
    console.log("contents of a.the-link:", window.$("a.the-link").text());
  }
);
```

Am I missing something stupid?  Thanks.

**Comment by domenic** [comment]
From the readme:

> Note that as of our 4.0.0 release, jsdom no longer works with Node.js™, and instead requires io.js. You are still welcome to install a release in the 3.x series if you use Node.js™.

**Comment by jhudson8** [comment]
doh!  sorry to have wasted your time
