### ISSUE TITLE
Can't get event bubbling with constructors other than Event

### ISSUE THREAD

**Issue by Rich-Harris** [tmpvar/jsdom#1077]
I believe this is related to https://github.com/tmpvar/jsdom/pull/1073 - it looks like there's no support for the `initEvent` parameter with constructors other than `Event`:

```js
// in a browser (tested in recent Chrome and FF)
e = new Event( 'click', { bubbles: true });
e.bubbles; // true

e = new MouseEvent( 'click', { bubbles: true });
e.bubbles; // true

// in jsdom
e = new Event( 'click', { bubbles: true });
e.bubbles; // true

e = new MouseEvent( 'click', { bubbles: true });
e.bubbles; // false!!!
```

The same goes for other event constructors. WebIDL makes my eyes glaze over but am I right in thinking that all event constructors should accept an `eventInit` dictionary? Can try and put a PR together if that's helpful. Thanks

**Comment by domenic** [comment]
Yeah, agreed this is missing. Should be a pretty simple fix to the "super() call" in each event constructor. PR welcome, with tests of course :)
