### ISSUE TITLE
'Secondary' events not firing

### ISSUE THREAD

**Issue by Rich-Harris** [tmpvar/jsdom#1079]
Apologies if a similar issue has been raised before, I couldn't find one.

In browsers, some user interactions result in multiple events (e.g. clicking in an input field triggers a `click` event and a `focus` event, whereas clicking on a checkbox triggers a `click` and a `change`). Some of those secondary events are automatically triggered by programmatic events, and some aren't (a programmatic `click` in a text input doesn't result in a `focus` event, but the same event on a checkbox *does* result in a `change`.)

I've no idea if there's a spec governing which secondary events are supposed to follow programmatic events (or if there's a better name for them than 'secondary events'), but either way jsdom's behaviour differs from browsers:

```js
document.body.innerHTML = '<input type="checkbox">';
var input = document.querySelector( 'input' );

input.addEventListener( 'change', function () {
  console.log( 'changed!' );
});

console.log( 'before input.click():', input.checked );

input.click();
console.log( 'after input.click():', input.checked );

var event = newMouseEvent( 'click' );
input.dispatchEvent( event );
console.log( 'after input.dispatchEvent():', input.checked );
```

In browsers, this results in

* before input.click(): false
* changed!
* after input.click(): true
* changed!
* after input.dispatchEvent(): false

In jsdom, we get this result:

* before input.click(): false
* after input.click(): true
* after input.dispatchEvent: true

This seems like it might be a massive headache to implement in a way that's consistent with browser behaviour, so if it's out of scope I understand. Would be glad to try and contribute though I'm not entirely sure where one would start.

**Comment by domenic** [comment]
Definitely in scope. I imagine this is in the HTML Standard...

Probably easiest to figure out by finding places we currently dispatch events on form controls... I can't imagine we *entirely* forget to do so.

**Comment by yaycmyk** [comment]
Currently seeing this with a radio input I'm playing with. Using `.click()` on it doesn't seem to trigger the normal cascade that ends in `.checked` becoming true and then the eventual `change` event.

**Comment by yaycmyk** [comment]
Also, the behavior of clicking a `<label>` element with `for` attribute does not trigger a delegated click to the appropriate `<input>` element with a corresponding `id`

**Comment by domenic** [comment]
Would love small minimal test cases written with code that show the behavior difference between browsers and jsdom. E.g. link to a jsbin which console.log's "true" in browsers and "false" when put in a jsdom.

**Comment by yaycmyk** [comment]
here's a native browser one for the `<label>` example: https://jsbin.com/siloyojaga/edit?html,output

**Comment by domenic** [comment]
Thanks, but that actually isn't a code example, it's a manual test. Can you produce a similar example using .click() or dispatchEvent("click", ...)?

**Comment by yaycmyk** [comment]
Quite right, here's a programmatic version: https://jsbin.com/qopepamucu/1/edit?html,output

**Comment by domenic** [comment]
Heh. Still not quite what I was looking for, but got me on the right path: https://jsbin.com/qopepamucu/1/edit?html,console,output

I'll see if we can get that one fixed in jsdom at least. This weekend perhaps!

**Comment by yaycmyk** [comment]
And I don't know how to get jsdom working in the browser, but here's something I whipped up in the REPL:

```js
var dom = require('jsdom').jsdom;
var doc = dom('<html><body><input id="foo" name="bar" value="baz" /><label id="foo-label" for="foo">My Label</label></body></html>');

doc.getElementById('foo').checked; // false
doc.getElementById('foo-label').click();
doc.getElementById('foo').checked; // false
```

**Comment by yaycmyk** [comment]
@domenic Awesome, thanks. I'll use a different pen next time, not familiar with jsbin at all :laughing:

**Comment by yaycmyk** [comment]
And here's a REPL example of the `change` event for a radio not being triggered on `click`, but `checked` is actually being set to `true` as expected:

```js
var onChangeFired = false;
var dom = require('jsdom').jsdom;
var doc = dom('<html><body><input type="radio" id="foo" name="bar" value="baz" /></body></html>');
var input = doc.getElementById('foo');

input.onchange = function() { onChangeFired = true; };
input.checked; // false

input.click();
input.checked; // true

// onChangeFired === false
```

**Comment by yaycmyk** [comment]
Any movement on this?

**Comment by domenic** [comment]
I don't see anything in the recent commit history relating to it, so no.

**Comment by yaycmyk** [comment]
> I'll see if we can get that one fixed in jsdom at least. This weekend perhaps!

Just was wondering if you had time to work on it
