### ISSUE TITLE
Node 0.12 support?

### ISSUE THREAD

**Issue by stevenvachon** [tmpvar/jsdom#1081]
It has the same [`vm`](https://nodejs.org/api/vm.html) capabilities as io.js, does it not?

**Comment by domenic** [comment]
No, it does not.

**Comment by stevenvachon** [comment]
Care to elaborate? I have not yet tried out io.js

**Comment by domenic** [comment]
The V8 version in Node 0.12 is too old to provide good support for vm.

In general we do not support legacy technology like Node.js.

**Comment by stevenvachon** [comment]
Ok, thanks.

**Comment by chapinkapa** [comment]
@domenic legacy? Really?
