### ISSUE TITLE
How to trigger the "onload" event or run the requirejs of the window?

### ISSUE THREAD

**Issue by xiaoshao** [tmpvar/jsdom#1083]
Now, I want to make a smoke test for my site? In my page, I used requirejs, so I want to check whether requirejs is executed. 

For example, In the requirejs, a div component will be added to the page. I want to check whether the div was added to page.

**Comment by domenic** [comment]
How would you test this in a normal browser?

**Comment by xiaoshao** [comment]
I use requirejs in my html as follows
'''
 <script type="text/javascript" src="js/lib/requirejs.js" data-main="js/mainApp.js"></script>
'''.
In normal browser, the onload event will be trigger automatically when the index.html is loaded.
So I can check the it. But In jsdom, the onload event didn't work, when I use jsdom.env("www.realestate.com.au",function(){.......});

**Comment by domenic** [comment]
Off the top of my head, you may want to read more about the initialization life cycle in the readme. I might be able to look into more later, but that has a good chance of being your issue.

**Comment by Sebmaster** [comment]
You'll need to provide more sample code. The `done` callback in `jsdom.env` *is*/occurs in the same tick as the `window.onload` callback.
