### ISSUE TITLE
Unexpected token ILLEGAL

### ISSUE THREAD

**Issue by Somebi** [tmpvar/jsdom#1093]
/jsdom.js:55
    throw new RangeError(`Invalid parsingMode option ${JSON.stringify(options.
                         ^
SyntaxError: Unexpected token ILLEGAL

Are you kidding... Mate, at least run your soft before pushing...

**Comment by domenic** [comment]
Are you kidding... Mate, at least read the readme before whining. https://github.com/tmpvar/jsdom#install

**Comment by Somebi** [comment]
I was updating from old version...

**Comment by Somebi** [comment]
Ugh....

**Comment by domenic** [comment]
Yes, well, doing that without reading the changelog is a great recipe for disaster.

**Comment by Somebi** [comment]
What disaster... It's not an nuclear reactor soft... You could have created new project if you move from node.js and leave only working version for node.js here.
Leaving no headache for the rest people.
Or at least make some check/test inside install procedure and abort/notify installation...
Think about others and fallbacks next time.

But thank you for contribution, sorry for my temper...

**Comment by inikulin** [comment]
@Somebi I don't see any reason for the rant here. It's an open source project, all versions prior to 4.0.0 works with the node. You can always do:
```
npm install jsdom@3.1.2
```

Or fork this project and make it node-compatible.

**Comment by kamuran21** [comment]
npm install jsdom@3.1.2 
gives error for my project ? what's wrong?

**Comment by Sebmaster** [comment]
@kamuran21 Most likely an error with [Contextify](https://github.com/tmpvar/jsdom/tree/39633c67c33f5ca9628a85f7c0df6a8a09595999#contextify).

**Comment by Somebi** [comment]
:DD

**Comment by starsinmypockets** [comment]
This may be a stupid question but, if current versions of jsdom no longer runs on node, why is it installed via NPM?

**Comment by Joris-van-der-Wel** [comment]
npm is for io.js, node.js, browsers, bower, etc.

Look at the huge animated text on https://www.npmjs.com/

**Comment by starsinmypockets** [comment]
::npm emoji::

**Comment by Joris-van-der-Wel** [comment]
Also, io.js is going to be renamed to node.js eventually. 

New language features are _required_ if you want a fully complaint dom and html implementation. Currently, not even the bleeding edge of v8 is sufficient. Even a complete implementation of ES6 would not be sufficient (ES7 might be sufficient if things like weak references will be part of it). The only alternative for jsdom would be to add a native part that extends node.js or io.js

**Comment by Somebi** [comment]
Domenic sorry mate, was too rush. More than a year have passed and you still working on this project. My deepest thanks. You are the true dev ;) Guess open source lives because of people like you. :)
