### ISSUE TITLE
Adding GitHub Hook for IRC

### ISSUE THREAD

**Issue by Getty** [tmpvar/jsdom#1095]
Hiho!

On the #jsdom IRC channel (on Freenode) we would love to see the activity on the repository. Would be really nice, if the IRC hook for this repository would be activated towards:

Server: chat.freenode.net
Port: 6667
Room: #jsdom
Nick: jsdom (or whatever you like)

none of the switches activated would be appreciated! :)

But not forgetting the "Active" switch on the end :)

Thanks in advance, this is 3 feet high and rising

**Comment by domenic** [comment]
Needs @tmpvar since he is the admin :)

**Comment by tmpvar** [comment]
hooked irc up to the master and irc (for testing) branches

output (in irccloud) looks like:

![screen shot 2015-04-23 at 8 57 22 pm](https://cloud.githubusercontent.com/assets/46673/7310512/767064a2-e9fb-11e4-9cca-681a673bd2bf.png)

feel free to reopen if I missed something

**Comment by Getty** [comment]
thats service :+1:
