### ISSUE TITLE
jsdom 5.0.1 throws SyntaxError on my node.js version 0.12.2

### ISSUE THREAD

**Issue by NozomiIto** [tmpvar/jsdom#1098]
`require('jsdom')` causes SyntaxError in my environment.

```
node_modules/jsdom/lib/jsdom.js:55
    throw new RangeError(`Invalid parsingMode option ${JSON.stringify(options.
                         ^
SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

I think my nodes.js cannot handle back-tick "`".

I ran node.js with `--harmony` option, but does not work..
Please tell me if any probrem on my environment.

### environment

PC: Mac OS X
node version: v0.12.2
jsdom version: 5.0.1

**Comment by Sebmaster** [comment]
See [README](https://github.com/tmpvar/jsdom#install).

**Comment by NozomiIto** [comment]
Oh sorry, I missed it.
Thank you very much!

**Comment by japrescott** [comment]
I was wondering since io.js and node.js will be merged together under the "open, neutral, Node.js Foundation", at what point will jsdom function on node.js again?

**Comment by domenic** [comment]
@japrescott when there is a Node.js release based on the io.js codebase.
