### ISSUE TITLE
unchecked checkbox should already be checked in click handler

### ISSUE THREAD

**Issue by brandon-bethke-neudesic** [tmpvar/jsdom#1101]
I have discovered if an input element of type checkbox is unchecked, and then clicked on, it should be considered checked when evaluated in the click handler. I assume this is the correct behavior. However, jsdom is setting checked only after all the click handlers have been dispatched and therefore when evaluating in the handler, the value is coming up false. I have verified the assumed correct behavior using jsfiddle.net

                // input element is initially unchecked and then clicked on.

                inputElement.addEventListener("click", function(e){
                    inputElement.checked.should.equal(true);
                    e.preventDefault(); // checked value will get reverted to false;
                });

Additionally, any solution, must consider that if the e.preventDefault() is called in the click handler then the checked value must be reverted.

**Comment by Joris-van-der-Wel** [comment]
Here's what the [spec](https://html.spec.whatwg.org) says:

> The click() method must run the following steps:
> 
> 1. If the element is a form control that is disabled, abort these steps.
> 1. Run synthetic click activation steps on the element.

---

> When a user agent is to run synthetic click activation steps on an element, the user agent must run the following steps:
> 
> 1. If the element's click in progress flag is set to true, then abort these 
> 1. Set the click in progress flag on the element to true.
> 1. Run pre-click activation steps on the element.
> 1. Fire a click event at the element. If the run synthetic click activation steps algorithm was invoked because the click() method was invoked, then the isTrusted attribute must be initialised to false
> 1. If this click event is not canceled, run post-click activation steps on the element.
> <br>If the event is canceled, the user agent must run canceled activation steps on the element instead.
> 1. Set the click in progress flag on the element to false.

---

> If the element is mutable, then: The pre-click activation steps consist of setting the element's checkedness to its opposite value (i.e. true if it is false, false if it is true), and of setting the element's indeterminate IDL attribute to false. The canceled activation steps consist of setting the checkedness and the element's indeterminate IDL attribute back to the values they had before the pre-click activation steps were run. The activation behaviour is to fire a simple event that bubbles named input at the element and then fire a simple event that bubbles named change at the element.

**Comment by bl-nero** [comment]
I'm affected by this, and it prevents me from creating tests using zombie.js.

**Comment by domenic** [comment]
I believe this is fixed in master (although we should add a test before closing the issue). Zombie is unfortunately many versions behind so is not a good testing ground.
