### ISSUE TITLE
CSS stylesheet loading needs to resolve relative URLs

### ISSUE THREAD

**Issue by dbo** [tmpvar/jsdom#1103]
Relative imports of stylesheets doesn't work, but resolves relative to the document base.

**Comment by Sebmaster** [comment]
Do you have a test case? Relative stylesheets should definitely work.

**Comment by dbo** [comment]
Sorry, I don't have a test case, but a fix that works for me on pull request #1105.

**Comment by dbo** [comment]
New [pull request](https://github.com/tmpvar/jsdom/pull/1106).
