### ISSUE TITLE
Would like better error handling of broken arguments

### ISSUE THREAD

**Issue by gijsk** [tmpvar/jsdom#1111]
E.g.:

```
jsdom = require('jsdom');
doc = jsdom.jsdom('<p>Hi</p>');
p = doc.getElementsByTagName('p')[0];
p.replaceChild({}, p.firstChild);
```

gives either `"Object #<Object> has no method 'dispatchEvent'"` or `"Cannot call method 'replace' of undefined"` depending on whether mutation events are on by default (they will be in the example above). However, it does seem to remove `p.firstChild`...

A real DOM doesn't do anything and returns a TypeError saying argument 1 doesn't implement interface `Node`.

**Comment by domenic** [comment]
Yeah, in general our argument checking is bad. We've been slowly improving that as we re-implement stuff. But I agree.

A fully general solution will need something like https://github.com/domenic/webidl-class-generator

**Comment by domenic** [comment]
The vast majority of APIs in jsdom are now implemented in Web IDL, with appropriate error checking. There are some outliers in the XHR and File API spaces, but I think we can call this closed now.
