### ISSUE TITLE
Update to tough-cookie@1.1.0

### ISSUE THREAD

**Issue by domenic** [tmpvar/jsdom#1112]
I tried but it broke a bunch of tests: https://travis-ci.org/tmpvar/jsdom/jobs/60607718#L373

@inikulin any ideas?

**Comment by inikulin** [comment]
@domenic This is due to SalesforceEng/tough-cookie#36. Previously, localhost was resolved as public suffix which is incorrect. Need to fix tests on our side. I'll issue a PR.
