### ISSUE TITLE
SyntaxError: Use of const in strict mode

### ISSUE THREAD

**Issue by eduardoinnorway** [tmpvar/jsdom#1114]
Hi, you are using ECMAScript 6 const and let only in node-iterator.js and parent-node.js, this causes issues when using other libraries that uses jsdom like for example zombie then you get the SyntaxError: Use of const in strict mode. If there is no mayor critical reason to use ECMAScript 6 on this two files, I suggest to be consistent and use var like the rest of the files.

**Comment by domenic** [comment]
https://github.com/tmpvar/jsdom#install

**Comment by domenic** [comment]
I am surprised you got this far, it was supposed to fail on this line https://github.com/tmpvar/jsdom/blob/master/lib/jsdom.js#L3

**Comment by eduardoinnorway** [comment]
Well it all started with cucumber-js and there was no mention of io.js only there :)
