### ISSUE TITLE
option.selected = 'selected' vs option.setAttribute('selected', 'selected')

### ISSUE THREAD

**Issue by shamus** [tmpvar/jsdom#1130]
I ran into some confusing behavior regarding selecting an option and I was hoping for some clarification on how to use the API. Suppose I have a select that looks something like this:

```html
<select>
  <option id="foo" value="foo">foo</option>
  <option id="bar" value="bar">bar</option>
</select>
```

I'm writing a test against a page retrieved from a server. During the page initialization, something like this happens:

```js
  document.getElementById('foo').selected = 'selected'
```

After the page is initialized, I driving the UI in my test with some code that looks like this:

```js
  document.getElementById('bar').setAttribute('selected', 'selected')
```

The results were confusing. First, I noticed that `select.value` still equaled "foo". Then, I noticed that both options were selected. Digging into jsdom I see that using the selected setter on option sets a `dirtyness` flag. Once that flag is set, `setAttribute` no longer deselects previously selected options. So I modified my test to look like this:

```js
  document.getElementById('bar').selected = 'selected'
```

While this ensures that only one option is selected, `select.value` is still "foo". I notice that setAttribute, regardless of the `dirtyness` flag, forwards the call to `HTMLElement.prototype._attrModified` while the selected setter does not. This appears to affect how select reports its value. For now my test code looks like this:

```js
  document.getElementById('bar').selected = 'selected'
  document.getElementById('bar').setAttribute('selected', 'selected')
```

Which seems like a bit of a work around. Is this user error on my part?

**Comment by domenic** [comment]
Can you explain how the behavior you observe is different from that of browsers?

**Comment by shamus** [comment]
I believed I had an isolated test case but looking at it this morning I see a mistake in it.  In the (much) more complicated world of my real test I see different behavior in chrome and jsdom.

If I can isolate the issue I'll get back to you.  Thanks for the quick response!

**Comment by Joris-van-der-Wel** [comment]
I worked on this a while back and I remember that chrome (and IE) violate the specification (https://html.spec.whatwg.org/#concept-option-selectedness) a lot in the IDL form input stuff. Firefox (and jsdom ;) ) are a lot more compliant.

Basically how it is supposed to work is that the html attribute `selected="whatever"` specifies the default state and the IDL property `selected` specifies the current state, usually as input by the user.
If the user does not touch the `<select>` control and you never set the `selected` IDL property, setAttribute will change the selectedness, but as soon as the user changes the value or if you set `selected`, setAttribute no longer has an effect (dirtyness is now set). Even if you reset it to the default value. This means that `myoption.selected = myoption.selected` is not side effect free:

```javascript
var doc = jsdom.jsdom();
var option = doc.createElement("option");

t.strictEqual(option.selected, false, "selectedness is false by default");

option.setAttribute("selected", "selected");
t.strictEqual(option.selected, true, "selected property must return the current selectedness");

option.removeAttribute("selected");
t.strictEqual(option.selected, false, "dirtiness is still false, the selectedness should have been changed");

option.selected = false; // sets the element's dirtiness flag to true
t.strictEqual(option.selected, false,
  "on setting, the selected property must set the element's selectedness to the new value");

option.setAttribute("selected", "selected");
t.strictEqual(option.selected, false, "selectedness should not have been changed because dirtiness is now true");
```

If you want to get rid of the dirtyness, reset the form.

This is also how `value` and `checked` works for `<input>` and `<textarea>`.

There might still be a bug in jsdom of course.
