### ISSUE TITLE
Properly implement toString's (class string)

### ISSUE THREAD

**Issue by Joris-van-der-Wel** [tmpvar/jsdom#1136]
See [Web IDL](http://www.w3.org/TR/WebIDL/#dfn-class-string).

``` javascript
document.createElement('div').toString() === "[object HTMLDivElement]";
HTMLDivElement.prototype.toString() === "[object HTMLDivElementPrototype]";
window.toString() === "[object Window]";
```

A few of those are already correct, but there are also a bunch missing

**Comment by domenic** [comment]
If we wait for an io.js release with toStringTag we can fix the result of Object.prototype.toString at the same time.
