### ISSUE TITLE
nodejs runs forever

### ISSUE THREAD

**Issue by quape** [tmpvar/jsdom#1144]
I use jsdom to create a jQuery object to parse some DOM stuff. This works perfectly but afterwards the script hangs forever.

    var jsdom      = require("jsdom").jsdom;
    var request    = require("request");

    request({
        uri: "http://www.spiegel.de",
    }, function(error, response, markup) {
        var doc = jsdom(markup);
        // window = doc.parentWindow;
        // $ = require('jquery')(window);
        // ...       
    })

 I figured out that this depends on the html page which is parsed. When you replace the url with `http://www.google.de` (which is quite small) there is no problem at all. If you use `http://searchengineland.com` it quits with `Segmentation fault: 11`. One some other pages it quits after 10 secs with:

    timers.js:110
        first._onTimeout();
             ^
    TypeError: string is not a function
        at Timer.listOnTimeout (timers.js:110:15)

Seems to be a problem with jsdom. Any hints?

**Comment by domenic** [comment]
What version of jsdom and io.js?

**Comment by quape** [comment]
I used `npm install jsdom@3` with node.js as I could not install the latest because I don't use io.js yet. Is it possible to just switch to io.js?

**Comment by domenic** [comment]
Yes, that would be best. Older jsdom versions are not maintained and especially for the sort of bugs you describe I imagine they are fixed in newer jsdom releases.

Closing since there's no action item for the team here, but feel free to continue discussing. And we'll reopen if the problem still appears with latest jsdom and io.js.

**Comment by quape** [comment]
Okay, everything works with iojs. Thanks.
