### ISSUE TITLE
question with doing $.ajax in jsdom@3

### ISSUE THREAD

**Issue by totopia** [tmpvar/jsdom#1147]
I am trying to do a mocha test against some ajax calls with jsdom. I am getting 
`statusText: 'TypeError: Cannot call method \'open\' of undefined'` which refers to following lines of code in jquery where options.xhr() returned undefined. If xhr is undefined, xhr.open() obviously will fail.

````
support.cors = !!xhrSupported && ( "withCredentials" in xhrSupported );
support.ajax = xhrSupported = !!xhrSupported;

jQuery.ajaxTransport(function( options ) {
	var callback;

	// Cross domain only allowed if supported through XMLHttpRequest
	if ( support.cors || xhrSupported && !options.crossDomain ) {
		return {
			send: function( headers, complete ) {
				var i,
					xhr = options.xhr(),
					id = ++xhrId;
				
				xhr.open( options.type, options.url, options.async, options.username, options.password );

````

Here's how I am initializing jQuery in my test:
````
var jsdom = require("jsdom");
global.window = jsdom.jsdom().parentWindow;
global.$ = require('jquery/dist/jquery');
global.$.support.cors = true;
````

Am I missing something in order to use the ajax request with jsdom?

**Comment by domenic** [comment]
That is not the usual way of initializing a jQuery instance you can use. Usually it is more like

```js
var jsdom = require("jsdom");

jsdom.env(
  "",
  [require.resolve("jquery")],
  function (errors, window) {
    // use window.$
  }
);
```

The thing you are doing seems kind of crazy but also like it kind of might work so I am not sure exactly what the problem would be with it.

**Comment by totopia** [comment]
@domenic got it. the missing piece was the require("xmlhttprequest").XMLHttpRequest
Isn't xmlhttprequest part of jsdom by default?

**Comment by domenic** [comment]
Yes, it is, but it's on the jsdom window, not the global. Maybe jQuery just references `XMLHttpRequest` instead of `window.XMLHttpRequest`.

In general the approach in your OP seems pretty fragile unless you also copy over every property from `window` to `global`.

**Comment by totopia** [comment]
hmm...good call. maybe I don't need global namespace there, just use window.
