### ISSUE TITLE
ChildNode.remove()

### ISSUE THREAD

**Issue by pemrouz** [tmpvar/jsdom#1149]
This would be a minor nice-to-have, just noting as a fyi: There doesn't seem to be a [ChildNode.remove()](https://developer.mozilla.org/en-US/docs/Web/API/ChildNode/remove). The following works fine though:

```js
node.parentNode.removeChild(node)
```

**Comment by domenic** [comment]
Pull request welcome! :)

**Comment by Joris-van-der-Wel** [comment]
The rest of `ChildNode` is also missing :p

**Comment by pemrouz** [comment]
@domenic - happy to help out! However, took a cursory look through the codebase before opening, and it didn't appear straightforward or even clear what I need to do. If you can link me to any contributing guides/docs that would get me up and running and/or provide some guidance on how you would implement `ChildNode` yourself, I can take another look (and also hopefully send PRs instead of issues in the future)..

**Comment by domenic** [comment]
CONTRIBUTING.md should be pretty helpful. If you're still stuck, you'll probably want to parallel https://github.com/tmpvar/jsdom/blob/master/lib/jsdom/living/non-document-type-child-node.js and its tests.

**Comment by domenic** [comment]
This turns out to be the one part of ChildNode that we *do* implement, woohoo.
