### ISSUE TITLE
stopImmediatePropagation is not a function

### ISSUE THREAD

**Issue by alansouzati** [tmpvar/jsdom#1152]
Hi,

  I'm calling `event.stopImmediatePropagation()` in my app. In the browser everything works fine. But inside the jsdom environment I keep getting `undefined is not a function`. Any ideas on how to load the stopImmediatePropagation function?

I'm using Node 0.12.0, Npm 2.7.5, and jsdom 4.4.0.

Any help is appreciated.

**Comment by Sebmaster** [comment]
`stopImmediatePropagation` is not implemented in jsdom (yet). PRs as always welcome.

**Comment by domenic** [comment]
Fixed by 2c8933905e9b81436843fe8d429918876a277e54!
