### ISSUE TITLE
Removed style elements do not get removed from document.styleSheets

### ISSUE THREAD

**Issue by stuartlangridge** [tmpvar/jsdom#1157]
Demonstration:

    var jsdom = require("jsdom");
    var pageHTML = '<!doctype html><html><head>' +
        '<style>p { color: green; }</style><style>div { color: red; }</style>' +
        '</head><body></body></html>';
    var removeScript = "var style2 = document.getElementsByTagName('style')[1]; " +
        "style2.parentNode.removeChild(style2);";
    jsdom.env({
        html: pageHTML,
        src: removeScript,
        done: function(err, window) {
            console.log("Number of style elements in the page:", 
                window.document.getElementsByTagName("style").length);
            console.log("Length of document.styleSheets:",
                window.document.styleSheets.length);
        }
    });

This should print 1, 1 and instead prints 1, 2. 

This is similar to https://github.com/tmpvar/jsdom/issues/690 but that's about leaking memory; this is more concerned with the data being _wrong_ and so iterating over `document.styleSheets` gives incorrect answers.

**Comment by Joris-van-der-Wel** [comment]
Looks like someone left a todo note for precisely this issue: [lib/jsdom/level2/style.js:80](https://github.com/tmpvar/jsdom/blob/6e52bcdc4805323ea2407887d5a35d484ee6d1f7/lib/jsdom/level2/style.js#L80)
