### ISSUE TITLE
window.getComputedStyle does not work with background-image

### ISSUE THREAD

**Issue by stuartlangridge** [tmpvar/jsdom#1160]
A quick demonstration:

    var jsdom = require("jsdom");
    var pageHTML = '<!doctype html><html><head><style>' +
    'div {background-image: url("http://example.com/no.png"); color:green}' +
    '</style></head><body><div></div></body></html>';

    jsdom.env({
        html: pageHTML,
        done: function(err, window) {
            var div = window.document.getElementsByTagName("div")[0];
            var sty = window.getComputedStyle(div);
            console.log(sty.color); // => green, as expected
            console.log(sty["background-image"]); // => empty string
            console.log(sty.backgroundImage); // => empty string
        }
    });

**Comment by chad3814** [comment]
I'll take a look...

**Comment by chad3814** [comment]
Sorry, there was just bad code parsing url() values that had quotes, fixed in cssstyle 0.2.29.
