### ISSUE TITLE
Searching for empty attributes in CSS selectors incorrectly matches missing attributes

### ISSUE THREAD

**Issue by stuartlangridge** [tmpvar/jsdom#1163]
var jsdom = require("jsdom");
    var pageHTML = '<!doctype html><html><head></head><body><div></div><div title=""></div><div title="yes"></div></body></html>';

    jsdom.env({
        html: pageHTML,
        done: function(err, window) {
            console.log(window.document.querySelectorAll("div[title='']").length); // => 2 (wrong!)
            console.log(window.document.querySelectorAll("div[title][title='']").length); // => 1 (correct)
        }
    });

Note that a selector `div[title='']` should not match `<div>`, but here does.

**Comment by dperini** [comment]
@stuartlangridge
thank you for the heads up ... I can confirm the bug.
It would be easy to fix for newer browsers and `jsdom`.
It would be more difficult to fix for IE 8 and older versions.
Can you open an issue in the `nwmatcher` repository ?

**Comment by stuartlangridge** [comment]
https://github.com/dperini/nwmatcher/issues/95 filed.

**Comment by dperini** [comment]
@stuartlangridge
appreciate the heads up and the help with this issue.
The problem should be fixed for all browsers by commit https://github.com/dperini/nwmatcher/commit/26d7b36

**Comment by domenic** [comment]
@dperini awesome! Let me know when you do a new nwmatcher release with that fix and I can update jsdom's dependency.

**Comment by dperini** [comment]
@domenic
I will wait up to next Monday to be able to run all the tests and ensure nothing else is broken.
Maybe you can run related `jsdom` tests too ... to make sure everything is working there !
I believe I was able to maintain backward compatibility with IE6/7/8.

**Comment by domenic** [comment]
OK, a clean jsdom install should pull down the latest nwmatcher, which I've verified fixes this. Thanks for finding!!
