### ISSUE TITLE
Efficient backing data structure

### ISSUE THREAD

**Issue by Joris-van-der-Wel** [tmpvar/jsdom#1165]
I keep running into performance issues related to simple manipulations of the dom tree. There are a lot of `O(n)`  cases, even a few `O(n^2)`. 

I can probably get most of those down to `O(1)` by creating a linked tree data structure. So my current idea is to create a separate package for this purpose. It would provide many tree manipulation and querying methods dom implementations would need. 

Related: #1156

**Comment by Joris-van-der-Wel** [comment]
First version: https://github.com/Joris-van-der-Wel/js-symbol-tree

Next up is the equivalent of Node._indexOf(), with caching. And various accessors used in the DOM standard, such as preceding and following.

**Comment by domenic** [comment]
Looking great to me. Curious how much of a perf hit a WeakMap version would introduce, but that could be transparently changed at some point (e.g. if V8 gets faster with weak maps).

I opened a few cosmetic issues but overall happy to start using this whenever you've got a PR ready.

**Comment by Joris-van-der-Wel** [comment]
Last I checked WeakMap was still pretty slow. Symbol will likely remain much faster because they could be optimized using v8's fast properties stuff (I am not sure if they are). Are you considering WeakMap because of `Object.getOwnPropertySymbols()`?

This will be very easy to compare after I integrate the lib. Although the name of the lib would be incorrect if it changes to WeakMap hah.

**Comment by domenic** [comment]
> Are you considering WeakMap because of Object.getOwnPropertySymbols()?

That, and you can't add symbols to frozen objects. But in practice both gOPS and freezing will cause lots of havoc in jsdom today so it's more just an idle wondering than anything else.
