### ISSUE TITLE
Is there a way to wrap jsdom.env to work with KOA?

### ISSUE THREAD

**Issue by butaixianran** [tmpvar/jsdom#1167]
I try to use bluebird.promisify or bluebird.promisifyAll to wrap jsdom.env to make it yieldable, but failed.

With bluebird.promisify, it just don't work. with bluebird.promisifyAll, jsdom.env actually works but throw an error that  you can't yield "undefined".

Is there a solution to make jsdom work with Koa?
Thanks.

**Comment by Joris-van-der-Wel** [comment]
Do you have an example?

**Comment by domenic** [comment]
We are considering a promise-based redesign as part of #1139. #1159 will also help a bit.

But in the end jsdom.env in its current form is just too weird and variadic to be wrapped by something generic like promisify/promisifyAll. You're better off writing your own custom wrapper function using `new Promise`.

**Comment by domenic** [comment]
Also, you might want `jsdom.jsdom` as a simpler, synchronous alternative.

**Comment by Joris-van-der-Wel** [comment]
`Promise.fromNode` from bluebird might work

**Comment by butaixianran** [comment]
redesign...that's great. for now, based on your suggestion, I just write some code in the "done" callback to make it yieldable only in my case.

Thanks for your suggestion, it helps.
