### ISSUE TITLE
Some exceptions within unit tests are eaten

### ISSUE THREAD

**Issue by Joris-van-der-Wel** [tmpvar/jsdom#1168]
Some exceptions are eaten in unit tests without any warning on the terminal, the test simply times out.

I have noticed this in the callback for `env()`, but also in internal event handles such as the infamous `DOMNodeInsertedIntoDocument`.

One place where you could test this behaviour is here: https://github.com/tmpvar/jsdom/blob/96e763253cf24d2e1720efe9742783c2d9fb3e74/test/level2/style.js#L25. Try throwing something in that callback.

It looks like something is handling and ignoring uncaught exceptions. The exception is logged properly if i add the following:

```javascript
process.on('uncaughtException', function(err) {
  console.log('Caught exception: ' + err);
});
```

**Comment by domenic** [comment]
I'm not opposed to adding such a handler as a quick-fix inside our test runner. Root-causing it might be better, but on the other hand the test runner is kind of crazy anyway and might be replaced, so it might not be worth the effort.
