### ISSUE TITLE
Use of setImmediate causes CSP violation in atom/electron

### ISSUE THREAD

**Issue by mangecoeur** [tmpvar/jsdom#1172]
[ Opening issue here as recommended in https://github.com/YuzuJS/setImmediate/issues/46]

In the (more locked down) nodejs environment used in Atom Editor/Electron run time the setImmedate dependency causes CSP violations (due, among others, to use of new Function() ) . It would be great if jsdom could run in this environment.

**Comment by domenic** [comment]
Fixed and will be out in next release (which is likely 6.0.0).
