### ISSUE TITLE
Refactor NodeList

### ISSUE THREAD

**Issue by Joris-van-der-Wel** [tmpvar/jsdom#1173]
After some refactoring in #1169, NodeList could probably benefit of a refactor too. (And also the descendants of `NodeList` such as `HTMLCollection`). 

Things to consider:
- Wait for ES6 Proxy in v8 so that we can be 100% spec complaint? Although from what I've heard this will take a while.
- Implement `Elements` which is a subclass of `Array` (can we do this from "user" land?)
- Implement `Symbol.iterator` for these collections (firefox supports this already)
- Instead of creating a temporary array, use an iterator
- Can `lengthFromProperties` be avoided?
- Get rid of the `mapper()` function in utils.js?

**Comment by Zirro** [comment]
I think this can be closed, given all the changes in https://github.com/tmpvar/jsdom/pull/1934.

**Comment by TimothyGu** [comment]
Not sure about the Elements class and the mapper function bullet points have been done, but other than that closing sounds good.
