### ISSUE TITLE
browser vm contexts do not have common globals

### ISSUE THREAD

**Issue by domenic** [tmpvar/jsdom#1175]
Haven't created a tiny repro yet, but this is the cause behind almost all of the current the failures in the better-errors branch. In that branch, the following test:

```js
exports["onerror catches exceptions thrown in inline event handlers"] = function (t) {
  const doc = jsdom(`<body onclick="throw new Error('oh no!')"></body>`, { url: "http://example.com" });

  doc.defaultView.addEventListener("error", function (event) {
    t.equal(event.message, "oh no!");
    t.equal(event.filename, "http://example.com");
    t.ok(event.lineno > 0, "lineno set");
    t.ok(event.colno > 0, "colno set");
    t.ok(event.error);
    t.done();
  });

  doc.body.click();
};
```

fails with "window.Error is not a function". If I add

```diff
diff --git a/lib/jsdom/vm-shim.js b/lib/jsdom/vm-shim.js
index 941d399..40ccb7d 100644
--- a/lib/jsdom/vm-shim.js
+++ b/lib/jsdom/vm-shim.js
@@ -13,6 +13,8 @@ exports.createContext = function (sandbox) {
     configurable: true,
     enumerable: false
   });
+
+  sandbox.Error = Error;
 };

 exports.isContext = function (sandbox) {
```

then almost all of the failures go away.

I am not sure what the correct solution is here. Do we set all the built-ins as inherited? Is there a way to get fresh copies of them (even in a worker, where there are no iframes to use)? @Sebmaster, thoughts?

**Comment by Sebmaster** [comment]
We should probably add a list of built-ins to our escodegen rewriter which ignores these specific ones so they're not replaced by window.{{builtin}}. Then it'd just use the browsers native ones which should be fine, right?

**Comment by domenic** [comment]
It'd probably be OK, but it does differ from io.js where each context gets fresh copies of the built-ins :-/.

**Comment by Sebmaster** [comment]
Well, it is an extra copy since it's running in a webworker anyways...

**Comment by domenic** [comment]
Sure but all jsdoms inside the web worker will use the same built-ins, whereas all jsdoms inside io.js will use different built-ins. This is a reasonably big change in behavior in the face of code that monkeypatches built-ins.

**Comment by Sebmaster** [comment]
Oh, that's right. However this is already a bit of problem, since we should actually provide new versions of our own classes too. So monkey patching is already pretty much doomed.

**Comment by domenic** [comment]
Good point. OK then, yeah I think your fix is best.

**Comment by domenic** [comment]
Wait, that solution is not good. Then if you explicitly refer to `window.Error` it will still not work.

**Comment by Sebmaster** [comment]
Oh right, I wasn't aware that was defined there. We'll have to put it on the sandbox then.
