### ISSUE TITLE
MouseEvent constructor is ignoring properties in eventInit param

### ISSUE THREAD

**Issue by brandon-bethke-neudesic** [tmpvar/jsdom#1185]
The code is ignoring some eventInit properties and setting them to null. I.E., I cannot set the shiftKey property in the eventInit param, because it gets set to null by the code in the constructor. It's also not setting the default values.

Taken from events.js

    core.MouseEvent = function(eventType, eventInit) {
        core.UIEvent.call(this, eventType, eventInit);
        this.screenX = null;
        this.screenY = null;
        this.clientX = null;
        this.clientY = null;
        this.ctrlKey = null;
        this.shiftKey = null;
        this.altKey = null;
        this.metaKey = null;
        this.button = null;
        this.relatedTarget = null;
    };

https://w3c.github.io/uievents/#interface-MouseEvent

**Comment by domenic** [comment]
Yep, definitely a bug. Would love your help fixing it. Here is probably the most modern style of Event class we have: https://github.com/tmpvar/jsdom/blob/master/lib/jsdom/living/error-event.js but you could also go for the more-hacky fix of just porting over the properties (with appropriate type conversions).

**Comment by domenic** [comment]
Fixed by https://github.com/tmpvar/jsdom/commit/5459bec38660658e4e18642265f61c3d79e984dd.
