### ISSUE TITLE
Issue with installation

### ISSUE THREAD

**Issue by Imahmedz** [tmpvar/jsdom#1188]
Hello,
I get this error when installing jsdom

C:\..\node_modules\node-jsdom\node_modules\contextify>if not defined npm_config_node_gyp (node "C:\Program Files(x86)\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (rebuild)

I'm running Windows

**Comment by domenic** [comment]
The current version of jsdom does not use the contextify module, so the first thing you need to do is update to the latest jsdom.

**Comment by Imahmedz** [comment]
But I'm using Nodejs and the latest version of jsdom works wwith iojs only

**Comment by domenic** [comment]
Ah, yep. In that case this isn't an appropriate support forum, as we're no longer working on older versions of jsdom.
