### ISSUE TITLE
location.href holds URLs with invalid encoding.

### ISSUE THREAD

**Issue by cpojer** [tmpvar/jsdom#1191]
Trying to upgrade a large codebase to FB jest/jsdom 6.1 and got a lot of failing tests that rely on certain URL encoding:

Repro (in a jest test):
```js
location.href = 'http://facebook.com/?foo=%7B%22abc%22';
console.log(location.href); // prints http://facebook.com/?foo=7B22abc22
```

**Comment by Sebmaster** [comment]
Fixed in `whatwg-url` 0.6.2.

**Comment by domenic** [comment]
Thanks for the report @cpojer and thanks for the quick fix @Sebmaster!

**Comment by cpojer** [comment]
thank you!
