### ISSUE TITLE
Significant perf regression in JSDom 6.1

### ISSUE THREAD

**Issue by bterlson** [tmpvar/jsdom#1193]
Attempting to upgrade ecmarkup to JSDom 6.1 I came across a severe performance regression that is preventing me from upgrading. Just about every phase of the build process takes longer so I'm not clear where exactly the regression lies.

To reproduce the problem, do the following:

```
npm install -g git+https://github.com/bterlson/ecmarkup.git#jsdom6
git clone https://github.com/jmdyck/es-spec-emu
ecmarkup es-spec-emu/es-spec.emu out.html
```

The last step takes at least 10x longer, maybe more, in jsdom 6.1.

**Comment by domenic** [comment]
This regression was presumably from the "^5.0.1" specified in the current master package.json, i.e. from 5.6.1. My guess is URL issues, similar to https://github.com/tmpvar/jsdom/issues/1156#issuecomment-129845809

**Comment by domenic** [comment]
Recent perf work has fixed this and Ecmarkup is now on the latest jsdom \o/
