### ISSUE TITLE
Supported WebSocket implementations

### ISSUE THREAD

**Issue by rgbkrk** [tmpvar/jsdom#1195]
There's code we want to be able to test with JSDom that uses websockets. There are a [lot of different implementations](http://stackoverflow.com/questions/16392260/which-websocket-library-to-use-with-node-js). Which would you suggest for use in contexts server side in JSDom + client side in the browser? I'm leaning towards [ws](https://github.com/websockets/ws).

**Comment by Joris-van-der-Wel** [comment]
Well, if you are wondering about integration into jsdom, my vote would go to one that:

* is well maintained
* has no binary dependencies
* implements the api per spec

**Comment by domenic** [comment]
In particular, `ws` definitely does not implement the spec API, e.g. using `on` instead of `addEventListener` and so on.

I'm a little unclear what the purpose of this question is. Are you preparing to create a PR to add web socket support to jsdom?

**Comment by rgbkrk** [comment]
I'd create a PR to add websocket support if you'd want it. For code that I'm testing using JSDom, I also want to be able to test websockets (while being able to browserify the whole lot).

**Comment by domenic** [comment]
That would be lovely!

**Comment by rgbkrk** [comment]
Would it be appropriate to use `ws` under the hood, but make the API match the API specification for websockets?

**Comment by domenic** [comment]
Definitely.

**Comment by avesus** [comment]
What the purpose of JSDom in XI century if it doesn't support WebSockets?..
:-)
@rgbkrk +1
@domenic have you integrated the PR?

**Comment by domenic** [comment]
@avesus It turns out a lot of people find purpose in it so far despite it not being a complete browser.

> have you integrated the PR?

What PR?

**Comment by rgbkrk** [comment]
I never made a PR, ended up getting away from jsdom for a bit as well as the project I wanted websockets for. Back to using it again though!

**Comment by davidworkman9** [comment]
This would be so nice to have!

**Comment by domenic** [comment]
Please use the voting buttons and don't add "me too" comments. Deleting the one that just appeared.

**Comment by davidworkman9** [comment]
Voting buttons? I'm looking around for this, found a (change petition)[https://www.change.org/p/github-inc-add-voting-functionality-for-github-issues] but it appears that github has not implemented any voting system..

**Comment by inikulin** [comment]
@davidworkman9 
![image](https://cloud.githubusercontent.com/assets/453071/14461332/beb76b70-00ca-11e6-9ac1-745bc8514712.png)

**Comment by davidworkman9** [comment]
@inikulin thanks. I was not aware that in github land that reaction.meaning == vote.meaning (or that you could use reactions as a voting mechanism). Sorry about my lack of proper github social skills.

**Comment by rgbkrk** [comment]
Hey it's ok, the feature has only been around a few weeks IIRC.

**Comment by alexey2baranov** [comment]
what is the current state of websocket in jsdom?

**Comment by Sebmaster** [comment]
It's not implemented.

**Comment by alexey2baranov** [comment]
@Sebmaster 
It is very hard to separate out code from websockets. We would like to test views but views require models, models require websockets. Moking models is possible but very close test range. 

Do you plan to implement websokets in near future?

**Comment by Sebmaster** [comment]
I don't think anyone of us is currently implementing it, or prioritizing it in the near future. So unless there's a PR or a change of priorities, probably not.

**Comment by palmerj3** [comment]
Is anyone interested in collaborating on this?

I'm willing to do the work but would be great to have others participate at least in reviews.

**Comment by TimothyGu** [comment]
@palmerj3 I'd be interested, but I'm sure the rest of @jsdom would be too. Just make sure to look at the requirements @Joris-van-der-Wel listed out when choosing a WS library: https://github.com/tmpvar/jsdom/issues/1195#issuecomment-131390814. If you hit any bumps, we'll be on #jsdom at Freenode to help :)

**Comment by thdxr** [comment]
Is anyone working on this? Will take a crack at it otherwise

**Comment by rgbkrk** [comment]
No one is working on this. [`ws` does support `addEventListener` now](https://github.com/websockets/ws/blob/16f727d3e061eff7713eabc1ae367f65438d8ddb/doc/ws.md#websocketaddeventlistenertype-listener) so you should be able to use that module directly.

**Comment by domenic** [comment]
In general we're not able to use any modules directly as they don't support the full Web IDL semantics; wrapping will still be necessary. See https://github.com/tmpvar/jsdom/blob/master/Contributing.md#architecture for more information.

**Comment by thdxr** [comment]
Would using this not work? https://www.npmjs.com/package/universal-websocket-client

**Comment by domenic** [comment]
That definitely wouldn't be a good idea; it's just a wrapper around `ws`, so we'd then need a wrapper around a wrapper around ws. Let's just do one layer of wrapping, please.

**Comment by thdxr** [comment]
AFAIK this wrapper does implement this spec API

**Comment by domenic** [comment]
Yes, but as I tried to explain (and Contributing.md goes into in more detail), it doesn't implement it in a way that's compatible with jsdom's systems. For example, jsdom already contains an EventTarget, so we can't use the one that ws *(or universal-websocket-client) comes with; then we'd have duplicates.

**Comment by thdxr** [comment]
Ah thank makes sense.  Will dig into the contributing docs. Thanks

**Comment by rgbkrk** [comment]
Thanks @domenic and @thdxr.

**Comment by TimothyGu** [comment]
FYI there is now an active PR implementing the entirety of the WebSocket APIs, in https://github.com/tmpvar/jsdom/pull/2088. Please, check it out!

**Comment by TimothyGu** [comment]
The WebSocket API PR just got merged! Support will be available in the next jsdom release.
