### ISSUE TITLE
Make virtual console sendTo automatically send jsdomErrors to error unless { dontSendJsdomErrors: true } is passed

### ISSUE THREAD

**Issue by domenic** [tmpvar/jsdom#1199]
Looking at the setup code in https://github.com/tmpvar/jsdom/issues/1198, the current set-up is kind of unnecessarily painful. If the user has opted in to sending web-page-induced stuff to their console, sending jsdomErrors there seems reasonable as well, as long as there is a way to turn it off.

@jeffcarp, do you agree?

**Comment by jeffcarp** [comment]
Yep, that sounds great!

**Comment by jeffcarp** [comment]
Unless you or someone wants to do it sooner I can pick this up sometime this upcoming week.

**Comment by Joris-van-der-Wel** [comment]
I think `{ sendJsdomErrors: false }` is better than `{ dontSendJsdomErrors: true }`

**Comment by domenic** [comment]
The default has to be falsy. A better name is welcome though. `omitJsdomErrors: true` perhaps.

@jeffcarp Thanks for the offer! I have grand plans to put in some hours on jsdom later today, but if those fall through (i.e. if I haven't fixed this by end of weekend) then I'd love your help.
