### ISSUE TITLE
response status

### ISSUE THREAD

**Issue by wormen** [tmpvar/jsdom#1202]
tell me how this module can I get a response code?

**Comment by domenic** [comment]
I don't understand the question. Please add more detail, including an example of some code that works in web browsers but does not work in jsdom.

**Comment by wormen** [comment]
Yes, now delete committees

**Comment by wormen** [comment]
simple ... eg if code

```
var jsdom = require("jsdom");

jsdom.env({
  url: "http://news.ycombinator.com/",
  scripts: ["http://code.jquery.com/jquery.js"],
  done: function (err, window) {
    var $ = window.$;
    console.log("HN Links");
    $("td.title:not(:last) a").each(function() {
      console.log(" -", $(this).text());
    });
  }
});
```

I need to in addition to html I could get a response status (for example: 200, 301, 404, etc.)

**Comment by domenic** [comment]
Again, you can give an example of code **that works in web browsers** but does not work in jsdom?

**Comment by wormen** [comment]
I'm using this code is not in the browser, and in iojs

**Comment by domenic** [comment]
Right. The purpose of jsdom is to provide an emulation of browser APIs. If the browser does not contain an API for something, then jsdom will not implement it.

So although I still cannot tell exactly what you are asking for, I get the feeling that it is out of scope for jsdom.

**Comment by wormen** [comment]
The bottom line is that the browser response to the request contained in the headlines, but how to get it in jsdom I do not know

**Comment by domenic** [comment]
OK. Well, since there is no code you can write that does this in a browser, there is no code you can write in jsdom that does it either, and there never will be.

**Comment by Joris-van-der-Wel** [comment]
what you will want to do is: Use whatever library you like to make the http request, this gives you status codes, headers, content etc. Then pass the html to jsdom.

**Comment by wormen** [comment]
another question ...
Can using jsdom determine whether the connected js library (eg jquery) or not

**Comment by Sebmaster** [comment]
You may be able to access `window.$` or `window.jQuery` to determine if they're used.

**Comment by wormen** [comment]
I have a slightly different time meant ... I asked to ensure that it was possible to know in advance, to connect the same jquery or not
I'm interested in the participation of the code


var jsdom = require("jsdom");

jsdom.env({
  url: "http://news.ycombinator.com/",
  **`scripts: ["http://code.jquery.com/jquery.js"],`**
  done: function (err, window) {
    var $ = window.$;
    console.log("HN Links");
    $("td.title:not(:last) a").each(function() {
      console.log(" -", $(this).text());
    });
  }
});
