### ISSUE TITLE
Windows documentation needs to be updated

### ISSUE THREAD

**Issue by redmunds** [tmpvar/jsdom#1205]
In the Windows documentation section (https://github.com/tmpvar/jsdom/tree/3.x#windows), the [Visual Studio Express 2013 for Windows Desktop](http://www.visualstudio.com/downloads/download-visual-studio-vs#d-express-windows-desktop) points to **Visual Studio Express 2015 for Windows Desktop**.

Since VS 2015 does not yet seem to be supported, the link should be fixed.

**Comment by domenic** [comment]
PR welcome. We don't maintain that branch anymore ourselves.

**Comment by redmunds** [comment]
Can't seem to find a better link. Closing.
