### ISSUE TITLE
`window.getComputedStyle()` causes process to hang

### ISSUE THREAD

**Issue by jwarkentin** [tmpvar/jsdom#1214]
It only happens with certain websites, but if you run this snippet of code you can watch the process hang indefinitely and eat 100% CPU:

```js
var jsdom = require('jsdom');

jsdom.env(
  'http://news.hjnews.com/maxread/intermountain/back-to-school-health-tips-for-kids/article_d5183d0c-45dd-11e5-8bfe-27b864db0d65.html',
  function(err, window) {
    console.log(window.getComputedStyle(window.document.body));
  }
);
```

**Comment by jwarkentin** [comment]
FYI, while most of the time it hangs, every once in a while it doesn't hang so it can be deceiving.

**Comment by domenic** [comment]
This is going to be a fun one.

If you're up for helping us track it down, it would be great if you could take the source of that page, and start deleting stuff until it stops hanging, to try to narrow down exactly what is causing it. But, we'll get to it regardless...

**Comment by jwarkentin** [comment]
Ok, I tracked it down. It comes down to the fact that there's a huge `<style>` tag with a bunch of CSS in the head and it includes this comment:

```
// MAIN MENU - (used to keep mobile menu options hidden and keep weather/search and menu on one line) //
```

If you remove the `/` between `weather/search` it's fine. But with the slash it hangs.

**Comment by domenic** [comment]
Thank you so much! That sounds like it won't be too hard to fix, thankfully.

The best part is that `//` comments don't work in CSS. (So, I'm betting what's happening is that the parser wasn't tested on such cases.)

**Comment by domenic** [comment]
I found two underlying issues here:

- https://github.com/NV/CSSOM/issues/76
- https://github.com/dperini/nwmatcher/issues/97

Hopefully one of them will get fixed soon. The nwmatcher one is kind of crippling too.

**Comment by jwarkentin** [comment]
I'm glad you found the issue! That CSSOM project looks dead though. It needs new maintainers or that issue will probably never get looked at. Luckily the more critical problem is in nmwatcher.

**Comment by domenic** [comment]
Yeah, I have publish and git rights to it, but don't know the codebase that well... basically I can accept PRs.

**Comment by dperini** [comment]
Fixed !
