### ISSUE TITLE
Support for `insertAdjacentHTML`

### ISSUE THREAD

**Issue by danawoodman** [tmpvar/jsdom#1219]
Is there plans to support [`element.insertAdjacent`](https://developer.mozilla.org/en-US/docs/Web/API/Element/insertAdjacentHTML) in jsdom?

```js
document.body.insertAdjacentHTML('afterbegin', '<p>Hello World</p>')
```

Results in:

```
TypeError: document.body.insertAdjacentHTML is not a function
```

**Comment by Joris-van-der-Wel** [comment]
Yes, I was planning to add this eventually

**Comment by mbrevda** [comment]
+1. Fresh jquery convert here: is there another way that I can use in the meantime?

**Comment by domenic** [comment]
You can just use `document.body.innerHTML = '<p>Hello World</p>' + document.body.innerHTML`. It will be slower as it has to re-parse everything, but it will work. You can also use DOM APIs directly.

**Comment by mbrevda** [comment]
Oh, cool. Thanks! Seems `insertAdjacentHTML` is much more efficient, but I guess this will do in the mean time

**Comment by Joris-van-der-Wel** [comment]
Here is how you can avoid a reparse. This would be similar to how `insertAdjacentHTML` could be implemented:

```javascript
function htmlToFragment(ownerDocument, markup) {
    const container = ownerDocument.createElement('div');
    container.innerHTML = markup;
    const fragment = ownerDocument.createDocumentFragment();
    while (container.firstChild) {
        fragment.appendChild(container.firstChild);
    }
    return fragment;
}
```
(might contain typo's)

Then you can do something like: `node.appendChild(htmlToFragment(document, '<p>hello world</p>'))`

**Comment by domenic** [comment]
Yeah, that will generally work, although it doesn't work for e.g. inserting `<tr>`s into tables.

**Comment by patrickfatrick** [comment]
+1. Trying out jsdom for the first time today and came across this limitation.

**Comment by tombh** [comment]
You can write your own with something like `window.HTMLElement.prototype.insertAdjacentHTML = function(){}`

**Comment by inikulin** [comment]
@domenic It will work even for `<tr>` if you'll use `<template>` as `container`.
