### ISSUE TITLE
Setting .value on an input does not update the input's value attribute

### ISSUE THREAD

**Issue by stuartlangridge** [tmpvar/jsdom#1221]
node -e 'var jsdom=require("jsdom"), html="<!doctype html><html><body><input>";jsdom.env({html:html,done:function(err,window){var inp=window.document.querySelector("input");inp.value="fails";console.log(inp.outerHTML);inp.setAttribute("value","succeeds");console.log(inp.outerHTML);}});'

Note that this should print

    <input value="fails">
    <input value="succeeds">

but instead prints

    <input>
    <input value="succeeds">

because setting `.value` is not setting the `value` attribute.

**Comment by domenic** [comment]
I can't read that code.

**Comment by domenic** [comment]
Anyway, `.value` doesn't correspond to the `value=""` attribute. `.defaultValue` does.

Please test in a browser.

**Comment by stuartlangridge** [comment]
I stand corrected; thank you!
