### ISSUE TITLE
NodeList contains unspecified _length property which is enumerable

### ISSUE THREAD

**Issue by techkey** [tmpvar/jsdom#1224]
The `NodeList` object as returned by e.g. `querySelectorAll` contains a unspecified property `_length` which is `enumerable`, example:

`var list = document.querySelectorAll('span');`

`Object.getOwnPropertyDescriptor(list, '_length')` returns:

`{configurable: true, enumerable: true, value: 448, writable: true, __proto__: Object}`

`list.propertyIsEnumerable('_length')` returns `true`, which messes up functions like `Object.keys(list)` because the `_length` property is in the returned array too.

`Object.keys(list)` returns an array like this:

```javascript
[
    '0',
    ...
   '447',
   '_length'
]
```

`list.propertyIsEnumerable('length')` returns `false`, which is good. 

https://dom.spec.whatwg.org/#interface-nodelist

**Comment by domenic** [comment]
In general you're going to find lots of these properties all over jsdom, because we don't do private variables very well in general. But, we can certainly fix this particular instance, and any others you noticeas particularly problematic.

**Comment by techkey** [comment]
@domenic A fix for this instance would be great as I (and maybe other programmers) use `NodeList` and `Object.keys` a lot. Then at least I can remove all the filters that I've build in my code that uses `jsdom` to filter out the `_length` property.

Almost always I use native ECMAScript code and report problematic code if it's not too much trouble for you.

It's on my agenda to look at the source of `jsdom` so that maybe I can be of any help.

**Comment by domenic** [comment]
It's OK, I've already got a PR up :)

**Comment by techkey** [comment]
Cool thanks, btw `jsdom` is doing a great job so far :)

**Comment by domenic** [comment]
Fixed in master, new release coming shortly.
