### ISSUE TITLE
Highlight differences between jsdom.env and jsdom.jsdom options.

### ISSUE THREAD

**Issue by dsimmons** [tmpvar/jsdom#1228]
After spending quite a bit of time spinning my wheels as to why `document.referrer` wasn't being set correctly despite following the documented configuration, I found #1128 which noted that it shouldn't be nested under the `document` object when using `jsdom.jsdom`. `jsdom.env`, however, appears to work with the nested configuration based on the comments in the issues and local verification.

I understand that, without digging into the source too far, this likely stems from some form of technical debt relating to the API that has probably accumulated over time. In the meantime, prior to making potentially breaking changes and as a stopgap of sorts, it'd be helpful to have the documentation highlight differences between the two "environments" and their respective configurations. I know it would have saved me a good 45 minutes!

I'd be happy to help out where appropriate (although, admittedly, I'm not as well-versed in the API and its respective differences as a long-time user/contributor would be)! :smile:

**Comment by domenic** [comment]
> I understand that, without digging into the source too far, this likely stems from some form of technical debt relating to the API that has probably accumulated over time.

This is exactly right. #1128 is where I summed this up, although your experience shows that this is a lot worse than "a little messy". We should try to fix this. We can do it backward compatibly by just allowing the maximal union of both for now, and wait on #1139 for a larger fix.

**Comment by dsimmons** [comment]
> We can do it backward compatibly by just allowing the maximal union of both for now, and wait on #1139 for a larger fix.

I think that sounds like a very reasonable approach in the meantime! :+1:

I'll leave it up to you whether you want to leave this issue open (as a reminder for the time being) or go ahead and close it. If for no other reason, I wanted to surface an issue in the history for posterity's sake in the event that someone should run into the same problem in the future!

**Comment by domenic** [comment]
No, definitely leaving it open... was hoping to get it fixed in yesterday's release, but just didn't have the time.

**Comment by dsimmons** [comment]
Sounds good, let me know if there's any way I can help!

**Comment by dsimmons** [comment]
:+1: :clap:
