### ISSUE TITLE
getElementsByClassName() doesn't work with multiple class names

### ISSUE THREAD

**Issue by dsimmons** [tmpvar/jsdom#1232]
For convenient reference, [here's the relevant spec](
https://dom.spec.whatwg.org/#dom-document-getelementsbyclassname).

This example is admittedly little contrived (I'm working with a different document/DOM in my real code), but it sufficiently illustrates the issue.

### Test Case

```Javascript
import { env } from "jsdom";

new Promise(resolve => {
  env('https://github.com', (err, window) => resolve(window.document));
})
.then(document => {
  console.log(document.getElementsByClassName('header header-logged-out'));
});

// expect: (one element)
// result: {}
```

&nbsp;
However, making the same query from the devtools in an ***Incognito window*** for the URI https://github.com, it returns a non-zero number of elements:

![screenshot](https://dl.dropboxusercontent.com/u/6968139/oss/issues/Screenshot%202015-09-11%2018.21.45.png)

I'm seeing the same behavior in my test suite -- I can run it in the browser and it works as expected, but with the very same document-parsing code and JSDOM, I get an empty results set given a `getElementsByClassName()` query with more than one class name:

`document.getElementsByClassName('classA classB')`

Also, for what it's worth, if I change the above query to use either one of...
- `document.getElementsByClassName('classA')`
- `document.getElementsByClassName('classB')`

... I get a list of results.

:smile:

**Comment by domenic** [comment]
Wow. Congratulations, this is quite the bug. I never knew this was even part of the spec. And I'm also impressed so long went by with nobody noticing this.

Looking through [the code](https://github.com/tmpvar/jsdom/blob/08bc013da96bde74607cf7d6b9ff51a56e7931aa/lib/jsdom/level1/core.js#L728-L749) it looks like we just plain never got around to doing this. I'll try to fix this this weekend.

Very nice.

**Comment by dsimmons** [comment]
Thanks! I was genuinely concerned that I was missing something or made some sort of obvious mistake for the very same reason -- I couldn't believe that no one else had noticed this up to this point! Did several searches for previous issues and came up empty :smile: 

And wow, I sincerely appreciate your prompt response and for addressing this so quickly! I must say, I've been very impressed by your mean response time over the two issues I've opened as of late :wink: 

Looking forward to updating my test cases with the new tagged version! :+1:

**Comment by diego-hourly** [comment]
Hi there! I'm having this exact same problem. I see this is an old issue and seems it was already resolved but haven't been able to figure out whats wrong with my code.

```js
const JSDOM = require('jsdom').JSDOM;
const React = require('react');
const ReactDOM = require('react-dom');

const dom = new JSDOM(`<!DOCTYPE html><body></body>`);
const { document } = dom.window;

global.window = dom.window;
global.document = document;

module.exports = function (component) {
  const container = document.createElement('div');
  container.id = 'root';
  document.body.appendChild(container);
  ReactDOM.render(React.createElement(component), container);
  return container;
};

```

```javascript
import renderComponent from './renderComponent';

const TomeMenu = ({ openMenu, closeMenu, children }) => (
  <div>
    <div className="label hover" onClick={openMenu}>
      {label}
    </div>
    <div className="drop-down-menu">
      <div className="overlay" onClick={closeMenu} />
      <div className="arrow" />
      <div className="content">{children}</div>
    </div>
  </div>
);

const elem = renderComponent(TomeMenu);
const stubs1 = elem.getElementsByClassName('label hover');
console.log(stubs1.length) // prints 0
const stubs2 = elem.querySelectorAll('.label.hover');
console.log(stubs2.length) // Also prints 0

```
