### ISSUE TITLE
Resolving of relative and protocol-relative image URIs

### ISSUE THREAD

**Issue by dsimmons** [tmpvar/jsdom#1236]
This may be intended behavior and/or the responsibility of [cssstyle](https://www.npmjs.org/package/cssstyle), but I wanted to surface an issue anyway just in case.

[Here's a JSFiddle](https://jsfiddle.net/s63dsymm/) of what I'm attempting to do -- access `el.style.backgroundImage` of an HTMLElement to get the URI of its `background-image` property, where the URI itself in this specific instance is a protocol-relative URI. Per a quick test, it looks to have the same behavior using a "normal" relative URI.

--

**EDIT:** I could've done a better job of being explicit above. Invoking the Fiddle in Chrome results in `https://pbs.twimg.com/profile_images/638751551457103872/KN-NzuRl.png`, whereas in JSDOM it results in `//pbs.twimg.com/profile_images/638751551457103872/KN-NzuRl.png`.

--

[This looks to be the relevant section of the spec](http://www.w3.org/TR/CSS2/syndata.html#value-def-urii) after some quick digging. Interestingly, after running the Fiddle in various browsers, it seems that Firefox leaves it as-is, where as Webkit/Blink-based browsers auto-resolve it.

It's ***not*** a major inconvenience, as I'm able to use Node's [URL.resolve](https://nodejs.org/docs/latest-v0.12.x/api/url.html#url_url_resolve_from_to) to expand relative URI's (or write a quick little one-line check/"fix"). It was, however, different behavior than I experienced in my browser (Chrome latest), so I wanted to see if it was worth investigating further or should be left as-is.

**Comment by domenic** [comment]
It looks like per the latest spec the correct behavior is to not do any resolution, but instead simply string escaping: https://drafts.csswg.org/cssom/#serialize-a-url

**Comment by dsimmons** [comment]
In that case, this is a moot point! :smile:
