### ISSUE TITLE
Error: Unknown encoding: gbk

### ISSUE THREAD

**Issue by chenweiyj** [tmpvar/jsdom#1237]
I want to fetch a website with gbk encoding. However when I set the options to `{encoding: 'gbk'}` in `jsdom.env(url, scripts, {encoding: 'gbk'}, callback)`, it returns `Error: Unknown encoding: gbk`. So how can I fetch the right website? I want to store parts of the fetched content in `utf8` encoding.

**Comment by domenic** [comment]
I don't believe Node.js supports gbk encoding. So, you'd need to do the decoding yourself, then supply the resulting utf8 string to jsdom.

**Comment by chenweiyj** [comment]
I have succeeded by first using `request` to fetch the html in raw data and then convert it to utf8 by 'iconv-lite'.
