### ISSUE TITLE
help porting old 3.x code using window.run

### ISSUE THREAD

**Issue by kapouer** [tmpvar/jsdom#1240]
Hi,

in a small project i used to `window.run(scriptStr)` and also i was able to set `window.somefunc` from outside the window context and call it from inside the window context.
I started by trying
```
var context = require('vm').createContext(window);
var vmscript = new (require('vm').Script)(script);
vmscript.runInContext(context);
```
But somehow it feels wrong. Is it ?

**Comment by domenic** [comment]
Yes, this relies on some internal details of jsdom, that will not necessarily always work the same way.

The best thing to do is to create a `<script>` tag and insert the code there.

```js
const scriptEl = window.document.createElement("script");
scriptEl.textContent = script;
window.document.body.appendChild(scriptEl);
```

**Comment by kapouer** [comment]
Ok, good idea, but that requires document to be ready...

**Comment by domenic** [comment]
Yes. What kind of useful script could run inside the document otherwise?

**Comment by Sebmaster** [comment]
If you don't need the document to be ready, you can also use the `created` property in the config object provided to `jsdom.env`.

**Comment by Sebmaster** [comment]
If you don't need the document to be ready, you can also use the `created` property in the config object provided to `jsdom.env`.

**Comment by aral** [comment]
@kapouer I had the same issue today while (finally) upgrading [Set](https://ind.ie/labs/set)’s dependencies. My solution was to replace `window.run` with `window.eval`.

Otherwise, the only other change I had to implement was to replace `document.parentWindow` with `document.defaultView`.

**Comment by kapouer** [comment]
@aral i'm calling run (or eval) from outside the context of the window, not from inside. Do you ?

**Comment by aral** [comment]
@kapouer Calling it from Node.

See https://source.ind.ie/project/set/blob/master/lib/set-express.coffee#L67
