### ISSUE TITLE
driverdan/node-XMLHttpRequest seems to be abandoned 

### ISSUE THREAD

**Issue by thorn0** [tmpvar/jsdom#1250]
A lot of pull requests without attention since January.
https://github.com/driverdan/node-XMLHttpRequest/pulls

**Comment by domenic** [comment]
Yes. Why did you open this issue on jsdom?

**Comment by thorn0** [comment]
Because it's jsdom's important dependency, which currently has a lot of issues. And many of those issues can be fixed by existing PRs. I thought you might have been not aware of this situation.

**Comment by domenic** [comment]
Oh, no, we're definitely aware. If you look at some PRs and issues over there you can see us commenting urging people to fork and maintain a new version.

**Comment by thorn0** [comment]
Its author is back and has merged a couple of PRs today.
