### ISSUE TITLE
TypeError : Cannot read property 'open' of undefined.

### ISSUE THREAD

**Issue by livesankp** [tmpvar/jsdom#1259]
Recently i updated my node version to v4.1.2 from v0.12.

I also updated jsdom and jquery node_modules and after that my node program stopped working. I am getting type error "Cannot read property 'open' of undefined".

My jquery node module is 2.1.4 and jsdom is 6.5.1 all latest available versions.

This is sample code from my program look like.

```js
//jsdom dependancy of jQuery
var jsdom = require('jsdom').jsdom, document = jsdom('test');
global.window = document.defaultView;
var $ = require('jquery');
$.support.cors = true;
//her mygeturl is asp.net web api
$.get( 'mygeturl' ).done(function( data ) {
    console.log("Data Loaded: " + data);
})
.fail(function( xhr, textStatus, errorThrown ) {
    console.log(textStatus);
    console.log(errorThrown);          
});
```

Ajax call is failing now. It was working before upgrade but not working anymore due to error.

**Comment by domenic** [comment]
Sorry nobody helped you with this. There have been a lot of fixes in jsdom to XHR. If you are still having this problem with the latest version please let us know and we will reopen and help.
