### ISSUE TITLE
cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by sankp** [tmpvar/jsdom#1262]
Hello,

I am trying to do this my jquery node_module is v2.1.4 and jsdom is v6.5.1

```js
//jsdom dependancy of jQuery
var jsdom = require('jsdom').jsdom, document = jsdom('paddio');
global.window = document.defaultView;

//test below line again new jQuery 3.0.0 module again
global.XMLHttpRequest = window.XMLHttpRequest;

//jQuery 
var $ = require('jquery');
$.support.cors = true;
```

While initializing jsdom i am getting exception i have attached the image for this.
I am using Visual Studio Code to debug node program.
![jsdom error](https://cloud.githubusercontent.com/assets/9613276/10466125/3365644c-71b8-11e5-931d-a3180fc691e4.PNG)

Please help me to resolve this issue.

**Comment by Sebmaster** [comment]
Your code works fine for me - but also seems kinda incomplete...

**Comment by domenic** [comment]
What Node.js version are you using? I imagine VSCode probably comes with an old one.

**Comment by livesankp** [comment]
So Visual Studio Code give option to break program for All Exceptions. When i choose that option it catches this exception of image. If i don't choose that option then it doesn't break there and it initializes jQuery also but then when i tries to initialize signalr using 
var signalr = require('./util/jquery.signalR-2.2.0.js');
Signalr fails saying jQuery is not initialize. So due to this error my entire program stops.

So i wondered what could be the cause then i found out jsdom was failing initially and because of that jQuery and SignalR not working.

**Comment by livesankp** [comment]
@domenic I installed latest version of Node v4.1.2 verified using node -v

**Comment by domenic** [comment]
OK. In that case I think the break on all exceptions thing is a red herring. signalr is probably confused for other reasons.

In general you should not be trying to use jsdom by attaching properties to the node.js global object. You should instead be running code inside the jsdom browser window, as all the examples in the readme show.

**Comment by livesankp** [comment]
I was trying this. https://github.com/tmpvar/jsdom#for-the-hardcore-jsdomjsdom

It was working so far. After node upgrade from 0.12 to 4.1.2 and jquery, jsdom uprade this entire flow broke.

**Comment by Sebmaster** [comment]
SignalR checks for the global `window.jQuery`, so that's where you need to append jQuery.

However it's probably better if you use jsdom.env(), you can load the jQuery and signalr script there and it'll do the right thing.

**Comment by domenic** [comment]
@livesankp your example in the original post bears no resemblance to https://github.com/tmpvar/jsdom#for-the-hardcore-jsdomjsdom. It is setting global properties, instead of e.g. doing `window.document.appendChild(scriptElement)`.

**Comment by livesankp** [comment]
@Sebmaster window.jQuery = $; this is working. No error in Signalr are now.

Looks like issue is resolved but can you suggest what will be best way to use here. Combining all 3.

**Comment by domenic** [comment]
The best way is to stop mucking with the global. Here is an example to get you started, but you'll have to finish it.

```js
const jsdom = require("jsdom").jsdom;
const document = jsdom();
const window = document.defaultView;

const script1 = document.createElement("script");
script1.src = pathToJqueryJSFile(); // fill this in yourself
document.body.appendChild(script1);

// now do the same for angular and signalr
```

**Comment by livesankp** [comment]
var jsdom = require("jsdom").jsdom;
var doc = jsdom(undefined, undefined);
global.window = doc.defaultView;

//test below line again new jQuery 3.0.0 module again
global.XMLHttpRequest = window.XMLHttpRequest;

//jQuery 
var $ = require('jquery');
$.support.cors = true;
window.jQuery = $;

//SignalR added externally, Configuration, Common functions, Constant
var signalr = require('./util/jquery.signalR-2.2.0.js');

@Sebmaster @domenic So this is working now. Is this the correct way to go with ?

Once this is initialize i will be able to do other serialport connection and other stuff.

**Comment by Sebmaster** [comment]
You're doing it wrong. That way it can still break depending on what else singalR accesses.

Use [jsdom.env](https://github.com/tmpvar/jsdom#easymode-jsdomenv) and load your jquery and signalR with the `scripts` option. They'll get a proper environment in there (which prevents other stuff from breaking) and you can access them by accessing window.prop (for example `window.$` for jquery).
