### ISSUE TITLE
jQuery click() and checking for dynamic element

### ISSUE THREAD

**Issue by nousacademy** [tmpvar/jsdom#1267]
var jsdom = require("jsdom");

    jsdom.env(
        "http://www.web.com", ["https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"],
        function(err, window) {
            var $ = window.$;
            //console.log($('#pdp_size_select').length)
            $('a#pdp_size_select').click();

        console.log($('a.size_button').length)
        console.log('hello')
        

        
 
        //console.log(window.$('.pdp_size_select').text())
        //console.log(window.$('#pdp_size_select').click());
        }
    );

does jsdom support the click() method, and how would I approach dynamic elements??

**Comment by Joris-van-der-Wel** [comment]
`click()` is partially supported: it triggers a `'click'` event on the target element (unless the element is `disabled`). However jsdom does not support navigation.

https://github.com/tmpvar/jsdom/blob/master/lib/jsdom/level2/html.js#L379

**Comment by Joris-van-der-Wel** [comment]
I am not sure what you mean by dynamic elements? what are you trying to do?

**Comment by nousacademy** [comment]
I'm basically trying to click an element that triggers a dynamic dropdown that is being ajaxed in. And then select and click an element on that dropdown

**Comment by domenic** [comment]
Is there specific code that works differently in a browser from in jsdom? The code you gave doesn't actually test anything, it just clicks things.

**Comment by nousacademy** [comment]
well after the click I was expecting the dynamic dropdown to appear but when i check for its existence it doesnt show up

**Comment by Sebmaster** [comment]
Did you wait until the AJAX request finishes?

**Comment by nousacademy** [comment]
yes i did.

**Comment by Sebmaster** [comment]
You'll need to give us some small reproducible test case then, for us to be able to help you.

**Comment by nousacademy** [comment]
var jsdom = require("jsdom");

    jsdom.env(
        "http://www.eastbay.com/product/model:235098/sku:06954006/jordan-1-flight-3-mens/black/grey/?cm=GLOBAL%20SEARCH%3A%20KEYWORD%20SEARCH",     ["https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"],
        function(err, window) {
            var $ = window.$;
            //console.log($('#pdp_size_select').length)
            $('a#pdp_size_select').click();
            setTimeout(function() {
                console.log($('a.size_button').length)
                console.log('hello')

            }, 5000)

 
        }
    );

When I put .length of the dropdown elements I just get 0 back (aka not there)..

**Comment by rkubik** [comment]
Any updates? Having the same issue, however, I explicitly specify `features` to allow script execution (from the docs):

    FetchExternalResources : ['script'],
    ProcessExternalResources : ['script'],
    MutationEvents: ['2.0']

**Comment by Joris-van-der-Wel** [comment]
Are you sure that you are timing things properly? Are you trying to click on something before it exists? One way to workaround that issue is to keep polling the availability of an element:

```
function waitForElement(document, selector) {
  const MAX_ATTEMPTS = 30;

  return new Promise( (resolve, reject) => {
    let attempts = 0;

    function attempt() {
      ++attempts;

      const node = document.querySelector(selector);
      if (node) {
        resolve(node);
        return;
      }

      if (attempts >= MAX_ATTEMPTS) {
        reject(Error('Unable to find node with selector `' + selector + '` after ' + attempts + ' attempts' ));
      }

      setTimeout(attempt, 1000);
    }

    attempt();
  });
}



jsdom.env("http://some.where/", (err, window) => {
  const document = window.document;
  
  waitForElement(document, 'a#foo').then(anchor => {
    anchor.click();
  });
});
```
