### ISSUE TITLE
Browserifying jsdom gives invalid regular expression error

### ISSUE THREAD

**Issue by rchrdschfr** [tmpvar/jsdom#1268]
On Windows 7 (I did not choose this),

In a project with jsdom installed:
`var jsdom = require('jsdom')`

browserifying that into `jsdom.js` and then

`<script type="text/javascript" src="jsdom.js"></script>`

gives this error in the console

`Uncaught SyntaxError: Invalid regular expression: .... Range out of order in character class`

**Comment by domenic** [comment]
Hmm. Our CI verifies that browserification is working correctly: https://travis-ci.org/tmpvar/tmpvar/jsdom/jobs/86092245

Are you sure you are using Node.js 4?

**Comment by jeffcarp** [comment]
I was able to replicate this using Node 4.2.1 on OS X Yosemite viewing in Chrome:

<img width="1188" alt="screen shot 2015-10-19 at 10 49 46 pm" src="https://cloud.githubusercontent.com/assets/916028/10599080/c2419c9e-76b3-11e5-9f20-628b9f537cb2.png">

It looks like it's coming from somewhere within acorn.

**Comment by domenic** [comment]
:(

I wonder what's wrong with our CI setup... now I don't trust it...

**Comment by rchrdschfr** [comment]
Sorry guys, turns out this was due to not setting the `charset="UTF-8"' in the script tag in my HTML. I think you can still trust your CI!
