### ISSUE TITLE
jsdom-core?

### ISSUE THREAD

**Issue by pspeter3** [tmpvar/jsdom#1273]
Is there a subset package of jsdom that just provides the ability to create a new document/window?

**Comment by Sebmaster** [comment]
A `Window` includes everything else, so that doesn't really make sense. How do you want to restrict what to include?

**Comment by pspeter3** [comment]
What I meant more what I don't need the ability to parse markup, request pages, use jQuery, run custom JavaScript, etc. I just want to be able to have a fake DOM in node for tests.

**Comment by domenic** [comment]
> parse markup

So you don't want `innerHTML` and `outerHTML` to work?

> request pages

So you don't want iframes to work?

> use jQuery

The only way to stop jQuery from working would be to remove script support entirely... is that what you want?

> run custom JavaScript

I guess that is what you want!

> I just want to be able to have a fake DOM

What is a fake DOM with all these DOM features removed?? Doesn't seem like a DOM at all.

**Comment by pspeter3** [comment]
Sorry, I think I'm being unclear and for the record, I believe that `jsdom` is awesome. The only feature I use from `jsdom` is `jsdom.jsdom(null);` for running React tests with mocha. I was just trying to ascertain if one of jsdom's dependencies provided that support.

**Comment by Sebmaster** [comment]
> . The only feature I use from jsdom is `jsdom.jsdom(null);`

That's the thing though, jsdom.jsdom returns a document, which contains a reference to everything else (windows, elements, iframes, script support, etc.). Unless you know exactly which of those you need, it's not really possible to give a recommendation here. Chances are though, if react uses any kind of dom features you'll need to pull in the whole thing - there are some alternatives, but they mostly don't implement the actual DOM apis, or just have a very sparse implementation, which is only useful if the implemented features are exactly what you need.

As far as I know React has shallow rendering support which doesn't use the dom which might help, but I've never worked with it so I have no idea what it does exactly / if that'll work for you.
