### ISSUE TITLE
Add jQuery as a dependency? 

### ISSUE THREAD

**Issue by JaKXz** [tmpvar/jsdom#1274]
Since so many of the examples and the use cases for jsdom use jQuery, wouldn't it make sense to include it in the `package.json` `dependencies`? I understand people will want to bring in their own versions of the library, but, they can continue to do that and jsdom can just include the latest version by default.

Apologies if this has been discussed already, I couldn't find the thread.

**Comment by domenic** [comment]
I'd rather remove the examples that use jQuery as a dependency. How many did you find?

**Comment by JaKXz** [comment]
All of the easymode examples, and the "jQueryify" example of course.

My context is that I need something that compiles/renders HTML in my tests, and then allows me to verify things like styles being applied... [cheerio](https://www.npmjs.com/package/cheerio) (inspired by this project) can do the basic things that I need but does not render HTML, so I came here - just as a sanity check, my assumption/understanding that jsdom does render HTML is correct right?

**Comment by Sebmaster** [comment]
We don't really "render" as in visual if that's what you mean. You're gonna need something like phantomjs for that.

**Comment by JaKXz** [comment]
Hmm. I don't really need the "visual" part... but I just need something that will apply styles inside the `<style>` element to the elements on the DOM. I figured/was hoping I could get away from the weight of phantomjs/protractor or something similar because this is a super small library that just compiles different pieces of an HTML template and my tests just want to verify certain elements got certain styles applied.

Forgive the tangent here - I do still think that bundled jQuery would make a good addition to this library.

**Comment by Joris-van-der-Wel** [comment]
jsdom applies css rules from selectors. you can query for them using `getComputedStyle()`. It also keeps track of the interaction of the `node.style` IDL atribute with the `style="..."` content attribute. It does not yet perform layouting however, for example `node.clientWidth` will always be 0.

You could publish your own module that combines jsdom and jquery for your purpose. http://substack.net/many_things
