### ISSUE TITLE
env configuration with scripts doesn't fire 'done' callback

### ISSUE THREAD

**Issue by yairEO** [tmpvar/jsdom#1287]
// my machine
    windows   7
    node      5
    npm       3.3.12
    jsdom     7.0.2

My test file looks like this:

    var chai = require('chai'),
        expect = chai.expect,
        should = chai.should(),
        jsdom = require('jsdom');

    jsdom.env({
      html: '<html><body></body></html>',
      scripts: ["http://code.jquery.com/jquery-2.1.4.min.js"],
      done: function (err, window) {
        console.log("loaded");
        var $ = window.$;
      }
    });

I'm trying to load jQuery (tried locally then from the internet) but the `done` callback never gets fired, so I guess something isn't working properly...Running `mocha` from node.

What am I doing wrong?

**Comment by Sebmaster** [comment]
You need to put it in an `it` declaration for mocha to execute it. Your file works fine if executed with node directly, and with `it` it also works in mocha.

**Comment by yairEO** [comment]
Does it even cache the script which i'm pulling? seems odd to fetch the same script from the internet on every `it` call which jsdom is at....

ha, well I didn't know it only works inside an `it` declaration (how come?) anyway, now i put it inside an `it `declaration and it still doesn't show anything:



    describe('a basic test', function(){

        // var toDoList = new ToDoList();

        it('should pass when all is ok', function(){
            // console.log(toDoList);
            jsdom.env({
                html: '<html><body></body></html>',
                scripts: ["http://code.jquery.com/jquery-2.1.4.min.js"],
                done: function (err, window) {
                    console.log("loaded"); // never gets called
                }
            });

            (!!1).should.be.true;
        })
    })

**Comment by Sebmaster** [comment]
> Does it even cache the script which i'm pulling?

It does not. There's no shared state between jsdom instances.

> ha, well I didn't know it only works inside an it declaration (how come?)

Probably something mocha specific, no idea what they're doing to the script.

**Comment by jeffcarp** [comment]
@yairEO for asynchronous tests in mocha, you need to specify a `done` callback in the arguments of your `it` function, then call it when your test is over. More here: https://mochajs.org/#asynchronous-code

This should work:

```js
describe('a basic test', function(){

    // var toDoList = new ToDoList();

    it('should pass when all is ok', function(done){
        // console.log(toDoList);
        jsdom.env({
            html: '<html><body></body></html>',
            scripts: ["http://code.jquery.com/jquery-2.1.4.min.js"],
            done: function (err, window) {
                console.log("loaded"); // never gets called
                done();
            }
        });

        (!!1).should.be.true;
    })
})
```

**Comment by yairEO** [comment]
Took me quite a time to realize JSDOM is only for the tests. I thought it creates an encapsulated DOM environment (where I can load jQuery) so my web-app which is highly coupled to jQuery could be tested. My web app is made of ES6 modules which I import and test each of them, and they use jQuery (but they don't import it, I use jQuery from google CDN). 

Anyway, I was sure JSDOM is something it isn't..

**Comment by Joris-van-der-Wel** [comment]
jsdom is a browser with a huge todo list
