### ISSUE TITLE
`setTimeout` and `setInterval` does not support strings as callbacks

### ISSUE THREAD

**Issue by diegoperini** [tmpvar/jsdom#1291]
Browsers tend to evaluate `setTimeout('myFunction()',0)` type of usage. Current javascript client implementation in jsdom causes a crash. I forked the project to silence such errors but I believe an implementation that mimics browsers would be more appropriate.

Here is the [fork](https://github.com/diegoperini/jsdom-se)

**Comment by overflowz** [comment]
Hi, I need this feature asap, I could not find the implementation where should I change it. I'm just interested, when you will support this feature or can you point me where it is implemented?

Regards.

**Comment by domenic** [comment]
This will be implemented when someone, perhaps you, submits a pull request (that matches the spec). The place to do so would be https://github.com/tmpvar/jsdom/blob/d7b2f7b91e7aa64c072db7a8c3bbd16f9d1d2095/lib/jsdom/browser/Window.js#L131-L139
