### ISSUE TITLE
element.hasAttribute("style") no longer working

### ISSUE THREAD

**Issue by Rleahy22** [tmpvar/jsdom#1292]
Before this change: https://github.com/tmpvar/jsdom/commit/6e52bcdc4805323ea2407887d5a35d484ee6d1f7, testing that changing an element's style updated the style attribute worked when testing ```el.hasAttribute("style")```.  After that change ```el.hasAttribute("style")``` always returns false.

**Comment by domenic** [comment]
Fascinating. Thanks for the bisect. Will try to fix ASAP... curious how this is possible since the internal hack we were using was meant to be the same as the officially-provided one.

**Comment by domenic** [comment]
I am not able to reproduce this:

```js
"use strict";
const jsdom = require("jsdom");

const document = jsdom.jsdom();

document.body.style.color = "red";

console.log(document.body.getAttribute("style")); // color: red;
console.log(document.body.hasAttribute("style")); // true
```

**Comment by domenic** [comment]
Will reopen when you provide a repro :)

**Comment by Rleahy22** [comment]
Interesting. I'll try to put together a working example. Thanks for looking into it.

**Comment by Rleahy22** [comment]
fwiw, That change actually surfaced an error in my earlier code that the previous version missed. So good work!
