### ISSUE TITLE
Can I fake the location?

### ISSUE THREAD

**Issue by justinmchase** [tmpvar/jsdom#1300]
I want to load a file from the file system, but I want the location to be something like: ```http://example.com/test/foo.html```

I am testing script that looks at `window.location` properties to do some stuff and I need to test location to seem like the real location. Is there a way to do this?

in my `done:` function I did this, but it didn't seem to work:

```
done: function (err, window) {
  window.location = {
    // ...
   }
}
```

From the perspective of the script the location ends up being `{}` when I do this.

**Comment by justinmchase** [comment]
Actually it looks like just setting `window.location.href = 'http://example.com'` works... I was thinking that would cause a navigation event now i"m not so sure.

**Comment by domenic** [comment]
You should use the url option to jsdom() or env(). Changing href won't work well as we improve jsdom to support navigation.
