### ISSUE TITLE
/node_modules/jsdom/lib/jsdom/living/generated is empty

### ISSUE THREAD

**Issue by vcarel** [tmpvar/jsdom#1301]
When I install jsdom latest (i.e. 7.1.0) on my project, I can't use it because the directory ```./node_modules/jsdom/lib/jsdom/living/generated``` is empty.

Since those files are generated in the prepublish task, I think your intention was to include them in the npm package (and not to generate them on-the-fly during the installation).

I never published npm packages, but I believe those files have been omitted because they are mentionned in the  ```.gitignore``` file. According to the page below, you may just create a ```.npmignore``` file to make npm ignore the ```.gitignore```:
https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package

**Comment by Sebmaster** [comment]
Not empty for me with a freshly installed version from npm. You sure that's a clean install?

**Comment by vcarel** [comment]
Oh wait... I was installing from the github repo! (I was debugging with
older versions). You can close the ticket.

My apologies
