### ISSUE TITLE
[CANVAS] TypeError: Cannot read property 'styleSheets' of undefined

### ISSUE THREAD

**Issue by mbrevda** [tmpvar/jsdom#1306]
I'm getting the following when jsdom encounters a canvas object:
```
DIR/node_modules/jsdom/lib/jsdom/browser/Window.js:270
    forEach.call(node.ownerDocument._styleSheets, readStylesFromStyleSheet);

TypeError: Cannot read property '_styleSheets' of undefined
    at Window.getComputedStyle.sheet (DIR/node_modules/jsdom/lib/jsdom/browser/Window.js:270:36)
    at computeDimension (http://127.0.0.1:3474/app-ae4a8270.js:20534:10)
    at new Chart (http://127.0.0.1:3474/app-ae4a8270.js:20542:28)
    at module.exports.Backbone.View.extend.draw (http://127.0.0.1:3474/app-ae4a8270.js:24073:22)
    at null.<anonymous> (http://127.0.0.1:3474/app-ae4a8270.js:24010:18)
    at Timer.listOnTimeout (timers.js:92:15)
```

`computeDimension` is called like [this](https://github.com/nnnick/Chart.js/blob/42976724241907797f341a5db7c4b7f47887b18b/src/Chart.Core.js#L36)

**Comment by Sebmaster** [comment]
The jsdom -> node-canvas interaction is sadly not great, we probably don't set our internal state properly on the canvas object which breaks this.

**Comment by mbrevda** [comment]
Is there some way to tell jsdom to skip over certain elements?

**Comment by Sebmaster** [comment]
I'm guessing we just can't handle the getComputedStyle call on a canvas in general, so you'll have to avoid that until that gets fixed.

**Comment by mbrevda** [comment]
Right, but how? Do I need to add browser sniffing to my code or something?

**Comment by Sebmaster** [comment]
Either that, or you could wrap the call in a try-catch.

**Comment by mbrevda** [comment]
Thanks!

**Comment by domenic** [comment]
Still a bug, we can fix this, leaving open until we do.

**Comment by mbrevda** [comment]
:+1:

**Comment by domenic** [comment]
I wasn't able to reproduce a crash with the following code:

```js
  const document = jsdom.jsdom("<canvas style='width: 100px;'></canvas>");
  const window = document.defaultView;
  const canvas = document.querySelector("canvas");

  t.strictEqual(window.getComputedStyle(canvas).getPropertyValue("width"), "100px");
```

Could you find a similar minimal example perhaps? Also, let us know whether or not you have the `canvas` npm package installed?

**Comment by mbrevda** [comment]
still working on getting back to this, sorry for the delay

**Comment by mbrevda** [comment]
It doesn't appear like prerendering via jsdom is going to scale for us, and hence I wont be continuing my efforts with this. That being said, I would suggest creating a chart chart.js and see if that throws the same error. Good luck!
