### ISSUE TITLE
checked as property fails server side

### ISSUE THREAD

**Issue by Kflash** [tmpvar/jsdom#1314]
Hi. I'm using JSDOM, and discovered if you set checked as property and try to get it's value. It will always return false. Even if you force the value to be true.

If I try to run same code in a headless browser it gives me the right values.

There are other issues like this as well for properties and attributes.

**Comment by Joris-van-der-Wel** [comment]
Are you using a recent version? I did a lot of work on checked, selected and value a while back. We even had those implemented better than chrome (better as in, per the specification)

Note that the IDL property `node.checked` is not always equal to the `<input checked>` attribute. This is how it is supposed to work. Maybe you need `node.defaultChecked`?, which is the IDL property that is supposed to be equal to the html attribute.

Maybe you could post a small test case?

**Comment by Kflash** [comment]
Hi. The issue solved itself. After running the same test twice with same
error it started to work on last attempt.
I think the problem was related to how my fixtures was set up.

Just to be sure I upgraded to latest version.

So you can close this
