### ISSUE TITLE
Update parse5 to 2.0.0 to get line/col numbers in LocationInfo

### ISSUE THREAD

**Issue by sykaeh** [tmpvar/jsdom#1315]
As discussed in #1194 it would be nice to have line and column numbers for the location info. This has been implemented in the new version of parse5, 2.0.0 (see inikulin/parse5#67). 

It would be great if we could upgrade the included version of parse5 from 1.5.1 to 2.0.0. However there are some breaking changes in that update which means that it requires more work than just changing the version number.

**Comment by Sebmaster** [comment]
See #1316. I had a branch going before already, but was waiting for the final release of 2.0. Rebased it on master too.
