### ISSUE TITLE
http-equiv="refresh" supported?

### ISSUE THREAD

**Issue by stevenvachon** [tmpvar/jsdom#1319]
I don't see anything resembling it in the source code. If not, I've just written a parser that would be helpful for its implementation: [http-equiv-refresh](https://npmjs.com/http-equiv-refresh)

**Comment by Sebmaster** [comment]
It's not, jsdom doesn't support any navigation at all actually. zombie.js extends jsdom and does try to support navigation (somewhat) though.

**Comment by stevenvachon** [comment]
Ah, thank you.
