### ISSUE TITLE
Standard style property "transform" is not available

### ISSUE THREAD

**Issue by yaycmyk** [tmpvar/jsdom#1321]
It seems like the vendor prefixed version `webkit-transform` is available on the `HTMLElement.style` node, but not the W3C version.

**Comment by yaycmyk** [comment]
Actually it seems like getting `transform` from JSDOM objects doesn't work at all. I tried `window.getComputedStyle(HTMLElement)` and the `.style` way and neither retrieves the value.

**Comment by Sebmaster** [comment]
Do you set both `webkit-transform` and `transform` in your style, or just one of them? We don't actually process styles much - they don't properly inherit and they do not have any dependency on each other.

If you could get us a small test case, that'd be great.

**Comment by yaycmyk** [comment]
I look for the following:
```
'transform',
        'WebkitTransform',
        'MozTransform',
        'OTransform',
        'msTransform',
```

To my knowledge, `style['webkit-transform']` doesn't actually do anything.

**Comment by yaycmyk** [comment]
To replicate, create an element and do the following with it:

```js
const domElement = document.createElement('div');

domElement.style.transform = 'translate3d(0px, 0px, 0px)';

assert(domElement.style.transform === 'translate3d(0px, 0px, 0px)'); // undefined
```

I can only get it to work if I use this specific pattern:

```js
const domElement = document.createElement('div');

domElement.style['webkit-transform'] = 'translate3d(0px, 0px, 0px)';

assert(domElement.style.WebkitTransform === 'translate3d(0px, 0px, 0px)');
```

**Comment by yaycmyk** [comment]
I'm going to replicate this PR against CSSOM, since I think that's where the issue actually is...

**Comment by yaycmyk** [comment]
Issue in a different module
