### ISSUE TITLE
Setting env configuration with raw cookie value via attribute "cookie" appears to be deprecated.

### ISSUE THREAD

**Issue by danetb** [tmpvar/jsdom#1323]
Tried creating env with a custom configuration, like such, but the cookie header is absent from the resulting http request.

```
jsdom.env({
    url: 'http://localhost',
    cookie: 'key=value; expires=Wed, Sep 21 2011 12:00:00 GMT; path=/',
    done: function (err1, window1) {
        //...
    }
});
```

**Comment by domenic** [comment]
Confirmed. This is actually unfortunately hard to fix as all our cookie-related logic is confusingly wedged in _after_ the initial request. I can continue giving it a try...

**Comment by kedadi** [comment]
looks like the way to go is through headers:

```
jsdom.env({
    url: 'http://localhost',
    headers: {
      cookie: 'key=value; expires=Wed, Sep 21 2011 12:00:00 GMT; path=/',
    }
    done: function (err1, window1) {
        //...
    }
});
```

**Comment by domenic** [comment]
Going to close this as the new API provides a much better mechanism for adding cookies, and the old API has a workaround as documented above.
