### ISSUE TITLE
removeChild error

### ISSUE THREAD

**Issue by kuraga** [tmpvar/jsdom#1324]
Good day!

I get error on `parent.removeChild(node)`:
```
 at [object Object].core.Node.removeChild (node_modules/jsdom/lib/jsdom/level1/core.js:754:14)
 at [object Object].core.Node.removeChild (node_modules/jsdom/lib/jsdom/level2/events.js:365:28)
```
Note: `node` isn't `undefined` and not yet `remove`d.

Can you help, please? Thanks!

**Comment by Sebmaster** [comment]
We need a full error and a repro case would be useful. It's impossible to start debugging with this info.

**Comment by kuraga** [comment]
Oh my God, I understood! I create DOM fragment via `min-document` package (it's black box for me cause it's used in another package), append to `js-dom`'s `document.body` and `removeChild` it from `js-dom`'s parent node, too! Uh!!!
