### ISSUE TITLE
Can't call toDataURL() on canvas element

### ISSUE THREAD

**Issue by prashcr** [tmpvar/jsdom#1326]
**index.js**
```
var jsdom = require('jsdom');
var Canvas = require('canvas');

jsdom.env({
  url: 'http://www.w3schools.com/html/html5_canvas.asp',
  done: function(err, window) {
    if (err) console.log(err);
    console.log('Loaded W3schools Canvas page');
    var canvas = window.document.getElementById('myCanvas');
    console.log(canvas.toDataURL());
  }
});
```  
  
Running this gives me

```
Error: invalid arguments at Canvas.toDataURL  
```
  
So I pass in `'image/png'` to `toDataURL()`. But then I get an empty image.  
  
What am I doing wrong?
  
Further details here http://stackoverflow.com/questions/34433198/how-do-i-use-jsdom-to-grab-an-image-from-a-canvas-element

**Comment by prashcr** [comment]
That fixes the error, but the resulting data URI is still an empty image.

What was I doing wrong? Or is this just not supported by jsdom?

**Comment by Sebmaster** [comment]
You are not enabling on-page scripts, so nothing is drawing on the canvas. See https://github.com/tmpvar/jsdom#external-resources.
