### ISSUE TITLE
could not install jsdom

### ISSUE THREAD

**Issue by pkumar84** [tmpvar/jsdom#1331]
Dear developers,

whenever i try to run below command i get and error 

pkumar-mbpr:registries-ui pkumar$ npm install jsdom
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "jsdom"
npm ERR! node v4.2.4
npm ERR! npm  v2.14.12
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package react@0.14.3 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-datagrid@2.0.1 wants react@>=0.14.0
npm ERR! peerinvalid Peer react-dnd@2.0.2 wants react@^0.14.0
npm ERR! peerinvalid Peer react-dom@0.14.3 wants react@^0.14.3
npm ERR! peerinvalid Peer react-addons-test-utils@0.14.5 wants react@^0.14.5

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/pkumar/code/reg-ui-react/registries-ui/npm-debug.log

Any idea  ?

**Comment by domenic** [comment]
This doesn't seem to have anything to do with jsdom, but rather with react. I'd suggest fixing the react-related parts of your project as it suggests.

**Comment by domenic** [comment]
In other words, you could do `npm install anythingatall` and you would get the same errors.

**Comment by pkumar84** [comment]
i c, will try, thank you ,
