### ISSUE TITLE
Now the browser test runner is broken on Travis

### ISSUE THREAD

**Issue by domenic** [tmpvar/jsdom#1339]
https://travis-ci.org/tmpvar/jsdom/jobs/100284756

The pain never ceases. Maybe we actually broke the browser tests? I don't have Java installed currently; will have to investigate tomorrow.

**Comment by domenic** [comment]
Yeah it's a legit break:

Uncaught Error: Cannot find module '../living/generated/HTMLElement'

**Comment by domenic** [comment]
Ah, annoying. It's because register-wrappers.js uses dynamic require. I wanted to rename that file anyway...

**Comment by domenic** [comment]
I see two possibilities for fixing this:

```js
const mapping = {
  HTMLElement: [require("./generated/HTMLElement.js")],
  HTMLAnchorElement: [require("./generated/HTMLAnchorElement.js"), "a"],
  HTMLAppletElement: [require("./generated/HTMLAppletElement.js"), "applet"],
  ...
};
```

for brevity, or

```js
const mapping = {
  HTMLElement: {
    file: require("./generated/HTMLElement.js"),
    tags: []
  },
  HTMLAnchorElement: {
    file: require("./generated/HTMLAnchorElement.js"),
    tags: ["a"]
  },
  HTMLAppletElement: {
    file: require("./generated/HTMLAppletElement.js"),
    tags: ["applet"]
  },
  ...
};
```

for clarity. @Sebmaster do you have a preference? I guess the file will not be edited very often...

**Comment by domenic** [comment]
We could also write a script to generate it I suppose.

**Comment by Sebmaster** [comment]
I'd go for the second option - there are a few elements with multiple tags which make the fake-tuple kinda awkward.
