### ISSUE TITLE
Default `window.navigator.userAgent` value is `undefined`

### ISSUE THREAD

**Issue by necolas** [tmpvar/jsdom#1344]
Using `jsdom@7.2.2` I get the following error from modules using `navigator.userAgent`:

```js
Cannot read property 'indexOf' of undefined
```

According to the README, there is a default UA used in requests and set in [jsdom.js#L314-L325](https://github.com/tmpvar/jsdom/blob/7.2.2/lib/jsdom.js#L314-L325).

> `config.userAgent`: the user agent string used in requests; defaults to `Node.js (#process.platform#; U; rv:#process.version#)`

However, there is no default value for `window.navigator.userAgent` in [browser/Window.js#L309-L311](https://github.com/tmpvar/jsdom/blob/7.2.2/lib/jsdom/browser/Window.js#L309-L311), and browser module authors assume `userAgent` will always be a string. I can confirm that the errors go away by defaulting to a string:

```js
get userAgent() {
  return options.userAgent || '';
}
```

If a PR from me would save rather than waste your time, I'd be happy to give it go. Where would you want tests to go?

**Comment by domenic** [comment]
Hmm yeah, both requests and navigator.userAgent should be using that default value. A PR would be lovely. Tests could go in the old https://github.com/tmpvar/jsdom/blob/master/test/jsdom/index.js blob I guess :)

**Comment by necolas** [comment]
I wrote a test – https://github.com/necolas/jsdom/commit/c27e1466b1ae13f7c45ce37bdfa88796f6543c06 – but it passes. Applying it to 7.2.2 also results in a pass. That seems to make sense, since the `Window` is created with the config from `jsdom` that sets the default UA. So I'm now confused as to why we're getting that error :)

**Comment by domenic** [comment]
Maybe it is a difference when using jsdom.jsdom() in the tests vs. jsdom.env() or something else in your original code?

**Comment by necolas** [comment]
ah, yes it is. i'll close since the issue isn't in jsdom; would you like the test put up as a PR anyway?

**Comment by domenic** [comment]
Are you sure it's not a bug in jsdom? jsdom.env() and jsdom.jsdom() should both have a default user agent...

**Comment by necolas** [comment]
If I change the test as follows, it still passes:

```js
var document = jsdom.env('<html><body></body></html>', function (err, window) {
  test.strictEqual(typeof window.navigator.userAgent, 'string', 'window.navigator.userAgent should be a string');
  test.strictEqual(window.navigator.userAgent, defaultUserAgent, 'window.navigator.userAgent should have the correct default value');
  test.done();
})
```

I can provide a bit more context based on the digging around I did earlier today. We have a Karma plugin to launch jsdom, it's fairly simple and sets up jsdom but the `userAgent` is `undefined` in the test/app files.

```js
// some-browser-component.js

console.error(window.navigator)
// =>
// Object{userAgent: undefined, appName: 'Node.js jsDom', platform: 'darwin', appVersion: 'v5.4.0', noUI: true, cookieEnabled: true}
```

Logging the UA from within the jsdom `created` callback confirms that the default UA string is correctly set at that point.

```js
// jsdom-launcher.js
const jsdomBrowser = function (baseBrowserDecorator) {
  baseBrowserDecorator(this);

  this._start = function (url) {
    jsdom.env({
      url: url,
      features : {
        FetchExternalResources: ["script", "iframe"],
        ProcessExternalResources: ["script"]
      },
      created: function (error, window) {
        console.error(window.navigator.userAgent) // => "Node.js ..."
      }
    });
  };
}
```

I'm assuming that doing work outside of the callbacks may be a problem, and thought the fix lies there rather than jsdom :)

**Comment by deepsweet** [comment]
I have the same problem with Karma + jsdom@7, `window.navigator.userAgent` is `undefined` even if I'm trying to modify it in `created` callback. any solutions? rolling back to jsdom@6 helps.

**Comment by domenic** [comment]
I would really appreciate a repro that does not involve Karma.

**Comment by bchociej** [comment]
Despite my best efforts, I could not reproduce this outside of Karma. However, for what it's worth, I bisected the problem to commit 2c8933905e9b81436843fe8d429918876a277e54.

**Comment by carlmw** [comment]
It appears to only affect iframes which explains the problems with the karma runner. I've replicated with this:

```javascript
const jsdom = require('jsdom'),
  http = require('http');

http.createServer((req, res) => {
  res.writeHead(200, {'Content-Type': 'text/html'});
  res.end('');
}).listen(8000);

jsdom.env({
  html: '<iframe src="http://localhost:8000"></iframe>',
  features: {
    FetchExternalResources : ['script', 'iframe'],
    ProcessExternalResources : ['script']
  },
  onload: (window) => {
    console.log(
      window.document.querySelector('iframe').contentWindow.navigator.userAgent
    ); // => undefined
  }
});
```

**Comment by bchociej** [comment]
Ah! I was just about to post about the iframe thing. Long story short, karma loads its stuff in an iframe, and I am also able to create a reliable test case where `navigator.userAgent` is undefined in the iframe
