### ISSUE TITLE
Empty MutationEvent object

### ISSUE THREAD

**Issue by henrikkorsgaard** [tmpvar/jsdom#1345]
Hi,
When listening for mutationEvents, e.g. DOMSubtreeModified or DOMNodeInserted, I get an empty event object.

I'm running jsdom ^7.2.2
jsdom.jsdom(htmlMarkup, {}).defaultView; without any special options/features.

I'm appending elements to body and receive the event, but it is just empty.

I don't know if I'm doing something wrong or if the mutationEvents aren't implemented as full event objects.

- Henrik

**Comment by domenic** [comment]
Can you give some example xode?

**Comment by henrikkorsgaard** [comment]
Here is a simplified snippet of my code. It gives the same result. From the code below I get 2 mutation events, but console.log output is just ```MutationEvent {}```. 

```
    let window = jsdom('<html><body><div id="test"></div></body></html>', {}).defaultView;
    window.document.addEventListener('DOMNodeInserted', function(e){
        console.log(e); // result: MutationEvent {} 
    }, false);
    window.addEventListener('load', function(){
        let el = window.document.createElement('div');
        let le = window.document.getElementById('test');
        el.innerHTML = "foo";
        le.innerHTML = "bar";
        window.document.body.appendChild(el);
    });
```
Is that sufficient or do you need more?

**Comment by domenic** [comment]
The MutationEvent still has its properties; they just don't show up in the console, since they are unenumerable.

**Comment by henrikkorsgaard** [comment]
Ok, that explains it. Thank you
