### ISSUE TITLE
initKeyboardEvent() doesn't initialize KeyboardEvent

### ISSUE THREAD

**Issue by rhysd** [tmpvar/jsdom#1346]
Code to repro:

```javascript
var jsdom = require('jsdom');

jsdom.env('<html><body></body></html>', function(err, window) {
    if (err) {
        console.error(err);
        return;
    }

    var k = new window.KeyboardEvent('keydown');
    k.initKeyboardEvent(
        'keydown',
        false,
        false,
        window,
        '',
        '',
        0,
        '',
        false
    );

    console.log(k);
});
```

Output:
```
KeyboardEvent {}
```

It seems that `KeyboardEventImpl` object behind the `KeyboardEvent` object is initialized correctly.

- Environment
  - jsdom 7.2.2
  - Node.js v4.2.1
  - OS X 10.11.1

**Comment by rhysd** [comment]
I also tried `document.createEvent('KeyboardEvent')` but it resulted in the same.

**Comment by domenic** [comment]
When you console.log an object with non-enumerable properties, like almost every DOM object, the properties do not show up in the console. They are still there.

**Comment by rhysd** [comment]
Ah, thank you for the kind answer :flushed:
