### ISSUE TITLE
setTimeout and setInterval on window should return numeric ID

### ISSUE THREAD

**Issue by alvarorahul** [tmpvar/jsdom#1348]
setTimeout and setInterval on the jsdom window currently return the NodeJS timer object. Ideally, though it should return a numeric ID

**Comment by alvarorahul** [comment]
if nobody's is looking into anything similar, I can submit a pull request for this with a proposed fix

**Comment by domenic** [comment]
Well there's https://github.com/tmpvar/jsdom/pull/1342 but @Sebmaster has been lazy on tests so I wouldn't be too sad if you stomped on his changes :P
Tests would go in web-platform-tests/to-upstream/html/webappapis/timers/. Things to test off the top of my head:

- Return type for both setTimeout and setInterval
- Ensure the counter increments with subsequent calls
- Ensure the counter is shared between the two
- Ensure clearTimeout works

**Comment by alvarorahul** [comment]
Cool, i'll give it a try.

**Comment by alvarorahul** [comment]
So, I've submitted a pull request which seems to be passing CI. @domenic, @Sebmaster  could you please take a look?

**Comment by domenic** [comment]
Fixed by https://github.com/tmpvar/jsdom/commit/f53876aa0368b3debb73272db5023708e53b24fb!
