### ISSUE TITLE
Support full set of selectable input types

### ISSUE THREAD

**Issue by orlandohohmeier** [tmpvar/jsdom#1351]
JSDOM does not support the full list of selectable input types (according to WHATWG) and throws an exception if an unsupported element is selected. Please update the `_allowSelection` condition to include the full list of supported input types. 

List of selectable input types according to WHATWG:

* Text (type=text)
* Search (type=search)
* URL (type=url)
* Telephone (type=tel)
* E-mail (type=password)
* Password (type=password)
* Date (type=date)
* Month (type=month)
* Week (type=week)
* Time (type=time)
* Local Date and Time (type=datetime-local)
* Number (type=number)
* Color (type=color)
* File Upload (type=file)

/source https://html.spec.whatwg.org/multipage/forms.html#the-input-element

Besides the condition update I suggest to fail select calls on unsupported input types silently as propose by WHATWG:

> In the case of input elements, if the control has no text field, then the method must do nothing.

/source https://html.spec.whatwg.org/multipage/forms.html#dom-textarea/input-select

Many thanks in advance! :bow:

**Comment by domenic** [comment]
Pull request welcome! Should not be too difficult to change the list coded into the source.

**Comment by orlandohohmeier** [comment]
Yeah, should be easy. I will try to give it a shot in the next days, but can't promise anything.

**Comment by yaycmyk** [comment]
I'll hop on this if you don't have time @orlandohohmeier, I helped with the original implementation.

**Comment by yaycmyk** [comment]
> For input elements, calling these methods while they don't apply, and getting or setting these attributes while they don't apply, must throw an InvalidStateError exception.

Can't avoid the exception, unfortunately. I'm working on implementing this now.

**Comment by yaycmyk** [comment]
Also rewrote the tests again for this: https://github.com/w3c/web-platform-tests/pull/2591. I thought I added these in my PR a while ago @domenic?

**Comment by domenic** [comment]
Hmm I don't see them in https://github.com/tmpvar/jsdom/tree/master/test/web-platform-tests/to-upstream/html/semantics/forms, so not sure.

**Comment by yaycmyk** [comment]
This can be closed I think.
