### ISSUE TITLE
Invariant Violation: dangerouslyRenderMarkup()

### ISSUE THREAD

**Issue by RaulTsc** [tmpvar/jsdom#1352]
Hi,

I get this when trying to test some code. Shouldn't this work? Or am I missing something?

```
Invariant Violation: dangerouslyRenderMarkup(...): Cannot render markup in a worker thread. Make sure `window` and `document` are available globally before requiring React when unit testing or use ReactDOMServer.renderToString for server rendering.
    at invariant (/.../TodoReact/node_modules/fbjs/lib/invariant.js:39:15)
```

https://github.com/RaulTsc/TodoApp-React/blob/master/src/app.jsx#L52-L61

https://github.com/RaulTsc/TodoApp-React/blob/master/test/index.js#L38-L39

**Comment by Sebmaster** [comment]
We don't support this style of [test setup](https://github.com/RaulTsc/TodoApp-React/blob/711bee1c9f897d8fbfad9117880a42d3838cf98d/test/setup.js#L29-L31). It's really incomplete and might break anytime.

If you want to test with jsdom, provide jsdom the same bundle you'd provide a browser with.

**Comment by RaulTsc** [comment]
Still not working. Can you give me an example of a more complete setup?

**Comment by RaulTsc** [comment]
Ok so doing --require setup.js when running the tests makes it work. Weird stuff. If anyone else encounters this problem check my repo to see how I set it up.
