### ISSUE TITLE
Error thrown on relative src urls

### ISSUE THREAD

**Issue by asivitz** [tmpvar/jsdom#1360]
I have an svg element with a relative src, i.e. "icons/x.svg".
I get `TypeError: Invalid URL` when trying to render it.

From the spec (https://url.spec.whatwg.org/#syntax-url-path-relative-scheme-less), this should be a valid url.

**Comment by domenic** [comment]
This is probably fixed in master... will test.

**Comment by asivitz** [comment]
Thanks. I tried master myself, but I got this error:

```
Error: Cannot find module '../living/generated/utils'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\Users\asivitz\projects\eagle-print\node_modules\jsdom\lib\jsdom\browser\documentfeatures.js:3:18)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\Users\asivitz\projects\eagle-print\node_modules\jsdom\lib\jsdom.js:13:26)
```

**Comment by domenic** [comment]
You need to run `npm run prepublish`

**Comment by asivitz** [comment]
Oh thanks.
`master` does not seem to fix this though :/

**Comment by domenic** [comment]
Oh, OK! Well, I can fix it tonight then.

Can you produce a minimal example that I can run using `node example.js`? Should be 5 lines or less.

My guess is that you are leaving the default base URL of `about:blank`. But that should not cause an error, just cause the `.href` attribute to fail to resolve to a full URL. So this is still a bug even if you can work around it by setting a different document URL.

**Comment by asivitz** [comment]
Ah, I understand the problem a bit better now. I'm using a react component which loads the svg content, but I'm using jsdom in a test which doesn't have access to the actual resources anyway. So, for my purposes, I don't really care if the actual SVG loads (I'm testing the other rendered dom around it). So, I guess I understand why it would throw an error, although perhaps the message could be a bit clearer.

Anyway, your workaround works perfectly, so thanks a bunch for that.

If you feel this is an actual bug, here's the reproduce case:
```
var window = require("jsdom").jsdom().defaultView;

var req = new window.XMLHttpRequest();
req.open("GET", "relative.svg", false);
req.send();
```
Cheers

**Comment by domenic** [comment]
OK, yes, this is working as expected. If you open `about:blank` in any browser and execute those lines in the console, it throws some kind of "invalid URL" error.
