### ISSUE TITLE
jsdom should return real charset

### ISSUE THREAD

**Issue by ReklatsMasters** [tmpvar/jsdom#1364]
Now jsdom returned just string "UTF-8" without detect real charset. It`s a bug or you have reasons for this? Can i make [PR](https://github.com/ReklatsMasters/jsdom/tree/fix-charset) to fix it?

**Comment by Sebmaster** [comment]
We don't support encodings, so chances are if you have a document in jsdom, it's encoded in UTF8.

**Comment by ReklatsMasters** [comment]
Not always. If page have tag `<meta http-equiv="Content-Type" content="text/html; charset=windows-1251">`, then encoding is `windows-1251`, not UTF-8.

**Comment by domenic** [comment]
Right, but we don't support parsing it using that encoding, so it is utf-8 regardless.

**Comment by ReklatsMasters** [comment]
So, maybe it makes sense to add a non-standard api (_or another temporary package_) to get real encoding? In any case, it is very important begavior, that should be written in readme.

**Comment by domenic** [comment]
What do you mean "the real encoding"? The real encoding is UTF8 for any JavaScript strings (basically) so any jsdom you construct will always be utf8.

**Comment by yaycmyk** [comment]
Technically UTF-16, but yeah.

**Comment by domenic** [comment]
Well, technically UCS-2. But for the purposes of text-manipulation APIs on the web, UTF-8.

In reality all the meta charset does is change how the browser interprets byte streams into strings (whether they be JavaScript strings in jsdom, or C++ strings in Chrome, or Rust strings in Servo). In jsdom there's no way to feed it a byte stream so meta charset is not really relevant anyway.

**Comment by inikulin** [comment]
> Can i make PR to fix it?

Unfortunately, it's much more complcated than that. Document encoding calculated from different sources: `content-type` HTTP-header, BOM, parent document encoding (for `iframe`s), `<meta>` tags.

**Comment by inikulin** [comment]
Here is the complete algorithm if you mind to elaborate: https://html.spec.whatwg.org/multipage/syntax.html#determining-the-character-encoding

**Comment by domenic** [comment]
We'd also need to introduce some way of feeding jsdom a byte string instead of a string, so that decoding even is meaningful.
