### ISSUE TITLE
Add optional support for image loading through Canvas.Image

### ISSUE THREAD

**Issue by lehni** [tmpvar/jsdom#1365]
Now that there is support for the Canvas API through node-canvas, I think it makes sense to also support image loading through the `Canvas.Image` class from the same module.

I am willing to work on this, but would need a few pointers, as I am new to the JSDom internals.

I have looked at the `HTMLCanvasElementImpl` class and understand roughly how to patch this into `HTMLImageElementImpl`. The main problem I am currently facing is that I'm not sure how i am supposed to load the binary image files. Should I use `resourceLoader` for this, or ist that only for text files? 

This relates to #189, but since this is about an actual implementation through node-canvas, I thought it might be better to open a separate issue.

**Comment by Sebmaster** [comment]
> Should I use resourceLoader for this, or ist that only for text files?

Yes, resourceLoader is for all resources used for a specific Window. You should fine the resourceLoader in `this.ownerDocument._resourceLoader` (iirc). It takes care of automatically canceling requests when `window.close` is called and firing an error event when the request fails (which might actually not be applicable for every case, but I haven't found one yet, so we've left it in there).

**Comment by lehni** [comment]
Ok, but how to load the binary data with it? So far I have tried:

    resourceLoader.download(url, null, document._cookieJar, null, (error, data) => {...}

As well as:

    resourceLoader.load(this, url, data => {...}

In both cases, data is a string.

**Comment by Sebmaster** [comment]
The actual request is done with the [request](https://github.com/request/request#requestoptions-callback) library, which "specifies" encoding: utf-8 by default, you should be able to provide an option object with that set to null to get a Buffer.

**Comment by lehni** [comment]
Ah, great! This works, I get binary data now:

    resourceLoader.download(value, { encoding: null }, document._cookieJar, null, (error, data) => {...}

**Comment by lehni** [comment]
I have a feeling I should be using `resourceLoader.load` instead, as that appears to be handling the closed windows and all, but there is no way to pass on encoding options to that, unfortunately (it only receives these arguments: `(element, url, callback)`).

**Comment by lehni** [comment]
Another reason for using `resourceLoader.load()` is that only this function handles loading of local files... But there really is no way to pass on the encoding option here. File loading is always done with utf8 encoding also, and the data that it is reading into is a string, not a buffer. It looks like this would require quite a few changes to `resourceLoader`, unfortunately.

**Comment by domenic** [comment]
Please feel free to fix resource loader :)

**Comment by lehni** [comment]
Great, I shall try : )

What do you think is best: To add an optional `encoding` parameter at the end of each function's argument list, behind `callback` (and hence not changing the calling sequence), or to insert it before callback and adjusting all the places where they are called? People maybe expect the callback to be the last argument?

I also wonder if we really need an encoding parameter, or if it's simply a `binary` parameter, indicating we want binary data instead of the default encoding option.

**Comment by lehni** [comment]
Hmm, this is getting more tricky... The way the resource loader is currently implemented, "load" gest triggered as soon as the data is loaded, before the image data is actually parsed. There can still be an error in the data itself, which should not trigger a load event, but an error event instead. Oh dear.

**Comment by lehni** [comment]
Forget that last comment. I can throw an error from the callback and it triggers an error event instead of the load event.

**Comment by lehni** [comment]
So I have created PR #1366 for this. I think it's pretty complete, but there is one open question: I think it would be nice to add a non-standard method similar to `HTMLCanvasElement.toBlob()`, called `HTMLCanvasElement.toBuffer()`, which would allow people to easily export the render image in a node.js enivronment:

```js
var image = new Image();
image.addEventListener('load', function(event) {
    var canvas = document.createElement("canvas");
    canvas.width = canvas.height = 1000;
    var ctx = canvas.getContext('2d');
    ctx.drawImage(image, 0, 0);
    canvas.toBuffer(function(buffer) {
        var fs = require('fs'),
            out = fs.createWriteStream(__dirname + '/out.jpg');
        out.write(buffer);
    }, "image/jpg");
});

image.src = 'http://assets.paperjs.org/images/marilyn.jpg';
```

Alternatively, we could consider adding a non-standard `Blob.buffer` property to `Blob`:

```js
    canvas.toBlob(function(blob) {
        var fs = require('fs'),
            out = fs.createWriteStream(__dirname + '/out.png');
        out.write(blob.buffer);
    }, "image/png");
```

What do you think?

**Comment by domenic** [comment]
Wow, awesome PR! I'm going to have a hard time reviewing it too soon due to standards meetings all week, but I'm excited.

As for nonstandard methods, what we usually do for those is add a `jsdom.canvasToBlob(...)` or `jsdom.blobToBuffer(...)` or similar.

**Comment by lehni** [comment]
Glad you like it! And I can add this, that's easy. `jsdom.canvasToBlob()` isn't needed since that [is standard](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toBlob), but `jsdom.blobToBuffer(...)` would be useful indeed! And `jsdom.canvasToBuffer(...)` might be a nice short-cut to have.

The patch currently fails some tests, I need to look into this another day, as it's late here now.

**Comment by lehni** [comment]
With 2e4db590ced63ab43fe05ca2cae939dd0365b55b, this is now possible:

```js
canvas.toBlob(function(blob) {
    var fs = require('fs'),
        out = fs.createWriteStream(__dirname + '/out.jpg');
    out.write(jsdom.blobToBuffer(blob));
}, "image/jpg");
```

But I may need some help with this one failing test. It seems quite bizarre to me, I am not sure what that particular test is actually trying to achieve.

**Comment by lehni** [comment]
I forgot to mention. The created document needs this setting for the FetchExternalResources feature:

```js
    let document = jsdom.jsdom('<html><body></body></html>', {
        features: {
          FetchExternalResources : ["img"]
        }
    });
```

**Comment by lehni** [comment]
This can be closed as #1366 has been merged in.

**Comment by asturur** [comment]
Hello guys if someone is reading here, i just upgraded to latest jsdom version.
I have some comments in the codebase of fabricjs written before i joined and of wich i fail to determine the root cause:

```
if (fabric.isLikelyNode) {
        replacement.src = canvasEl.toBuffer(undefined, fabric.Image.pngCompression);
        // onload doesn't fire in some node versions, so we invoke callback manually
        _this._element = replacement;
        !forResizing && (_this._filteredEl = replacement);
        callback && callback(_this);
      }
```

Can we say that with latest jsdom the image.onload event should be fired 100% sure?

**Comment by asturur** [comment]
i meant, using:
```
var document = jsdom.jsdom('<html><body></body></html>', {
    features: {
      FetchExternalResources : ['img']
    }
});
```
and no errors going on,
can i trust image.onload with node-canvas?

**Comment by lehni** [comment]
@asturur yes with this configuration, no issues are currently known. That's how we're using it in https://github.com/paperjs/paper.js

Cheers!

**Comment by asturur** [comment]
@lehni i m trying to improve fabricjs support for node since jsdom should provide all i need since version 9.

i m stuck with images and dataurls and can't figure how. Are you available for some help in case?

**Comment by asturur** [comment]
@lehni i m trying to improve fabricjs support for node since jsdom should provide all i need since version 9.

i m stuck with images and dataurls and can't figure how. Are you available for some help in case?
