### ISSUE TITLE
base tag not respected for `link` urls

### ISSUE THREAD

**Issue by jamietre** [tmpvar/jsdom#1373]
After updating from 7.2.2 to 8.0.2, the html `base` tag seems to be ignored.

Snippet:

    <head>
        <base href="http://localhost:5000/">
        <link href="styles/style.css">
    </head>

This results in:

    Error: ENOENT: no such file or directory, open '..\report-server\styles\style.css'

stacktrace:

    Error: Could not load link: "styles/style.css"
        at ...\code\report-server\node_modules\jsdom\lib\jsdom\browser\resource-loader.js:36:21
        at Object.check (..report-server\node_modules\jsdom\lib\jsdom\living\nodes\Document-impl.js:83:11)
        at ReadStream.<anonymous> (..\report-server\node_modules\jsdom\lib\jsdom\living\nodes\Document-impl.js:101:12)
        at ReadStream.wrappedEnqueued (..\report-server\node_modules\jsdom\lib\jsdom\browser\resource-loader.js:200:16)
        at emitOne (events.js:77:13)
        at ReadStream.emit (events.js:169:7)
        at fs.js:1682:12
        at FSReqWrap.oncomplete (fs.js:82:15)

**Comment by domenic** [comment]
That is not a valid base URL, I am pretty sure. I doubt that code works in a web browser.

**Comment by jamietre** [comment]
Sorry that wasn't a cut and paste, I fixed it. The HTML has not chagned since I updated, it used to work.

**Comment by domenic** [comment]
It's quite possible that by increasing spec compliance we made things that used to work, stop working.

Can you produce a full code snippet, that I can run with `node test.js`, showing the problem?

**Comment by jamietre** [comment]
Sure, I'll work it up.

**Comment by jamietre** [comment]
https://github.com/jamietre/jsdom-base-url-issue

**Comment by domenic** [comment]
Thanks, will investigate!

**Comment by jamietre** [comment]
Thanks. I just updated the repo to correct some confusing things that were result of my haste... but the changes have effect on the outcome.
