### ISSUE TITLE
Web platform tests for XHR have started failing

### ISSUE THREAD

**Issue by domenic** [tmpvar/jsdom#1380]
Master was fine, I re-ran the build, now it is not fine: https://travis-ci.org/tmpvar/jsdom/jobs/107099285

I wonder if one of our dependencies changed.

**Comment by dmethvin** [comment]
Based on the tests that are failing, it sounds like the Node 5.6.0 security update.

https://nodejs.org/en/blog/vulnerability/february-2016-security-releases/

**Comment by domenic** [comment]
Oooh, good catch, thank you!!! I wouldn't have figured that out for a long time.

**Comment by domenic** [comment]
Based on https://github.com/nodejs/http-parser/issues/281 I think we might just need to disable these tests until either Node fixes itself or we write a whole new HTTP parser from scratch :(
