### ISSUE TITLE
parentWindow vs defaultView

### ISSUE THREAD

**Issue by samarpanda** [tmpvar/jsdom#1381]
## parentWindow vs defaultView

Is it the same as document, where `parentWindow` works in IE and `defaultView` works for all other browsers?

Wondering while setting up a react test suite using jsdom. Below works fine
```js
var jsdom = require('jsdom');

global.document = jsdom.jsdom('<!doctype html><html><body></body></html>');
global.window = document.defaultView;
```

Below error's out: TypeError: Cannot read property 'addEventListener' of undefined
```js
var jsdom = require('jsdom');
global.document = jsdom.jsdom('<!doctype html><html><body></body></html>');
global.window = document.parentWindow;
```

Any reason why 2nd option doesn't seems to be working?

**Comment by domenic** [comment]
Yes, parentWindow is a nonstandard IE-only property. Since jsdom is not IE, we don't support it.

**Comment by samarpanda** [comment]
@domenic :+1: Thanks. Closing the issue.
