### ISSUE TITLE
Event handler objects are not `this` in handleEvent.

### ISSUE THREAD

**Issue by thetalecrafter** [tmpvar/jsdom#1382]
The snippet `addEventListener('click', { handleEvent() { console.log(this) } }, false)` will log the object passed in all major browsers, but logs the window object in jsdom.

https://dom.spec.whatwg.org/#concept-event-listener-invoke doesn't seem to necessarily require the current browser behavior, but it would nice to be consistent.

**Comment by Sebmaster** [comment]
Thaaaat's a regression. Weird that we have no test for that though...

**Comment by domenic** [comment]
@Sebmaster want to implement callback interfaces in webidl2js? ^_^

**Comment by Sebmaster** [comment]
Can't actually repro this.

```js
'use strict';

const jsdom = require('./');

const doc = jsdom.jsdom();
doc.body.addEventListener('click', {
    handleEvent(e) {
        console.log(this); // HTMLBodyElement
    }
})

doc.body.dispatchEvent(new doc.defaultView.Event('click'));
```

works fine. Please attach a test case so we can investigate this.

**Comment by thetalecrafter** [comment]
It shouldn't be `HTMLBodyElement`. It should be object `{ handleEvent }`.

**Comment by Sebmaster** [comment]
Ahhhh, I see, we can do that.

**Comment by thetalecrafter** [comment]
I can try to fix in a PR if you'd like.

**Comment by thetalecrafter** [comment]
Is `lib/jsdom/living/events/EventTarget-impl.js` the right place to make a change? I thought I saw this implementation as generated code before, and was a little nervous to touch it.

**Comment by domenic** [comment]
Yep, that should do it. In your local checkout there will also be generated code, in a folder called `generated`, but that you can ignore. Just be sure to add a new web-platform-test!

**Comment by domenic** [comment]
A good place to add the test would be `test\web-platform-tests\to-upstream\dom\events\EventTarget-this-of-listener.html`
