### ISSUE TITLE
expose the 'hidden' property

### ISSUE THREAD

**Issue by aaronshaf** [tmpvar/jsdom#1385]
https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/hidden

**Comment by domenic** [comment]
I don't understand what this is asking for. jsdom already supports `getAttribute("hidden")` and `setAttribute("hidden", "")`.

**Comment by domenic** [comment]
It also already supports the `el.hidden = true`/`el.hidden = false` property: https://github.com/tmpvar/jsdom/blob/1fe6566fed57890edb89c96660bca07bfc5ccba1/lib/jsdom/living/nodes/HTMLElement.idl#L10
