### ISSUE TITLE
Missing xmldom

### ISSUE THREAD

**Issue by ThisIsJohnBrown** [tmpvar/jsdom#1392]
Using Node.js v5.6.0 and jsdom v8.0.4.

Had a `missing module xmldom` error when installing.

`npm install xmldom` got the whole thing working, but seems like an issue with dependencies.

**Comment by Joris-van-der-Wel** [comment]
Afaik, jsdom does not use xmldom. So it seems this is either an issue in a different package or your own project.

**Comment by yaycmyk** [comment]
I've noticed that occasionally in npm3, nested dependencies go missing. Could be the case here.

**Comment by Joris-van-der-Wel** [comment]
Upgrading a project from npm 2 to 3 usually fails for me so i delete the entire node_modules directory before upgrade.

**Comment by domenic** [comment]
Yeah, not much we can do here since we don't actually use this package.
