### ISSUE TITLE
Unexpect behaviour using non-standard HTML tag image

### ISSUE THREAD

**Issue by ncuillery** [tmpvar/jsdom#1394]
When I set the innerHTML of an element with `<image></image>`, the tag is transformed to the standard image tag `img`.

It seems to happen only with innerHTML. To reproduce: (copy-paste from the README.md)

```javascript
var jsdom = require("jsdom");

jsdom.env(
  "https://iojs.org/dist/",
  ["http://code.jquery.com/jquery.js"],
  function (err, window) {
    console.log("there have been", window.$("a").length - 4, "io.js releases!");

    // Start here
    var elementDiv = window.document.createElement('div');
    elementDiv.innerHTML = '<image></image>';
    console.log(elementDiv.firstChild.outerHTML); // ---> <img>

    var elementImg = window.document.createElement('image');
    console.log(elementImg.outerHTML); // ---> <image></image>
  }
);
```

If you are wondering why I filled this twisted issue: I use Jest (testing framework based on jsdom) to test a React application. I used to mock my image components by creating dummy "image" component `TestUtils.mockComponent(MyImageComponent, 'image');` and since React 0.14, React renders these components with innerHTML instead of createElement: https://github.com/facebook/react/pull/4611/files#diff-c66701e4ca8fce9507233d224556a71dR994

I can easily fix my tests by using an another dummy tag ("myimage"). I just thought you would be interested in knowing this inconsistency

**Comment by dmethvin** [comment]
http://stackoverflow.com/questions/11928566/img-vs-image-tag-in-html

**Comment by inikulin** [comment]
@ncuillery This is consistent with browsers and specs. HTML spec says to replace any occurrences of the `<image>` in the **markup** for the historical reasons. Meanwhile, then you create element manually via DOM this rules doesn't apply because there is no parsing happening.

**Comment by ncuillery** [comment]
OK it makes sense :smile: Thanks for the explanation.
