### ISSUE TITLE
Bug when parsing self closing a tag

### ISSUE THREAD

**Issue by thanosk** [tmpvar/jsdom#1395]
I think jsdom (currently version 8.0.4) does not handle correctly self closing a tags, i.e. `<a id="myid" />`

This is my reference code:
```
#!/usr/bin/env node

var fs = require('fs');
var jsdom = require('jsdom');
var parse5 = require('parse5');
var xmlserializer = require('xmlserializer');

var page_file = process.argv[2];

var doc = jsdom.jsdom(fs.readFileSync(page_file, 'utf8'), {});
console.log(doc.documentElement.outerHTML);
```

This is the valid xhtml I feed it with:

```
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
    <title>my title</title>
    <meta http-equiv="Content-Type" content="application/xhtml+xml; charset=utf-8" />
</head>
<body>
    <p>
        <a id="myid" />
    </p>
</body>
</html>
```

jsdom produces invalid xhtml (notice the repeated a tag and the empty lines):

```
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en"><head>
    <title>my title</title>
    <meta http-equiv="Content-Type" content="application/xhtml+xml; charset=utf-8">
</head>
<body>
    <p>
        <a id="myid">
    </a></p><a id="myid">


</a></body></html>
```

If I use `<a id="myid"></a>` instead, there are no problems.
Can you fix it in a future release, please ? :-) 
TIA

**Comment by inikulin** [comment]
By default jsdom parses page in HTML mode. Since XHTML is XML you need to set `config.parsingMode` to `xml` (see: https://github.com/tmpvar/jsdom#how-it-works).

**Comment by thanosk** [comment]
Oh sorry guys for opening this issue, then. I was initially aware of the parsingMode, but then saw its side-note and unconsciously thought I should not use it. Thanks for the quick reply.

**Comment by noelelias** [comment]
Solution for preparing the HTML before sending it off to jsdom:
```
const contentPrecompile = (content) => {
  return content.replaceAll(/<(.*?) .*?\/>/gm, (match, tagName) => {
    return `${match.slice(0, -2)}></${tagName}>`;
  });
```

**Comment by jkingsummit** [comment]
> By default jsdom parses page in HTML mode. Since XHTML is XML you need to set `config.parsingMode` to `xml` (see: https://github.com/tmpvar/jsdom#how-it-works).

`parsingMode` doesn't seem to be mentioned on the page you referenced.  I'm glad this issue existed because I didn't find this any other way.
