### ISSUE TITLE
Text.wholeText Support

### ISSUE THREAD

**Issue by livoras** [tmpvar/jsdom#1397]
According to https://developer.mozilla.org/en-US/docs/Web/API/Text/wholeText, in normal browsers

```
var text = document.createTextNode('some text')
console.log(text.wholeText) // => 'some text'
```

but in `jsdom` it gets 'undefined'.

**Comment by domenic** [comment]
Yep, this is unimplemented. See Contributing.md for instructions on how to submit a pull request with proper implementation, tests, etc.
