### ISSUE TITLE
ajax calls which return response with charset=utf-16 not parsed correctly

### ISSUE THREAD

**Issue by alvarorahul** [tmpvar/jsdom#1398]
Digging a bit into this, it turns out that in xmlhttprequest.js, responseBuffer.toString() which seems to be causing the issue

If I try passing in responseBuffer.toString("ucs2") things start working

**Comment by Sebmaster** [comment]
We don't do any encoding stuff at all yet. Byte streams are always assumed to be utf8. See also https://github.com/tmpvar/jsdom/issues/1364#issuecomment-173748986.

**Comment by alvarorahul** [comment]
I took a stab at addressing this in the following pull request #1400 
The fix is limited to the response buffers returned in XmlHttpRequest, If you think this is ok, I can add tests for it.
