### ISSUE TITLE
application/json throws exception in virtualConsole

### ISSUE THREAD

**Issue by Jpunt** [tmpvar/jsdom#1402]
Let's say you've got this page:

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <script type="application/json" id="json">
      { "test": 42 }
    </script>
    <script type="text/javascript">
      console.log('hi');
    </script>
  </body>
</html>
```

and fetch it with:

```js
const jsdom = require('jsdom');

const virtualConsole = jsdom.createVirtualConsole();
virtualConsole.sendTo(console);

jsdom.env({
  url: 'http://localhost:8000/',
  features: {
    FetchExternalResources: ['script'],
    ProcessExternalResources: ['script'],
  },
  virtualConsole: virtualConsole,
  done: (err, window) => {
    if (err) throw err;
    const json = JSON.parse(window.document.querySelector('#json').innerHTML);
    console.log('json:', json);
  }
})
```

you'll get the following output:

```
Error: Uncaught [SyntaxError: Unexpected token :]
    at reportException (/Users/Jasper/Desktop/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:56:24)
    at processJavaScript (/Users/Jasper/Desktop/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:73:7)
    at HTMLScriptElementImpl._eval (/Users/Jasper/Desktop/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:27:7)
    at /Users/Jasper/Desktop/node_modules/jsdom/lib/jsdom/browser/resource-loader.js:25:22
    at Object.check (/Users/Jasper/Desktop/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:83:11)
    at /Users/Jasper/Desktop/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:101:12
    at HTMLScriptElement.<anonymous> (/Users/Jasper/Desktop/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:18:74)
    at invokeEventListeners (/Users/Jasper/Desktop/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:209:27)
    at HTMLScriptElementImpl._dispatch (/Users/Jasper/Desktop/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:129:9)
    at HTMLScriptElementImpl.dispatchEvent (/Users/Jasper/Desktop/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:91:17) [SyntaxError: Unexpected token :]
hi
json: { test: 42 }
```

I can't figure out exactly what causes this, but:

- it doesn't fail when the `features`-config is removed
- it doesn't fail when the `script`-element is replaced by a `div`
- It still fails when the code in `done` is removed (so it seems to be before this point)
- the rest of the page seems to function fine (as 'hi' is still logged)

**Comment by domenic** [comment]
Hmm! My guess is it's executing all scripts as JS, instead of only the ones with the correct or missing type atribute. Nice catch!

**Comment by Jpunt** [comment]
Ah, that sounds reasonable, thanks :+1:

**Comment by Jpunt** [comment]
I've got it down to this fix: https://github.com/Jpunt/jsdom/commit/4e0fb58d54778443104e9a8f4f8d623ae6334d3c

I'm not very familiar to the codebase, but does it make sense? It solves the problem for me and all tests seem to run ok (except some that also didn't run before this change). 

I'm struggling a bit where to write a new test for this change, could you point me at the right direction? Of course, *if* you agree to this fix :)

**Comment by domenic** [comment]
That's the right place in the codebase, but the wrong fix. We need to support all of https://html.spec.whatwg.org/#javascript-mime-type

For tests, check out Contributing.md for some guidelines. (Some web-platform-tests might already exist for this, which would be great.) If they don't then maybe adapt one from https://jsfiddle.net/uyge274e/ which I saw last time this came up in Chromium.

**Comment by Jpunt** [comment]
Alright, how about something like this? https://github.com/tmpvar/jsdom/commit/69dcdedc7e6dafd136627e1a0f502b2092c9f321

I'll look into testing as soon as I can :+1:

**Comment by domenic** [comment]
Looks pretty reasonable, just use a Set instead of an array, and pull the set declaration outside the function so you aren't re-creating it every time the function is called. Thanks for working on this!

**Comment by Jpunt** [comment]
roger that, will take a look at that tomorrow.
