### ISSUE TITLE
EventTarget constructor name is "Window"

### ISSUE THREAD

**Issue by TimBarham** [tmpvar/jsdom#1404]
This isn't a huge issue, but I report it for the sake of consistency: the `EventTarget` constructor appears to be the `Window` constructor, so `constructor.name` for the `EventTarget` prototype returns "Window":

``` js
var jsdom = require('jsdom');
jsdom.env('', function (err, win) {
    var element = win.document.createElement('div');

    var htmlDivElementProto = Object.getPrototypeOf(element);
    console.log(htmlDivElementProto.constructor.name + ' (expect "HTMLDivElement")');

    var htmlElementProto = Object.getPrototypeOf(htmlDivElementProto);
    console.log(htmlElementProto.constructor.name + ' (expect "HTMLElement")');

    var elementProto = Object.getPrototypeOf(htmlElementProto);
    console.log(elementProto.constructor.name + ' (expect "Element")');

    var nodeProto = Object.getPrototypeOf(elementProto);
    console.log(nodeProto.constructor.name + ' (expect "Node")');

    var eventTargetProto = Object.getPrototypeOf(nodeProto);
    console.log(eventTargetProto.constructor.name + ' (expect "EventTarget")');
});
```

The final line outputs `Window (expect "EventTarget")`

Like I said, no biggie, but unexpected when walking the prototype chain of an HTML element :smile:.

**Comment by domenic** [comment]
My bet is that we're not resetting .constructor correctly when setting up the inheritance hierarchy. Nice find.

**Comment by Sebmaster** [comment]
We overwrite the constructor of EventTarget [here](https://github.com/tmpvar/jsdom/blob/master/lib/jsdom/utils.js#L94). We should probably just Object.create, instead of using our own util method - it sucks, tbh.
