### ISSUE TITLE
thoughts about window.navigator.noUI and page visibility api

### ISSUE THREAD

**Issue by kapouer** [tmpvar/jsdom#1405]
Hi,
this is a follow-up of https://github.com/tmpvar/jsdom/issues/642.

The [Page visibility API](https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API) looks like a way for client code to know if it's running in a "half browser" or not:
`document.visibilityState == "prerender"`

I like that because:
* it does not define a non standard property
* for some use cases (isomorphic server rendering) the name is natural
* the check is harmless, browsers not supporting the api return undefined
* it might not even be up to jsdom to set that value - userland can set it to prerender
in its server rendering code if needed.

**Comment by domenic** [comment]
Interesting. I'd be open to changing this (and removing noUI). Pull request welcome. You'd want to implement the IDL at https://www.w3.org/TR/page-visibility/#sec-document-interface using the new IDL-based architecture discussed in https://github.com/tmpvar/jsdom/blob/master/Contributing.md#architecture

**Comment by kapouer** [comment]
Ok, so can you have a quick look at
https://github.com/kapouer/jsdom/commit/78bfd15688c79008797bab24af6a1525bae40fc4 ?

The choices i've made to always return true for "hidden" and "prerender" for visibilityState seem all right - but you probably have a better grasp of which default values they should be.

**Comment by kapouer** [comment]
Also please check https://github.com/kapouer/jsdom/commit/e1d481be523edd6a61d06c36a210f00ac3460202;
which calls for two decisions to make:
1. do you want to deprecate `navigator.noUI` before removing it ?
2. what is the best replacement to advise ? `document.hidden` or `document.visibilityState == 'prerender'` ?

`document.hidden` can happen quite often in various situations on a real browser with UI.
I met the `prerender` state on Safari 9 when i started typing the url of a recently visited web page i developed using a client-side library that actually manages the prerender state. Interestingly, Safari runs the web page with that visibilityState, and emits the `visibilitychange` event when the page becomes visible.
What i like about prerender is the fact that in both cases (server jsdom or client prerendering) the meaning is the same.

**Comment by domenic** [comment]
> do you want to deprecate navigator.noUI before removing it ?

We can just leave it in until the next major version. Add a `// TODO MAJOR` to do so.

> what is the best replacement to advise ? document.hidden or document.visibilityState == 'prerender' ?

The latter sounds better to me, I agree.
