### ISSUE TITLE
Unreliable Object.getOwnPropertyNames

### ISSUE THREAD

**Issue by WebReflection** [tmpvar/jsdom#1409]
I've just discovered a very weird and unexpected behavior with the `jsdom.window` on node `v5.7.0`

```js
var window = require('jsdom').jsdom().defaultView;
Object.keys(window).every(
  function(k){return~this.indexOf(k)},
  Object.getOwnPropertyNames(window)
);
```

I would expect that `Object.getOwnPropertyNames` list includes all `Object.keys` too but this is upside down so that `Object.keys(window).length` is `205` but `Object.getOwnPropertyNames(window).length` is `49`

In order to have the list of all own keys I need to concatenate both operations.

Is this an expected behavior? Thanks.

**Comment by domenic** [comment]
This is https://github.com/nodejs/node/issues/3158.

**Comment by WebReflection** [comment]
I see, I couldn't understand what the hack was going on. Thanks for the info.
