### ISSUE TITLE
Unable to test templateUrl with angular directives

### ISSUE THREAD

**Issue by winnemucca** [tmpvar/jsdom#1411]
We are trying unit testing our angular directives with jsdom.  It is simple enough to test controllers and services, but we are running into issues testing directives.   I have a global window for angular and am requiring angular mocks in the setup.  

````
global.angular = global.window.angular;

require('angular-mocks/angular-mocks');
`````

I tried to  make a XMLHttpRequest but the request came back as not defined.  I am doing this on node, so it seems to be an issue.  I am wondering can this be done?  
````
                       var directiveTemplate = null;
			var req = new XMLHttpRequest();
			req.onload = function () {
				directiveTemplate = this.responseText;
			};
			req.open("get", "../../partials/directiveTemplate.html", false);
			req.send();
````

**Comment by domenic** [comment]
You should not add things to Node's globals. Instead, you need to run any script (such as your XHR-doing script) inside the jsdom itself, by using `window.createElement("script")` and such.

**Comment by winnemucca** [comment]
In the case that I want html files though I would not use   
````
window.createElement("script") 
````
right?   I want the have all of the files from a module available for the tests.   
I cannot require html files with node.  But I thought that I could `require('fs')`.   

Can we use `jsdom.env(config);`  To access a html file?  I see there are ways to access html fragments.

**Comment by domenic** [comment]
If you want HTML files you would use `fs.readFile` + `jsdom.jsdom`, or you would use `jsdom.env`, yes. (It has a `file:` option IIRC.)

**Comment by winnemucca** [comment]
It is `config.file`  

I should be able to figure this out the more that I play with it, but I am wondering can we set it up as an object?

```
jsdom.env({
	html: '../../Templates/explore-hero-base-template.html'
});

```
But is the callback necessary to do some configuring of its own?  Or can we pass a created or onload option?

**Comment by Sebmaster** [comment]
If you use `html` you can't pass a path, you have to pass the raw html.

> Or can we pass a created or onload option?

`done` should be good enough, unless you want to do some shimming work before your html is loaded, then _add_ `created`.

**Comment by winnemucca** [comment]
I'll customize it more after I get the tests working.   Goal for right now is just to set it up correctly.  

I set my file up as so

   ````
var jsdom = require('jsdom').jsdom;

global.document = jsdom('<html><head><script></script></head><body></body></html>');
global.window = global.document.defaultView;
global.navigator = window.navigator = {};
global.location = global.window.location;
global.Node = window.Node;
global.HA = global.window.HA || {}
global.HA.cdn = global.window.cdn || {}

require('angular/angular');
global.window.jQuery = require('jquery');

global.window.mocha = {};
global.window.beforeEach = beforeEach;
global.window.afterEach = afterEach;

global.jQuery = global.window.jQuery;
global.angular = global.window.angular;

require('angular-mocks/angular-mocks');


jsdom.env({
	file: '../../Templates/explore-hero-base-template.html',
	done: function (err, window) {
		var $ = window.$;
		console.log($);
	}
});


````

However, before I can do anything in the done block I must figure out why I would get 
`ReferenceError: jsdom is not defined`

This seems to be an odd error message for syntax.   Is there more to defining **done**?

**Comment by RobbertWolfs** [comment]
Any progress on this issue?

**Comment by winnemucca** [comment]
No, I had time constraints and had to move to Karma to get my testing done
quickly.

**Comment by RobbertWolfs** [comment]
No problem, I used a quick fix. 
I used pug (previous jade) as template engine so I did this in a beforeEach so my template was rendered and returned as html.

```
beforeEach(() => {
        $httpBackend
                              .whenRoute('GET', './studio/components/nav-bar.component.html')
                              .respond(pug.renderFile('./app/studio/components/nav-bar.component.pug'));
    });
```

**Comment by RobbertWolfs** [comment]
My solution fails when trying to access the element controller afterwards... So if anyone has a better solution it would be appreciated..
