### ISSUE TITLE
failures when used in test262

### ISSUE THREAD

**Issue by WebReflection** [tmpvar/jsdom#1413]
this is probably not the highest priority ever for this project but I was running a DOM simulation and some conformance with [test262](https://github.com/tc39/test262) when I've realized that `built-ins/Array/of/does-not-use-prototype-properties` fails like a charm so I had to blacklist it (and waste a decent amount of time to understand it wasn't my code failing but jsdom).

If you go in `Document.js` file you can see a lot of loops used to populate an array and use it to apply some other function.

```js
Document.prototype.createEvent = function createEvent(_interface) {
  if (!this || !module.exports.is(this)) {
    throw new TypeError("Illegal invocation");
  }
  if (arguments.length < 1) {
    throw new TypeError("Failed to execute 'createEvent' on 'Document': 1 argument required, but only " + arguments.length + " present.");
  }

  // here one cause of the problem
  const args = [];
  for (let i = 0; i < arguments.length && i < 1; ++i) {
    // setting index 0 like this passes through the prototyope
    args[i] = utils.tryImplForWrapper(arguments[i]);
  }
  // same here
  args[0] = conversions["DOMString"](args[0]);
  return utils.tryWrapperForImpl(this[impl].createEvent.apply(this[impl], args));
};
```

There are many similar loops like that and all of them could be swapped via `const args = {length: arguments.length};` or, when some index is set regardless, `const args = {length: Math.max(arguments.length, 2)};` or similar approach.

This would guarantee that `test262` logic won't be corrupted by this module and when `Array.of` is tested like the following:
```js
Object.defineProperty(Array.prototype, "0", {
  set: function(v) {
    $ERROR('Should define own properties');
  }
});

var arr = Array.of(true);
assert.sameValue(arr[0], true);
```
and there is a DOM around that should simply trigger events and propagate errors possibly without interfering with the environment, nothing bad happens.

However, since apparently there's not a single bug related to `test262` and jsdom, does anyone actually care at all about this?

If yes, I might try to put some effort into fixing all loops of this project and avoid corrupted operations when `Array.prototype` is poisoned but I'd like to know if such PR would be even accepted since it feels like I'm better off blacklisting few tests and ignore the fact I can't fully trust the fake DOM environment when it runs under test262 via node, instead of via browser.

Thanks in advance for any sort of outcome.

**Comment by domenic** [comment]
Like most node packages, jsdom is not meant to operate in an environment with poisoned built-ins. Thanks for checking.

**Comment by WebReflection** [comment]
fair enough
