### ISSUE TITLE
Specify required version of Node

### ISSUE THREAD

**Issue by lehni** [tmpvar/jsdom#1418]
Given the new dependency on modern JS, I am wondering if it wouldn't make sense to add something along these lines to `package.json`?

```json
  "engines": {
    "node": ">=4.0.0"
  },
```

**Comment by domenic** [comment]
This is taken care of with feature detection instead of user agent sniffing: https://github.com/tmpvar/jsdom/blob/master/lib/jsdom.js#L3

**Comment by lehni** [comment]
Oh, I see. Out of curiosity: What's the reasoning behind not specifying it in package.json?

**Comment by domenic** [comment]
I googled around a bit and found https://www.nczonline.net/blog/2009/12/29/feature-detection-is-not-browser-detection/. This is a pretty old discussion.

**Comment by yaycmyk** [comment]
I don't really understand this decision either. Part of the benefit of the `engines` functionality is to be an early warning system to someone using the module that it won't work on their system. Why even let someone get all the way through installing it and all the dependencies before having it fail?

Seems like bad developer UX.

**Comment by lehni** [comment]
I agree... While feature detection makes sense in a browser environment where user agents can be spoofed, and I never thought that the same was necessary for Node.js
