### ISSUE TITLE
Expose request API

### ISSUE THREAD

**Issue by thiagofelix** [tmpvar/jsdom#1419]
Looking at line: [resource-loader.js#L160](https://github.com/tmpvar/jsdom/blob/master/lib/jsdom/browser/resource-loader.js#L160)

Is there any problem in exposing the whole [request](https://github.com/request/request) API from the resourceLoader.download method extended with the abort() function which current exists?

The use case is to pipe the request result stream to [iconv-lite](https://www.npmjs.com/package/iconv-lite) and use a different character encoding to decode **incrementally**.

Thanks

**Comment by domenic** [comment]
Well, we definitely don't want to expose implementation details like which library we're using to do fetches. And we don't support incremental parsing at the moment. But if you want to use `request` yourself, you can certainly use that instead of using `defaultFetch`. Does that answer the question?
