### ISSUE TITLE
Remove default encoding

### ISSUE THREAD

**Issue by thiagofelix** [tmpvar/jsdom#1420]
According to the [request](https://github.com/request/request) documentation:
> encoding - Encoding to be used on setEncoding of response data. If null, the body is returned as a Buffer. Anything else (including the default value of undefined) will be passed as the encoding parameter to toString() (meaning this is effectively utf8 by default)

It will by default use 'utf-8', so why jsdom ensure encoding 'utf-8' is set by default?
[jsdom.js#207](https://github.com/tmpvar/jsdom/blob/master/lib/jsdom.js#L207)

The problem with that is that it is not possible to force encoding to be null and apply a custom encoding system afterwords, it always encode as utf-8.

Any thoughts?

**Comment by domenic** [comment]
I don't quite understand what the bug is here. Are you objecting to us being explicit and using the string `'utf-8'` instead of omitting it? Or is jsdom displaying incorrect behavior in some way? If so, please provide a repro case?
