### ISSUE TITLE
SVGElement is not implemented

### ISSUE THREAD

**Issue by Tpower36** [tmpvar/jsdom#1423]
Hi,
I'm new with using jsdom and I did not find an answer in the documentation. In a old example from 2014 someone used this code to support svg features:
`doc.implementation.addFeature(`
  `'http://www.w3.org/TR/SVG11/feature#BasicStructure', '1.1'`
`)`
In the latest versions of jsdom this does not work because addFeature is not a function. Is there a way to enable SVG 1.1?

**Comment by domenic** [comment]
Such code would never have worked in jsdom. I'm not sure where you found it. (It would have done nothing, whereas now it throws.)

What do you mean by "enable SVG 1.1?" What is some example code that works in browsers but not in jsdom?

**Comment by Tpower36** [comment]
I try to use a library called svg.js in Node.js and it doesn't work because SVGElement is not defined. Here is my code:

	`var jsdom = require("jsdom").jsdom;`
	`var document = jsdom("<div id='drawing'></div>");`
	`var window = document.defaultView;`
	`var doc = window.document;`
	
	`var svgjs = require('svg.js')(window)`

**Comment by domenic** [comment]
Yes, SVGElement is not yet implemented in jsdom. Pull request welcome!

**Comment by Tpower36** [comment]
Okay, thanks for your fast answer

**Comment by nhunzaker** [comment]
I'm interested in helping out here if I can. What is the status of https://github.com/tmpvar/jsdom/pull/1445?

**Comment by domenic** [comment]
It seems pretty stalled to me :(

**Comment by nhunzaker** [comment]
No worries. 

@Fuzzyma Where do you stand with https://github.com/tmpvar/jsdom/pull/1445? Anything I can to do help, or pick up the work?

**Comment by Fuzzyma** [comment]
All the code available is in the PR I think. Atm I do not have time to follow that path further. But I am still interested in this feature. Feel free to pick up the work. I hard trouble digging in the, a it peculiar, code of jsdom :)

**Comment by nhunzaker** [comment]
Feel free to push em up :). It'll take me a while to familiarize myself with JSDOM anyway.

**Comment by Fuzzyma** [comment]
Done - hope it helps more than it creates confusion^^

**Comment by tomitrescak** [comment]
Guys, what is the status on this? Is there any way this can be moved forward? How can I help? It seems that PR is there with some conflicts

**Comment by domenic** [comment]
A pull request is still welcome. That one was abandoned.

**Comment by Fuzzyma** [comment]
if you are using svg.js and need this PR only for using svg.js on node you can tale a look at [svgdom](https://github.com/svgdotjs/svgdom) which aims to make svg.js usable on node.

**Comment by caub** [comment]
I'll try to add some svg support, because I need jsdom for SVGO, for using and adding tests on https://github.com/jarek-foksa/path-data-polyfill.js/ too

SVGElement    (not really needed, maybe it's helpful to allow to put getElementById on it)
SVGPathElement   (needed for path-data polyfill)

It just need to be very basic so, just those class should exist and be associated to the right elements.

is it bad if it's partial? because indeed implemented the full SVG spec would be horrible

**Comment by domenic** [comment]
It's not bad if it's partial, but the parts that are there, need to be implemented according to the SVG spec. (SVG 2, to be precise.)

Be sure to read Contributing.md to get an introduction to how we generate a lot of code from IDL files and such.

**Comment by caub** [comment]
Yes thanks, I did something a bit ridiculous for now https://github.com/tmpvar/jsdom/pull/1946

I can add get/setPathData SVG2 polyfill I linked, I'll first make tests

**Comment by MadhuVaddi** [comment]
@Tpower36 , I made following changes
Version using: jsdom@3.1.2

doc.implementation.addFeature(
'http://www.w3.org/TR/SVG11/feature#BasicStructure', '1.1'
)
 to 
doc.implementation._addFeature(
'http://www.w3.org/TR/SVG11/feature#BasicStructure', '1.1'
)

Mainly, I changed **addFeature** to **_addFeature**

It is working for me..

**Comment by joeyhub** [comment]
Is this fixed? This doesn't necessarily need SVG support for at least minimal XML support. It doesn't really need to be fancy. As far as I can tell by default you're just disappearing unrecognised attributes. Simply not doing that could potentially be enough.
