### ISSUE TITLE
Log full stack trace

### ISSUE THREAD

**Issue by Jpunt** [tmpvar/jsdom#1424]
With the virtual console, it's possible to catch an error-message and log it to a (for instance) node-console:

```js
const virtualConsole = jsdom.createVirtualConsole();
virtualConsole.on('error', (...errors) => console.log(errors));
```

Unfortunately, only the first two lines will be logged. Is it possible to get the full stack trace? Logging with `console.trace` will get the jsdom-part of the stack, not the code running in the jsdom-environment.

**Comment by domenic** [comment]
In some cases `error.detail` contains an original error object.

A small test case showing the problem would be helpful.

**Comment by Jpunt** [comment]
Would you expect for this to work?

```js
virtualConsole.on('error', error => console.log(error.detail));
```

This logs undefined. But you're absolutely right, this conversation would be a bit easier with an isolated test-case. I'll get to it tomorrow (if time) :+1:

**Comment by domenic** [comment]
It's been a while since I touched the code, honestly. I can't really remember any scenarios in which jsdom wraps things up in its own error. (Maybe when window.onerror fires but there's no listeners for it?)

Looking forward to the test case.
