### ISSUE TITLE
XMLHttpRequest doesn't work 

### ISSUE THREAD

**Issue by aaani** [tmpvar/jsdom#1426]
Hello, I have a developed a browser library and I am testing it using mocha and mocking browser environment with [mocha-jsdom](https://github.com/rstacruz/mocha-jsdom). Everything works perfectly except `XMLHttpRequest`. For ex:
```
var oReq = new XMLHttpRequest();
console.log(url);
oReq.addEventListener("progress", updateProgress);
function updateProgress (oEvent) {
    if (oEvent.lengthComputable) {
        var percentComplete = oEvent.loaded / oEvent.total;
        console.log(percentComplete + " completed");
    } else {
        console.log("Length not computable");
        // Unable to compute progress information since the total size is unknown
    }
}
oReq.addEventListener("load", function(){
    callback(JSON.parse(oReq.response));
});

oReq.addEventListener("error", transferFailed);
function transferFailed(evt) {
    console.log("An error occurred while transferring the file.", evt);
}
oReq.open("GET",url);
oReq.send();
```
with above code in my browser lib, none of the callbacks (load, error, or progress) are ever triggered. I have verified that the url is correct and when I try with hardcoded urls say "https://www.google.com" I get the same outcome. (Also above code works when I run it in the browser manually)

This is what my jsdom config looks like:
```
    jsdom({
        url: 'http://localhost:8080',
        src: [
            fs.readFileSync(...),
            //... more dependencies
        ],
    }
    });
```
Please let me know how I can make XMLHttpRequest work in mocha tests.

**Comment by inikulin** [comment]
Seems like https://github.com/tmpvar/jsdom/issues/1203 dup

**Comment by aaani** [comment]
Thanks @inikulin. That solves the main issue. I do have another question for you:
```
 var oReq = new window.XMLHttpRequest();
```
^ This works. But
```
var oReq = new XMLHttpRequest();
```
^ This doesn't. Why?

**Comment by inikulin** [comment]
Because in browser global object is `window` while in node it's obviously not. So you need explicitly specify `window`. Meanwhile, if you execute script by inserting `<script>` element or specifing it in `jsdom.env` as shown in https://github.com/tmpvar/jsdom/issues/1203#issuecomment-160725194 it will be executed in the sandboxed envirionment by jsdom where global object is `window` making it similar to the browsers.
