### ISSUE TITLE
Url in error

### ISSUE THREAD

**Issue by gsouf** [tmpvar/jsdom#1431]
Hi, getting the error message with a problem in the url 'https://github.com/t'  ;)

![screenshot from 2016-03-31 09 44 38](https://cloud.githubusercontent.com/assets/3215399/14168958/646f7eae-f725-11e5-9f79-2d8a51513c0e.png)

**Comment by inikulin** [comment]
Well, you need to use Node.js 4 or newer as it suggests.

**Comment by gsouf** [comment]
Yes I understand the error, I repport the issue because the url is not valid!  /t instead of /tmpvar/jsdom#install

**Comment by inikulin** [comment]
More likely it's a problem with your terminal - it trims chars that doesn't fit the window

**Comment by gsouf** [comment]
Nop, the terminal window is something like 5x larger, and is able to display larger strings

**Comment by gsouf** [comment]
![screenshot from 2016-03-31 11 04 40](https://cloud.githubusercontent.com/assets/3215399/14170922/65654cde-f730-11e5-867b-ed7e7ab4c55e.png)

**Comment by gsouf** [comment]
Well, i'm figuring out that the error is not displayed as a version error, but as a syntax error.

That means the string is not sent, instead node just shows the begning of line with the syntax error, that's why the url is not full

**Comment by domenic** [comment]
Yeah, not much we can do about Node's error display here; maybe file an issue on nodejs/node.

**Comment by gsouf** [comment]
I dont now much about node, but maybe you can bootstrap the application from a compatible file to display a cooler error for old nodejs?
