### ISSUE TITLE
ability to eval script when ProcessExternalResources = []

### ISSUE THREAD

**Issue by kapouer** [tmpvar/jsdom#1437]
Hi,
this might be a feature request, but for now it's a question:
i need to load an html document into a DOM and not execute "onload" attributes nor scripts,
yet still be able to run user scripts in the window context. To achieve that, i contextify window
just after creation, and use window.eval where needed.
This can be useful to transform an existing document in a browser environnement but without
actually "running" it - typically, in [the prepare phase of express-dom](https://github.com/kapouer/express-dom).
However it seems jsdom executes the onload attribute if window has been contextified !
It looks a little like a bug - shouldn't jsdom check document features instead of availability of a contextified window ? Or maybe i overlooked the code and am missing something ?

**Comment by domenic** [comment]
This will be accomplished in [newapi](https://github.com/tmpvar/jsdom/blob/newapi/lib/newapi1.md) by `{ runScripts: "outside-only" }`.

**Comment by kapouer** [comment]
FYI in webkitgtk i manage to prevent the default behavior with a user script that sets up a MutationObserver before the document is parsed and that fiddles with scripts type and removes onload inline attribute and re-adds it just after insertion, and also by preventing load of remote scripts. Despite being not easy it's possible and has stayed effective through several releases.
