### ISSUE TITLE
Error Serializing Inherited Attributes

### ISSUE THREAD

**Issue by deckar01** [tmpvar/jsdom#1442]
Extending the `Object.prototype` causes `Element.outerHTML()` to break.

```js
var jsdom = require('jsdom');

Object.prototype.test_name = 'test_value';

var dom = jsdom.jsdom('<div id="0"></div>');

var div = dom.getElementById('0');

console.log(div.test_name);
console.log(div.outerHTML);
```

```html
test_value
<div id="0" test_value:test_name="test_value"></div>
```

This tells me that the issue is with the jsdom since its [`documentAdapter`](https://github.com/tmpvar/jsdom/blob/master/lib/jsdom/browser/documentAdapter.js) is being passed to the serializer.

I would expect jsdom to skip attributes inherited from Object.

Oddly if `Object.prototype` is extended after the DOM is initialized it works as expected.

```js
var jsdom = require('jsdom');

var dom = jsdom.jsdom('<div id="0"></div>');

Object.prototype.test_name = 'test_value';

var div = dom.getElementById('0');

console.log(div.test_name);
console.log(div.outerHTML);
```

```html
test_value
<div id="0"></div>
```

I suspect the `HTMLElement` inheritance tree affects the attributes when creating the div, but requires explicit calls through the DOM APIs to change, so the fix will likely be during the attributes initialization.

**Comment by domenic** [comment]
Great minimal test case, thank you. Shouldn't be too hard to fix.

**Comment by deckar01** [comment]
If there is anything I can help with let me know.

It looks like [`test/living-dom/attributes.js`](https://github.com/tmpvar/jsdom/blob/master/test/living-dom/attributes.js) would be a good place to test this behavior. If you don't get to it before I do, I wouldn't mind contributing some tests.

**Comment by domenic** [comment]
I think https://github.com/tmpvar/jsdom/blob/master/test/jsdom/parsing.js would be best, actually.

**Comment by deckar01** [comment]
That makes sense.

**Comment by deckar01** [comment]
I thought about adding a nested `describe` block to handle the global setup in `before` and `after`, but I decided to just setup and teardown in the body of the `specify` since mocha doesn't really offer an `after` utility for a single test.

https://github.com/deckar01/jsdom/commit/baf7189f608578cfb2bcbf3c7062e7fc5787bbe6
