### ISSUE TITLE
Some files in lib/jsdom/living/generated directory require non-existent files

### ISSUE THREAD

**Issue by azotova** [tmpvar/jsdom#1449]
I installed v. 8.3.1 and ran into the following issue. The file `lib/jsdom/living/generated/DOMPointReadOnly` ends with `const Impl = ("../nodes/DOMPointReadOnly-impl.js")`, and the file `../nodes/DOMPointReadOnly-impl.js` doesn't exist. Also, the file 'ScrollIntoViewOptions' contains `const ScrollOptions = require("./ScrollOptions");`, which can't be found too. I am trying to use Webpack and it throws errors because of those require statements. The possible workaround is to use `module.noParse` option in Webpack, but it doesn't work for me for some reason (maybe because the skipped files are expected to have no call to `require`). 
Before that I used v. 8.1.1 of jsdom and don't remember facing this problem. Am I doing something wrong now or is this a jsdom issue? Thanks!

**Comment by Sebmaster** [comment]
It seeeems like something went wrong with publishing there @domenic? Can't find a reference to those files in git or the generated output.

However those files are also not required anywhere, so I guess it's partially a webpack bug in that it tries to parse/execute unreferenced files?

**Comment by domenic** [comment]
Yeah, this is my bad, I had some temporary files on my filesystem while publishing I guess. Will try re-publishing...

**Comment by inikulin** [comment]
~~Shameless plug~~: you definetly need to try https://github.com/inikulin/publish-please =)

**Comment by brcarey** [comment]
Hi @domenic, any idea when we might get the new version?

**Comment by domenic** [comment]
Usually I work on jsdom on weekends, so I'd anticipate Saturday or Sunday.

**Comment by brcarey** [comment]
excellent, thanks very much

**Comment by azotova** [comment]
@domenic  Thank you so much!

**Comment by exah** [comment]
I'm still having issue with jsdom@9.4.1 and Meteor + Webpack

```
=> Errors prevented startup:

   While processing files with webpack:webpack (for target os.osx.x86_64):
   app/server.js: ./~/jsdom/lib/jsdom/living/generated/FileReader.js
   Module not found: Error: Cannot resolve 'file' or 'directory' ../file-api/FileReader-impl.js in
   /Users/john/Developer/Strelka/draft-blog/node_modules/jsdom/lib/jsdom/living/generated
   resolve file
   /Users/john/Developer/Strelka/draft-blog/node_modules/jsdom/lib/jsdom/living/file-api/FileReader-impl.js doesn't exist
   ...
```
