### ISSUE TITLE
jsdom + PhantomJS

### ISSUE THREAD

**Issue by loretoparisi** [tmpvar/jsdom#1450]
Latest `PhantomJS 2.1` is built on top of `Qt.5.5` WebKit. Will `jsdom` run on it?

**Comment by domenic** [comment]
I don't know! You can try it and report back?

Closing since this is not an issue with jsdom.

**Comment by loretoparisi** [comment]
@domenic Ok I will try, I'm aware that `Qt 5.5` is using an old version of WebKit (before ECMA6 for sure), but so far I'm not sure which version is, so only option is to try it!. I will report back then.
