### ISSUE TITLE
disabled not working as expected

### ISSUE THREAD

**Issue by Kflash** [tmpvar/jsdom#1451]
Hi. I created a SELECT element, and set the disabled attribute to true. Then I tried to forward a click handler on it, to see if it got triggered when the element becomes disabled. This was not working.
The element still enabled, and click handler worked. 

I ran this with Mocha + JSDOM.

I then tried the same with Karma and Mocha, and everything worked as expected.

**Comment by domenic** [comment]
Can you provide a small minimal test case, not involving mocha but instead a 5-10 line program with only jsdom as a dependency, reproducing the problem?

**Comment by Kflash** [comment]
I used my own workflow when I tested. And you see my jsdom config here plus link to react issue.https://github.com/Kflash/havunen/blob/master/config/dom.js

So simply enough write a server test and you will see it

**Comment by domenic** [comment]
I'm sorry, we don't accept issues without small repros; we don't have time to debug your application for you. Closing until you are able to provide such a repro.

**Comment by Kflash** [comment]
Not a problem. I swapped to testem and everything works fine. And will just inform others to do the same.

**Comment by domenic** [comment]
Perfect!
