### ISSUE TITLE
Support responseURL attribute in XMLHttpRequest

### ISSUE THREAD

**Issue by eloquence** [tmpvar/jsdom#1455]
The responseURL attribute is useful for obtaining the result of a 301 or 302 redirect. It's currently not supported by jsdom.

https://xhr.spec.whatwg.org/#the-responseurl-attribute

Is there a reason not to implement this? If not, I may take a crack at a PR myself.

**Comment by nicolashenry** [comment]
I missed this attribute when I implemented it. I will try to make [this test](https://github.com/w3c/web-platform-tests/blob/master/XMLHttpRequest/responseurl.html) pass in a PR when I can.
