### ISSUE TITLE
 `jsdom 7.x onward only works on Node.js 4 or newer: https://github.com/t

### ISSUE THREAD

**Issue by noahehall** [tmpvar/jsdom#1459]
/home/ubuntu/fame/node_modules/jsdom/lib/jsdom.js:3
() => `jsdom 7.x onward only works on Node.js 4 or newer: https://github.com/t
 
$ nvm ls
      v5.9.1
->   v5.10.1
      system

What is the issue here?

**Comment by noahehall** [comment]
ubuntu@ip-172-31-14-20:~/fame$ node -v
v5.10.1

**Comment by Sebmaster** [comment]
The node version you're using to execute your project is not the one you're executing with `node -v` probably.

**Comment by noahehall** [comment]
Hmm, how would I determine that?

**Comment by Joris-van-der-Wel** [comment]
```
console.log(process.argv);
```
```
P:\>node foo.js
[ 'C:\\Program Files\\nodejs\\node.exe', 'P:\\foo.js' ]
```

**Comment by noahehall** [comment]
Thanks @Sebmaster  and @Joris-van-der-Wel 

console.log(process.argv) doesnt show the node version

I inserted it at the top of my app.js

[ 'node', '/home/ubuntu/fame/dist/app.js' ]

**Comment by noahehall** [comment]
the cmd im using to start the project
cd project/home
node dist/app.js

So it would have to be the same node v5.1

**Comment by noahehall** [comment]
Thanks for your help!

this also pointed me in the right direction
http://stackoverflow.com/questions/11177954/how-do-i-completely-uninstall-node-js-and-reinstall-from-beginning-mac-os-x

Looks like in /usr/bin there are different versions installed and thats the one its using.

Can I just delete the files in /usr/bin ?

**Comment by noahehall** [comment]
Looks like I now need to tell sudo to use nvm

**Comment by noahehall** [comment]
Boom! this did it
n=$(which node);n=${n%/bin/node}; chmod -R 755 $n/bin/*; sudo cp -r $n/{bin,lib,share} /usr/local

I think I coudl have just put nvm in my path too
