### ISSUE TITLE
Attr not inherting from Node breaks libraries

### ISSUE THREAD

**Issue by mjgp2** [tmpvar/jsdom#1466]
Hi!

I know Attr does not inherit from Node in the latest draft of the DOM4 spec, however all main browsers still have the methods in Attr, albeit they are marked as deprecated.

Not having these methods breaks many libraries as they have not transitioned to DOM4 as it is still a working draft.

Can we put the methods back (albeit it deprecated)?

**Comment by mjgp2** [comment]
Also see: https://github.com/w3c/dom/issues/6

**Comment by domenic** [comment]
We don't have any plans to update this until the spec does. Also, we following https://github.com/whatwg/dom/, not the W3C fork.

I'd suggest filing an issue on the DOM Standard (not the fork) describing real-world web pages which are broken by the change. In the past this has led to adding back some of the old methods.

**Comment by mjgp2** [comment]
Hi @domenic 

My point is that all the main browsers still have `Attr` inheriting from `Node` as well as the extra `ownerElement` property. Understand that this isn't the case in the latest spec.

Firefox actually has made the `ownerElement` property obsolete, which is very confusing:

```
ownerElement Deprecated since Gecko 7.0 Obsolete since Gecko 29.0
This property has been removed from Firefox 29. Since you can only get Attr objects from elements, you should already know the owner.
Contrary to above claim, Document.evaluate can return Attr objects from an XPath, in which case you would not easily know the owner.
```

However they seem to have added it back in, as it is available currently in the browser :/

All in all it seems like a mess and is very confusing :) 

Understand your rationale about following the latest spec, though it's not what browsers do in the wild. Is the goal of jsdom to act like a "regular browser" or to follow the latest spec?

wgxpath is an example of a library that it breaks, and indeed any library that uses `node.type === 2` and so on.
