### ISSUE TITLE
How to access DOM elements appended by ajax fetch?

### ISSUE THREAD

**Issue by coodoo** [tmpvar/jsdom#1475]
I have a page with a "Load More" button, once clicked it will fetch next 10 items and append it to the page. 

Just wondering how do I access these 10 elements? I tried waiting for 10 secs then query the document again but nothing showed up, just want be sure this is a use case supported by jsdom? Thanks.

**Comment by Sebmaster** [comment]
Yes, that should be possible.

**Comment by coodoo** [comment]
That was my thought too but didn't seem to work, mind pointing me at a working example?

Btw, Do I have to explicitly allow external scripts running?

**Comment by Sebmaster** [comment]
You do if you use .env. See [here](https://github.com/tmpvar/jsdom#external-resources).

**Comment by coodoo** [comment]
Unfortunately it still doesn't work, here's a simple test case, mind having a look?

```javascript
var jsdom = require( 'jsdom' );

let url = 'http://www.nytimes.com/section/us?action=click&contentCollection=Science&module=SiteIndex&region=Footer&pgtype=article'

let config = {

	onload: function(window){
		console.log( 'load: ', window )
	},

	done: function( err, window ){
		let $elem = window.$('.initial-set article.story .story-body .headline')

		// 20 items
		console.log( 'original size: ', $elem.length, ' >last item:', $elem.last().text() )

		// click load more button
		let $btn = window.$('#latest-panel button.load-more-button')
		console.log( 'btn=', $btn.text() )
		$btn.trigger('click')

		// wait for 3sec, should have 40 items, but still 20
		setTimeout( function(){
			let $a = window.$('.initial-set article.story .story-body .headline')
			console.log( 'new size 1: ', $a.length, ' >last item: ', $elem.last().text() )
		}.bind(this), 3000)

		// wait for 6 sec, should have 40 items, but still 20
		setTimeout( function(){
			let $a = window.$('.initial-set article.story .story-body .headline')
			console.log( 'new size 2: ', $a.length, ' >last item: ', $elem.last().text() )
		}.bind(this), 6000)

	},

	features: {
		FetchExternalResources: ["script"],
		ProcessExternalResources: ["script"],
		SkipExternalResources: false
	  },
}

jsdom.env(
  url,
  ['http://code.jquery.com/jquery.js'],
  config,
);
```

**Comment by vsemozhetbyt** [comment]
@coodoo 
It's because additional news are contained in the `.additional-set`, not in the `.initial-set`. By the way, the elements are accessible even before you click on the button (you may check in the browser by `document.querySelectorAll('.additional-set article.story .story-body .headline')` — or get all of them by `document.querySelectorAll('.stream article.story .story-body .headline')`). `.additional-set` is updated later on by page scrolling.

**Comment by coodoo** [comment]
Yes I'm aware of that, but in browser after one clicks the `show more` button, there will be 10 more items added to `additional-set` and you can query those with the same selector.

The point here is trying to verify that dynamically loaded and appended DOM elements could be accessed (if it works in browser, it should work in jsdom), so far I had tough luck getting it work with most of the sites I tested, help?

**Comment by vsemozhetbyt** [comment]
@coodoo 
Are you sure? I enter in the Chrome console `[...document.querySelectorAll('.initial-set article.story .story-body .headline')].length` and get `20`. Then I click on the button, enter the same again and still get the 20.

**Comment by vsemozhetbyt** [comment]
How can you get 10 more items added to `.additional-set` by the selector for another element? `.additional-set` is not a child of `.initial-set`.

**Comment by coodoo** [comment]
Just verified again with this granular selector `$('#latest-panel .stream .initial-set li')`, here's the results inside `initial-set`:

Before - 10 items excluding Ad
<img width="697" alt="1" src="https://cloud.githubusercontent.com/assets/325936/15113185/59c71420-1625-11e6-94b8-7b1e4194950e.png">

After - 20 items excluding Ad
<img width="695" alt="2" src="https://cloud.githubusercontent.com/assets/325936/15113188/5f4fcb94-1625-11e6-870d-96f984a3af45.png">

I would expect in jsdom after waiting for 10 secs and query again, there should be 20+ items inside `initial-set` instead of 10?

**Comment by vsemozhetbyt** [comment]
It's strange. What I see in the last Chrome:

Before - 10 items excluding Ad
![1](https://cloud.githubusercontent.com/assets/10393198/15113463/1e9f6eba-15fd-11e6-8722-d136486424aa.png)

After - 10 items excluding Ad
![2](https://cloud.githubusercontent.com/assets/10393198/15113472/2baee5b8-15fd-11e6-8aaa-db02033e312c.png)

**Comment by vsemozhetbyt** [comment]
For me the page behavior indeed is different in the browswer and in the jsdom, but slightly not in the way you have described.

In the browser after load:
`.initial-set=20`
`.additional-set =20`
In the browser after click on the button:
`.initial-set=20`
`.additional-set =30`
In the browser after scroll to the end:
`.initial-set=20`
`.additional-set =40`

Later on each scroll adds 10 elements to the `.additional-set` (and to the `.stream ` which is parent for both `.initial-set` and `.additional-set`), the `.initial-set` remains the same.

In the jsdom after load:
`.initial-set=20`
`.additional-set =20`
In the jsdom after click on the button:
`.initial-set=20`
`.additional-set =20`
In the jsdom after scroll to the end:
`.initial-set=20`
`.additional-set =20`

It seems click on the button in the browser adds 10 elements to the `.additional-set` not by itself, but with some other event (connected somehow with scrolling) and jsdom can't reproduse this event (may be because it lacks layout features).

I've tested by this code (I've remove jquery for more clean tests and add some ES6):

```javascript
require('jsdom').env({
  url: 'http://www.nytimes.com/section/us?action=click&contentCollection=Science&module=SiteIndex&region=Footer&pgtype=article',
  done: function(err, window){
    const doc = window.document;
    
    const elems1 = doc.querySelectorAll('.stream article.story .story-body .headline');
    console.log(`size 1: ${elems1.length}, last item: ${[...elems1].pop().textContent.trim()}\n`);

    const btn = doc.querySelector('#latest-panel button.load-more-button');
    console.log(`btn = ${btn.textContent}\n`);
    btn.click();

    setTimeout(() => {
      const elems2 = doc.querySelectorAll('.stream article.story .story-body .headline');
      console.log(`size 2: ${elems2.length}, last item: ${[...elems2].pop().textContent.trim()}\n`);
      
      window.scrollTo(0, doc.body.scrollHeight);

      setTimeout(() => {
        const elems3 = doc.querySelectorAll('.stream article.story .story-body .headline');
        console.log(`size 3: ${elems3.length}, last item: ${[...elems3].pop().textContent.trim()}\n`);
      }, 10000);
    }, 3000);
  },
  features: {
    FetchExternalResources: ['script'],
    ProcessExternalResources: ['script']
  },
});
```

**Comment by vsemozhetbyt** [comment]
The output is:
```
size 1: 40, last item: Majority-Female Council in Seattle Faces Backlash After Sports Arena Vote

btn = Show More

size 2: 40, last item: Majority-Female Council in Seattle Faces Backlash After Sports Arena Vote

size 3: 40, last item: Majority-Female Council in Seattle Faces Backlash After Sports Arena Vote
```

The output should be:
```
size 1: 40, last item: Majority-Female Council in Seattle Faces Backlash After Sports Arena Vote

btn = Show More

size 2: 50, last item: Majority-Female Council in Seattle Faces Backlash After Sports Arena Vote

size 3: 60, last item: Majority-Female Council in Seattle Faces Backlash After Sports Arena Vote
```

**Comment by vsemozhetbyt** [comment]
It seems that `click` event does not fired as well:

```javascript
require('jsdom').env({
  url: 'http://www.nytimes.com/section/us?action=click&contentCollection=Science&module=SiteIndex&region=Footer&pgtype=article',
  done: function(err, window){
    const doc = window.document;
    
    const elems1 = doc.querySelectorAll('.stream article.story .story-body .headline');
    console.log(`size 1: ${elems1.length}, last item: ${[...elems1].pop().textContent.trim()}\n`);

    const btn = doc.querySelector('#latest-panel button.load-more-button');
    console.log(`btn = ${btn.textContent}`);
    console.log(`btn.style.display = ${btn.style.display}`);
    btn.click();

    setTimeout(() => {
      console.log(`btn.style.display = ${btn.style.display}\n`);
      const elems2 = doc.querySelectorAll('.stream article.story .story-body .headline');
      console.log(`size 2: ${elems2.length}, last item: ${[...elems2].pop().textContent.trim()}\n`);
      
      window.scrollTo(0, doc.body.scrollHeight);

      setTimeout(() => {
        const elems3 = doc.querySelectorAll('.stream article.story .story-body .headline');
        console.log(`size 3: ${elems3.length}, last item: ${[...elems3].pop().textContent.trim()}\n`);
      }, 10000);
    }, 10000);
  },
  features: {
    FetchExternalResources: ['script'],
    ProcessExternalResources: ['script']
  },
});
```

After click `btn.style.display` should be `'none'`, but it is still `''`.

**Comment by vsemozhetbyt** [comment]
Well, seems the problem is more fundamental.

The page in the browser with JavaScript disabled contains 13 `script` elements. The page with JavaScript enabled contains 77 `script` elements. Check it in console by this code:
```JavaScript
const scripts = [...window.document.querySelectorAll('script')];
console.log(scripts.length, scripts.map(s => s.src));
```

The page in the jsdom with JavaScript disabled contains 13 `script` elements. The page with JavaScript enabled contains 24 `script` elements. Check it by this code:
```JavaScript
require('jsdom').env({
  url: 'http://www.nytimes.com/section/us?action=click&contentCollection=Science&module=SiteIndex&region=Footer&pgtype=article',
  done: function(err, window){
    setTimeout(() => {
      const scripts = [...window.document.querySelectorAll('script')];
      console.log(scripts.length, scripts.map(s => s.src));
    }, 1000*10);
  },
  features: {
    FetchExternalResources: ['script'],
    ProcessExternalResources: ['script']
  },
});
```
Increasing the timeout does not change the number. It seems jsdom just does not download and execute all the scripts. May be it is due to errors in scripts that download other scripts or some oter errors (in XHR end so on).

We could correctly study difference in the elements and events behavior only when the scripts number in the jsdom is equal to scripts number in the browser.

**Comment by vsemozhetbyt** [comment]
Next step in the investigation.

I've added some error handling according with main help recommendations:
```javascript
const jsdom = require('jsdom');

jsdom.env({
  url: 'http://www.nytimes.com/section/us?action=click&contentCollection=Science&module=SiteIndex&region=Footer&pgtype=article',
  done: (err, window) => {
    setTimeout(() => {
      const scripts = [...window.document.querySelectorAll('script')];
      console.log(`\n${scripts.length}: ${scripts.map((s, i) => `${i + 1}: ${s.src}`).join('\n')}\n`);
    }, 1000*10);
  },
  features: {
    FetchExternalResources: ['script'],
    ProcessExternalResources: ['script'],
  },
  virtualConsole: jsdom.createVirtualConsole().sendTo(console),
});
```
The output:
```
Error: Not implemented: HTMLCanvasElement.prototype.getContext (without installing the canvas npm package)
    (stack)
Error: Uncaught [TypeError: document.hasFocus is not a function]
    (stack)

24: (scripts)
```
It seems `document.hasFocus()` does not implemented in the jsdom. So I've added a stub:
```javascript
const jsdom = require('jsdom');

jsdom.env({
  url: 'http://www.nytimes.com/section/us?action=click&contentCollection=Science&module=SiteIndex&region=Footer&pgtype=article',
  done: (err, window) => {
    window.document.hasFocus = () => {return false;};
    
    setTimeout(() => {
      const scripts = [...window.document.querySelectorAll('script')];
      console.log(`\n${scripts.length}: ${scripts.map((s, i) => `${i + 1}: ${s.src}`).join('\n')}\n`);
    }, 1000*10);
  },
  features: {
    FetchExternalResources: ['script'],
    ProcessExternalResources: ['script'],
  },
  virtualConsole: jsdom.createVirtualConsole().sendTo(console),
});
```
After this fix console is flooded with information. First of all one of the scripts dumped to console a huge object. Then some errors follows. However, in the end I have near 40 scripts of the page.

So I've returned to first test code:
```javascript
const jsdom = require('jsdom');

jsdom.env({
  url: 'http://www.nytimes.com/section/us?action=click&contentCollection=Science&module=SiteIndex&region=Footer&pgtype=article',
  done: (err, window) => {
    const doc = window.document;
    doc.hasFocus = () => {return false;};
    
    setTimeout(() => {
      const scripts = [...doc.querySelectorAll('script')];
      console.log(`\n${scripts.length}: ${scripts.map((s, i) => `${i + 1}: ${s.src}`).join('\n')}\n`);

      const elems1 = doc.querySelectorAll('.stream article.story .story-body .headline');
      console.log(`size 1: ${elems1.length}, last item: ${[...elems1].pop().textContent.trim()}\n`);

      const btn = doc.querySelector('#latest-panel button.load-more-button');
      console.log(`btn = ${btn.textContent}`);
      console.log(`btn.style.display = ${btn.style.display}`);
      btn.click();

      setTimeout(() => {
        console.log(`btn.style.display = ${btn.style.display}\n`);
        const elems2 = doc.querySelectorAll('.stream article.story .story-body .headline');
        console.log(`size 2: ${elems2.length}, last item: ${[...elems2].pop().textContent.trim()}\n`);
        
        window.scrollTo(0, doc.body.scrollHeight);

        setTimeout(() => {
          const elems3 = doc.querySelectorAll('.stream article.story .story-body .headline');
          console.log(`size 3: ${elems3.length}, last item: ${[...elems3].pop().textContent.trim()}\n`);
        }, 1000*10);
      }, 1000*10);
    }, 1000*10);
  },
  features: {
    FetchExternalResources: ['script'],
    ProcessExternalResources: ['script']
  },
  //virtualConsole: jsdom.createVirtualConsole().sendTo(console),
});
```
Output:
```
45: (scripts)

size 1: 40, last item: Article Details Widespread Claims of Sex Abuse at Private Schools

btn = Show More
btn.style.display =
btn.style.display = none

size 2: 40, last item: Article Details Widespread Claims of Sex Abuse at Private Schools

size 3: 40, last item: Article Details Widespread Claims of Sex Abuse at Private Schools
```
As you can see the click event now fires (`btn.style.display = none`), however the scroll event still gives nothing.

You can try to discover scripts errors, add some other stubs or forbid some unnecessary scripts and see if the essential event will fire.

**Comment by Sebmaster** [comment]
> however the scroll event still gives nothing.

Scrolling events will never firein jsdom (unless you dispatch them manually) since there's no rendering.
