### ISSUE TITLE
createElementNS not implementing SVG interface correctly

### ISSUE THREAD

**Issue by Aweary** [tmpvar/jsdom#1480]
Specifically the SVG interface. The `className` attribute on an SVG should return an instance of `SVGAnimatedString`, but instead it is returning a string.

```js
var jsdom = require('jsdom').jsdom;
var document = jsdom();
var svg = document.createElementNS('http://www.w3.org/2000/svg', 'svg')
svg.className
// ''

**Comment by Sebmaster** [comment]
We don't support any of the SVG DOM (yet), so that's "intended". You'll notice the created element is not a `SVGSVGElement`.

**Comment by Aweary** [comment]
@Sebmaster thanks for the quick response, is there an issue tracking SVG DOM implementation that I can watch? We want to stay on top of it for [enzyme](https://github.com/airbnb/enzyme/issues/375).

**Comment by Sebmaster** [comment]
It's not a high priority for anyone on the team as far as I know, but #1423 will definitely get closed when we implement it, although the actual implementation progress will probably not be in there.

**Comment by alexbeletsky** [comment]
@Sebmaster can I please ask about plans regarding this issue? I'm using `enzyme` for testing React components, there is an issue https://github.com/airbnb/enzyme/issues/375 that prevents full render testing of components with SVG elements.

That would be great to understand if this one eventually implemented or not?

**Comment by Aweary** [comment]
@alexbeletsky we have a PR open https://github.com/airbnb/enzyme/pull/448 that should fix SVG behavior in enzyme.

**Comment by alexbeletsky** [comment]
@Aweary awesome, thanks for an update! Looking forward to https://github.com/airbnb/enzyme/pull/448 getting merged!
