### ISSUE TITLE
Content-Length is blocked in CORS requests

### ISSUE THREAD

**Issue by Sebmaster** [tmpvar/jsdom#1491]
While checking into sindresorhus/fast-cli#2, I noticed that we're blocking client-JS from reading the Content-Length header, because it fails [this](https://github.com/tmpvar/jsdom/blob/72b53d9682dd60aa98047439c4f810584027de6b/lib/jsdom/living/xmlhttprequest.js#L805) check.

It seems to me the [spec](https://fetch.spec.whatwg.org/#cors-safelisted-response-header-name) says that basically all headers except Set-Cookie / Set-Cookie2 are allowed (due to `Any value in list that is not a forbidden response-header name.`)? That kinda seems too permissive to me... But Content-Length definitely sounds like something that should be exposed, so there's a bug here somewhere...

/cc @nicolashenry

**Comment by nicolashenry** [comment]
I shouldn't have deleted any headers here since I use these later for progress events. I will do a pull request to fix this.

**Comment by nicolashenry** [comment]
For the speed issue, I think "Buffer.concat" is done too many times. I have really better results using buffer lists, you can test it here : https://github.com/nicolashenry/jsdom/tree/fix-5

**Comment by Sebmaster** [comment]
Hoooooly moly, that's giving me 130/140, and at that point roughly my internet might cap out, so that's at least a 3x speed boost. Reeeally nice job there!

**Comment by sindresorhus** [comment]
@nicolashenry Did you ever land the performance improvements? Is there an existing issue about it?

**Comment by nicolashenry** [comment]
I am a little bit busy lately. I will work on it again in a few weeks.
