### ISSUE TITLE
Setting a script element's `src` attribute after insertion does not load the `src` target.

### ISSUE THREAD

**Issue by am0ry** [tmpvar/jsdom#1495]
If you modify a script's `src` attribute after the element has been attached, the target script is never loaded.

This example will always log `false` to the console:

__script.js__
```javascript
window.script_executed = true;
```

__runner.js__
```javascript
const jsdom = require('jsdom');

const window = jsdom.jsdom("").defaultView;

window.script_executed = false;

const script = window.document.createElement("script");
window.document.body.appendChild(script);
script.src = "script.js";

// assume script.js will load asynchronously
setInterval(() => {
  console.log(window.script_executed);
}, 1000);
```

A comparable script that executes in a browser and logs `true`:
```html
<html>
  <body>
    <script type="text/javascript">
      window.script_executed = false;

      var script = window.document.createElement("script");
      window.document.body.appendChild(script);
      script.src = "script.js";

      setInterval(function() {
        console.log(window.script_executed);
      }, 1000);
    </script>
  </body>
</html>
```

**Comment by vsemozhetbyt** [comment]
1. I've tested with src = [absolute pathes](https://github.com/tmpvar/jsdom/issues/1483) — no execution as well.
2. I've tested with src = http URL — no execution as well.

**Comment by vsemozhetbyt** [comment]
However this works fine;

```js
const jsdom = require('jsdom');

const window = jsdom.jsdom(`
<html>
  <body>
    <script type="text/javascript">
      window.script_executed = false;

      var script = window.document.createElement("script");
      window.document.body.appendChild(script);
      script.src = "script.js";

      setInterval(function() {
        console.log('inside: ', window.script_executed);
      }, 1000);
    </script>
  </body>
</html>
`, {virtualConsole: jsdom.createVirtualConsole().sendTo(console),}).defaultView;

setInterval(() => {
  console.log('outside: ', window.script_executed);
}, 1000);
```

Both  `console.log` is `true`.

**Comment by vsemozhetbyt** [comment]
The script is not even loaded. Add this line into the both cases before `src` changing and compare the output:
```js
script.addEventListener('load', () => {console.log('loaded');});
```

**Comment by domenic** [comment]
It may help to use the virtual console to log errors

**Comment by vsemozhetbyt** [comment]
I use it, no errors.
```js
const window = jsdom.jsdom("",
  {virtualConsole: jsdom.createVirtualConsole().sendTo(console)}).defaultView;
```

**Comment by vsemozhetbyt** [comment]
Test case with http URL, `load` event and two checkpoints in the `script.js`.

**`http://vsemozhetbyt.github.io/test/script.js`:**
```js
window.script_executed = true;
document.body.title = '123';
```
**Node.js script:**
```js
const jsdom = require('jsdom');

const window = jsdom.jsdom(
  '',
  {virtualConsole: jsdom.createVirtualConsole().sendTo(console)}
).defaultView;

window.script_executed = false;

const script = window.document.createElement('script');
window.document.body.appendChild(script);
script.addEventListener('load', () => {console.log('loaded');});
script.src = 'http://vsemozhetbyt.github.io/test/script.js';

setInterval(() => {
  console.log(window.script_executed);
  console.log(window.document.body.title);
}, 1000);
```
**Output:**
```
false
[empty string]
...
```
**Run in Chrome console or Source snippet with any document:**
```js
window.script_executed = false;

const script = window.document.createElement('script');
window.document.body.appendChild(script);
script.addEventListener('load', () => {console.log('loaded');});
script.src = 'http://vsemozhetbyt.github.io/test/script.js';

setInterval(() => {
  console.log(window.script_executed);
  console.log(window.document.body.title);
}, 1000);
```
**Output:**
```
loaded
true
123
...
```

**Comment by am0ry** [comment]
It's worth noting that reversing the order so that the `src` attribute is set on the script element before it is attached will fire the `load` event and eval the target script correctly.

__runner__
```javascript
```
__output__
```
loaded
true
...
```

**Comment by am0ry** [comment]
You can see why the jsdom API behaves this way in [`HTMLScriptElementImpl`](https://github.com/tmpvar/jsdom/blob/master/lib/jsdom/living/nodes/HTMLScriptElement-impl.js#L34-L43). Implementing `_attrModified` on [`HTMLScriptElementImpl`](https://github.com/tmpvar/jsdom/blob/master/lib/jsdom/living/nodes/HTMLScriptElement-impl.js#L31) could allow the resource to be loaded when the `src` attribute is modified.

**Comment by domenic** [comment]
Yeah, seems like we have a straight-up bug here. I can try to fix sometime this upcoming week. Thanks for all the in-depth investigation!

**Comment by am0ry** [comment]
Looks like dynamically constructed `link` elements have the same problem. In this example the `load` event is never fired:

```javascript
const jsdom = require('jsdom');

const window = jsdom.jsdom("").defaultView;

const link = window.document.createElement("link");
link.rel = "stylesheet";
link.addEventListener("load", () => {
  console.log("loaded");
});

window.document.body.appendChild(link);
link.href = "style.css";
```

**Comment by vsemozhetbyt** [comment]
It seems the doc is somewhat incomplete on this point.

> `FetchExternalResources`
> _Default_: `["script"]`

```js
const jsdom = require('jsdom');

const window = jsdom.jsdom(
  "", {
    virtualConsole: jsdom.createVirtualConsole().sendTo(console),
  }
).defaultView;

const link = window.document.createElement("link");
link.rel = "stylesheet";
link.addEventListener("load", () => {
  console.log("loaded");
});

link.href = "http://www.addic7ed.com/css/wikisubtitles.css";
window.document.body.appendChild(link);

setInterval(() => {
  console.log(link.href);
}, 1000);
```
`load` fired.
```js
const jsdom = require('jsdom');

const window = jsdom.jsdom(
  "", {
    virtualConsole: jsdom.createVirtualConsole().sendTo(console),
    features: {FetchExternalResources : false},
  }
).defaultView;

const link = window.document.createElement("link");
link.rel = "stylesheet";
link.addEventListener("load", () => {
  console.log("loaded");
});

link.href = "http://www.addic7ed.com/css/wikisubtitles.css";
window.document.body.appendChild(link);

setInterval(() => {
  console.log(link.href);
}, 1000);
```
`load` does not fired.
Does it need a new issue?

**Comment by vsemozhetbyt** [comment]
`img` loading does not depend on `src` order towards `appendChild`. However, it is loaded regardless of `FetchExternalResources` (`load` fired with `FetchExternalResources : false`, `FetchExternalResources : ["script"]` or `FetchExternalResources` undefined):
```
const jsdom = require('jsdom');

const window = jsdom.jsdom(
  "", {
    virtualConsole: jsdom.createVirtualConsole().sendTo(console),
    features: {FetchExternalResources : false},
  }
).defaultView;

const img = window.document.createElement("img");
img.addEventListener("load", () => {
  console.log("loaded");
});

window.document.body.appendChild(img);
img.src = "https://github.com/fluidicon.png";

setInterval(() => {
  console.log(img.src);
}, 1000);
```
`load` fired.

**Comment by vsemozhetbyt** [comment]
`iframe` loading does not depend on `src` order towards `appendChild` as well. However, the number of event firing depends on `src` order towards `appendChild`:

`src` -> `appendChild` : one `loaded`
`appendChild` -> `src` : two `loaded`
```js
const jsdom = require('jsdom');

const window = jsdom.jsdom(
  "", {
    virtualConsole: jsdom.createVirtualConsole().sendTo(console),
    features: {FetchExternalResources : ["iframe"]},
  }
).defaultView;

const iframe = window.document.createElement("iframe");
iframe.addEventListener("load", () => {
  console.log("loaded");
});

window.document.body.appendChild(iframe);
iframe.src = "https://github.com/";

setInterval(() => {
  console.log(iframe.contentWindow.document.documentElement);
}, 1000);

```

**Comment by domenic** [comment]
I don't think further testing is helpful here. It's clear that there are implementation bugs in resource loading with regard to attributes changing. I'll spend some time fixing them.

**Comment by snuggs** [comment]
@domenic how's this coming along? And do you need help? This currently now is even bigger than before as this prevents HTML imports. Do you need help on the feature? What's next and what's the timeline. Sorry for the myriad of questions however I have my developers asking "Why not just scrap JSDOM if it has that many implementation bugs and use PhantomJS. SMH FML.

Thanks in advance!

**Comment by domenic** [comment]
I haven't had time to work on this. As this is an open-source software project that I do in my spare time on weekends, we don't have a roadmap or timeline. If you're willing to help with a pull request, that would definitely be appreciated.

**Comment by katylava** [comment]
Is there a workaround? Some way I can say... "Hey, jsdom, I know you're done but can you load just one more script for me?"

**Comment by Sebmaster** [comment]
@katylava Create a new script tag and set the source there and append it to the body.

**Comment by domenic** [comment]
The iframe behavior is actually per-spec and matches browsers, but I have fixes for link and script in master now. They will be going out in the next release.
