### ISSUE TITLE
Is there a way to get http status code in `done` callback?

### ISSUE THREAD

**Issue by vsemozhetbyt** [tmpvar/jsdom#1496]
Can I, say, detect `404` in a code like this?
```js
const jsdom = require('jsdom');
jsdom.env({
  url: 'https://en.wikipedia.org/wik',
  done: (err, window) => {
    if (err) { console.error(err); return; }
    console.log(window.document.querySelector('title').textContent);
  },
});
```
Is there a way to do this in `jsdom` at all? If I get it right, `4**` or `5**` codes don't fire error events.

**Comment by domenic** [comment]
No. To do this, it's best to do the request yourself, then pass the resulting string to jsdom.
