### ISSUE TITLE
Timers in the Window context prevent Node.js process from exit and window object from GC clean-up

### ISSUE THREAD

**Issue by vsemozhetbyt** [tmpvar/jsdom#1498]
If `FetchExternalResources` and `ProcessExternalResources` contain `'script'` and page scripts set timers, Node.js process does not exit.

Test code 1 (page scripts with some possible timers are under user's control):
```javascript
const jsdom = require('jsdom');

jsdom.env({
  html: `
    <!doctype html>
    <html>
      <head>
        <meta charset="UTF-8">
        <title></title>
      </head>
      <body>
        <script>
          window.document.title = 'Scripted Title';
          window.setInterval(() => {}, 1000);
        </script>
      </body>
    </html>
  `,
  done: (err, window) => {
    console.log(window.document.title);
  },
  features: {
    FetchExternalResources: ['script'],
    ProcessExternalResources: ['script']
  },
});
```
After logged output the script just freezes. However, if all timers are cleaned up, the script exits properly:
```javascript
const jsdom = require('jsdom');

jsdom.env({
  html: `
    <!doctype html>
    <html>
      <head>
        <meta charset="UTF-8">
        <title></title>
      </head>
      <body>
        <script>
          window.document.title = 'Scripted Title';
          window.setInterval(() => {}, 1000);
        </script>
      </body>
    </html>
  `,
  done: (err, window) => {
    console.log(window.document.title);
    
    let id = window.setTimeout(() => {}, 0);
    console.log(id);
    while (id) {
      window.clearTimeout(id);
      id--;
    }

    id = window.setInterval(() => {}, 0);
    console.log(id);
    while (id) {
      window.clearInterval(id);
      id--;
    }
  },
  features: {
    FetchExternalResources: ['script'],
    ProcessExternalResources: ['script']
  },
});
```
Test code 2 (page scripts with many timers are beyond easy user's control):
```javascript
const jsdom = require('jsdom');

jsdom.env({
  url: 'http://www.nytimes.com/',
  done: (err, window) => {
    console.log(window.document.title);
  },
  features: {
    FetchExternalResources: ['script'],
    ProcessExternalResources: ['script']
  },
});
```
After logged output the script just freezes as well. And if all timers are cleaned up, the script exits properly too:
```javascript
const jsdom = require('jsdom');

jsdom.env({
  url: 'http://www.nytimes.com/',
  done: (err, window) => {
    console.log(window.document.title);
    
    let id = window.setTimeout(() => {}, 0);
    console.log(id);
    while (id) {
      window.clearTimeout(id);
      id--;
    }

    id = window.setInterval(() => {}, 0);
    console.log(id);
    while (id) {
      window.clearInterval(id);
      id--;
    }
  },
  features: {
    FetchExternalResources: ['script'],
    ProcessExternalResources: ['script']
  },
});
```

**Comment by vsemozhetbyt** [comment]
Maybe thish feature shoul be documented, so that user knows of a need to call `window.close();` in the end of the document pocessing. Or some option should be provided to allow the Node.js script not to wait until `Window` eventloop drained.

**Comment by domenic** [comment]
There's no way to execute code in the future without keeping the process in which that code will execute alive. So documenting seems like the way to go here.

**Comment by vsemozhetbyt** [comment]
It seems it really should be documented. It turns out this is not simply the obstacle for script exit, but the cause of memory leaks. Say, a script need to process a big number of pages, and each page set timer. Then GC will clean no window objects.

Tests:

_1) Page scripts without timers and without `window.close()`._
```javascript
const jsdom = require('jsdom');
const virtualConsole = jsdom.createVirtualConsole().sendTo(console);

const html =
  `<!doctype html><html><head><meta charset="UTF-8"><title></title></head>
  <body><script>window.document.title = 'Test';</script></body></html>`;

const reqNum  = 10000;
let   counter = 0;

function test() {
  counter++;
  if (counter > reqNum) return;
  
  jsdom.env({
    html,
    done: (err, window) => {
      if (!(counter % 100)) console.log(counter);
      setTimeout(test, 1);
    },
    features: {
      FetchExternalResources: ['script'],
      ProcessExternalResources: ['script']
    },
    virtualConsole,
  });
}

test();
```
The script quickly iterates the pages, GC is working (memory increases and decreases around 300 MB), and finally the script properly exits.

_2) Page scripts with timers and without `window.close()`._
```javascript
const jsdom = require('jsdom');
const virtualConsole = jsdom.createVirtualConsole().sendTo(console);

const html =
  `<!doctype html><html><head><meta charset="UTF-8"><title></title></head>
  <body><script>window.setInterval(() => {}, 1000);</script></body></html>`;

const reqNum  = 10000;
let   counter = 0;

function test() {
  counter++;
  if (counter > reqNum) return;
  
  jsdom.env({
    html,
    done: (err, window) => {
      if (!(counter % 100)) console.log(counter);
      setTimeout(test, 1);
    },
    features: {
      FetchExternalResources: ['script'],
      ProcessExternalResources: ['script']
    },
    virtualConsole,
  });
}

test();
```
The memory constantly increases up to 1500 MB, then script's speed falls, and then the script is aborted with 'out of memory'.

![timers_mem](https://cloud.githubusercontent.com/assets/10393198/15519045/4d4226e2-2208-11e6-8b7e-a4655329ccbe.png)

_3) Page scripts with timers and with `window.close()`._
```javascript
const jsdom = require('jsdom');
const virtualConsole = jsdom.createVirtualConsole().sendTo(console);

const html =
  `<!doctype html><html><head><meta charset="UTF-8"><title></title></head>
  <body><script>window.setInterval(() => {}, 1000);</script></body></html>`;

const reqNum  = 10000;
let   counter = 0;

function test() {
  counter++;
  if (counter > reqNum) return;
  
  jsdom.env({
    html,
    done: (err, window) => {
      if (!(counter % 100)) console.log(counter);
      setTimeout(test, 1);
      window.close();
    },
    features: {
      FetchExternalResources: ['script'],
      ProcessExternalResources: ['script']
    },
    virtualConsole,
  });
}

test();
```

The same as the first case.

**Comment by domenic** [comment]
Yes, I don't think large test cases is really helpful here since I've already said what the behavior is, but I agree it should be documented. Do you have any suggestions for wording of the documentation?

**Comment by vsemozhetbyt** [comment]
Well, I am not a native English speaker and my English is bad, so maybe I should not suggest a large amount of the text. However, something like that (with your additions and corrections) may be helpful:

It should be taken into consideration, that timers in the page scripts (set by `window.setImmediate()`, `window.setInterval()` and `window.setTimeout()`) could prevent `window` object from being GC-ed and thereby could cause memory leaks. These timers also could interfere with main process eventloop and prevent the script from natural exit after eventloop drain. To mitigate these risks, `window.close()` should be called after each document processing completion.
