### ISSUE TITLE
Assigning null to element.style.background throws an error

### ISSUE THREAD

**Issue by fordbzd** [tmpvar/jsdom#1499]
In my mocha test case, if I have the following code:

        document.body.innerHTML = "<div id=\"ctrl\" style=\"background:#111;border:1px\"></div>";
        var a = document.body.firstChild;
        a.style['background'] = null;

Then I will get:

    TypeError: Cannot read property 'split' of null

In our code, the last statement is used to invalid and thus clean the value of the specific style. It can be achieved by other ways, but the problem is that it works in previous build (8.0.2 and before) and in Chrome. It seems in latest implementation String.split() is used when assigning values to style without null check.

**Comment by domenic** [comment]
Thank you for the report. This is a bug in the cssstyle module maintained by @chad3814. I will open another issue over there.

**Comment by chad3814** [comment]
cssstyle@0.2.35 published with fix
