### ISSUE TITLE
Are the docs up to date?

### ISSUE THREAD

**Issue by mendrik** [tmpvar/jsdom#1500]
I tried to get a simple jsdom page to load with one local script, without much success.
Docs seem very inconsistent, there is jsdom.env({...}), jsdom.env(arg1, arg2) and jsdom.jsdom({...}). 
Of all the documented callbacks only 'created' seems to work, done and onload are never called.
There is little information how to get the real window object. Is it during the callback functions, .defaultView or .createWindow().

Anyhoo in all.js I have multiple variables defined like var xy = ...; but my jsdom window.xy is always undefined.
```
var htmlSource = fs.readFileSync("./test/test.html", "utf8"),
    appSource = fs.readFileSync("./public/javascripts/all.js", "utf8");

jsdom.debugMode = true; // seems to do nothing either?

var doc = jsdom.jsdom(htmlSource, {
    features: {
        FetchExternalResources: ['script'],
        ProcessExternalResources: ['script'],
        MutationEvents: '2.0',
        QuerySelector: false
    },
    src: [appSource],
});
```

Shouldn't that work like this? I'm using latest 9.2.0 version.

Help would be greatly appreciated,
Andreas

**Comment by domenic** [comment]
The docs are up to date. I have no idea what debugMode is; that isn't documented, so maybe you are looking at a very old docs? Similarly MutationEvents and QuerySelector are not documented options or options that exist.

As the docs say,

> jsdom.env is an API that allows you to throw a bunch of stuff at it, and it will generally do the right thing.

so that is why you see multiple signatures in use.

If you can produce a small test case that I can run with `node test.js` I can debug your issues further. But I am concerned by how you seem to be using options that don't exist.

**Comment by mendrik** [comment]
Thanks for your time, here is a small zip you can try it with. requires mocha and jsdom (`npm install` will suffice) and run with `mocha`
My window.xy is never set. 
[sample.zip](https://github.com/tmpvar/jsdom/files/279365/sample.zip)

**Comment by Sebmaster** [comment]
jsdom.jsdom does not work that way.

```js
var jsdom = require('jsdom'),
    fs = require('fs');

var htmlSource = fs.readFileSync("./test.html", "utf8"),
    appSource = fs.readFileSync("../javascript/all.js", "utf8");

jsdom.env({
    html: htmlSource,
    features: {
        FetchExternalResources: ['script'],
        ProcessExternalResources: ['script']
    },
    src: [appSource],
    done: function(errors, window) {
        document = window.document;

        if (!window.xy) {
            console.error('Something has gone wrong. window.xy must not be undefined.');
        }

        console.log(document.body.innerHTML);
            console.log(errors, 'I was supposed to get here');
        }
});
```

**Comment by mendrik** [comment]
hmm this works! thanks, any way I can buy a beer? :)
