### ISSUE TITLE
Newly-imported dom/events/Event-dispatch-multiple-stopPropagation.html fails when enabled

### ISSUE THREAD

**Issue by domenic** [tmpvar/jsdom#1501]
Interestingly it also fails in Chrome. @Sebmaster, mind taking a look?

**Comment by Sebmaster** [comment]
The stop propagation flag is never cleared in the spec except in [initialize event](https://dom.spec.whatwg.org/#concept-event-initialize). That, in turn, is only reset as a default and in initEvent. Seems like we're working according to spec here?

**Comment by domenic** [comment]
I'll take this over to the web-platform-tests repo...
