### ISSUE TITLE
Adding methods to prototypes of Element, Node, etc.

### ISSUE THREAD

**Issue by timjim-kr** [tmpvar/jsdom#1503]
Hi there,

I've just started experimenting with jsdom (moving our repo away from domino).  We'd previously added some extensions to domino's `Element`, `Document`, `Window` and other classes, and I'm trying to port those extensions to the jsdom equivalents of those classes.

One key thing is that I would need to define a new method on, for example, the `Element` prototype, and then have all the subclasses get that new method on their prototypes as well.

I haven't come up with a great approach so far, but here are the ideas that I've come across and why I'm not excited about them:

1. Send a pull request to jsdom with the updates.
  * Cons:
    * Some of the extensions we've built are not fully-baked, and fully-baking them would take more effort than I'm willing to invest at the moment.
2. Fork a local version of jsdom
  * Cons:
    * Makes subsequent version updates much more painful.
    * Just feels wrong.
3. For any class (like `Element`) where I want to add a new prototype method, iterate over all the children and define a prototype method on them.
  * Cons:
    * Tedious code.
    * Just feels wrong.
4. Stick with domino
  * Cons:
    * Domino is failing us for other reasons, and although we've made a fix there, upgrading to the latest version appears to disrupt configurability (like setting a different user agent for a particular test).

Would love suggestions on how to tackle this.  Thanks in advance!

Tim

**Comment by Sebmaster** [comment]
> For any class (like Element) where I want to add a new prototype method, iterate over all the children and define a prototype method on them.

Why would you need to iterate over all children? If it's not defined on a child-class, it'll search the prototype chain upwards until JS finds such a method.

**Comment by timjim-kr** [comment]
Sorry.  This is probably due to my ignorance of JavaScript.  I just did a simple example and it worked exactly as you described, so I must have had a coding error somewhere.  I will report back if it's anything worth reporting.

**Comment by timjim-kr** [comment]
Turns out the issue is the `Object.create()` calls at the start of the generated files.  For example, in the generated HTMLElement.js file:
```HTMLElement.prototype = Object.create(Element.interface.prototype);```

The `Object.create`, as I understand it, creates a copy of the `Element prototype` (and that copy will have references to the original `Element.prototype` functions).

Because of this, the search of the prototype chain will search up these copies created by `Object.create`, which means anything added to, say, `Element.prototype` after the `Object.create` call will not be found.

**Comment by domenic** [comment]
That's not true.

Can you give a small ten line example that works in browsers but not in jsdom?

**Comment by timjim-kr** [comment]
Yeah, turns out it was PEBKAC.  I was actually redefining a method that already existed (`focus`) in an intermediate subclass (`HTMLElement`) that I missed when I was looking for the definition in `HTMLDivElement` and `Element`.  My apologies for the distraction and my confusion.
