### ISSUE TITLE
Using getBoundingClientRect() Method?

### ISSUE THREAD

**Issue by xaviervalarino** [tmpvar/jsdom#1504]
I wanted to test some code that uses the `getBoundingClientRect()` method with _jsdom_, but always get zeros in the returned value after applying styles like `left`, `top`, `width`, _etc_ to the DOM node. This seems related to #1435 in that these styles wont be reflected in getBoundingClientRect since there is no viewport, but I wanted to see if this was actually the case, and if so, if there is any work-around.

Is my best option (aside from decoupling my code from the viewport) using something like [phantom](https://github.com/ariya/phantomjs) or [smokestack](https://github.com/hughsk/smokestack)?

**Comment by Sebmaster** [comment]
jsdom doesn't do any layouting, so stuff like that won't be possible.

**Comment by xaviervalarino** [comment]
Thanks @Sebmaster!
