### ISSUE TITLE
Add exposed decoding support

### ISSUE THREAD

**Issue by vsemozhetbyt** [tmpvar/jsdom#1506]
If I get it right, as for now jsdom only suppots encodings for `env()` 'magic' calls. If site charset is not one of the standard Node.js encodings (utf8 or ascii), there is no way to transfer decoded string from `http.request()` to `jsdom.jsdom()`, neither is there a way to transfer body buffer to `jsdom.jsdom()` for decoding.

Maybe jsdom could expose decoding API so that users could manage without external decoding modules.

**Comment by domenic** [comment]
IMO the best thing to do here would be to pull out https://github.com/tmpvar/jsdom/blob/master/lib/jsdom/living/helpers/encoding.js#L7-L45 into a separate package that people can use independently of jsdom.

**Comment by domenic** [comment]
And I guess https://github.com/tmpvar/jsdom/blob/master/lib/jsdom/living/helpers/encoding.js#L47-L258 is also a pretty good package

**Comment by domenic** [comment]
This is now done:

- https://github.com/jsdom/html-encoding-sniffer
- https://github.com/jsdom/whatwg-encoding
