### ISSUE TITLE
jsdom's eval API doesn't allow setting the filename properly.

### ISSUE THREAD

**Issue by cpojer** [tmpvar/jsdom#1509]
@Sebmaster switched us to use eval a while back. It turns out that breaks a bit with the callsites npm module.

When an error is thrown or captured, the stack trace has the correct file name information available. However, when we retrieve the stack object using `prepareStackTrace` and call `getFileName` on individual CallSites objects, the file names coming from inside the context are empty. I don't know why this happens, but in Jest, using `vm.runInContext` with the filename argument this fixes the problem. I've attached a few useful links, including a repository by @lencioni that works well as a repro. To debug I added some console.log into the callsite module.

Repro repository in this issue: https://github.com/facebook/jest/issues/1048
See https://github.com/tj/callsite/blob/master/index.js#L4
See https://github.com/facebook/jest/blob/master/packages/jest-environment-jsdom/src/index.js#L36

Can we figure out a way to set the vm filename so that v8/node will pick it up properly?

**Comment by domenic** [comment]
I guess this is fixed with the addition of evalVMScript in https://github.com/tmpvar/jsdom/commit/24c28fdb575f790c09997f314af4bd561682ae72.
