### ISSUE TITLE
disable inline script

### ISSUE THREAD

**Issue by kennytordeur** [tmpvar/jsdom#1512]
Hi,

In my scenario i just want to load some html into jsdom but i don't want the inline javascript to be executed. 

For example.

`jsdom.jsdom("<html><body><script>console.log("test");</script></body></html")`

I don't want the console.log to be executed.

Is this possible?

**Comment by Sebmaster** [comment]
Use jsdom.env or explicitly disable ProcessExternalResources in the options.

**Comment by Joris-van-der-Wel** [comment]
```javascript
var doc = jsdom(`<html><body><script>console.log("test");</script></body></html>`, {
    features: {
      ProcessExternalResources: false
    }
});
```
Your original example has a syntax error by the way ;)

**Comment by domenic** [comment]
FWIW this will be the new default in newapi: https://github.com/tmpvar/jsdom/blob/newapi/lib/newapi1.md#executing-scripts

**Comment by kennytordeur** [comment]
Thanks. I already had those extra options but i passed them in like this
```javascript
var doc = jsdom(`<html><body><script>console.log("test");</script></body></html>`, {
      ProcessExternalResources: false
});
```
I didn't now i had to put them in "features". My inline JavaScript doesn't get executed now.
