### ISSUE TITLE
[Angular 2] | ZoneJS not working 

### ISSUE THREAD

**Issue by kuashe** [tmpvar/jsdom#1513]
Using this HTML page

```
<html>
  <head>
    <title>Angular 2 QuickStart</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
  <!-- 3. Display the application -->

    <script src="https://npmcdn.com/zone.js@0.6.12?main=browser"></script>
  <body>
    <button id='foo' >Click me ! </button>
  </body>

</html>
```

And this code 

```
var fs = require("fs")
var jsdom = require("jsdom");
var doc = jsdom.jsdom( fs.readFileSync("index.html") , {
    virtualConsole: jsdom.createVirtualConsole().sendTo(console),

    features: {
      FetchExternalResources : ["script"],
       ProcessExternalResources: ["script"]
    }
});

```

I have the following error

> Error: Uncaught [TypeError: Cannot set property onreadystatechange of [object Object] which has only a getter]

**Comment by ollwenjones** [comment]
Understand why this would be tough, but would love the option to skip the browser in Angular 2+ tests, just as I do in React.
👍

**Comment by thymikee** [comment]
`jsdom` must run in a function wrapped Zone.js context. I had the same problem when I was working on using Jest in Angular and it's already solved problem. IMO It has nothing to do with `jsdom` and this should be closed. 

@kuashe If you're curious, here's a [jest-preset-angular](https://github.com/thymikee/jest-preset-angular) which enables you to test Angular apps in `jsdom`. What's better, it's several times faster than Karma with Chrome.

**Comment by vangorra** [comment]
Confirmed jsdom working with zone.js using jest-preset-angular. Doesn't look like a jsdom issue.

**Comment by Swiip** [comment]
Please take a look at my PR #1610. I know it was not good enough to be merged. But the diff points what is wrong between zone and jsdom. I'm running integration tests on Angular 2 with pure jsdom and this patch for some times now.
