### ISSUE TITLE
Dynamically loaded application missing DOM content

### ISSUE THREAD

**Issue by kallewoof** [tmpvar/jsdom#1518]
Take the Meteor todo example app,

``` bash
$ mkdir test
$ cd test
$ git clone https://github.com/meteor/todos
$ cd todos
$ meteor npm install
$ meteor
```

And, once it finishes loading, run a test.js script with

``` javascript
const jsdom = require('jsdom');

jsdom.env({
  url: 'http://localhost:3000/',
  features: {
    FetchExternalResources: ['script'],
    ProcessExternalResources: ['script'],
    SkipExternalResources: false,
  },
  done: (errors, window) => {
    if (errors) console.log('errors:', errors); else console.log('done');
    setTimeout(() => {
      console.log('querySelector: ', window.document.querySelector('#__blaze-root'));
      console.log('getElementById: ', window.document.getElementById('__blaze-root'));
      window.close();
    }, 5000);
  },
});
```

which gives output:

```
done
querySelector:  null
getElementById:  null
```

From e.g. Chrome doing 'inspect' on an element on the page at `http://localhost:3000` will show that there is a `<div id="__blaze-root">`. 

Note that "Show page source" from browser does not show __blaze-root as it is loaded dynamically. The identical output is seen in jsdom in `document.body.innerHTML`, i.e. it is lacking the __blaze-root div and its contents.

Am I trying to push a cube through a triangular hole or is this a bug?

**Comment by vsemozhetbyt** [comment]
May be it would be helpful to add `virtualConsole` argument to `env` to check if there are any errors from scripts that load `__blaze-root`.

**Comment by kallewoof** [comment]
@vsemozhetbyt Thanks for the idea. I did that and got

`You are running a browser with no localStorage or userData support. Logging in from one tab will not cause another tab to be logged in.`

I am looking into ways to get around the above now.

**Comment by kallewoof** [comment]
I'm pretty much stuck. The files in the `scripts` option to `jsdom.env` are called after the Meteor app checks `localStorage` support so my proxy implementation's `window.localStorage` object doesn't appear in time.

**Comment by Sebmaster** [comment]
Use the `created` callback to shim functionality. Sadly it doesn't support importing script files like `scripts` does, so you'll have to do that yourself.

**Comment by kallewoof** [comment]
@Sebmaster Thanks, that did it! The message now went away, but the results are unfortunately the same.

The localStorage.js file: https://gist.github.com/kallewoof/0fa22a0ab3550e22c50f1357c1d0a4ce

The updated script:

```javascript
const fs = require('fs');
const jsdom = require('jsdom');
const virtualConsole = jsdom.createVirtualConsole();
virtualConsole.on('log', console.log);

const localStorage = fs.readFileSync('localStorage.js').toString();

jsdom.env({
  virtualConsole,
  url: 'http://localhost:3000/',
  features: {
    FetchExternalResources: ['script'],
    ProcessExternalResources: ['script'],
    SkipExternalResources: false,
  },
  created(error, window) { /* eslint no-unused-vars: 0 */
    eval(localStorage); /* eslint no-eval: 0 */
  },
  done: (errors, window) => {
    if (errors) console.log('errors:', errors); else console.log('done');
    setTimeout(() => {
      console.log('querySelector: ', window.document.querySelector('#__blaze-root'));
      console.log('getElementById: ', window.document.getElementById('__blaze-root'));
      window.close();
    }, 5000);
  },
});
```

The output:
```
done
querySelector:  null
getElementById:  null
```

**Comment by domenic** [comment]
You probably want `window.eval(localStorage)`, not `eval(localStorage)`.

**Comment by kallewoof** [comment]
Sorry for late response. I honestly didn't expect anyone to think that was the reason but there you have it. Tested with window.eval instead of eval and got the same results.

**Comment by Buom01** [comment]
Great new !

For me, Blaze-layout didn't do its job. I am finally find why.
Solution:
add `window.postMessage = undefined;` in jsdom created event.
Explantion:
We want to force meteor to use `window.setTimeout` in `Meteor.defer` instead of `postMessage`

See :
- https://github.com/meteor/meteor/blob/87681c8f166641c6c3e34958032a5a070aa2d11a/packages/meteor/setimmediate.js#L138
- https://github.com/kadirahq/blaze-layout/blob/0b2a50f7945e8392acf8226c62528f9b7923e697/lib/client/layout.js#L17

**Comment by kapouer** [comment]
A more forward-compatible approach is simply to provide a `window.setImmediate` function that doesn't try weird microtask tricks. All frameworks usually try to use setImmediate before anything else.

**Comment by domenic** [comment]
setImmediate is not standard (there exists a spec for it, but only IE implements it) so that's not an option for jsdom.

**Comment by JulianKingman** [comment]
@kallewoof did you ever figure this out? I can't seem to scrape any meteor sites, even [meteor.com](https://www.meteor.com/), I just get the site title and an empty page. Here's what I have so far:
````javascript
jsdom.env({
            url: 'https://www.meteor.com/',
            scripts: ["http://code.jquery.com/jquery.js"],
            userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36',
            headers: {
                'Connection': 'keep-alive',
                'Accept': '*/*',
                'Accept-Encoding': 'gzip, deflate, sdch',
            },
            features: {
                FetchExternalResources: ["script", "frame", "iframe", "link", "img"],
                ProcessExternalResources: ['script'],
            },
            created: function (err, window) {
                window.localStorage = function() {};
                window.postMessage = undefined;
            },
            done: function (err, window) {
                var $ = window.$;
                window.setTimeout(function () {
                    $('script, style').each(function () {
                        $(this).remove();
                    });
                    cosole.log(filterText($('html').text()));
                    window.close();
                }, 5000);
            },
        });
````
Note: the headers don't seem to matter, I was just trying different things.

**Comment by kallewoof** [comment]
@JulianKingman Nope, I gave up.

**Comment by JulianKingman** [comment]
It's strange, other JS sites seem to work (like Facebook).

**Comment by JulianKingman** [comment]
Data is loaded into meteor via websockets, is the reason this doesn't work because jsdom doesn't work with websockets (#1195)? Even with the localstorage message, it should still be possible to load the HTML content of a dynamically generated page.
