### ISSUE TITLE
Can't Import

### ISSUE THREAD

**Issue by PatrickDuncan** [tmpvar/jsdom#1520]
Hi, I'm simply trying to require('jsdom') after installing and it's giving an unexpected token ')' error on the third line. If I remove that line I get a error at the const.

Node v6.0.0
npm v3.8.6

I can require angular, angular-mocks, cheerio, etc. fine. Anyone know the problem?

**Comment by vsemozhetbyt** [comment]
Could you add the code example that causes these errors and copy-paste error messages it throws?

**Comment by PatrickDuncan** [comment]
I decided to use mocha-jsdom and no problems!
