### ISSUE TITLE
create element: tagname is undefined

### ISSUE THREAD

**Issue by kennytordeur** [tmpvar/jsdom#1524]
Hi,
When i create an element of tag "HR", i always get an undefined as tagname of this element.

`var element = document.createElement("HR");`
`console.log(element.tagName); // is always undefined`

Is there a way to resolve this?

**Comment by Sebmaster** [comment]
```js
var jsdom = require('jsdom');

var document = jsdom.jsdom();
var element = document.createElement("HR");
console.log(element.tagName); // works fine
```
works fine. Gotta be some other issue.

**Comment by kennytordeur** [comment]
I've found the problem, it was nothing related to jsdom.

Thanks for the awsner.

**Comment by raphaelokon** [comment]
@Sebmaster Hey. We are observing the same behavior. 

@kennytordeur Can you share what the bugger was for you?


Thanks.

```js
var jsdom = require("jsdom");

let doc = jsdom.jsdom("<!doctype html><html><head><meta charset=\"utf-8\"><style></style></head><body></body></html>");
console.log(jsdom.serializeDocument(doc)); // ==> <!doctype html><html><head><meta charset=\"utf-8\"><style></style></head><body></body></html>
console.log(jsdom.serializeDocument(doc.createElement("HR"))); //==> TypeError: Cannot read property 'tagName' of null at Object.exports.isElementNode
console.log(jsdom.serializeDocument(doc.createTextNode("Just text"))); //==> TypeError: Cannot read property 'tagName' of null at Object.exports.isElementNode

``` 

/cc @pglh-localstars

**Comment by Sebmaster** [comment]
Please look at the method you're using. serialize_Document_, so you have to provide it a `Document`. Use `outerHTML` if you want to serialize elements.

**Comment by raphaelokon** [comment]
Thanks. I know I am using serialize_Document_ – but that same function was working in v7 so I was wondering as I remembered this here …

https://github.com/tmpvar/jsdom/blob/master/Changelog.md#removed-non-standard-dom-apis

**Comment by Sebmaster** [comment]
That was basically just a coincidence since most of our internal structures to represent Elements were the same, but that changed during the big refactor in 8.0.0 (which probably broke it, I assume).

**Comment by raphaelokon** [comment]
Aye … very good! Thanks for that!
