### ISSUE TITLE
jsdom doesn't fetch img resources

### ISSUE THREAD

**Issue by levimm** [tmpvar/jsdom#1525]
Hi guys,
I have following code trying to visit a site through url using jsdom.env:

```js
jsdom.env({
  proxy: "XXX",
  userAgent: "XXX",
  url: "XXX",
  features:  {
          FetchExternalResources   : ['script', 'link', 'frame', 'iframe', 'img'],
          ProcessExternalResources : ['script'],
          SkipExternalResources : false
  },
  done: ........
});
```

It works for javascript resources. But not works for images. There're no such requests for the images from the network traffic. Is this intended?

**Comment by Sebmaster** [comment]
Image loading is only enabled if the [canvas module is enabled](https://github.com/tmpvar/jsdom/blob/37532c74235c9eb0260bdcf424719c8e3d7b129b/lib/jsdom/living/nodes/HTMLImageElement-impl.js#L12-L23). It's a bit unexpected I guess.

**Comment by levimm** [comment]
Thanks. @Sebmaster
