### ISSUE TITLE
Pure JavaScript implementation?

### ISSUE THREAD

**Issue by fxfactorial** [tmpvar/jsdom#1526]
Is it possible to get 

1) this library as a single JS file including all its dependencies 
2) a pure JavaScript implementation that doesn't assume the existence of node, aka no fs module 

Best is both, thank you

**Comment by domenic** [comment]
Nope! jsdom depends crucially on Node or node-like libraries.

**Comment by fxfactorial** [comment]
Okay, is it possible to know what parts of the nodeApi are actually required?

**Comment by domenic** [comment]
I am not aware of use using any parts that are not required.

**Comment by fxfactorial** [comment]
I'm saying is like to know what parts of the nodejs API are actually used/expected to exist

**Comment by Joris-van-der-Wel** [comment]
This list is probably incomplete:
* require('vm') - a sandbox for the scripts on the page you are loading
* require('fs')
* require('url')
* require("path")
* require("querystring")
* require("events")
* require("crypto")
* require("https")
* require("zlib")
* require("os")
* require("buffer")
* process.nextTick

However, you can use most of jsdom in a browser using browserify. We even test for this. In this case we can not create a proper sandbox, nor can we read local files.

**Comment by fxfactorial** [comment]
Much appreciated

**Comment by fxfactorial** [comment]
@Joris-van-der-Wel How can I get jsdom wrapped up using browserify?

**Comment by Joris-van-der-Wel** [comment]
something like:

```
// foo.js
const jsdom = require('jsdom');
doStuff(jsdom.jsdom('<p>foo</p>'));
```
`browserify foo.js`
