### ISSUE TITLE
svgElement.className should not do anything

### ISSUE THREAD

**Issue by adius** [tmpvar/jsdom#1528]
As can be seen in https://jsfiddle.net/qccp9c10/ `svgElement.className` should not set the class on the element,
but in jsdom it does.

In another instance I even got this error message: `TypeError: Cannot assign to read only property 'className' of object '#<SVGCircleElement>'`
But I wasn't able to reproduce this error with a simple example.

**Comment by Sebmaster** [comment]
We don't implement SVG (yet). svgElement is therefore actually an `HTMLUnknownElement` and setting className there is valid (I assume without checking).

> In another instance I even got this error message: `TypeError: Cannot assign to read only property 'className' of object '#<SVGCircleElement>'`

Pretty sure that's not a jsdom thing, since we don't have `SVGCircleElement`, therefore also can't produce the error.

**Comment by adius** [comment]
> We don't implement SVG (yet)

Couldn't you then at least print a warning like 'Not implemented yet. Behavior can differ from standard.' or something like this

> In another instance I even got this error message: TypeError: Cannot assign to read only property 'className' of object '#<SVGCircleElement>'
> But I wasn't able to reproduce this error with a simple example.

What I actually meant is that in Browsers this error pops up and should therefore also occur
in jsdom under the same circumstances.
(The problem is I wasn't able to reproduce the exact circumstances under which this error occurs)
