### ISSUE TITLE
[TypeError: Cannot read property '_location' of null]

### ISSUE THREAD

**Issue by xuorig** [tmpvar/jsdom#1530]
Hello,

I'm getting `[TypeError: Cannot read property '_location' of null]` on a specific test.

It seems to appear when using https://github.com/stacktracejs/stacktrace.js only. Looking at the source, it seems like `idlUtils.wrapperForImpl(idlUtils.implForWrapper(window._document)` is `null`.

How can that happen, any clues to help me debug here ?

Thanks!

**Comment by domenic** [comment]
Can you provide a small (~10 line) file we can use to reproduce this error?

**Comment by xuorig** [comment]
So I ended up never being able to reproduce, I'll go ahead and close this.
