### ISSUE TITLE
Appending a Blob to FormData fails when filename not included in append()

### ISSUE THREAD

**Issue by DrewML** [tmpvar/jsdom#1533]
To start with, thanks to all the maintainers for the amazing job on this lib!

```
Cannot read property 'replace' of undefined
TypeError: Cannot read property 'replace' of undefined
    at new File (/Users/alevine/planner-ui/node_modules/jsdom/lib/jsdom/living/file.js:14:40)
    at FormData.append (/Users/alevine/planner-ui/node_modules/jsdom/lib/jsdom/living/form-data.js:30:17)
```

Quick summary of what is happening:

1. Code creates new `FormData` in `jsdom`
2. `.append()` is called with 2 arguments (`name` and `value`), where `value` is a Blob created with `new Blob()`
3. `jsdom` calls `new File()`, using `value.name` as the filename
4. The constructor for `File` tries to call `String.prototype.replace` on `fileName`, which throws because `fileName` (which is optional for a manually constructed `Blob`) is undefined

I was able to address this in my own code for the time being by supplying the 3rd argument (`filename`) to `append()`.

Here is some quick sample code that can be used to replicate:

```javascript
var formData = new FormData();
var file = new Blob([
   JSON.stringify({})
], { type: 'application/json' });
formData.append('somename', file);
```

I'd be willing to contribute a fix, but I'm not 100% on what the _correct_ fix is. I can try and dig into the spec once I'm outside of work hours, but any hints to send me in the right direction would be appreciated :)

**Comment by DrewML** [comment]
Ok, looked into this a little bit more. I'm new to reading the spec, so forgive my ignorance if I'm missing something obvious.

https://xhr.spec.whatwg.org/#concept-formdata-entry

> The FormData object represents an ordered list of entries. Each entry consists of a name and a value.

> For the purposes of interaction with other algorithms, an entry's type is "string" if its value is a string and "file" otherwise. If an entry's type is "file", its filename is the empty string if value is not a File object, and otherwise its filename is the value of entry's value's name attribute.

https://w3c.github.io/FileAPI/#file-constructor

> Let n be a new string of the same size as the fileName argument to the constructor. Copy every character from fileName to n, replacing any "/" character (U+002F SOLIDUS) with a ":" (U+003A COLON).

> Return a new File object F such that:

> F has a readability state of OPENED.
F refers to the bytes byte sequence.
F.size is set to the number of total bytes in bytes.
F.name is set to n.

It doesn't really seem like the spec defines what to set the `name` as in the scenario that one is not provided, and the entry type for the `append` call is _not_ a string.

It looks like both Firefox and Chrome set the `name` to `blob`. Would this be an acceptable solution to implement in `jsdom`?

**Comment by domenic** [comment]
The trick is that it's hidden inside the IDL: https://w3c.github.io/FileAPI/#dom-file-file

```webidl
[Constructor(sequence<BlobPart> fileBits,
            [EnsureUTF16] DOMString fileName,
            optional FilePropertyBag options
),
Exposed=(Window,Worker)]
```

Right now File is not implemented using jsdom's Web IDL framework, so we need to implement the logic here manually. A first pass might just be

```js
if (fileName === undefined) {
  throw new TypeError("fileName is required");
}
fileName = String(fileName);
```

which omits the [EnsureUTF16] logic, but at least takes care of the `DOMString`. This would be a prelude before any of the function's actual logic. So a filename must be provided.

Similarly, FormData's append is

```webidl
  void append(USVString name, USVString value);
  void append(USVString name, Blob value, optional USVString filename);
```

which in combination with the given algorithm should end up something like this (although the details are *very* complicated and I might have gotten it wrong):

```js
append(name, value, filename) {
  if (name === undefined) {
    throw new TypeError("name is required");
  }
  name = conversions.USVString(name); // conversions = require("webidl-conversions");

  if (value === undefined) {
    throw new TypeError("value is required");
  }
  
  if (isBlob(value)) {
    if (filename !== undefined) {
      filename = conversions.USVString(value);
      value = new File([value], filename);
    }
  } else {
    value = conversions.USVString(value);
  }
  
  appendNewEntry({ name, value });
}
```

Does this make sense?

**Comment by DrewML** [comment]
Hey @domenic,

Thanks for taking the time to break that down for me - very much appreciated.

re: the changes to make the `File` constructor throw, that definitely makes sense to me.

re: the updates to the `append` algorithm, there is piece I'd like further clarification on.

```javascript
  if (isBlob(value)) {
    if (filename !== undefined) {
      filename = conversions.USVString(value);
      value = new File([value], filename);
    }
  } else {
    value = conversions.USVString(value);
  }
```

In this case, after making the updates to the `File` constructor, wouldn't this still throw (although, more explicitly this time) because we would not be creating a `File` instance at all, due to `filename` being undefined when not provided?

**Comment by domenic** [comment]
My reading of the spec is that you do not create a File from a Blob in that case. It simply says:

> Append a new entry whose name is name, and value is value, to context object's list of entries. 

So the entry value will still be a string.

Do you see a different behavior in browsers? If so we may have found a spec bug.

**Comment by DrewML** [comment]
> Do you see a different behavior in browsers?

Yeah, both Chrome and Firefox are creating a `File`.

Sample code:

```javascript
var formData = new FormData();
var file = new Blob([
   JSON.stringify({})
], { type: 'application/json' });
formData.append('somename', file);
formData.entries().next().value
```

Chrome:
![image](https://cloud.githubusercontent.com/assets/5233399/16363957/6536b40a-3ba0-11e6-831a-25fc8018684e.png)

Firefox:
![image](https://cloud.githubusercontent.com/assets/5233399/16363960/7414b882-3ba0-11e6-99ee-81a702257040.png)

**Comment by domenic** [comment]
Thanks! Filed https://github.com/whatwg/xhr/issues/73; when we get some spec clarity here we can fix jsdom.

**Comment by DrewML** [comment]
@domenic Thanks for filing that. Looks like those changes were reverted. New algorithm updates state:

![image](https://cloud.githubusercontent.com/assets/5233399/16437304/4792b94a-3d6b-11e6-9f2c-f1f2401c16a5.png)

Just to verify, at this point, I assume the correct PR to submit to `jsdom` would include:

1. The updates you mentioned to the `File` constructor to throw explicitly when the filename is mentioned
2. Implement the algorithm you outlined above for `append`, but include the addition of steps 3 & 4

Does that sound right?

**Comment by domenic** [comment]
Yeah, that sounds right!

**Comment by DrewML** [comment]
You beat me to it - thank you!
