### ISSUE TITLE
Resource loader failed to download images

### ISSUE THREAD

**Issue by levimm** [tmpvar/jsdom#1536]
Hi guys,

Recently I have some troubles to download images. It's working fine previously until [this](https://github.com/tmpvar/jsdom/commit/37532c74235c9eb0260bdcf424719c8e3d7b129b#diff-1a52358c6676670a7d156c67445b1e2b) commit. Now the network relative url is parsed into local path on my machine. Is this intended or it's a bug?

Cheers

**Comment by Sebmaster** [comment]
Do you have an example code + URL=

**Comment by levimm** [comment]
You can easily reproduce it by using a localhost serving with image like &lt;img src="/test.jpg"&gt;. Then use jsdom.env to request the server. In resource-loader.js, the string "/test.jpg" is never parsed into network path because `const resourceUrl = exports.resolveResourceUrl(document, url);` is removed. So it's resolved into local path like "C:\\test.jpg" later.

**Comment by domenic** [comment]
Can you please provide us with 10-20 lines of example code that we can debug? Asking us to set up such a server based on your verbal description is OK, but it means that this will be lower-priority compared to other issues where the reporters have made our jobs easier.

**Comment by levimm** [comment]
server.js
`var path = require('path');
var express = require('express');
var app = express();
var staticPath = path.resolve(__dirname, '/public');
app.use(function (req, res, next) {
    console.log("Request: " + req.url);
    next();
});
app.use(express.static('public'));
app.listen(3000, function() {
    console.log('listening');
});`

client.js
`var jsdom = require("jsdom");
 jsdom.env({
  url: "http://127.0.0.1:3000/test.html",
  features: {
    FetchExternalResources: ['script', 'link', 'frame', 'iframe', 'img'],
    ProcessExternalResources: ["script"],
    SkipExternalResources: false
  },
  done: function(err, window) {
  }
});
`

test.html
`<html>
    <head>
     </head>
<body>
	 <img src="/test.jpg">
     </body>
</html>`

**Comment by domenic** [comment]
Great, thank you! I hope to have time ot look into this this weekend.
