### ISSUE TITLE
What is the best way to detect if the script is running in JSDOM environment?

### ISSUE THREAD

**Issue by JanisE** [tmpvar/jsdom#1537]
What is the best way to detect within a script whether it is running in a browser normally, or it is running in JSDOM by NodeJS?

**Comment by domenic** [comment]
I would probably do `navigator.userAgent.includes("Node.js") || navigator.userAgent.includes("jsdom")`.

(The first condition is true in current jsdom; a future major version of jsdom will change so that the latter condition is true instead.)

**Comment by JanisE** [comment]
OK, thank you! I did `window.name == 'nodejs'` until now.

**Comment by mikemellor11** [comment]
Any news on when the jsdom user agent will be implemented? We run our scripts in the browser and in node so we could do with a better check for jsdom specifically.

**Comment by domenic** [comment]
It's already implemented; see the readme.

**Comment by matthew-dean** [comment]
The only way to detect JSDOM is by looking for a sub-string in the user-agent? There's nothing more efficient? Also, I don't see this documented in the readme.

**Comment by sokcuri** [comment]
```typescript
const isNativeWindow = Object.getOwnPropertyDescriptor(_window, 'window')?.get?.toString().includes('[native code]');
```

JSDOM has custom getters. if the getter is native code, you can check window is JSDOM or native window

**Comment by brillout** [comment]
@sokcuri Neat, this seem to work reliably.
```js
const isRealBrowser = Object.getOwnPropertyDescriptor(globalThis, 'window')?.get?.toString().includes('[native code]') ?? false
```
