### ISSUE TITLE
how to detect element changes in jsdom 9

### ISSUE THREAD

**Issue by kennytordeur** [tmpvar/jsdom#1540]
Hi,

I know that Mutationobservers are not support so i used the DOMATTRCHANGED event. This worked but when i updated to the latest version of jsdom, this event never got fired. Is there a reason for this? And how can i detect element changes is the latest version of jsdom?

Thanks

**Comment by Sebmaster** [comment]
See the [changelog](https://github.com/tmpvar/jsdom/blob/master/Changelog.md#900). You'll have to stay with 8.x for now if you can't find a workaround for that.

**Comment by kennytordeur** [comment]
ok thanks. i think i just need to stay with the 8.x for now.
