### ISSUE TITLE
‘defaultEncoding’ and ‘encoding’

### ISSUE THREAD

**Issue by HsuTing** [tmpvar/jsdom#1541]
I want to set `encoding: ‘utf-8’` to parse a Chinese website, but it did not show the string as `utf-8`. As a result, I trace the source code. I found it use `defaultEncoding` rather than `encoding`, and it set `defaultEncoding` to `windows-1252`. Finally, I set `defaultEncoding` rather than `encoding`.

So, what is `encode` used for?

**Comment by domenic** [comment]
I don't know what `encode` is. Where did you find that?

**Comment by HsuTing** [comment]
Sorry, my fault. I meen `encoding`.
I see [this page](https://github.com/tmpvar/jsdom/commit/de94af13c203d4d3c56cb29de184c685c9db7dc6).
So, I think I can set `encoding: utf-8`.

**Comment by domenic** [comment]
Oh. I think the code has changed a lot since 2011.

In general overriding the encoding is not supported. Instead, we act like browsers and parse for `Content-Type` headers and `<meta charset>` declarations.

**Comment by HsuTing** [comment]
Thank you.
I think new way is very great 👍 .
