### ISSUE TITLE
Add an evalScript API

### ISSUE THREAD

**Issue by domenic** [tmpvar/jsdom#1543]
I believe that both @kapouer @cpojer want something like the following:

```js
const vm = require("vm");

// https://nodejs.org/api/vm.html#vm_new_vm_script_code_options
const script = new vm.Script(`/* lots of code here */`, { filename, lineOffset, columnOffset, timeout, ... });

jsdom.evalVMScript(window, script);
```

(In the upcoming [newapi](https://github.com/tmpvar/jsdom/blob/newapi/lib/newapi1.md) this would look like `dom.evalVMScript(script)`)

This is less simple and straightforward compared to `window.eval`, but it allows some benefits which are useful for our heavy users, like code caching, filename/line number/column number customization, and timeouts.

Would this meet peoples' needs?

**Comment by kapouer** [comment]
Not sure the timeout should be handled by jsdom. Otherwise yes.

**Comment by domenic** [comment]
It's an option of `vm.Script` actually :)

**Comment by cpojer** [comment]
yeah this would be awesome, thanks @domenic. Can we get something like this in next week or so?

**Comment by Sebmaster** [comment]
We should enable scripting if `ProcessExternalResources: ['script']` wasn't given, I think?

**Comment by domenic** [comment]
I'd kind of prefer to just do the minimal work here and then create a better version for newapi, which has the proper distinction between "dangerously" and "outside-only" to make it work nicely.
