### ISSUE TITLE
querySelector fails on class selector

### ISSUE THREAD

**Issue by ain** [tmpvar/jsdom#1544]
__How to reproduce__:

1. Create `jsdom`:
  ```js
global.document = jsdom.jsdom(`<!doctype html>
  <html style="margin-top:10px;">
    <head>
      <meta charset="utf-8">
    </head>
    <body style="margin-top:20px;" class="ui-page">
    </body>
  </html>`);
  ```

2. Retrieve `.ui-page`: 
  ```js
let page = document.querySelector('.ui-page');
  ```

__What happens__: 
`page` is null.

__What should happen__:
`page` should equal 
  ```js
let page = document.querySelector('body');
```
which is not null.

Version: `9.2.1`.

**Comment by vsemozhetbyt** [comment]
I can't reproduce on jsdom 9.3.0.
```js
const jsdom = require('jsdom');

global.document = jsdom.jsdom(`<!doctype html>
<html style="margin-top:10px;">
  <head>
    <meta charset="utf-8">
  </head>
  <body style="margin-top:20px;" class="ui-page">
  </body>
</html>`);

console.log(document.querySelector('.ui-page'));
```
```
HTMLBodyElement {}
```

**Comment by domenic** [comment]
Cannot reproduce here either. Going to close, but happy to reopen if we got something wrong. Thanks for the nice issue template with very small repro case!

**Comment by ain** [comment]
No luck here. Tested both `9.3.0` and `9.4.0`. 

Class-based query on any other element than `body` succeeds, but not the body.

**Comment by Sebmaster** [comment]
Maybe the class has been removed by the time you try to retrieve the element? Try logging `jsdom.serializeDocument(document)` and see if it still contains the class.

**Comment by ain** [comment]
Yup, had the same idea, must be implementation error, otherwise wouldn't make sense.

**Comment by ain** [comment]
Confirmed, implementation error. `document.write` had killed the classes on body element.

Sorry for the noise, hopefully it'll prove useful for someone having an hiccup on the same topic.
