### ISSUE TITLE
[9.4.0] ReferenceError: MouseEvent is not defined

### ISSUE THREAD

**Issue by tleunen** [tmpvar/jsdom#1546]
Getting this error with the newly released 9.4.0.

```
ReferenceError: MouseEvent is not defined
```

See https://circleci.com/gh/tleunen/react-clickdrag/88

**Comment by Sebmaster** [comment]
```js
jsdom = require('jsdom');

const doc = jsdom.jsdom('<!doctype html><html><body></body></html>', {
  url: 'http://test/'
});
const window = doc.defaultView;

console.log(window.MouseEvent)
```
=>
```
me@host:~/jsdom/test$ node test
[Function: MouseEvent]
```

Looks fine to me. Your code is wrong, it was probably broken by 8978de23642f7276f20640f911dc1eebfc3f1d05. But if you check `Object.keys(window)` in your browser, you'll see that `MouseEvent` is not in there.

**Comment by tleunen** [comment]
Interesting, `window.MouseEvent` works, but not `MouseEvent`. It used to work with 9.3.0

**Comment by Sebmaster** [comment]
Because your setup.js is broken and expects interfaces on window to be enumerable, which is not the case according to spec.

**Comment by tleunen** [comment]
Could you give me a working example then?
Because with your initial example `MouseEvent` is still not defined. `window.MouseEvent` is though.

**Comment by Sebmaster** [comment]
It's not supposed to be defined globally. You're (trying to) mixing your node global with the window globals, which is not something we want to support at all. See [this thread](https://github.com/tmpvar/jsdom/issues/1203#issuecomment-160725194) for more info; it comes up somewhat regularly.

**Comment by tleunen** [comment]
Gotcha.

Could you tell me where the spec says it should not be enumerable? Is it this section ([from here](https://www.w3.org/TR/html5/browsers.html#the-window-object))?
> When the incumbent settings object specifies an effective script origin that is different than a Window object's Document's effective script origin, the user agent must act as if any changes to that Window object's properties, getters, setters, etc, were not present, and as if all the properties of that Window object had their [[Enumerable]] attribute set to false.

Not sure to really understand all this, but if you say it should not be enumerable in jsdom, I guess that's correct :)

**Comment by domenic** [comment]
No, it's in the Web IDL spec, in the section on interface objects. (Plus, nobody implements the W3C's HTML fork. See https://html.spec.whatwg.org instead.)

**Comment by Sebmaster** [comment]
[This](https://heycam.github.io/webidl/#es-interfaces) is the section where it's defined.

**Comment by tleunen** [comment]
Might be related but since 9.4.0, it seems I'm not able to use `sinon` to restore a spy on `document.addEventListener`

The second time I create the spy, I get this error: `TypeError: Attempted to wrap addEventListener which is already wrapped`, but I'm 100% sure the spy is restored. (`document.addEventListener.restore();`)

Any idea?
