### ISSUE TITLE
Globalizing window keys

### ISSUE THREAD

**Issue by amsul** [tmpvar/jsdom#1549]
From https://github.com/tmpvar/jsdom/blob/master/Changelog.md for v9.4.0:

> Fixed all constructors that appears as globals on the jsdom window object to be non-enumerable.

As a result of this, jsdom-global breaks at setting up the globals: https://github.com/rstacruz/jsdom-global/blob/bc52cfefbfe9931e6c367d38cdd8a60cd216dce8/index.js#L37-L41

```js
Object.keys(window).forEach(function (key) {
  if (blacklist.indexOf(key) !== -1) return
  keys.push(key)
  global[key] = window[key]
}))
```

How is this behavior expected to be handled now?

**Comment by domenic** [comment]
See https://github.com/tmpvar/jsdom/wiki/Don't-stuff-jsdom-globals-onto-the-Node-global. This was never a supported scenario.

Closing since this is not a jsdom bug, but happy to continue discussing in the closed thread.

**Comment by amsul** [comment]
@domenic ah, thanks for the clarification.

So the only way to achieve the same goal is to pass the scripts in as a string?

I'm sure this may be beyond your scope of knowledge, but would you happen to have any suggestions on how this can be done while running tests with mocha?

**Comment by domenic** [comment]
I gave a pretty clear example of how to do that in https://github.com/tmpvar/jsdom/wiki/Don't-stuff-jsdom-globals-onto-the-Node-global#an-example-in-a-test-runner, I thought.

**Comment by amsul** [comment]
@domenic I meant more as something we could simply just `--require` from the cli, which `jsdom-global` enabled. But I guess not. Thanks anyways!

**Comment by domenic** [comment]
I imagine there are probably opportunities for helper packages that make the process easier. For example, maybe you could write a helper library to simplify all that to

```js
const jsdomTester = require("jsdom-tester");

let window;
beforeEach(() => window = jsdomTester(require.resolve("../../whatever.js")));

// your tests here
```

I guess you could even shorten this further to just

```js
require("jsdom-tester")(require.resolve("../../whatever.js"));
```

if you were willing to create a global `window` variable.

I'm happy to add examples of such things to the wiki page if people come up with good ones.
