### ISSUE TITLE
set html content of an element behaves different with browser

### ISSUE THREAD

**Issue by levimm** [tmpvar/jsdom#1552]
Hi Guys,

I notice this different behavior when you try to set the html content of an element. Here's an example:
`<script>jQuery("li").html("<span> Hello </span>");</script>`
`<li><script>var tmp3 = "Test script 3";</script></li>`

In browser(chrome), if I set the html before the li element show up, nothing will happen. The li element will not be changes. But in jsdom, the content will always be changed no matter what order it is. Is this intended?

Cheers

**Comment by Sebmaster** [comment]
Not intended, but sadly a problem with our script loading behaviour which is hard to fix.
