### ISSUE TITLE
No inheritance between standard interfaces

### ISSUE THREAD

**Issue by muroc** [tmpvar/jsdom#1553]
```js
if (document.body instanceof window.Node) {
  // standard
} else {
  // jsdom
}
```

I could fix it if someone provide me with directions.

**Comment by Sebmaster** [comment]
Works for me. Which version are you on?

**Comment by domenic** [comment]
Cannot reproduce: https://tonicdev.com/577c4dec7da47e13004552c8/577c4dec7da47e13004552c9

**Comment by muroc** [comment]
ahh, sorry... my bad
