### ISSUE TITLE
Expose window on global

### ISSUE THREAD

**Issue by KrysKruk** [tmpvar/jsdom#1554]
The idea is to provide a method which will easily extend the given object by the JSDom `window` own properties with their descriptors.

##### Usecase
Using JSDom in unittests on Node to simulate browser environment.

##### Reason
After https://github.com/tmpvar/jsdom/commit/bc9b6b40fd4e9e8bbedd440fdc491f6ace561324 the `Image` constructor is no longer *enumerable*. `Object.getOwnPropertyNames` seems to be broken, because it doesn't contain `Image` property. See https://github.com/airbnb/enzyme/issues/483 .

##### Disadvantages
I'm not sure whether it's JSDom job even if it's a common usecase (e.g. [Using Enzyme with JSDOM](https://github.com/airbnb/enzyme/blob/master/docs/guides/jsdom.md)). Also it looks like a workaround for the V8 `Object.getOwnPropertyNames` bug.

What do you think? I'm still not able to extract what's wrong with `Object.getOwnPropertyNames` and create an issue with some reasonable reproduce steps.

**Comment by Sebmaster** [comment]
See #1549. You shouldn't mix `global` and `window`, but rather execute your code in the jsdom sandbox (or at least define all your functions you want to test there and then call them from outside).

**Comment by domenic** [comment]
Yes, this is explicitly a very bad idea and something you should not do: https://github.com/tmpvar/jsdom/wiki/Don't-stuff-jsdom-globals-onto-the-Node-global

**Comment by domenic** [comment]
Forgot to add, closing since this is not a jsdom bug, but happy to continue discussing in the closed thread.
