### ISSUE TITLE
Cannot import jsdom

### ISSUE THREAD

**Issue by vladnicula** [tmpvar/jsdom#1558]
Using the following bable plugins:

```
"babel-core": "^6.10.4",
"babel-loader": "^6.2.4",
"babel-plugin-react-transform": "^2.0.0",
"babel-plugin-transform-class-properties": "^6.10.2",
"babel-plugin-transform-object-assign": "^6.5.0",
"babel-polyfill": "^6.9.1",
"babel-preset-es2015": "^6.5.0",
"babel-preset-react": "^6.5.0",
```

And mocha and jsdom:

```
"jsdom": "^9.4.1",
"mocha": "^2.4.5",
```

And the following `.babelrc`:

```
{
	"presets": ["es2015", "react"],
	"plugins": ["transform-object-assign", "transform-class-properties"]
}
```

And this packages.json test command:

```
"test": "find ./shared ./client -name '*.spec.js' | xargs mocha --compilers js:babel-core/register --require test/helpers/react-jsdom.js --reporter spec --recursive -w -c"
```

I get:

> Cannot find module './properties/azimuth'

If I don't import jsdom in the `test/helpers/react-jsdom.js` file, I don't get this error. 

Is this maybe related to jsdom? 

Thanks!

**Comment by vladnicula** [comment]
Looks like the cssstyle package is not correctly installed with the latest version of jsdom. 

https://github.com/chad3814/CSSStyleDeclaration/blob/master/lib/properties/azimuth.js doesn't exist in my node modules.

**Comment by Sebmaster** [comment]
CSSStyle should [compile all those files together](https://github.com/chad3814/CSSStyleDeclaration/blob/master/scripts/generate_properties.js) during the publish process, so this file should not exist I think. No idea why babel tries to load it.

**Comment by vladnicula** [comment]
Removing jsdom and reinstalling worked. Not sure what was the issue. 👍 thanks anyway
