### ISSUE TITLE
MouseEvent properties are not initialized correctly when using .click() method

### ISSUE THREAD

**Issue by moll** [tmpvar/jsdom#1559]
Hey,

I'm not sure what any spec says about that, but from my limited testing of browsers, synthesized click events come with a `detail` property of `0`, differentiating them from real clicks that have it at 1 or higher. The `button` and `buttons` property are `0`, too, indicating the left mouse button.

[JSDOM's HTMLElement.prototype.click implementation](https://github.com/tmpvar/jsdom/blob/94ce8c4ed79f866528cd464875635cfaa3ae84cb/lib/jsdom/living/nodes/HTMLElement-impl.js#L67) has `detail` and other properties as `undefined`.

**Comment by domenic** [comment]
Hmm. Because [the default value for the dictionary](https://github.com/tmpvar/jsdom/blob/13b2326b57ec621c4b75a64966ea23d89d8fce99/lib/jsdom/living/events/UIEvent.idl#L9) is zero, it should be 0 in all click events created by default. Do you have a small 10-line test case showing that this is not the case in jsdom?

**Comment by moll** [comment]
For some reason, the following throws for me on JSDOM v9.4.1 with Node v4.3.0:

```js
var Jsdom = require("jsdom")
var assert = require("assert")

var reporter = Jsdom.createVirtualConsole()
reporter.on("jsdomError", function(err) { throw err })
var document = Jsdom.jsdom(undefined, {virtualConsole: reporter})
var window = document.defaultView

document.body.addEventListener("click", function(ev) {
  assert(ev.detail === 0)
})

document.body.click()
```

**Comment by domenic** [comment]
@Sebmaster, this is an interesting bug arising from the webidl2js bindings. As-is, the line

```js
    const event = MouseEvent.createImpl(["click", { bubbles: true, cancelable: true }], {});
```

never triggers the actual generated MouseEvent constructor, and thus never gets all the dictionary defaulting goodness. Any ideas on the best fix? Maybe just call the real constructor, then use implForWrapper? Although even that is failing, hmm... I'll upload a PR.

**Comment by moll** [comment]
Just to confirm liveliness, I believe v9.12 has not fixed this yet. My workaround since last year for those in need:

```js
var HTMLElement = require("jsdom/lib/jsdom/living").HTMLElement
var MouseEvent = require("jsdom/lib/jsdom/living").MouseEvent

HTMLElement.prototype.click = function() {
  this.dispatchEvent(new MouseEvent("click", {
    button: 0, buttons: 1, bubbles: true, cancelable: true, detail: 0
  }))
}
```

**Comment by zaaack** [comment]
Hit this problem, too. This break my test code with react-router-dom's Link, because it is using `event.button===0` to trigger navigate.
See: https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/modules/Link.js#L41
