### ISSUE TITLE
window.getComputedStyle poor performance

### ISSUE THREAD

**Issue by staramir** [tmpvar/jsdom#1560]
I am currently in the process of bringing in some code written for the browser to nodejs which involves running window.getComputedStyle on a lot of elements. In the browser we are seeing times under 500ms where as with jsdom's implementation of getComputedStyle our times are above 5000ms. 

I created a sample that takes ~3000ms to execture in nodejs using jsdom@9.4.1, jquery@3.1.0 and xmldom@0.1.22

```
var jsdom = require('jsdom');
var window = jsdom.jsdom().defaultView;
var DOMParser = require('xmldom').DOMParser;
var jQuery = $ = require('jquery')(window);

var xml = '<span style="color: #fff;">test</span>';
var xmlDom = $(xml);

console.time('getComputedStyle');
for (var i = 0; i < 1000; i++) {
    var cs = window.getComputedStyle(xmlDom[0]);
}
console.timeEnd('getComputedStyle');
```

And here is a jsfiddle to test in broswer which takes about ~0.5ms: https://jsfiddle.net/3dzLLf5x/

**Comment by muroc** [comment]
And why do you need to call `window.getComputedStyle`?

**Comment by staramir** [comment]
While I listed the test case with a single element, generally our documents have many nested elements and we need to process the computed styles for all the child elements.

**Comment by vsemozhetbyt** [comment]
Node.js 6.3.0, jsdom 9.4.1, Win 7. Simplified test code:

```js
process.stdout.write('Loading jsdom... ');
const jsdom = require('jsdom');
console.log('Loaded.\n');

const doc = jsdom.jsdom('');
const win = doc.defaultView;

console.time('getComputedStyle');
for (let i = 0; i < 1000; i++) {
    const cs = win.getComputedStyle(doc.body);
}
console.timeEnd('getComputedStyle');
```
```
getComputedStyle: 7193.454ms
```
In the last Chrome for `about:blank`:
```js
console.time('getComputedStyle');
for (let i = 0; i < 1000; i++) {
    const cs = window.getComputedStyle(document.body);
}
console.timeEnd('getComputedStyle');
```
```
getComputedStyle: 3.725ms
```

**Comment by Joris-van-der-Wel** [comment]
jsdom has a benchmarking infrastructure that you might be interested in (using benchmarkjs). See here for an example: https://github.com/tmpvar/jsdom/blob/master/benchmark/dom/construction.js

You can even let browserified jsdom compete with chrome, simply checkout jsdom and run:
```
npm install
npm run prepublish
npm run benchmark-browser
```
This last command gives you a file url that you can visit with chrome. To run a benchmark, open the chrome devtools console and use the global `run()` function. Here's an example:

```
run('dom/construction/createElement')
# dom/construction/createElement #
native x 3,014,759 ops/sec ±3.73% (48 runs sampled)
jsdom  x 230,345 ops/sec ±1.70% (63 runs sampled)
Fastest is "native", which is 13.09x faster than the slowest "jsdom "
```

**Comment by vsemozhetbyt** [comment]
According to perf log, the main suspect is [line 397](https://github.com/dperini/nwmatcher/blob/master/src/nwmatcher-noqsa.js#L397) in the `nwmatcher-noqsa.js`. If commented out, the time become ~900 ms (still much slower then in the browser, but 7 times faster then previous result). However, many errror messages are outputed in the console with this line commented out (but no throw or script abortion).

**Comment by flaviut** [comment]
The link referenced by @vsemozhetbyt should be https://github.com/dperini/nwmatcher/blob/29a1cdc284e330ec6aa38e31c2f02e755a536381/src/nwmatcher-noqsa.js#L397

I've also run across this issue. There are two problems here, as far as I can tell:

1. Getting an error at this point in the code isn't very exceptional and happens very frequently, returning an error is a better choice (and doesn't force nodejs to gather a stack trace!)
2. [`setPropertiesFromRule()`](https://github.com/tmpvar/jsdom/blob/8403b8a/lib/jsdom/browser/Window.js#L380) doesn't know how to parse CSS. As an example, given the rule (from `default-stylesheet.js`): 
```
-webkit-any(article,aside,nav,section) :-webkit-any(article,aside,nav,section) :-webkit-any(article,aside,nav,section) :-webkit-any(article,aside,nav,section) h1
```
`setPropertiesFromRule()` will try to split it up like
```json
[
   "",
   ":-webkit-any(article",
   ",",
   "aside",
   ",",
   "nav",
   ",",
   "section) :-webkit-any(article",
   ",",
   "aside",
   ",",
   "nav",
   ",",
   "section) :-webkit-any(article",
   ",",
   "aside",
   ",",
   "nav",
   ",",
   "section) :-webkit-any(article",
   ",",
   "aside",
   ",",
   "nav",
   ",",
   "section) h1",
   ""
]
```

which is obviously incorrect.

**Comment by dperini** [comment]
@staramir / @vsemozhetbyt 
you can retry now using nwmatcher 1.4.0 the changes may be of help improving the performances.
You will have to use both the VERBOSITY and LOGERRORS flags, setting them to `false` to mute both the exceptions and the console output.

**Comment by flaviut** [comment]
Updated benchmarks:

# Code
## Browser
```js
console.time('getComputedStyle');
for (let i = 0; i < 10000; i++) {
    const cs = window.getComputedStyle(document.body);
}
console.timeEnd('getComputedStyle');
```

## Node
```js
const { JSDOM } = require('jsdom');
const dom = new JSDOM('<body></body>');
const win = dom.window;

console.time('getComputedStyle');
for (let i = 0; i < 10000; i++) {
    const cs = win.getComputedStyle(win.document.body);
}
console.timeEnd('getComputedStyle');
```

# Results

| Test                                        	| Duration 	|
|---------------------------------------------	|----------	|
| jsdom@10 (VERBOSITY=true, LOGERRORS=true)   	| 115.70s  	|
| jsdom@10 (VERBOSITY=false, LOGERRORS=false) 	| 8.90s    	|
| jsdom@11 (VERBOSITY=true, LOGERRORS=true)   	| 6.10s    	|
| jsdom@11 (VERBOSITY=false, LOGERRORS=false) 	| 5.44s    	|
| Chromium 57.0.2987.98                       	| 43.3ms   	|

**Comment by dperini** [comment]
Wow ... big performance improvements for jsdom@11 in this case !

**Comment by dperini** [comment]
The reported issue have been fixed ... should this be closed ?

**Comment by flaviut** [comment]
I'm not sure. There's still a way to go in improving performance of jsdom to be close to that of browsers, but from what I can tell, the gains would come from nwmatcher's end. There's nothing more to fix in jsdom.
