### ISSUE TITLE
Upgrade tough-cookie due to vulnerability

### ISSUE THREAD

**Issue by jpollard-cs** [tmpvar/jsdom#1573]
vulnerability details here: https://snyk.io/vuln/npm%3Atough-cookie%3A20160722
fix is to upgrade to tough-cookie version 2.3 or greater

**Comment by Sebmaster** [comment]
Dupe of #1572. Since we're only fixing to major version, a simple `npm update` will fix it already though.

**Comment by jpollard-cs** [comment]
@Sebmaster sorry about that - did a search on `tough-cookie` before opening this issue, but didn't find anything for some odd reason
