### ISSUE TITLE
Unexpected token ')' in Safari and Firefox

### ISSUE THREAD

**Issue by Slind14** [tmpvar/jsdom#1576]
Hi,
when using the lib with safari or firefox I get an "Unexpected token ')' error on this line: 
https://github.com/tmpvar/jsdom/blob/master/lib/jsdom.js#L3

Is this a known incompatibility or am I doing something wrong?

**Comment by domenic** [comment]
It only works in modern versions of those browsers. For Safari, that probably only consists of technical preview.

**Comment by Slind14** [comment]
Ahh. Is there any simple workaround? I use it in a mobile app, which
doesn't work on ios but on Android.

**Comment by domenic** [comment]
Well, a new iOS version should be dropping soon. In the meantime, a transpiler like Babel might help?
