### ISSUE TITLE
preventDefault has different behavior with real browser

### ISSUE THREAD

**Issue by levimm** [tmpvar/jsdom#1577]
Hi Guys,

I'm encountering following issue:
`<a href="/test.html" id="demo">
  <span onclick="myFunction()">
    Click here
  </span>
</a>`

In browser, if you click on the span element, the click event bubbled to the anchor element is not defaultPrevented. While in jsdom (EventTarget-impl.js), it will invoke the E.preventDefault(). And the event bubbled is defaultPrevented.

Could someone explain about this behavior?

Cheers

**Comment by domenic** [comment]
Can you produce a more comprehensive test case? E.g. a self-contained jsbin we could run that shows different behaviors in browsers and in jsdom? Be sure to use el.click() instead of instructions like "click the span element".

**Comment by levimm** [comment]
Thanks for the reply, @domenic . Actually it's an easy question. In jsdom, if there're internal listeners like "onclick=...", it will mark the click event defaultPrevented. 

Here's the test case. 
`<html>
    <head>
<a href="/test.html" id="demo1">
		<span id="demo2" onclick="myFunction2()">
			Click here
		</span>
	 </a></head>
<body>
<script>function myFunction2() {
			window.alert("onclick");
		}
var eleA=document.getElementById("demo1");
var eleS=document.getElementById("demo2");
eleA.addEventListener("click", function(e){window.alert(e.defaultPrevented);console.log(e.defaultPrevented);}); 
eleS.click()</script></body>
</html>`

In browser, it will navigate to new page. I understand jsdom doesn't support navigation. However, the click event bubbles to anchor element is defaultPrevented.

**Comment by i8-pi** [comment]
I've patched up the test case and put it in a [jsbin](http://jsbin.com/revoripuye/edit?html,console,output). Here is the code for reference
```html
<!DOCTYPE html>
<html>
<body>
  <a href="/test.html" id="demo1">
    <span id="demo2" onclick="myFunction2()">Click here </span>
  </a>
  <script>
    function myFunction2() {
      console.log("onclick");
    }
    var eleA = document.getElementById("demo1");
    var eleS = document.getElementById("demo2");
    eleA.addEventListener("click", function(e) {
      console.log(e.defaultPrevented);
    });
    eleS.click()
  </script>
</body>
</html>
```

In jsdom, the console outputs are "onclick" and true
In jsbin, the console outputs are "onclick" and false

**Comment by domenic** [comment]
Ah perfect, that's exactly the kind of thing we were hoping for. I can try to prioritize a fix for this soon.

**Comment by dmethvin** [comment]
It looks like [this conditional](https://github.com/tmpvar/jsdom/blob/8a0b236e7eab37154d652f33c781d9c5f8013d19/lib/jsdom/living/events/EventTarget-impl.js#L258) should be `returnValue === false`. Do you want a PR with a test?

**Comment by domenic** [comment]
That would be lovely <3

**Comment by domenic** [comment]
Might be good to fix https://github.com/tmpvar/jsdom/blob/8a0b236e7eab37154d652f33c781d9c5f8013d19/lib/jsdom/living/events/EventTarget-impl.js#L255 to be `=== true` as well while there...
