### ISSUE TITLE
Returning an empty HTMLDivElement

### ISSUE THREAD

**Issue by ramramps** [tmpvar/jsdom#1578]
here is the snippet 
let testhtml = ```"<html><body><div id=app><div id=viewer></div></div></body></html>" ```  
jsdom.env({   
            html:testhtml ,                                          
            done: function (err: any, window: any) {                                                                           
                  console.log(window.document.getElementById("viewer"));                                                                   
            }
        });

Here window.document.getElementById("viewer") returns an empty HTMLDivElement. 
In chrome, I got *div id="viewer"*    the expectation is it should return the same div element.

Is it a bug or am I missing something here?

**Comment by Sebmaster** [comment]
Please provide a full repro in something like jsbin. It's impossible to debug it like this.

**Comment by ramramps** [comment]
I have simplified the code there. the console.log has only HTMLDivElement {}

**Comment by domenic** [comment]
Oh. That is intended, and is how Node's console works. All the properties are still there.
