### ISSUE TITLE
Better CORS error messages

### ISSUE THREAD

**Issue by ymmn** [tmpvar/jsdom#1580]
Whenever there's a CORS error of any sort, there's basically no good error message that comes through anywhere. The only way I could debug my problems was by exploring the jsdom source code and manually adding `console.log` statements in the `validCORSHeaders` function.

Is there a better way for me to debug these network errors? If not, is there any way to have better error messages come through on `XMLHTTPRequest.onerror`, like the data that's on the actual `DOMException` for example

**Comment by domenic** [comment]
Yeah we should definitely at least log a nice error to the virtual console. We may also be able to improve the DOMException. Pull requests welcome!

**Comment by jmarchello** [comment]
@ymmn What error did you get and how did you solve it? I'm having similar issues.

**Comment by i8-pi** [comment]
I tried to reproduce this but I do get an error message

```javascript
'use strict';
const http = require('http');
const jsdom = require('jsdom');

function startServer() {
    return new Promise((resolve, reject) => {
        const server = http.createServer();

        server.on('request', (request, response) => {
            response.end();
        });

        server.listen(0, '127.3.4.5', () => {
            resolve({
                host: server.address().address,
                port: server.address().port
            });
        });
    });
}

Promise.all([startServer(), startServer()])
.then((servers) => {
    jsdom.env(
        "http://" + servers[0].host + ":" + servers[0].port,
        { virtualConsole: jsdom.createVirtualConsole().sendTo(console) },
        (error, window) => {
            let xhr = new window.XMLHttpRequest();
            xhr.open('GET', "http://" + servers[1].host + ":" + servers[1].port);
            xhr.send();
        }
    );
})
.catch(err => { throw err });
```

Gives this console output
```
Error: Cross origin http://127.3.4.5:40913 forbidden
    at dispatchError (/home/i8-pi/src/jsdom/lib/jsdom/living/xmlhttprequest.js:941:21)
    at validCORSHeaders (/home/i8-pi/src/jsdom/lib/jsdom/living/xmlhttprequest.js:953:7)
    <snip>
```
Maybe the virtualConsole was not hooked up?

**Comment by ymmn** [comment]
@i8-pi woops, I never hooked up the virtualConsole. I just hooked it up and everything works perfectly, thanks!
