### ISSUE TITLE
Can you a little bit more elaborate serializeDocument  method?

### ISSUE THREAD

**Issue by t0lkman** [tmpvar/jsdom#1586]
Can you a little bit more elaborate serializeDocument  method?
var serializeDocument = require("jsdom").serializeDocument;

I am not sure I understand what it is doing

**Comment by Sebmaster** [comment]
It just serializes `document.doctype.outerHTML` (although that doesn't exist) + `document.documentElement.outerHTML`.

**Comment by joeyhub** [comment]
TypeError: jsdom.serializeDocument is not a function

It doesn't do anything as it doesn't exist.
