### ISSUE TITLE
DOMParser.parseFromString removes CDATA from document

### ISSUE THREAD

**Issue by galziv** [tmpvar/jsdom#1593]
Greetings.

When creating XMLDocument using DOMParser from a string which contains CDATA, the CDATA is removed from the output.

Example:

``` js
console.log(new window.DOMParser().parseFromString('<main><sub><![CDATA[http://someurl.com]]></sub></main>','text/xml').documentElement.innerHTML);
```

output:

``` html
<sub></sub>
```

**Comment by domenic** [comment]
Per http://jsbin.com/fugomeyubi/edit?html,console,output that code should not succeed anyway, hmm.

**Comment by narirou** [comment]
I have same issue. :(

**Comment by billhimmelsbach** [comment]
I'm having the same issue.

**Comment by DavidBabel** [comment]
same issue here

**Comment by domenic** [comment]
Remember that +1 comments are not helpful. I'll be deleting several recent ones and all future ones.

**Comment by DavidBabel** [comment]
Actually it helps to know if an issue is still active. But i get your point
