### ISSUE TITLE
Namespace support seems to be incomplete

### ISSUE THREAD

**Issue by BobFrGit** [tmpvar/jsdom#1595]
I can't get it to work right. I'm assuming that it's not fully implemented in the version 9.5.0

In this example

```
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:rmf="http://www.frankston.com/public"><head>

<span rmf:value="year">2012!</span>

let rmfNS = "http://www.frankston.com/public";
hp.setAttributeNS(rmfNS, "test", "value");

<span rmf:value="year" test="value">2012!</span>
```
When I try to get the attribute using the NS name I get nothing. The value of hp.attributes[0] is {} (according to JSON.stringify). When I set the attribute the namespace is not set.

**Comment by domenic** [comment]
So, we probably do have bugs here. But, some troubleshooting tips:

JSON.stringify will not give useful values in jsdom, just like in the browser. I'd suggest logging hp.attributes[0].namespaceURI, localName, and prefix.

It would be ideal if you had a test that worked in https://jsbin.com, but not in jsdom, i.e. using a `<script>` element.

**Comment by BobFrGit** [comment]
Will work on JSBIN. inthe meantime the attributes values
```
<span rmf:value="year" test="value">2012!</span>
0 null rmf:value null
1 http://www.frankston.com/public test null
```
Fortunately .getAttribute("rmf:value") does work so there is a work-round.

**Comment by BobFrGit** [comment]
I"m new to JSBIn -- how do I access the JSDOM library there? This should be a simple repro.

**Comment by domenic** [comment]
The point of jsdom is to act like a browser, so the question is, does your code work in browsers?

**Comment by BobFrGit** [comment]
Related perhaps -- when I tried to use lookupPrefix on my documentElement it was undefined. Fortunately once I realized that the explicit prefix works I can workaround this for now.

**Comment by BobFrGit** [comment]
Thanks for the JSBin pointer. Alas, same result in the browser (though lookupPrefix is defined but returned null. 

```
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:rmf="http://www.frankston.com/public">
   <body>
      <span rmf:value="year">test</span>
   <body>
     </html>

var pfx = document.lookupPrefix("http://www.frankston.com/public");
console.log(pfx);
var sps = document.getElementsByTagName("span");
console.log(sps[0].outerHTML);
console.log(sps[0].getAttributeNS("http://www.frankston.com/public", "value"));
console.log(sps[0].getAttribute("rmf:value"));
```
The getAttributeNS gave me null but the one with rmf;:value worked.

As an FYI I had done the lookup with xmldom and the lookup worked but I had to use the : notation for the attributes. 

Now I need to question my understanding of xmlns vs. attributes

**Comment by domenic** [comment]
Ah OK, so it sounds like there is not a jsdom bug here, since we match browsers. Happy to continue discussing, but going to close this in that case.

**Comment by BobFrGit** [comment]
Just one postscript -- I didn't mention. I've been moving code from c# to TypeScript (JavaScript) and have been using namespaces in the .Net library and they work as I expect. I'm willing to say that the bug is in the browser's interpretation which doesn't make sense but understand why you'd go with that as the standards. I suspect that proper use of namespaces in attributes is rare enough that such bugs can lurk and be programmed around rather than addressed.

**Comment by domenic** [comment]
It's possible C#'s DOM library doesn't follow the [DOM Standard](https://dom.spec.whatwg.org/), on which jsdom and browsers base their behavior.

**Comment by BobFrGit** [comment]
As I said a long discussion. Did a quick look at the pointer you gave but it didn't seem to answer that. The reason I go with the C# is that it is internally consistent. The current DOM implementation isn't. If I do a lookup of the namespace (that is a bug) and get the prefix then using prefix:attribute does work. It should be equivalent to having an explicit namespace in the NS( version of the call.

Since I'm busy with other stuff I don't have the time to fully investigate this but as with so much of programming if there is a work-around the pressure to fix it is low. Next time I speak to an XML maven I'll ask about it.
