### ISSUE TITLE
Syntax error on full test suite run

### ISSUE THREAD

**Issue by snuggs** [tmpvar/jsdom#1597]
![capture d ecran 2016-09-12 a 22 39 11](https://cloud.githubusercontent.com/assets/38223/18459677/969eaf6c-7939-11e6-9bd3-178924dd554a.png)

**Comment by domenic** [comment]
Since this doesn't occur on my machine, it would be best if you could copy the entire stack trace, not just the bottom of it. Also, ensure you are running the latest Node.js.

**Comment by snuggs** [comment]
Cool. Thanks I'm new to installing locally so realizing there is a lot going on. In a hotel and just been waiting for the test suite to run/clone. Horrible wifi. Noticed failures running npm test. As always Thanks @domenic for everything you do.

**Comment by snuggs** [comment]
@domenic here is the full run 
![capture d ecran 2016-09-13 a 01 10 41](https://cloud.githubusercontent.com/assets/38223/18462279/d82b27e8-794e-11e6-9740-61c8fdf7d2ff.png)

**Comment by Sebmaster** [comment]
Try setting up your hosts file like this: https://github.com/w3c/web-platform-tests/#running-the-tests. The hosted w3c version is a bit flaky most of the time.

**Comment by domenic** [comment]
Closing, since it looks like the error message is already giving clear instructions :)
