### ISSUE TITLE
ERROR in htmltojsx 

### ISSUE THREAD

**Issue by smitahpe** [tmpvar/jsdom#1598]
Cannot resolve module 'fs' module. npm htmltojsx is installed but 'fs' folder has not installed. 

I'm using HTML to JSX Compiler tool (http://magic.reactjs.net/htmltojsx.htm) which converts and renders the html to react code. Same thing i tried to implement via code which is the npm 'htmltojsx'. 
Any help is appreciated.

Thanks

**Comment by Sebmaster** [comment]
Without a testcase and an error we can't help you.

**Comment by domenic** [comment]
It seems like this is on the wrong repo anyway. This is jsdom, not htmltojsx.

**Comment by smitahpe** [comment]
CODE
var HTMLtoJSX = require('html-to-jsx');
var converter = new HTMLtoJSX({createClass: false});
var output = converter.convert('<div>Hello world!</div>');

ERROR
var fs = require('fs'); in node_modules\jsdom-no-contextify\lib\jsdom.js
Cannot resolve module 'fs' module as no such module has been installed.

I'm struggling for this since last 3 days but no help :(:(

**Comment by domenic** [comment]
Sorry, that isn't related to our module. I'd suggest you post it on the html-to-jsx repository, or maybe the jsdom-no-contextify library. Neither of those is maintained by us.

**Comment by smitahpe** [comment]
jsdom code also need var fs = require("fs");

from where to install the fs module??

**Comment by domenic** [comment]
This is not related to jsdom. Locking this thread.
