### ISSUE TITLE
deep cloning of SVG node loses xlink namespace information

### ISSUE THREAD

**Issue by pkra** [tmpvar/jsdom#1601]
When deep cloning an SVG, the xlink namespace information gets mangled. 
This can lead to rendering issues (e.g., FF and Safari will fail to look up the `use` target). 

Minimal example (tested on jsdom v9.5.0):

```javascript
jsdom = require('jsdom'); 
doc = jsdom.jsdom();
doc.body.innerHTML = "<svg xmlns:xlink='http://www.w3.org/1999/xlink'><use xlink:href='#test'></use></svg>";
var clone = doc.body.firstChild.cloneNode(true);
console.log(clone.outerHTML);
// expected:
//<svg xmlns:xlink="http://www.w3.org/1999/xlink"><use xlink:href="#test"></use></svg>
// result: 
//<svg xlink="http://www.w3.org/1999/xlink"><use href="#test"></use></svg>
```

This seems similar to #861.

**Comment by pkra** [comment]
Note this can be worked around by using the original's outerHTML to build a clone manually.

**Comment by Sebmaster** [comment]
Are you sure this only occurs after the deepClone? If you print outer html before the clone, I'd expect the XML attributes to get mangled in a similar way, since we only serialise to html (even though we parse XML (kinda) correctly).

**Comment by pkra** [comment]
>  If you print outer html before the clone, I'd expect the XML attributes to get mangled in a similar way, since we only serialise to html (even though we parse XML (kinda) correctly).

What you are describing is just #861, right? (Which was fixed). To answer your question, I'm using outerHTML as a workaround in a project so I'm reasonably certain it works.

**Comment by pkra** [comment]
FYI, if you add `console.log(doc.body.firstChild.outerHTML);` to the minimal example, tis result is correct.

**Comment by pkra** [comment]
Thanks so much, @domenic !
