### ISSUE TITLE
jsdom.jsdom(...)

### ISSUE THREAD

**Issue by alexey2baranov** [tmpvar/jsdom#1603]
reading hire https://github.com/tmpvar/jsdom#listening-for-script-errors-during-initialization

> var window = jsdom.jsdom(...).defaultView;
> window.addEventListener("error", function (event) {
>   console.error("script error!!", event.error);
> });

What **...** does mean? is this the same config as for jsdom.env()?

thanks

**Comment by jeffcarp** [comment]
Yes, the options are the same. Under the hood, `jsdom.env` is just calling `jsdom.jsdom` ([lib/jsdom.js#L297](https://github.com/tmpvar/jsdom/blob/master/lib/jsdom.js#L297)).
