### ISSUE TITLE
virtual console not work

### ISSUE THREAD

**Issue by alexey2baranov** [tmpvar/jsdom#1604]
Hello! 
I'am very new with jsdom. I\m trying to test virtual console and see not output into node console. 

test.js
```javascript
jsdom.env({
    url: "http://localhost:8080/public/poligon-jsdom/index.html",
    virtualConsole: jsdom.createVirtualConsole().sendTo(console),
    done: function (err, win) {

    }
});
```

index.html
```html
<!DOCTYPE html>
<html>
<head>
    <script src="js/logic.js"></script>
</head>
<body>
</body>
</html>
```

logic.js

```javascript
setInterval(
    function(){
        console.log("from script "+new Date());
    },
    1000);

```

As you can see this simple test page outputs this string one per each second. It works nice when loaded in browser. But i can not see this output in node console when load it from domjs. What is my mistake?

> logic.js:7 from script Fri Sep 16 2016 15:55:16 GMT+0500 (YEKT)
> logic.js:7 from script Fri Sep 16 2016 15:55:17 GMT+0500 (YEKT)

**Comment by inikulin** [comment]
@alexey2baranov Virtual console doesn't redirect ouput to node console. It's an `EventEmitter` object: https://github.com/tmpvar/jsdom#capturing-console-output

**Comment by Sebmaster** [comment]
Your problem is that you do not enable in-page scripting. You need to add the `features` option to enable on-page scripts, see [here](https://github.com/tmpvar/jsdom#custom-external-resource-loader) for an example.

**Comment by alexey2baranov** [comment]
@Sebmaster thanks!

this code works fine

jsdom.env({
    url: "http://localhost:8080/public/poligon-jsdom/index.html",
    virtualConsole: jsdom.createVirtualConsole().sendTo(console),
    features: {
        FetchExternalResources : ["script"],
        ProcessExternalResources: ["script"]
    }
});
