### ISSUE TITLE
node global variable +webpack not works

### ISSUE THREAD

**Issue by alexey2baranov** [tmpvar/jsdom#1605]
hello!

I do a very simple nodejs test and get error. I have minifed code line by line and found that error throwned when trying to check node **global** variable. The only task of big bundle.webpack.js below is to check the global variable global.log4javascript (very short code at the end of file).

html page:
```html
<!DOCTYPE html>
<html>
<head>
    <script src="../bower_components/log4javascript/log4javascript_uncompressed.js"></script>
    <script src="../../bin/bundle.webpack.js"></script>
</head>
<body>
</body>
</html>

```
```javascript
bundle.webpack.js
var bundle =
/******/ (function(modules) { // webpackBootstrap
/******/ 	// The module cache
/******/ 	var installedModules = {};

/******/ 	// The require function
/******/ 	function __webpack_require__(moduleId) {

/******/ 		// Check if module is in cache
/******/ 		if(installedModules[moduleId])
/******/ 			return installedModules[moduleId].exports;

/******/ 		// Create a new module (and put it into the cache)
/******/ 		var module = installedModules[moduleId] = {
/******/ 			exports: {},
/******/ 			id: moduleId,
/******/ 			loaded: false
/******/ 		};

/******/ 		// Execute the module function
/******/ 		modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);

/******/ 		// Flag the module as loaded
/******/ 		module.loaded = true;

/******/ 		// Return the exports of the module
/******/ 		return module.exports;
/******/ 	}


/******/ 	// expose the modules object (__webpack_modules__)
/******/ 	__webpack_require__.m = modules;

/******/ 	// expose the module cache
/******/ 	__webpack_require__.c = installedModules;

/******/ 	// __webpack_public_path__
/******/ 	__webpack_require__.p = "";

/******/ 	// Load entry module and return exports
/******/ 	return __webpack_require__(0);
/******/ })
/************************************************************************/
/******/ ([
/* 0 */
/***/ function(module, exports) {

	/* WEBPACK VAR INJECTION */(function(global) {"use strict";

	/**
	 * Created by alexey2baranov on 8/20/16.
	 */

	if (!global.log4javascript) {
	    console.log("global.log4javascript not defined");
	}
	/* WEBPACK VAR INJECTION */}.call(exports, (function() { return this; }())))

/***/ }
/******/ ]);
```

and get this error:

> Error: Uncaught [TypeError: Cannot read property 'log4javascript' of undefined]
>     at reportException (/home/alexey2baranov/htdocs/kp-client/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:58:24)
>     at processJavaScript (/home/alexey2baranov/htdocs/kp-client/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:130:7)
>     at HTMLScriptElementImpl._eval (/home/alexey2baranov/htdocs/kp-client/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:65:7)
>     at /home/alexey2baranov/htdocs/kp-client/node_modules/jsdom/lib/jsdom/browser/resource-loader.js:30:22
>     at Object.check (/home/alexey2baranov/htdocs/kp-client/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:85:11)
>     at html.push.callback (/home/alexey2baranov/htdocs/kp-client/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:104:12)
>     at wrappedEnqueued (/home/alexey2baranov/htdocs/kp-client/node_modules/jsdom/lib/jsdom/browser/resource-loader.js:243:16)
>     at Request._callback (/home/alexey2baranov/htdocs/kp-client/node_modules/jsdom/lib/jsdom/browser/resource-loader.js:191:9)
>     at Request.init.self.callback (/home/alexey2baranov/htdocs/kp-client/node_modules/request/request.js:187:22)
>     at emitTwo (events.js:87:13)
>     at Request.emit (events.js:172:7)
>     at Request.<anonymous> (/home/alexey2baranov/htdocs/kp-client/node_modules/request/request.js:1044:10)
>     at emitOne (events.js:77:13)
>     at Request.emit (events.js:169:7)
>     at IncomingMessage.<anonymous> (/home/alexey2baranov/htdocs/kp-client/node_modules/request/request.js:965:12)
>     at emitNone (events.js:72:20)
>     at IncomingMessage.emit (events.js:166:7)
>     at endReadableNT (_stream_readable.js:921:12)
>     at nextTickCallbackWith2Args (node.js:442:9)
>     at process._tickCallback (node.js:356:17) [TypeError: Cannot read property 'log4javascript' of undefined]

**Comment by domenic** [comment]
This does not appear to have anything to do with jsdom, as far as I can tell. Happy to reopen if you can give repro steps that involve jsdom.
