### ISSUE TITLE
Clean way to get all "browser" globals?

### ISSUE THREAD

**Issue by lukechilds** [tmpvar/jsdom#1623]
Is there a clean way to get all variables that would normally be in the global scope in the browser? Basically everything on `window`?

I'm sure this worked for me before:

```js
const jsdom  = require('jsdom').jsdom;
const window = jsdom('<html><body></body></html>').defaultView;

const browserGlobals = Object.keys(window);
```

However it looks like at some point `jsdom` changed to using getters for some things on `window` so `Object.keys(window)` misses a lot of stuff.

I'm currently using:

```js
const jsdom  = require('jsdom').jsdom;
const window = jsdom('<html><body></body></html>').defaultView;

const browserGlobals = Object
                         .keys(window)
                         .concat(Object.keys(window._core))
                         .filter(prop => prop.substring(0, 1) !== '_');
```

But it feels a bit hacky, is there a cleaner way exposed by `jsdom` that I've overlooked?

**Comment by vsemozhetbyt** [comment]
@lukechilds I've tried to get all globals in depth for Web API and Node.js, see [this issue](https://github.com/nodejs/help/issues/228).

[Here is my last script](https://gist.github.com/vsemozhetbyt/2893a240dd4d86fd871cecd46a577c4e), the best I can do. [And some explanation](https://habrahabr.ru/post/310662/), unfortunately in Russian.

May be you can improve your code by using `getOwnPropertyNames` instead of `keys`.

**Comment by lukechilds** [comment]
@vsemozhetbyt Thanks for the suggestion but I don't think `getOwnPropertyNames` will help because it still wont return getters.

For example:

```js
window.HTMLElement
// [Function: HTMLElement]

Object.getOwnPropertyNames(window).indexOf('HTMLElement');
// -1
```

**Comment by vsemozhetbyt** [comment]
Do you try it in the Node with jsdom or in the browser? Maybe in jsdom it is not own property of `window`?

In the browser:

```js
window.HTMLElement
// function HTMLElement() { [native code] }
Object.getOwnPropertyNames(window).indexOf('HTMLElement')
// 615
```

**Comment by domenic** [comment]
> But it feels a bit hacky, is there a cleaner way exposed by jsdom that I've overlooked?

No. jsdom does not provide any facilities in this regard that are not already exposed in a browser, so your best bet is to find code that works in browsers.

The _core trick will break in a future jsdom release, probably a patch version, so I would definitely not advise it. Maybe we should rename _core right now to make sure people realize it's private API.

**Comment by vsemozhetbyt** [comment]
```js
Object.getOwnPropertyNames(window._core).indexOf('HTMLElement');
// 32
```

**Comment by vsemozhetbyt** [comment]
In the browser:

```js
Object.getOwnPropertyNames(window).length
// 1696
```

In the jsdom:

```js
const jsdom  = require('jsdom').jsdom;
const window = jsdom('<html><body></body></html>').defaultView;
console.log(Object.getOwnPropertyNames(window).length);
console.log(Object.getOwnPropertyNames(window._core).length);
// 122
// 127
```

**Comment by domenic** [comment]
This seems to be likely https://github.com/nodejs/node/issues/3158. Are you using Node v6?

**Comment by vsemozhetbyt** [comment]
Me? Yes, the 6.7.0

**Comment by domenic** [comment]
I guess maybe we only implement 122 APIs. Wow!

**Comment by vsemozhetbyt** [comment]
[Here is my script variant for jsdom](https://gist.github.com/vsemozhetbyt/3ad0378d79b68ea6dd7ebb4144b5137d).

Results:

jsdom 9.6.0
[Terms:  1,862](https://gist.github.com/vsemozhetbyt/0381ddd0b69d86b6321db31a1a88e5ef)
[Chains: 5,178](https://gist.github.com/vsemozhetbyt/2e2ce4ab142ff53d9ed98d4d7069871c)

In the browsers:

Google Chrome Canary 55.0.2867.0
[Terms:   3 339](https://gist.github.com/vsemozhetbyt/d4d1bb025cc9165b335ab680d617c465)
[Chains: 14 435](https://gist.github.com/vsemozhetbyt/636827943688f406a8eb1b0dff56b405)

Firefox Nightly 52.0a1 (2016-09-21)
[Terms:   5 040](https://gist.github.com/vsemozhetbyt/b4c558759caa025b09d72d7960ca1643)
[Chains: 14 417](https://gist.github.com/vsemozhetbyt/4913b2a1861df6e58faa5fc9823a14f6)

**Comment by lukechilds** [comment]
@domenic Thanks for your response.

> your best bet is to find code that works in browsers

This works in browsers:

```js
Object.getOwnPropertyNames(window);
```

But not `jsdom` due to using getters (I think?).

Thanks for the warning re `_core`. I've pinned the version of `jsdom` so that shouldn't cause any immediate issues.

The only other solution I can think of is manually maintaining an array of strings and updating it as things get added to `jsdom`. Then I'm not using undocumented features of `jsdom` but I'll still need to lock `jsdom` version and keep it up to date so if anything that's worse than the current solution.

@vsemozhetbyt Thanks for your effort but I only need the top level properties, that solution still doesn't get `HTMLElement` as a top level property.

**Comment by lukechilds** [comment]
@domenic Interestingly this works:

```js
jsdom.env(
  '<html><body></body></html>',
  function (err, window) {
    const browserGlobals = Object.getOwnPropertyNames(window);
  }
);
```

However I need to do this synchronously rather than in a callback. Is there a reason `window` in the above example behaves differently to `window` here:

```js
const jsdom  = require('jsdom').jsdom;
const window = jsdom('<html><body></body></html>').defaultView;
```

Sure you're a busy man but any light you can shed on this would be greatly appreciated.

**Comment by Sebmaster** [comment]
jsdom.jsdom has scripting implicitly enabled, causing the returned window to be a sandboxed one. jsdom.env does not, returning the raw window. Seems like the node `vm` implementation hides the properties on it.

**Comment by vsemozhetbyt** [comment]
@lukechilds `getOwnPropertyNames` seems to enumerates getters:

```js
const obj = {
  get k() {console.log('getter');},
  set k(v) {console.log('setter');},
}

obj.k;
obj.k = 1;

console.log(Object.getOwnPropertyNames(obj));
```
```
getter
setter
[ 'k' ]
```
I don't know why `HTMLElement` is not the own `window` key and how the `window.HTMLElement` works (`HTMLElement` is [window._core own key](https://gist.github.com/vsemozhetbyt/2e2ce4ab142ff53d9ed98d4d7069871c#file-js-nomenclature-jsdom-chains-txt-L2017-L2111) )

**Comment by lukechilds** [comment]
@Sebmaster Thanks, that's what I was looking for!

Got it working now with:

```js
const jsdom  = require('jsdom');
jsdom.defaultDocumentFeatures = {
    FetchExternalResources: false,
    ProcessExternalResources: false
};
const window = jsdom.jsdom('<html><body></body></html>').defaultView;

const browserGlobals = Object.getOwnPropertyNames(window);
```

Assuming this is safe and unlikely to break in future versions?

**Comment by vsemozhetbyt** [comment]
Sorry for possible noize. Yes, [the env variant](https://gist.github.com/vsemozhetbyt/7c96672ae41ef4e89a1363543d4c1266) with `jsdom.env` gives [the different structure](https://gist.github.com/vsemozhetbyt/6554aeeb4353d60ad6435b09264e92c2).

**Comment by Sebmaster** [comment]
> Assuming this is safe and unlikely to break in future versions?

Not in non-majors at least. The inconsistency is kinda dumb and we'll probably have to fix it someday, but it's ... complicated.

**Comment by lukechilds** [comment]
Haha, yes definitely caught me off guard.

I'll update my lib to use this over manually concatenating `window` and `window._core`.

Thanks!
