### ISSUE TITLE
Intl.NumberFormat ignore's locale

### ISSUE THREAD

**Issue by schmitch** [tmpvar/jsdom#1626]
Hello, currently we use `new Intl.NumberFormat('de-DE', {})` to format our numbers and tried to run our tests with jsdom however they fail the number formatting and will format the number with the default locale instead of the explicitly passed one:
`new Intl.NumberFormat('de-DE', {}). format(1000)` will yield `1,000` however in germany we use `.`  as a seperator, I also tried to pass different lower/upercases in locales: `de-de, de-DE, de`.

**Comment by Sebmaster** [comment]
jsdom doesn't explicitly implement Intl, so this is the native implementation provided by node. As far as I know, node doesn't ship locale data in their default builds so you'll have to get one which does.

**Comment by schmitch** [comment]
is there a way to override the implementation? I mean we used a [shim](https://github.com/andyearnshaw/Intl.js/tree/master/dist) on phantom.js

**Comment by schmitch** [comment]
nvm. basically you said everything, thanks.

**Comment by vsemozhetbyt** [comment]
@schmitch  Maybe you could try `full-icu`. See https://github.com/nodejs/node/issues/8818

**Comment by schmitch** [comment]
well on my mac i rebuilt node-js with full-icu, thanks @vsemozhetbyt however I'm not sure if installing npm install full-icu works on our ci servers. we use node-js within scala-js so I'm not sure if it will use `NODE_ICU_DATA`. but that was a great hint!
