### ISSUE TITLE
non-functional canvas library 

### ISSUE THREAD

**Issue by controversial** [tmpvar/jsdom#1633]
Is there an alternative to the `canvas` package that wouldn't introduce C dependencies like `libjpeg`? For my case, I just need canvas functions to not error, even if they don't do anything. I'd like a library for which all DOM elements would just return without calling anything. Does such a library exist?

**Comment by domenic** [comment]
Not that I'm aware of.

**Comment by controversial** [comment]
Ok. I guess I'll write my own then. How would one go about extending `jsdom` with new functionality like this?

**Comment by domenic** [comment]
You can use the [`created` callback](https://github.com/tmpvar/jsdom#createderror-window) to monkeypatch anything that's accessible from `window`, before any scripts run. So e.g. mess with `window.HTMLCanvasElement.whatever` or `window.CanvasRenderingContext2D`.

**Comment by controversial** [comment]
Ok. Thanks! I'll be able to use this from https://github.com/lukechilds/browser-env by modifying the `window` global in the same way, right?

**Comment by controversial** [comment]
Looks like I can. Thanks a lot for your help!

**Comment by domenic** [comment]
I'm not sure. That package uses [an explicitly not-supported antipattern](https://github.com/tmpvar/jsdom/wiki/Don't-stuff-jsdom-globals-onto-the-Node-global), so who knows what will happen.

**Comment by controversial** [comment]
Ok. It's [recommended by `ava` for browser testing](https://github.com/avajs/ava/blob/master/docs/recipes/browser-testing.md).
