### ISSUE TITLE
Can't dispatch KeyboardEvent in Jsdom

### ISSUE THREAD

**Issue by yandongCoder** [tmpvar/jsdom#1634]
Hi, I'm using jsdom in my unit test, and I need test mouse event and keyboard event.
Code like this will trigger click event I bind to "svg" element.

```
var event = new window.MouseEvent("click");
document.querySelector('svg').dispatchEvent(event);
```

But code like this will not trigger keydown event I bind to document or body, why? 

```
var event = new window.KeyboardEvent("keydown", {key: "z", char: "z", keyCode: 90});
document.dispatchEvent(event);
```

It will work in browser, but not work in jsdom.
where I was wrong?

**Comment by Nitive** [comment]
same problem

**Comment by Nitive** [comment]
Sorry, it was my mistake, everything works fine
![](http://s.csssr.ru/U09LGPMEU/2016-12-03-1019-qg7m6kyv21.png)

**Comment by yandongCoder** [comment]
What mistake? can you tell me why my code not working? @Nitive

**Comment by i8-pi** [comment]
You need to provide a minimal, complete, reproducible test case. The following code works for me
```js
'use strict';
const jsdom = require('./jsdom');

jsdom.jsdom(`
<html>
<body>
    <svg></svg>
<script>
    'use strict';
    var svg = document.querySelector('svg');
    svg.addEventListener('click', console.log);
    var event = new window.MouseEvent("click");
    svg.dispatchEvent(event);

    event = new window.KeyboardEvent("keydown", {key: "z", char: "z", keyCode: 90});
    document.addEventListener('keydown', console.log);
    document.dispatchEvent(event);
</script>
</body>
</html>
`,
    { virtualConsole: jsdom.createVirtualConsole().sendTo(console) }
);
```
Output
```
MouseEvent { isTrusted: [Getter] }
KeyboardEvent { isTrusted: [Getter] }
```

**Comment by Nitive** [comment]
@yandongCoder Something in my code, not sure what it exactly was.
@i8-pi example works for me fine.

**Comment by spen** [comment]
A re-jig of @i8-pi's example worked for me!
I thought I'd post for anybody else who finds their way to this issue 😁

```jsx
const onEscapeSpy = spy();
const wrapper = mount( <CloseOnEscape onEscape={ onEscapeSpy } /> );
const event = new window.KeyboardEvent( 'keydown', { keyCode: 27 } );
document.dispatchEvent( event );

expect( onEscapeSpy ).to.have.been.calledOnce;
```
Basically: create a new window.KeyboardEvent > dispatch that event > 👌

**Comment by ronen** [comment]
In case anybody (like me) finds this old issue because they're trying to dispatch a keyboard event from a specific node but intending to handle it in the document with `event.target` set appropriately (which is how [KeyboardEventHandler](https://github.com/linsight/react-keyboard-event-handler) works ), there are two things to note:

* You need to specify `bubbles: true` in the event so that it will bubble to the document
* If you're coming from enzyme, note that `mount()` does not put the component in the document, you need to specify `attachTo:` with a node that's in the document (React will complain if you try to directly attach to `document.body`)

A re-jig of @spen's code:

```js
const onEscapeSpy = spy();
document.addEventListener( 'keydown', onEscapeSpy )

const root = document.createElement( 'div' );
document.body.appendChild( root );
const wrapper = mount( <MyComponent />, { attachTo: root } );

const event = new window.KeyboardEvent( 'keydown', { keyCode: 27, bubbles: true } );
const targetNode = wrapper.getDOMNode();
targetNode.dispatchEvent( event );

expect( onEscapeSpy ).to.have.been.calledOnce;
expect( spy.lastCall.lastArg.target ).to.equal( targetNode ); 
```
