### ISSUE TITLE
Window.close windowToClean is undefined

### ISSUE THREAD

**Issue by tsirolnik** [tmpvar/jsdom#1636]
While calling window.close I get the following error (sometimes).

``` js
/home/xxxxx/node_modules/jsdom/lib/jsdom/browser/Window.js:290
      for (let i = 0; i < windowToClean.length; i++) {

TypeError: Cannot read property 'length' of undefined
    at windowCleaner (/home/xxxxx/node_modules/jsdom/lib/jsdom/browser/Window.js:290:40)
    at windowCleaner (/home/xxxxx/node_modules/jsdom/lib/jsdom/browser/Window.js:291:9)
    at Window.close (/home/xxxxx/node_modules/jsdom/lib/jsdom/browser/Window.js:298:6)
```

I've wrapped window.close with the following (I still get the error that I've pasted) 
So, close is not being called twice. - 

``` js
let close = window.close;
window.closed = false;
window.close = function() {
  if(!window.closed) {
    window.closed = true;
    close.bind(window)();
  }
}
```

**Comment by domenic** [comment]
A standalone repro case would be very helpful.

**Comment by tsirolnik** [comment]
This is an issue as the full code is being used on production. 
But, for the case, I'm using a browser a [tiny browser emulator based on jsdom](https://github.com/tsirolnik/undead), this issue happens when I'm creating a lot of instances (for testing purposes) and when they are being closed on different times.
