### ISSUE TITLE
Reminder: Cookies

### ISSUE THREAD

**Issue by dmitrymakhnin** [tmpvar/jsdom#1637]
It isn't obvious how cookies work in jsdom, so I keep forgetting and ending up looking at this repository and not finding anything helpful, so I'll leave this note to self so that next time I forget I can find the info here.

Note to self: in jsdom.env, set

```
headers: {
    'Cookie': <insert cookie string here>
}
```

**Comment by domenic** [comment]
You may also enjoy https://github.com/tmpvar/jsdom/blob/newapi/lib/newapi1.md for a preview of something upcoming that should be better.

**Comment by dmitrymakhnin** [comment]
I'm not used to responses that fast D:
