### ISSUE TITLE
getting the effective content height of a window onload

### ISSUE THREAD

**Issue by andynuss** [tmpvar/jsdom#1640]
I am using env() to load various news articles on common news sites, such as yahoo, as a first test of jsdom, and my desire to autoscroll my own documents' windows to the very bottom of the viewable content.

I am using the technique described in http://stackoverflow.com/questions/1145850/how-to-get-height-of-entire-document-with-javascript to get the scrollHeight of a document 5 seconds after the window onload callback commences, and my Height(window) function as follows return NaN.  Is this supposed to work?

``` javascript
function Height (window) {
    var body = window.document.body,
        html = window.document.documentElement;

    var height = Math.max(body.scrollHeight, body.offsetHeight,
                          html.clientHeight, html.scrollHeight, html.offsetHeight);
    return height;
}
```

**Comment by Sebmaster** [comment]
Since jsdom does not do layouting, you can't get (the correct) `scrollHeight` of anything
