### ISSUE TITLE
`document.createCDATASection` missing

### ISSUE THREAD

**Issue by brettz9** [tmpvar/jsdom#1642]
`document.createCDATASection` is missing though the spec indicates its presence: https://dom.spec.whatwg.org/#dom-document-createcdatasection

https://runkit.com/brettz9/5814f88df248640014f701e3/branches/master

**Comment by domenic** [comment]
Yes, it was recently added to the spec. Pull request welcome.

**Comment by snuggs** [comment]
@brettz9 @domenic addressed in https://github.com/tmpvar/jsdom/pull/1649
