### ISSUE TITLE
reconfigureWindow can only overwrite top?

### ISSUE THREAD

**Issue by fkrauthan** [tmpvar/jsdom#1655]
I just looked into the source code and it looks like you added `reconfigureWindow` to the library. But unfortunately the only property you can overwrite is top? I have a small problem where I have one test that plays around with the different navigator language fields to language detection which I can not run since the language fields are Symbols and therefor read only.

Is there anything I can do to get my test running with the latest jsdom version? Or can you guys extend the reconfigureWindow functionality?

**Comment by domenic** [comment]
You want to change navigator.language? It's configurable, so you can just change it:

```js
Object.defineProperty(window.navigator.language, {
  get() { return "ja-JP"; }
});
```

**Comment by fkrauthan** [comment]
@domenic Have you tried that before? I think the original defineProperty was set with configurable false which throws me the error: `TypeError: Cannot redefine property: systemLanguage`

**Comment by domenic** [comment]
No, it was set with configurable: true. I just tried it and it worked. That error message makes no sense anyway since systemLanguage is not the name of the property.

Here is a live working example: https://runkit.com/582a9986f5baa400148ace47/582a9986f5baa400148ace48

**Comment by fkrauthan** [comment]
Oh wait the navigator object itself is defined like that I assume? systemLanguage is actual a field some Browsers send. I just tested it on your website. When you replace language with systemLanguage it does not work.

**Comment by domenic** [comment]
I've never heard of systemLanguage, and it's non-standard, so not something we support in jsdom.

**Comment by fkrauthan** [comment]
Ah found my issue. Forgot to set explicit my overwritten defines as configurable too. I still think it would be nice to be able to use something like `reconfigureWindow` to set locales and the userAgent.

**Comment by domenic** [comment]
Great, glad it's working for you; going to close this then.

There's no need to introduce functionality that JavaScript already has built-in, to jsdom.

**Comment by fkrauthan** [comment]
Hmm I can not follow. You guys introduced reconfigureWindow to not have to use defineProperty (otherwise that method makes  no sense as you could set the _top property with the same method I assume). So I would suggest either removing that method or really as stated extend it with e.g. userAgent and or languages as well.

But yeah at the end my test is running so not required for me. Just think you guys should decide either always suggest the Native JS way or always a custom method that can do that but not mix and match.

**Comment by Sebmaster** [comment]
You can't set top with defineProperty since it's `configurable: false`, which is why we're not going to use reconfigureWindow for a property that is `configurable: true` :wink:

**Comment by fkrauthan** [comment]
Ah ok makes sense. Even so I do not fully understand why one is configurable false and the other true while both to me should be readOnly and not changeable.

Thanks for all your help.
