### ISSUE TITLE
Please state the license

### ISSUE THREAD

**Issue by neilstuartcraig** [tmpvar/jsdom#1656]
Hi
I was just creating a PR for https://github.com/dhamaniasad/HeadlessBrowsers/ and noticed that JSDom doesn't seem to have the license stated explicitly in the readme. I spotted the license file which looks to be MIT. I think it'd be nice to state that the project uses MIT in the readme, happy to create a PR to do so if that's OK and is helpful.

Cheers

**Comment by kapouer** [comment]
The presence of the LICENSE file, + the mention in package.json, makes it clear enough ?

**Comment by neilstuartcraig** [comment]
Yeah maybe so, i guess I (personally) prefer it to be stated in the readme, and that's quite commonly done in my experience e.g. https://github.com/facebook/react. Just seems a bit friendlier, especially for folks who aren'y so familiar with package.json.

**Comment by domenic** [comment]
The convention is to use a LICENSE file; the README contains information on how to use the library.
