### ISSUE TITLE
document.scripts should return list of all the scripts

### ISSUE THREAD

**Issue by gajus** [tmpvar/jsdom#1660]
```js
const scriptElement = document.createElement('script');

document.body.appendChild(scriptElement);

// Current behaviour (unexpected)
document.scripts === 'undefined';

// Expected behaviour
document.scripts instanceof HTMLCollection;
```

See https://developer.mozilla.org/en-US/docs/Web/API/Document/scripts

**Comment by gajus** [comment]
As far as I can think, this is simply an alias for `document.getElementsByTagName('script')`.

**Comment by domenic** [comment]
This is already implemented and published. Are you sure you are using the latest jsdom?

**Comment by gajus** [comment]
I am using v9.8.3.

To be precise, I am using [browser-env](https://github.com/lukechilds/browser-env).

Looking at the source code of the latter, there is nothing that would break this behaviour.

https://github.com/lukechilds/browser-env/blob/63e45b4dec1f4430ba078d53a738fd84d1d96d12/src/index.js

**Comment by gajus** [comment]
With all due respect, its not a good idea to close an issue prior to confirming whether it is not a bug.

**Comment by gajus** [comment]
Locally I have solved this issue by using `const scripts = document.getElementsByTagName('script');`.

**Comment by Sebmaster** [comment]
We don't actually generate code for `document.scripts`, it's commented in the IDL. Any reason you can remember for that @domenic? Seems like it's implemented in the impl class.

**Comment by domenic** [comment]
Ah, yeah, just an oversight. Thanks.
