### ISSUE TITLE
jsdom messed up with getComputedTextLength or getBBox function

### ISSUE THREAD

**Issue by csethanhcong** [tmpvar/jsdom#1664]
I'm facing a problem when trying to get size of text element using d3:

I tried getComputedTextLength or getBBox, my library doing well but when mock test with jsdom it returned following error: 

> TypeError: text.node(...).getBBox is not a function

Any ideas ?

**Comment by Sebmaster** [comment]
jsdom doesn't do any layouting, so neither of those methods would return anything sensible. You can just shim them in your `created` callback.

**Comment by csethanhcong** [comment]
@Sebmaster thank 
Hope jsdom will support layouting soon,

**Comment by JochenFromm** [comment]
Same problem here. How can you "shim" the methods in the callback, could you give an example?

**Comment by domenic** [comment]
https://github.com/tmpvar/jsdom#intervening-before-parsing

**Comment by JochenFromm** [comment]
Thanks, I tried

```
 const dom = new JSDOM('<!DOCTYPE html><body><p>Hello world</p></body></html>', {
   beforeParse(window) {
     HTMLUnknownElement.getComputedTextLength = (() => 200);
   }
 });
```

but still get the error `TypeError: tspan.node(...).getComputedTextLength is not a function`. What is the right element to mock ? 😕

**Comment by domenic** [comment]
No, you probably want window.HTMLElement. But I don't know what tspan.node(...) returns, so maybe log what that is.

**Comment by Sebmaster** [comment]
You also need to attach it to the prototype, not as a static method.

**Comment by eltimn** [comment]
For future reference; the node function returns a window.Element. This is what worked for us:

    const dom = new JSDOM('<!DOCTYPE html><body><p>Hello world</p></body></html>', {
      beforeParse(window) {
        window.Element.prototype.getComputedTextLength = function() {
          return 200
        }
      }
    })

**Comment by jordancoil** [comment]
Here is a simple function you can implement to polyfill for getBBox
`getBoundingBox(annotation) {
        if (annotation.getBBox) {
            return annotation.getBBox()
        } else if (annotation.attributes.d) {
            let xmin, xmax, ymin, ymax
            let path = annotation.attributes.d.value

            path = path.replace(/[a-z].*/g," ")
                       .replace(/[\sA-Z]+/gi," ")
                       .trim()
            
            const coordinate_list = path.split(" ")

            for (var coordinate of coordinate_list) {
                if (coordinate.length > 1) {
                    let initial_coordinate = coordinate.split(",")
                    xmin = xmax = initial_coordinate[0]
                    ymin = ymax = initial_coordinate[1]
                    break
                }
            }

            for (var coordinate of coordinate_list) {
                let xycoord = coordinate.split(",")
                if (!xycoord[1]) {
                    // ignore relative movements
                    xycoord[0] = xmin
                    xycoord[1] = ymin
                }
                xmin = Math.min(xmin, xycoord[0])
                xmax = Math.max(xmax, xycoord[0])
                ymin = Math.min(ymin, xycoord[1])
                ymax = Math.max(ymax, xycoord[1])
            }
            return [[xmin, ymax], [xmax, ymin]]
        }
    }`

**Comment by rssfrncs** [comment]
@jordancoil do you use this function to extend SVGGraphicsElement?

**Comment by jordancoil** [comment]
@rssfrncs It just allows you to get the bounding box coordinates on browsers that don't have support for getBBox()

**Comment by markov00** [comment]
@jordancoil Interesting polyfill, do you know if this also take in consideration styles applied to the svg element?

**Comment by Anand-Seniyar** [comment]
@eltimn can you please suggest what does 'return 200' in your code,
`const dom = new JSDOM('<!DOCTYPE html><body><p>Hello world</p></body></html>', {
  beforeParse(window) {
    window.Element.prototype.getComputedTextLength = function() {
      return 200
    }
  }
})`

**Comment by larrybotha** [comment]
For a quick implementation for tests in Jest:

```javascript
beforeEach(() => {
  window.SVGElement.prototype.getBBox = () => ({
    x: 0,
    y: 0, 
    // whatever other props you need
  });
});

afterEach(() => {
  delete window.SVGElement.prototype.getBBox;
});
```

Likely a better solution with mocks, but gotta be pragmatic so just doing what works for now.

**Comment by ronvenna** [comment]
```  
beforeEach(() => {
    window.SVGElement.prototype.getComputedTextLength = () => 200;
  });
```

Thanks to @larrybotha, This worked for me for getComputedTextLength.

**Comment by megha-ui** [comment]
@larrybotha @ronvenna ,

when am implimenting the above solution am getting following error:

**TypeError: Cannot read property 'prototype' of undefined**

kindly guide me

**Comment by larrybotha** [comment]
@megha-ui not sure why `SVGElement` wouldn't be available on `window` but you _may_ be able to add `SVGElement` to `window`:

```javascript
beforeEach(() => {
  // naive way to add SVGElement to window if it doesn't exist
  if (!window.SVGElement) {
	window.SVGElement = {};
  }

  window.SVGElement.prototype.getBBox = () => ({
    x: 0,
    y: 0, 
    // whatever other props you need
  });
});
```

This is untested, and will likely only mask an underlying issue - if you get other errors after doing this, then this isn't the correct approach, and you'll need to determine what the underlying issue is.

You can start by inspecting the `window` object inside `beforeEach` to determine whether `SVGElement` is there or not (see [Jest's troubleshooting tips](https://jestjs.io/docs/en/troubleshooting)), although at this point StackOverflow is a better place to get feedback.

**Comment by aparna-tavisca** [comment]
> @megha-ui not sure why `SVGElement` wouldn't be available on `window` but you _may_ be able to add `SVGElement` to `window`:
> 
> ```js
> beforeEach(() => {
>   // naive way to add SVGElement to window if it doesn't exist
>   if (!window.SVGElement) {
> 	window.SVGElement = {};
>   }
> 
>   window.SVGElement.prototype.getBBox = () => ({
>     x: 0,
>     y: 0, 
>     // whatever other props you need
>   });
> });
> ```
> 
> This is untested, and will likely only mask an underlying issue - if you get other errors after doing this, then this isn't the correct approach, and you'll need to determine what the underlying issue is.
> 
> You can start by inspecting the `window` object inside `beforeEach` to determine whether `SVGElement` is there or not (see [Jest's troubleshooting tips](https://jestjs.io/docs/en/troubleshooting)), although at this point StackOverflow is a better place to get feedback.

while trying to add `getBBox` method on `window.SVGElement.prototype`, I'am getting error, `Property 'getBBox' does not exist on type 'SVGElement'` and the `Quick Fix` of editor adds the `getBBox` method in the interface of `lib.dom.d.ts`, which is readable file. Is there any way to fix this?

```
  beforeEach(async function () {
     window.SVGElement.prototype.getBBox = () => ({
          x: 0,
          y: 0,
          height: 100,
          width: 100,
          bottom: 100,
          left: 100,
          right: 100,
          top: 100,
          toJSON: () => { }
        });
   });
```

**Comment by danbirle** [comment]
> @megha-ui not sure why `SVGElement` wouldn't be available on `window` but you _may_ be able to add `SVGElement` to `window`:
> 
> ```js
> beforeEach(() => {
>   // naive way to add SVGElement to window if it doesn't exist
>   if (!window.SVGElement) {
> 	window.SVGElement = {};
>   }
> 
>   window.SVGElement.prototype.getBBox = () => ({
>     x: 0,
>     y: 0, 
>     // whatever other props you need
>   });
> });
> ```
> 
> This is untested, and will likely only mask an underlying issue - if you get other errors after doing this, then this isn't the correct approach, and you'll need to determine what the underlying issue is.
> 
> You can start by inspecting the `window` object inside `beforeEach` to determine whether `SVGElement` is there or not (see [Jest's troubleshooting tips](https://jestjs.io/docs/en/troubleshooting)), although at this point StackOverflow is a better place to get feedback.

![image](https://user-images.githubusercontent.com/9007877/146216405-35629dcc-2f7c-4054-8bc6-dd093ae75c5c.png)

https://developer.mozilla.org/en-US/docs/Web/API/SVGGraphicsElement/getBBox

seems it's not a property of SVGElement anymore but for some reason i can't get it to work with SVGGraphicsElement either..... :(
