### ISSUE TITLE
can't get the Dynamic html

### ISSUE THREAD

**Issue by huhu502** [tmpvar/jsdom#1668]
var jsdom = require("node-jsdom");

jsdom.env(
   './svg.html',
  ["http://code.jquery.com/jquery.js",
  "./javascripts/lib/jquery.min.js",
  "./javascripts/lib/bootstrap.min.js",
  "./javascripts/lib/angular.min.js",
  "./javascripts/lib/angular-ui-router.min.js",
  "./javascripts/lib/ct-ui-router-extras.min.js",
  "./javascripts/lib/jszip.min.js",
  "./javascripts/lib/ngStorage.min.js",
  "./javascripts/lib/d3.min.js",
  "./javascripts/layout_modules/layout_modules.js",
  "./javascripts/lib/kendo.core.min.js",
  "./javascripts/lib/kendo.angular.min.js",
  "./javascripts/lib/kendo.userevents.min.js",
  "./javascripts/lib/kendo.validator.min.js",
  "./javascripts/lib/kendo.columnsorter.min.js",
  "./javascripts/lib/kendo.data.min.js",
  "./javascripts/lib/kendo.selectable.min.js",
  "./javascripts/lib/kendo.binder.min.js",
  "./javascripts/lib/kendo.editable.min.js",
  "./javascripts/lib/kendo.groupable.min.js",
  "./javascripts/lib/kendo.grid.min.js",
  "./javascripts/lib/kendo.numerictextbox.min.js",
  "./javascripts/lib/kendo.popup.min.js",
  "./javascripts/lib/kendo.tooltip.min.js",
  "./javascripts/lib/kendo.list.min.js",
  "./javascripts/lib/kendo.draganddrop.min.js",
  "./javascripts/lib/kendo.resizable.min.js",
  "./javascripts/lib/kendo.splitter.min.js",
  "./javascripts/lib/kendo.tabstrip.min.js",
  "./javascripts/lib/kendo.autocomplete.min.js",
  "./javascripts/layout_modules/shared/CeCommonLib/partlib/CeLayerBase.js",
  "./javascripts/layout_modules/shared/CeCommonLib/partlib/CeLayerDocument.js",
  "./javascripts/layout_modules/shared/CeCommonLib/partlib/CeLayerLogic.js",
  "./javascripts/layout_modules/shared/CeCommonLib/partlib/CeLayerMaker.js",
  "./javascripts/layout_modules/shared/CeCommonLib/partlib/CeLayerMask.js",
  "./javascripts/layout_modules/shared/CeCommonLib/partlib/CeLayerPaste.js",
  "./javascripts/layout_modules/shared/CeCommonLib/partlib/CeLayerSilkScreen.js",
  "./javascripts/layout_modules/shared/CeShareNG/drawing/CeLayoutSettings.js",
  "./javascripts/layout_modules/shared/CeShareNG/geometry/CeArc.js",
  "./javascripts/layout_modules/shared/CeShareNG/geometry/CeLarc.js",
  "./javascripts/layout_modules/shared/CeShareNG/geometry/CeBox2D.js",
  "./javascripts/layout_modules/shared/CeShareNG/geometry/CeCircle.js",
  "./javascripts/layout_modules/shared/CeShareNG/geometry/CeDiamond.js",
  "./javascripts/layout_modules/shared/CeShareNG/geometry/CeDonutRound.js",
  "./javascripts/layout_modules/shared/CeShareNG/geometry/CeDonutSqrRnd.js",
  "./javascripts/layout_modules/shared/CeShareNG/geometry/CeDonutSquare.js",
  "./javascripts/layout_modules/shared/CeShareNG/geometry/CeGeomFactory.js",
  "./javascripts/layout_modules/shared/CeShareNG/geometry/CeGeomHolder.js",
  "./javascripts/layout_modules/shared/CeShareNG/geometry/CeGeomTools.js",
  "./javascripts/layout_modules/shared/CeShareNG/geometry/CeGeometry.js",
  "./javascripts/layout_modules/shared/CeShareNG/geometry/CeLine.js",
  "./javascripts/layout_modules/shared/CeShareNG/geometry/CeLineSegs.js",
  "./javascripts/layout_modules/shared/CeShareNG/geometry/CeLocation.js",
  "./javascripts/layout_modules/shared/CeShareNG/geometry/CeOctagon.js",
  "./javascripts/layout_modules/shared/CeShareNG/geometry/CeOval.js",
  "./javascripts/layout_modules/shared/CeShareNG/geometry/CeOvalHalf.js",
  "./javascripts/layout_modules/shared/CeShareNG/geometry/CePolygon.js",
  "./javascripts/layout_modules/shared/CeShareNG/geometry/CePolygonWithHole.js",
  "./javascripts/layout_modules/shared/CeShareNG/geometry/CeRectCutCorner.js",
  "./javascripts/layout_modules/shared/CeShareNG/geometry/CeRectangle.js",
  "./javascripts/layout_modules/shared/CeShareNG/geometry/CeRefGeometry.js",
  "./javascripts/layout_modules/shared/CeShareNG/geometry/CeSquare.js",
  "./javascripts/layout_modules/shared/CeShareNG/geometry/CeSurface.js",
  "./javascripts/layout_modules/shared/CeShareNG/geometry/CeVertex.js",
  "./javascripts/layout_modules/shared/CeShareNG/geometry/CeVertexArc.js",
  "./javascripts/layout_modules/shared/CeShareNG/geometry/CeVertices.js",
  "./javascripts/layout_modules/shared/CeShareNG/geometry/GCPolygon.js",
  "./javascripts/layout_modules/shared/CeShareNG/geometry_old/CeArc.js",
  "./javascripts/layout_modules/shared/CeShareNG/geometry_old/CeGeometry.js",
  "./javascripts/layout_modules/shared/CeShareNG/geometry_old/CeVertex.js",
  "./javascripts/layout_modules/shared/CeShareNG/utility/CeLinkedMap.js",
  "./javascripts/layout_modules/shared/CeShareNG/utility/DoubleRounding.js",
  "./javascripts/layout_modules/shared/CeShareNG/utility/NumberHelper.js",
  "./javascripts/layout_modules/shared/CeShareNG/utility/StrSplitRule.js",
  "./javascripts/layout_modules/shared/CeShareNG/utility/StringHelper.js",
  "./javascripts/layout_modules/shared/CeShareNG/utility/StringList.js",
  "./javascripts/layout_modules/shared/data/LayoutData.js",
  "./javascripts/layout_modules/shared/data/interfaceData.js",
  "./javascripts/layout_modules/shared/data/stackupData.js",
  "./javascripts/layout_modules/shared/data/componentData.js",
  "./javascripts/layout_modules/shared/data/impedanceData.js",
  "./javascripts/layout_modules/desktop/LayoutCanvas/CanvasCircle.js",
  "./javascripts/layout_modules/desktop/LayoutCanvas/Canvas.js",
  "./javascripts/layout_modules/desktop/LayoutCanvas/CanvasObject.js",
  "./javascripts/layout_modules/desktop/LayoutCanvas/CanvasPath.js",
  "./javascripts/layout_modules/desktop/LayoutCanvas/CanvasPolygon.js",
 
  
  ],

  function (errors, window) {
    //debugger message

    var fs = require("fs");
    var layoutfileName = './resource/case3/layout.db';
    var layoutdata = fs.readFileSync(layoutfileName);
    var layDBContent = layoutdata.toString();

    var partfileName = './resource/case3/parts.db';
    var partdata = fs.readFileSync(partfileName);
    var partDBContent = partdata.toString();

    var bottomfileName = './resource/case3/layers/BOTTOM.lyr';
    var bottomdata = fs.readFileSync(bottomfileName);
    var bottomContent = bottomdata.toString();

    var gndfileName = './resource/case3/layers/GND.lyr';
    var gnddata = fs.readFileSync(gndfileName);
    var gndContent = gnddata.toString();

    var IS1fileName = './resource/case3/layers/IS1.lyr';
    var IS1data = fs.readFileSync(IS1fileName);
    var IS1Content = IS1data.toString();

    var IS2fileName = './resource/case3/layers/IS2.lyr';
    var IS2data = fs.readFileSync(IS2fileName);
    var IS2Content = IS2data.toString();

    var VCCfileName = './resource/case3/layers/VCC.lyr';
    var VCCdata = fs.readFileSync(VCCfileName);
    var VCCContent = VCCdata.toString();

    var topfileName = './resource/case3/layers/TOP.lyr';
    var topdata = fs.readFileSync(topfileName);
    var topContent = topdata.toString();

  window.__myObject = { partDBContent:partDBContent,layDBContent: layDBContent ,
    bottomContent:bottomContent,
    gndContent:gndContent,
    IS1Content:IS1Content,
    IS2Content:IS2Content,
    VCCContent:VCCContent,
    topContent:topContent};

  var scriptEl = window.document.createElement("script");
  scriptEl.src = "anotherScript.js";
  window.document.body.appendChild(scriptEl);

    jsdom.getVirtualConsole(window).sendTo(console);
     setTimeout(function(){

      console.log(window.$("svg").html());
    },2000);
  }
);

 the data can inject to the js.But the html is still is static .I can't get the dymatic html.
we can see in cmd is :+1: 
        Read part DB file data.
Succeed to load part DB.
Read layout DB file data.
CelayoutDB:[object Object]  undefined  undefined
CeIODataBlock {
  mName: 'GeomSymbols',
  mBlockData: 
   [ CeIODataBlock { mName: 'ShapeList', mBlockData: [Object] },
     CeIODataBlock { mName: 'ViaList', mBlockData: [Object] } ] }
Success to load layer file: TOP
metal：[object Object]

		<g> </g>

**Comment by domenic** [comment]
This is not the repository for node-jsdom.
