### ISSUE TITLE
Attr.nodeType return undefined

### ISSUE THREAD

**Issue by jsbr** [tmpvar/jsdom#1669]
example: 
```javscript
var d=document.createElement("div");
d.setAttribute("class","fixme")
d.attributes["class"].nodeType
```

nodeType should be 2  not undefined

NB: I use jsdom-global

**Comment by domenic** [comment]
[jsdom-global is not supported](https://github.com/tmpvar/jsdom/wiki/Don't-stuff-jsdom-globals-onto-the-Node-global). But in general, yes, we have not updated to the latest spec changes which make Attr a subclass of Node.

**Comment by domenic** [comment]
Let's fold this into #1641
