### ISSUE TITLE
FormData is missing some methods

### ISSUE THREAD

**Issue by niksajanjic** [tmpvar/jsdom#1671]
If I'm understanding this correctly, looking at this file:

https://github.com/tmpvar/jsdom/blob/a6acac4e9dec4f859fff22676fb4e9eaa9139787/lib/jsdom/living/xhr/FormData.idl

Seems like FormData supports _append_, _delete_, _get_, _getAll_, _has_ and _set_ methods. But, according to this reference:

https://developer.mozilla.org/en-US/docs/Web/API/FormData

It should also support _entries_, _keys_ and _values_. Seems like these methods are also part of living standard. Is it planned to add them in some future iteration?

**Comment by domenic** [comment]
Yeah. What we are missing here is support for automatically generating the methods for all iterables. So this is technically a feature request for https://github.com/jsdom/webidl2js .
