### ISSUE TITLE
no CanvasRenderingContext2D results in errors when trying to test chart.js

### ISSUE THREAD

**Issue by gfarrell** [tmpvar/jsdom#1672]
I'm using `jsdom` and `jsdom-global` for my tests (written with `mocha`). When I try running them, I get the following problem:

    ReferenceError: CanvasRenderingContext2D is not defined

[The offending line is here](https://github.com/chartjs/Chart.js/blob/v2.4.0/src/core/core.controller.js#L142).

`jsdom-global` doesn't inject `CanvasRenderingContext2D` into the global scope as it's not defined by `jsdom` (as can be seen [here](https://github.com/rstacruz/jsdom-global/blob/91b324ca02a8af14a268f863ff0731eae0779dac/keys.js)).

I'm not really sure how to go about solving this.

**Comment by domenic** [comment]
Unfortunately jsdom-global is not a supported way of using jsdom. See https://github.com/tmpvar/jsdom/wiki/Don't-stuff-jsdom-globals-onto-the-Node-global . As such this repo won't be able to help you.

I guess we should put this in some kind of issue template.

**Comment by gfarrell** [comment]
@domenic: please reopen as that's only the first part of the problem. The second part is that `CanvasRenderingContext2D` isn't defined by jsdom at all, I can't even inject it in the manner described in that link.

**Comment by gfarrell** [comment]
Also not sure that the method in the above link really applies for things like react rendering for tests (see http://airbnb.io/enzyme/docs/guides/jsdom.html).

**Comment by gor181** [comment]
[This is how I test Chart.js with mocha] https://github.com/chartjs/Chart.js/issues/3696#issuecomment-266360502
