### ISSUE TITLE
window.HTMLElement

### ISSUE THREAD

**Issue by mattpap** [tmpvar/jsdom#1675]
I would like to pollute `global` with members of `window`. This used to work in my earlier code (with simple `for in`), which used jsdom 5.x, but after upgrading to 9.8.3 I get the following:
```
$ node
> var jsdom = require("jsdom")
undefined
> global.document = jsdom.jsdom()
Document { location: [Getter/Setter] }
> global.window = global.document.defaultView; undefined
undefined
> global.window.HTMLElement
[Function: HTMLElement]
> "HTMLElement" in global.window
true
> global.window.hasOwnProperty("HTMLElement")
true
> Object.getOwnPropertyNames(global.window).indexOf("HTMLElement")
-1
> Object.keys(global.window).indexOf("HTMLElement")
-1
> for (var key in global.window) { if (key === "HTMLElement") console.log("found") }
undefined
> 
```
I get the same result under nodejs 4.x (4.4.1), 5.x (5.10.0) and 6.x (6.3.1).

Earlier I got (skipping initial matching lines):
```
> Object.getOwnPropertyNames(global.window).indexOf("HTMLElement")
71
> Object.keys(global.window).indexOf("HTMLElement")
20
> for (var key in global.window) { if (key === "HTMLElement") console.log("found") }
found
undefined
```
In a web browser (Chromium 51) I get:
```
> window.HTMLElement
HTMLElement() { [native code] }
> "HTMLElement" in window
true
> window.hasOwnProperty("HTMLElement")
true
> Object.getOwnPropertyNames(window).indexOf("HTMLElement")
534
> Object.keys(window).indexOf("HTMLElement")
-1
> for (var key in window) { if (key === "HTMLElement") console.log("found") }
undefined
```
It looks like `Object.getOwnPropertyNames()` should the the reliable way to obtain `HTMLElement`, but that doesn't work with jsdom 9.8.3. My original approach isn't even supported by a web browser. I know I can do `global.HTMLElement = global.window.HTMLElement`, but note that the same (most likely, I didn't test all combinations) happens for `Event`, `Image` at al. and I don't want to copy individual members manually. I'm not sure if it's my understanding being wrong or there is a bug in jsdom or nodejs. Any feedback is highly appreciated.

**Comment by domenic** [comment]
See https://github.com/tmpvar/jsdom/wiki/Don't-stuff-jsdom-globals-onto-the-Node-global. This is not a supported scenario.
