### ISSUE TITLE
Addition of keys.includes() does not work in Node versions < 6, breaks semver

### ISSUE THREAD

**Issue by eddieloeffen** [tmpvar/jsdom#1679]
This commit uses Array.prototype.includes which is not supported in older versions of Node:

https://github.com/tmpvar/jsdom/commit/30f7906a6a87d13ae69a22b5a3db134b49f70618#diff-8f9d03fb916b885159a93432e483b566R93

My npm install picked up the latest version 9.9.0. (package.json version is "^9.2.1").

This change breaks backwards compatibility so should increment the major version number according to semver, rather than the minor version number.

**Comment by Sebmaster** [comment]
On it

**Comment by Sebmaster** [comment]
Fixed in 7c2861d007793ebfa31f9a82be72556722d465cd and published 9.9.1.

**Comment by eddieloeffen** [comment]
Thanks for the quick turnaround! Tests are all working correctly again.
