### ISSUE TITLE
A possible typo in 'Don't stuff jsdom globals onto the Node global' document

### ISSUE THREAD

**Issue by gamtiq** [tmpvar/jsdom#1692]
It seems there is a typo in the following code from [Don't stuff jsdom globals onto the Node global](https://github.com/tmpvar/jsdom/wiki/Don't-stuff-jsdom-globals-onto-the-Node-global#running-code-inside-the-jsdom-context):
```js
const scriptEl = document.createElement("script");
scriptEl.textContent = myLibrary;
window.document.body.textContent = myLibrary;
```
I suppose the last line should be:
```js
window.document.body.textContent = scriptEl;
```

**Comment by domenic** [comment]
Thanks, fixed!
