### ISSUE TITLE
document URL parsing

### ISSUE THREAD

**Issue by PauloASilva** [tmpvar/jsdom#1693]
Hi,
I did notice a miss behavior on URL parsing when using Jest ([closed issue][1]) which should be bug in or missing feature of jsdom.

I would be glad to help you further but I will need some, perhaps, some guidance.

From the issue I did open for Jest

**What is the current behavior?**
```javascript
function parseURL (url) {
    var parser = document.createElement('a');

    parser.setAttribute('href', url);

    return {
        protocol: parser.protocol,
        username: parser.username,
        password: parser.password,
        host: parser.host,
        hostname: parser.hostname,
        port: parser.port,
        pathname: parser.pathname,
        search: parser.search,
        hash: parser.hash
    };
}
```

```javascript
Object.defineProperty(window.location, 'href', {
    writable: true,
    value: 'http://github.com'
});

parseURL('//somehost.com');
// {
//     "hash": "", 
//     "host": "", 
//     "hostname": "", 
//     "password": "", 
//     "pathname": "", 
//     "port": "", 
//     "protocol": ":", 
//     "search": "", 
//     "username": ""
// }
```
This is the Firefox and Google Chrome behavior when the source code runs on a page whose document.location is `about:blank` what is not expected as the `window.location.href` property is defined by ([Issue#890][1])

```javascript
Object.defineProperty(window.location, 'href', {
    writable: true,
    value: 'http://github.com'
});
```

**If the current behavior is a bug, please provide the steps to reproduce and either a repl.it demo through https://repl.it/languages/jest or a minimal repository on GitHub that we can `yarn install` and `yarn test`.**

**What is the expected behavior?**
```javascript
parseURL('//somehost.com');
// {
//     protocol: "https:",
//     username: "",
//     password: "",
//     host: "somehost.com",
//     hostname: "somehost.com",
//     port: "",
//     pathname: "/",
//     search: "",
//     hash: ""
// }
```

This is the Firefox and Google Chrome behavior when the source code run on a page whose document.location is other than `about:blank`.

---

This happened with jsdom v9.8.3 (as a Jest dependency).

Regards,
Paulo

[1]: https://github.com/facebook/jest/issues/2453

**Comment by PauloASilva** [comment]
Looking around I came to ["Stubbing/patching `window.location.href` in JSDom 8?" issue][1].

I would lik

[1]: https://github.com/tmpvar/jsdom/issues/1388

**Comment by domenic** [comment]
I'd suggest using the Jest API, since that ensures it's consistently set up the right way from the beginning. But there's also https://github.com/tmpvar/jsdom#changing-the-url-of-an-existing-jsdom-window-instance

**Comment by PauloASilva** [comment]
Hi @domenic,
Jest does not expose the `jsdom` instance on the global scope and it only allows setting the URL on `package.json` file. So there's no way to call `jsdom.changeURL()` at runtime.

On my use case I need to change the URL per `it()`.

I think we can improve jest+jsdom exposing the jsdom instance on global scope so that the `changeURL()` method can be called everywhere at any time, but I think it would also be great to have the `changeURL()` behavior with the `window.location` setter.
There is some constraint which should avoid this implementation?

**Comment by domenic** [comment]
We don't add nonstandard properties like changeURL to standard objects like window.location.

**Comment by PauloASilva** [comment]
I understand but `window.location` is a standard property, using the property setter, we can accomplish the same behavior without augmenting the API

**Comment by domenic** [comment]
No, you can't; window.location's setter performs a navigation, which is an entirely separate piece of functionality which jsdom does not yet support (and would require a lot of work to add).

**Comment by PauloASilva** [comment]
I do not agree that they are "an entirely separate piece of functionality" as when implementing the navigation part you will have to set the URL. I would say that right now it would be quite easy to make a partial implementation, just adding a setter with `jsdom.changeURL()` behavior.

What do you think?

I am checking with the jest guys whether or not the jsdom instance should be exposed on the global scope/environment ([issue][1]).

[1]: https://github.com/facebook/jest/issues/2460

**Comment by domenic** [comment]
No, we don't have any intention of implementing a fake navigation that only changes the URL. The most important parts of navigation are things like replacing every object (Window, Document, etc.) and until we can implement that, it's better to just output a not-implemented warning.

In the end it sounds like you have a problem not with jsdom, but with jest. jsdom already has a solution to your problem, with jsdom.changeURL. So I am going to close this issue.
