### ISSUE TITLE
Impossible to set cookies on runtime

### ISSUE THREAD

**Issue by TeoTN** [tmpvar/jsdom#1698]
I've come up across such problem: it's impossible to set a cookie during page runtime. My test is:
```
import Cookies from 'js-cookie';
import { jsdom, createCookieJar } from 'jsdom';

const doc = jsdom('<!doctype html><html><body></body></html>');
global.document = doc;
global.window = doc.defaultView;
global.window.name = '';

describe('Cookies test', () => {
    it('should set and get cookie', () => {
        const name = 'coo';
        const value = 'foo';
        Cookies.set(name, value);
        expect(Cookies.get(name)).to.be.equal(value);
    })
});
```

the same goes for 
```
document.cookie='coo=foo';
```
The cookie remains undefined.

My goal is to test whether the cookie is set when I click on some button on the page, which should be technically possible. 

My environment: "jsdom": "^9.8.3", "mocha": "^3.1.2","sinon": "^1.17.6", "expect.js": "^0.3.1", Node v6.9

**Comment by domenic** [comment]
This is presumably failing because you are using an unsupported pattern: https://github.com/tmpvar/jsdom/wiki/Don't-stuff-jsdom-globals-onto-the-Node-global

Also, you are using syntax (`import`) which is not supported on the platforms jsdom supports.

Closing for now, but happy to reopen if you can provide a repro using supported syntax and not using global variables.

**Comment by TeoTN** [comment]
Well, I'd be more than surprised if this would be either due to `import` or due to having references in `global`. I am also against naming the latter an anti-pattern. Firstly, I don't really want to have to create a separate jsdom environment for each test suite. Moreover, I don't feel that when you have a few more properties in node.js `global` then anything special happens - you're just shaping your testing environment whose mere purpose is to have things tested and it shouldn't really affect anything. So well, it's rather "another pattern" than "anti-pattern" but clearly we have different preferences (of course if you can think of some case when it really fails something then I am all ears)

Here's an example without imports and adjusted to use your readfile-embedstring pattern which also fails: https://github.com/TeoTN/jsdom-fail

**Comment by domenic** [comment]
Your jsdom-fail repo has two problems:

- It is trying to use `require` in a browser environment. That will just throw an error, causing nothing to happen.
- Even if that worked, it would be using two separate `js-cookie` modules: one in Node.js, and one inside the DOM. You need to consistently use the one inside the DOM if you want to see changes that are made to the DOM.

**Comment by TeoTN** [comment]
Ok, I see. But this means that while incorporating jsdom into existing project which is mostly written in ES2017 etc. I have to compile/transpile it first (in the don't put it in `globals` approach) since browsers don't really support module imports as for now (and so does not jsdom), am I right?
Moreover I can't rely on the libraries out-of-the-box in tests because I don't know whether they use window/document that is defined in the scope (see updated tests)? (And the question is what the heck is this library using that is unavailable...)

**Comment by domenic** [comment]
In general you should run your code the same way in jsdom that you run it in browsers; it's meant to emulate a browser. If you are using features browsers don't support, you'll need to work around that, e.g. by transpiling or bundling with webpack or...

You should be able to rely on any libraries out-of-the-box that you would be able to rely on in browsers, inside jsdom. For example, any library relying on `document` or `XMLHttpRequest` or `CSSStyleRule` will work inside jsdom, if run inside a script. But any library relying on `import` or `require` will not, since they don't work out of the box in a browser either.

**Comment by TeoTN** [comment]
But this of course would cause the testing time to increase vastly and I also can't stop the build process immediately when tests are failing because in fact I have to run the build before running any tests at all. And probably I would need an appropriate html, which comes from CMS. Ouch.

And it's valuable information, that `jsdom` is not just a really good mock of DOM but rather a separate environment... Have you ever thought about adjusting jsdom to work nicely in so-called `franken-environment`? 😉

Nevertheless I'll probably stick to writing a stub for the cookie library as I don't want to test its behaviour in the testing environment, as it's rather a matter of ensuring that it's functions are called with appropriate arguments and that some information is stored between calls.

Thank you for your time and help.

**Comment by Joris-van-der-Wel** [comment]
> Have you ever thought about adjusting jsdom to work nicely in so-called franken-environment?

The problem with polluting the `global` is that this trick can not be made compliant with the various specifications that we implement (such as DOM). There are a lot of weird features after decades of keeping the web backwards compatible. The libraries that you use may fail in unexpected ways.
