### ISSUE TITLE
SyntaxError thrown on document.querySelectorAll('meta[http-equiv]');

### ISSUE THREAD

**Issue by tsirolnik** [tmpvar/jsdom#1699]
I'm doing a simple `document.querySelectorAll('meta[http-equiv]');`, and for some reason I get the following error - 
```
SyntaxError at DocumentImpl.<anonymous> (/node_modules/jsdom/lib/jsdom/living/nodes/ParentNode-impl.js:83)
at DocumentImpl.querySelectorAll (/node_modules/jsdom/lib/jsdom/utils.js:133:45)
at Document.querySelectorAll (/node_modules/jsdom/lib/jsdom/living/generated/ParentNode.js:39)
at Function.getMetaRefreshURL (/app.js:31)
```

If it is a SyntaxError in the page, shouldn't it be reported via jsdomError why is it throwing?

**Comment by tsirolnik** [comment]
I can't reproduce either it as it was a production runtime error, this was happening while trying to reach google.com using Node 6.9.1 and jsdom 9.8.3.

The code flow is opening a window with http://google.com as its url and then just checking for the meta tag with the window.document.defaultView.document.querySelectorAll

**Comment by Marcelovk** [comment]
The page might be rewriting querySelectorAll using some js library.

**Comment by tsirolnik** [comment]
Interesting, haven't thought about that. I'll try to reproduce it.

**Comment by domenic** [comment]
Closing, happy to reopen with a minimal repro.
