### ISSUE TITLE
Error with React-Router URL

### ISSUE THREAD

**Issue by chawk** [tmpvar/jsdom#1702]
**Location-impl.js SyntaxError**

throw new DOMException(DOMException.SYNTAX_ERR, 'Could not resolve the given string "${url}" relative to the ' +

I'm trying to mount a React control using Enzyme and JSDOM but it throws this error.  The url being evaluated which is passed is "blank#/" which is showing up due to React-Router being used by this control being tested.  Ignoring this exception allows the code to run fine so I'm wondering if it's okay to wrap this in a try, catch?

```
replace(url) {
    // Should be entry settings object; oh well
    const parsedURL = parseURLToResultingURLRecord(url, this._relevantDocument);

    if (parsedURL === "failure") {
      throw new DOMException(DOMException.SYNTAX_ERR, `Could not resolve the given string "${url}" relative to the ` +
        `base URL "${this._relevantDocument.URL}"`);
    }

    this._locationObjectNavigate(parsedURL, { replacement: true });
  }
```

**Comment by domenic** [comment]
Probably you have not set a URL for your document, so it is trying to parse relative to about:blank and failing.

**Comment by ryancole** [comment]
@chawk you can set the URL using the `testURL` config setting.

**Comment by fgeorg** [comment]
I'm having the same problem. How can I test a component that uses createHashHistory? I'm not sure what you mean by the testURL config setting
