### ISSUE TITLE
Error using jsdom with Node 7.4.0

### ISSUE THREAD

**Issue by JakeDluhy** [tmpvar/jsdom#1706]
I am working on a project that uses mocha with jsdom and enzyme to run our integration tests within a virtual dom in Node. Right now I am using node 6.9.2, and everything works fine. I tried using 7.4.0, however running the tests I got the error
```
SyntaxError
    at XMLHttpRequest.open (/Users/jake/metamason/react-frontend/node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:458:15)
    at XMLHttpRequest.tryCatcher (/Users/jake/metamason/react-frontend/node_modules/rxjs/src/util/tryCatch.ts:7:27)
    at AjaxSubscriber.send (/Users/jake/metamason/react-frontend/node_modules/rxjs/src/observable/dom/AjaxObservable.ts:232:37)
    at new AjaxSubscriber (/Users/jake/metamason/react-frontend/node_modules/rxjs/src/observable/dom/AjaxObservable.ts:203:10)
    at AjaxObservable._subscribe (/Users/jake/metamason/react-frontend/node_modules/rxjs/src/observable/dom/AjaxObservable.ts:172:12)
```
I haven't really done any investigation into the root cause of this, but I thought I'd let you know what I saw. Here's the testHelper file that I use to set things up:
```javascript
const chai = require('chai');
const chaiImmutable = require('chai-immutable');
const jsdom = require('jsdom').jsdom;

// Set Chai Immutable
chai.use(chaiImmutable);

// Set up jsdom
global.document = jsdom('<html><body><div id="app"></div></body></html>', {
    url: 'http://example.com',
});

global.window = document.defaultView;
Object.keys(document.defaultView).forEach((property) => {
    if (typeof global[property] === 'undefined') {
        global[property] = document.defaultView[property];
    }
});

global.navigator = {
    userAgent: 'node.js',
};

window.sessionStorage = window.localStorage = {
    getItem() {},
    setItem() {},
    removeItem() {},
};
// jsdom doesn't have an implementation for this because they don't do layout.
// I opened an issue, and they might add a stub in the future with a warning
// Needed because the grommet Drop util was calling it for Menu components
window.HTMLElement.prototype.scrollIntoView = function() {};

window.performance = require('./helpers/performanceNowPolyfill')();
```

Let me know if you need any more info!

**Comment by domenic** [comment]
Thanks for the info! I'd love a repro here that is more minimal, so that we can tell the issue isn't being caused by e.g. the sessionStorage/localStorage stuff, or the performanceNowPolyfill, or the chai stuff, or the part where you add stuff to the global object.

**Comment by alistairjcbrown** [comment]
I can't really add to this for a solution, but we've been running the latest JSDOM under NodeJS v7.4.0 without any issues.

In case it helps narrow it down, here our JSDOM specific setup code, though it's not very different from the above which would indicate it's something else causing the issue.

```js
const jsdomDoc = jsdom.jsdom('<!doctype html><html><body></body></html>', { url: 'http://localhost' });

global.window = jsdomDoc.defaultView;
global.document = window.document;
global.navigator = window.navigator;
global.XMLHttpRequest = window.XMLHttpRequest;
global.HTMLElement = window.HTMLElement;
window.localStorage = new MockStorage();
window.sessionStorage = new MockStorage();
global.sinon = require('sinon'); // eslint-disable-line import/no-commonjs, import/newline-after-import
```

**Comment by JakeDluhy** [comment]
Thanks for the replies guys, sorry I haven't been able to get to this. I've been busy with other things (bumping the Node version down to 6.9.4 right now). I'm going to try to take a look in the near future to see if I can find out what's going on/repro (I think it _might_ have something to do with `rxjs` which we're using for ajax).

**Comment by trodrigues** [comment]
I believe I've found a similar issue when using Jest (which uses jsdom internally) together with Sinon's fake server in Node 7.

I've created a small test case which runs fine on Node 6.9.4 but not on 7.4.0:

```
var jsdom = require("jsdom");

jsdom.env(
  '<p><a class="the-link" href="https://github.com/tmpvar/jsdom">jsdom!</a></p>',
  ['http://sinonjs.org/releases/sinon-1.17.6.js'],
  function (err, window) {
    var server = window.sinon.fakeServer.create();

    server.respondWith("GET", "/path",
      [ 200
      , { 'Content-Type': 'application/json' }
      , '{"key": "value"}'
      ]
    );

    function reqListener () {
        console.log(this.responseText);
    }

    var oReq = new window.XMLHttpRequest();
    oReq.addEventListener("load", reqListener);
    oReq.open("GET", "/path");
    oReq.send();

    server.respond();

  }
);
```

It fails with the following:
```
/Users/trodrigues/laterpay/connector-ui/node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:458
        throw new DOMException(DOMException.SYNTAX_ERR);
        ^
SyntaxError
    at XMLHttpRequest.open (/Users/trodrigues/laterpay/connector-ui/node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:458:15)
    at Object.done (/Users/trodrigues/laterpay/connector-ui/testcase2.js:22:10)
    at process.nextTick (/Users/trodrigues/laterpay/connector-ui/node_modules/jsdom/lib/jsdom.js:320:18)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

The version of jsdom which jest is using is 9.9.1.

**Comment by avaly** [comment]
It seems that sinon can not replace the `global.XMLHttpRequest` (https://github.com/sinonjs/sinon/blob/master/lib/sinon/util/fake_xml_http_request.js#L700). Accessing `window.XMLHttpRequest` after sinon `fakeServer.create()` still returns the `jsdom` implementation for XHR.

If you substitute the line `var oReq = new window.XMLHttpRequest();` with `var oReq = new window.sinon.FakeXMLHttpRequest();`, this test case runs as expected under node `7.4.0`.

**Comment by mourner** [comment]
I'm investigating this issue too and boiled it down to a minimal test case. And it's really, really weird:

```
'use strict';
var window = require('jsdom').jsdom().defaultView;
var xhr = {};
window.XMLHttpRequest = xhr;
// window.XMLHttpRequest = xhr;
console.log(window.XMLHttpRequest === xhr);
```

If you run this test case with Node 7, it will say `false`. If you uncomment the commented line, it will be `true`. Same if you remove `'use strict'`. This seems like a really weird V8 bug to me.

I don't yet know what exactly in JSDom code triggers it though. If I create the `Window` object directly, it's also fine.

**Comment by mourner** [comment]
Ha! I just upgraded Node from 7.4.0 to the new 7.5.0 and the issue seems gone. Can you confirm? If so, this issue can be closed.

**Comment by domenic** [comment]
Yeah, there was a regression in v7.4.0. There are still some issues left, but maybe you're not hitting them as much. In general see https://github.com/nodejs/node/issues/6283 for a list of all the potential issues.

**Comment by trodrigues** [comment]
@mourner you're right. My test case above, and my tests running with jest/jsdom/sinon all now work perfectly.

**Comment by JakeDluhy** [comment]
7.5.0 works for me!

**Comment by ayxos** [comment]
Not working with 7.9.0! :(

**Comment by TimothyGu** [comment]
@ayxos Can you file a new issue, and follow the steps written in the issue template?

**Comment by huy-nguyen** [comment]
I have the same problem with node 8.1.3 (the latest version).

**Comment by domenic** [comment]
Locking this issue, as people are not producing useful bug reports, but instead just adding content-less +1s. Please file a new issue if you are having a problem, following the instructions in the issue template.
