### ISSUE TITLE
JSDom only recognizes a few CSS colors (because of how CSSStyle works)

### ISSUE THREAD

**Issue by SidneyNemzer** [tmpvar/jsdom#1707]
EDIT: after some investigation, it seems the the "CSSSStyle" module contains the logic to parse colors. It only recognizes a few choice keywords, and it doesn't convert keywords to rgb like the browser does.

As a result, JSDOM interpret computed style as follows:

Keywords are interpreted as keywords (but only a select few).
RGB, RBGA, and Hexcodes are returned as RGB or RGBA
HSL and HSLA are ignored completely

If JSDOM behaved like the browser, everything should be converted to RGB or RGBA. This is an issue with CSSStyle though, so I'll post an issue there.

**Comment by SidneyNemzer** [comment]
Followup question: Why does JSDom use the "cssstyle" module? What's wrong with the CSSStyleDeclaration that is implemented by CSSOM?

**Comment by domenic** [comment]
See the readme for cssstyle: https://www.npmjs.com/package/cssstyle

**Comment by SidneyNemzer** [comment]
I see, JSDom uses the CSS2Properties, which CSSOM doesn't support
