### ISSUE TITLE
Is it possible to use jsdom without canvas support?

### ISSUE THREAD

**Issue by rfgamaral** [tmpvar/jsdom#1708]
I don't need canvas support and I've been getting this error when importing jsdom into my project:

> 19 01 2017 13:07:19.722:ERROR [karma]: Error: Cannot find module 'canvas' from '.'

I'm not using the `<canvas>` element on my code  so I don't understand why I get that error. This should only happen if the `canvas` package is actually used for anything. But since I don't have `<canvas>` elements, why is it being used?

I could install the `canvas` package but I'm on Windows and that has a lot of dependencies just to install a simple package. I really didn't want to have all that work for a package I don't need.

Can I workaround this without having to install the `canvas` package?

**EDIT:**

Looking at the README:

> jsdom includes support for using the canvas package to extend any `<canvas>` elements with the canvas API. To make this work, you need to include canvas as a dependency in your project, as a peer of jsdom. **If jsdom can find the canvas package, it will use it, but if it's not present, then `<canvas>` elements will behave like `<div>`s.**

Why is my test suite crashing when I import `jsdom` into my spec files without having the `canvas` package installed?

**Comment by domenic** [comment]
I don't know! That sounds like a good question for Karma, which is the thing outputting that error message; jsdom is not outputting the error.

**Comment by Igloczek** [comment]
@domenic It's not related just to Karma.

I tried to run jsdom inside lambda function on Now.sh and get the exact same error. Adding `canvas` as a dependency is solving the issue, but... it's a huge package, in my case `node_modules` without it weights 21 MB, while with it 49 MB.
In most cases, it's not a big deal, but in a serverless environment, it makes the difference.

Logs from Now:
```
Error while initializing entrypoint: { Error: Cannot find module 'canvas'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
```

**Comment by domenic** [comment]
That sounds like a good question for Lamba, which is the thing outputting that error message.

**Comment by domenic** [comment]
I do not get that error when using jsdom alone. If you do, not involving other software like lambda or jest or webpack or karma, then consider opening a new issue, following the full issue template

**Comment by Slapbox** [comment]
Ah thank you @domenic, I am using Webpack though.

Is there any particular reason you can identify for why this wouldn't work in Webpack? Any idea if it's resolvable?

**Comment by molant** [comment]
@Slapbox take a look at https://webpack.js.org/configuration/resolve/ and resolve to a custom file that will allow the execution to continue.

**Comment by Slapbox** [comment]
@molant thanks for the idea! If I do that though, I think jsdom will think it has Canvas available and try to use it. Nonetheless I'll give it a shot and report back.

**Comment by molant** [comment]
Depends on what to do. The relevant line in jsdom is https://github.com/jsdom/jsdom/blob/d3facd595a28567443d39bc2c925f5366f7d0601/lib/jsdom/utils.js#L173

If you return an object that doesn't have a `createCanvas` function it shouldn't have to try to use it.

**Comment by hubgit** [comment]
I was able to work around this by adding `"canvas": "file:./canvas"` to the dependencies section of the app's package.json and creating `canvas/index.js` containing simply `module.exports = {}`.

That was enough to persuade jsdom that canvas wasn't available, after building the app with `@zeit/ncc` (webpack).

**Comment by Slapbox** [comment]
Just wanted to update this to say that doing something like what @hubgit did got me past that error (specifically @molant's recommendation about using Webpack resolve)

Unfortunately thjough jsdom got stuck in an infinite loop and crashed the debugger in some edge cases. I didn't determine the cause and ended up going another route.

**Comment by motoko89** [comment]
@Slapbox can you please share what route did you go to?

**Comment by Slapbox** [comment]
@motoko89, sorry I abandoned this line of work so I don't have anything I can share.

**Comment by intricatecloud** [comment]
Landing here from a google search for this specific scenario - i'm also using webpack with lambda.

The trick is to tell webpack to provide an empty stub of canvas:
```
    externals: {
        ...
        canvas: '{}',
    },
```
Note the quotes around the braces. This creates an empty object. If you use `{}`, you wind up getting an error "Cannot read property 'createCanvas' of undefined".

**Comment by sodijvoisjdvosijdvosi** [comment]
I worked through this issue with webpack just now too and had to use a somewhat different solution for my case. While these issues aren't directly caused by JSDOM code, they are common problems that people run into when compiling. Would it be fair game to create a wiki page for common workarounds so people can fix their problems without needing to reach out for help? Something like that could be linked to in a section the README.

It's one of those problems that falls in between projects so technically nobody really owns it 😦

**Comment by sodijvoisjdvosijdvosi** [comment]
If your use case doesn't ever depend on using `canvas`, the solution I would suggest is to stub it with webpack's null-loader library. The `canvas` dependency should still be kept as a devDependency and the webpack entry will look like:

```js
rules: [
  {
    include: path.resolve(__dirname, "node_modules/canvas"),
    use: "null-loader"
  }
]
```

**Comment by tim-kozak** [comment]
plugins: [
        new webpack.IgnorePlugin(/canvas/)
    ]

**Comment by labuladong** [comment]
> ```
> plugins: [
>     new webpack.IgnorePlugin(/canvas/)
> ]
> ```

The solution should be this now:

```
    plugins: [
        new IgnorePlugin({ resourceRegExp: /canvas/ })
    ]
```

read `IgnorePlugin` document [here](https://webpack.js.org/plugins/ignore-plugin/#example-of-ignoring-moment-locales)
