### ISSUE TITLE
How can I configure jsdom to use default locale?

### ISSUE THREAD

**Issue by BrunoQuaresma** [tmpvar/jsdom#1710]
In my computer the tests running with 'pt-BR' locale. But, in the Circle CI, they are running with 'en-US'. I want that this config be default. 

I try override the navigator.language property but this not works for toLocaleString methods.

**Comment by domenic** [comment]
This is not related to jsdom; this is a Node.js configuration issue. I don't know how to configure the default locale of Node.js, but asking on StackOverflow.com might give you some answers.

**Comment by BrunoQuaresma** [comment]
Thanks @domenic

**Comment by gstvribs** [comment]
Hi @BrunoQuaresma, what's the solution that you did? i currently have the same issue
