### ISSUE TITLE
undefined: HTMLElementImpl

### ISSUE THREAD

**Issue by 928PJY** [tmpvar/jsdom#1713]
Hi, I am doing something which wanted to use jquery in typescript, but I got a problem as followed.
![image](https://cloud.githubusercontent.com/assets/17958546/22235418/89df2486-e23a-11e6-89e8-ee97cc246d11.png)

![image](https://cloud.githubusercontent.com/assets/17958546/22235236/505e7d66-e239-11e6-88be-501a357327f0.png)

when I use jquery to get Html element 'article' or 'body'. their HTMLElement is all undefined and I can't find the reason, do you have some advice?

**Comment by Sebmaster** [comment]
Is there an actual error you're getting? It seems like vscode might just not understand that we hide our implementation in a symbol, which should not affect anything.

**Comment by domenic** [comment]
Please provide a small test case (not a screen shot) that we can run using `node testfile.js` and that produces the error.

**Comment by domenic** [comment]
Closing, happy to reopen if a repro case is provided.
