### ISSUE TITLE
jsdom doesn't preserve whitespace everywhere

### ISSUE THREAD

**Issue by RyanZim** [tmpvar/jsdom#1715]
I don't know if this is intended behavior or not, but if I do:
```js
var jsdom = require("jsdom")
var doc = jsdom.jsdom(
`<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <p>Hello  World!</p>
  </body>
</html>`
)
jsdom.serializeDocument(doc)
```
The result of `serializeDocument` is:
```html
<!DOCTYPE html><html><head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <p>Hello  World!</p>
  
</body></html>
```
Runkit: https://runkit.com/57ebc041d4a27f140028fd78/58893ce66ce5f10014700127

This isn't preserving whitespace outside `body` and `head`. The only reason I care about this is that it makes writing unit tests difficult for tools that use jsdom to manipulate HTML.

**Comment by domenic** [comment]
This is expected. It is how DOMs are serialized: http://jsbin.com/wetuforeya/edit?html,console

**Comment by RyanZim** [comment]
OK, just wondered.
