### ISSUE TITLE
HTML5 history popstate event is not fired on window 

### ISSUE THREAD

**Issue by capaj** [tmpvar/jsdom#1716]
I recently needed to use `window.location` in jsdom and I discovered `jsdom.changeURL(window, 'https://example.com/#someHash')`

Currently it does not trigger a `popstate` event on window, so my subscriber:
```javascript
window.addEventListener('popstate', (ev) => {

})
```

doesn't get notified. Could it get notified?

**Comment by domenic** [comment]
No. Changing the URL is not navigating. You can use dispatchEvent if you want to manually fire events.
