### ISSUE TITLE
First window.setTimeout on the page returns 0

### ISSUE THREAD

**Issue by n1313** [tmpvar/jsdom#1726]
It appears that the first `window.setTimeout` call on a jsdom page returns 0 instead of 1. This breaks code like `if (timeoutID) { window.clearTimeout(timeoutID); }`. Specification says "[return value is] a user-agent-defined integer that is greater than zero" ([W3](https://www.w3.org/TR/2011/WD-html5-20110525/timers.html)), "The returned timeoutID is a numeric, non-zero value" ([MDN](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/setTimeout)).

 If I'm not mistaken, [this line](https://github.com/tmpvar/jsdom/blob/master/lib/jsdom/browser/Window.js#L174) has the bug, it should be `++latestTimerId` instead of `latestTimerId++` (or `latestTimerId` should start from 1).

**Comment by domenic** [comment]
Nice! Pull requests (with tests) welcome.
