### ISSUE TITLE
how to stub values for documentElement.clientHeight?

### ISSUE THREAD

**Issue by tconroy** [tmpvar/jsdom#1729]
It's unclear to me how to stub in values for document.documentElement.clientHeight / clientWidth.

I'm aware that JSDOM does not actually render DOM so this value cannot be dynamically calculated. That is fine. I just need a way to hard code it, as some of my tests rely on reading the value and we do not wish to pull in phantomJS to this project.

Is there a way to set/stub these values? I've tried the following in my mocha test setup, which did not work:

```
global.document = jsdom('', {
  created: function(err, win) {
    if (!err) {
      win.outerWidth = win.innerWidth = 400;
      win.outerHeight = win.innerHeight = 300;
    }
  }
});
// doesn't work, test reads value as '0':
document.documentElement.clientHeight = 300;
document.documentElement.clientWidth = 400;
```

**Comment by domenic** [comment]
You need to use `Object.defineProperty` to change them to be getters returning the value you want. Just like in the browser, they are not assignable. I guess we should consider making this clearer in the readme, as it's common for all getter-only properties (of which there are a lot).

**Comment by tconroy** [comment]
Got it, thank you @domenic. I was under the false assumption that these were being exposed as simple object properties and not getters. 

Thank you! And 👍 to clarifying in the readme.
