### ISSUE TITLE
Illegal Invocation error when used in a  web-worker

### ISSUE THREAD

**Issue by jdthorpe** [tmpvar/jsdom#1732]
When packing jsdom into a webworker via browserify + webworkify, [this line](
https://github.com/tmpvar/jsdom/blob/master/lib/jsdom/browser/Window.js#L494) throws an `Illegal invocation` error.   This can be resolved by setting changing `clearTimeout` to `window.clearTimeout` in [this line](https://github.com/tmpvar/jsdom/blob/master/lib/jsdom/browser/Window.js#L174)

**Comment by domenic** [comment]
Can you give a small example file and the commands needed to run it? I've never used webworkify.

Changing that line would not be correct, as it would cause the timeouts to never be cleared since it's passing the wrong clearTimeout function.

**Comment by jdthorpe** [comment]
Hmm.  Unfortunately I'm starting with a large-ish code base (MathJax) and working backwards.  For what it's worth, the line that is generating this error is [this one](https://github.com/mathjax/MathJax/blob/6273842a9746731b9ecca0de18ec9fd50a36df99/unpacked/MathJax.js#L970),which MathJax [imports via AJAX](https://github.com/mathjax/MathJax/blob/6273842a9746731b9ecca0de18ec9fd50a36df99/unpacked/MathJax.js#L810-L829), and which gets translated to: 

        if (this.loading[file].timeout) {
                window.clearTimeout(this.loading[file].timeout);
        }

and `window.clearTimeout` invokes stopTimer.  However, calling `console.log(timers[1])`  in stopTimeout yields *` function clearTimeout() { [native code] }`*, and chrome complains when binding a native object to the jsdom window object in `timer[1].call(window, timer[0]);`.   

*In the end, the issue is that native timers are being handled by jsdom.*   

I wonder if makes sense to test for native timers before handling them, as in: 

     if ((/\{\s*\[native code\]\s*\}/).test('' + timer[1])){
        /*  timer[1] is a native timer */
     }else{
        /*  timer[1] is a jsdom timer */
     }

Unfortunately, I'm not versed in jsdom well enough to make a good suggestion as to where implement this fix. 

For what it's worth, my strack trace is below...

> Error: TypeError: Illegal invocation
    at Window.stopTimer (blob:null/85dbe41e-2907-4d60-98fc-9d64ea847a5f:64185)
    at Object.loadComplete (MathJax.js:1231)
    at Window.eval (toMathML.js?V=2.7.0:315)
    at Object.exports.runInContext (blob:null/85dbe41e-2907-4d60-98fc-9d64ea847a5f:101919)
    at processJavaScript (blob:null/85dbe41e-2907-4d60-98fc-9d64ea847a5f:96945)
    at HTMLScriptElementImpl._eval (blob:null/85dbe41e-2907-4d60-98fc-9d64ea847a5f:96882)
    at blob:null/85dbe41e-2907-4d60-98fc-9d64ea847a5f:65847
    at Object.check (blob:null/85dbe41e-2907-4d60-98fc-9d64ea847a5f:93074)
    at blob:null/85dbe41e-2907-4d60-98fc-9d64ea847a5f:93093
    at wrappedEnqueued (blob:null/85dbe41e-2907-4d60-98fc-9d64ea847a5f:66071)

**Comment by jdthorpe** [comment]
Ok, I'm pretty sure the correct solution is to change [this line](https://github.com/tmpvar/jsdom/blob/master/lib/jsdom/browser/Window.js#L494) to this: 

    var stopfn = timer[1];
    stopfn(timer[0]);

The reason that the current line fails is that it's setting the wrong context (`window`) for the native `clearTimeout` and `clearInterval` functions, and I'm willing to bet that the purpose of calling the `.call()` method is that calling `timer[1](timer[0])` also results in an Illegal Invocation error due to the fact that the implicit context of `timer[1](...)` is `timer`.

Hence the above solution works by calling the native function without implicitly or explicitly setting the context to a user defined object (i.e. `timer` or `window`).

**Comment by domenic** [comment]
Thanks for the investigation, but it really isn't helpful to suggest lines to change. What we need is a small, preferably 10-20 line reproduction case that we can add to our test suite to ensure that this feature continues to work going forward, and use to debug the best way to proceed.

**Comment by jdthorpe** [comment]
Here's a minimal reproducible example.  Note that it only raises an error when browserified, but not when in the Node.   It's a total edge-case due to the fact that MathJax calls `clearTimeout()` in some of the timer call-backs:

    [example.js]

    var document = require("jsdom").jsdom();
    var window = document.defaultView;
    window.console = console;
    window.addEventListener("error",function (event) {console.error(event.error.stack)});

    var script = document.createElement("script");
    script.type = "text/javascript";
    script.innerHTML = `
    var done = function(){ 
        clearTimeout(t); 
        }
    var t = setTimeout(done,100)
    ` 
    script.onerror = function(err){
        console.error("Script generated the following error:",err)
    }
    document.head.appendChild(script)

Then call: 

    browserify example.js -o bundle.js

then open `example.html` in chrome, firefox, or safari

     [example.html]
        
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title></title>
    </head>
    <body>
        <script src="file:///path/to/bundle.js"></script>
    </body>
    </html>

and something like this will be displayed on the console:

> TypeError: Illegal invocation
    at Window.stopTimer (example-bundle.js:63033)
    at Window.done (about:blank:4)
    at callback (example-bundle.js:63019)
