### ISSUE TITLE
XHR error when working with systemjs

### ISSUE THREAD

**Issue by unional** [tmpvar/jsdom#1733]
I'm working on a plugin system based on systemjs.
I am able to get it working on node and browser, so the config seems to be working.
However, it doesn't work when running test with `jsdom`.

Here is the test code:
```ts
import test from 'ava'

import jsdomify from 'jsdomify'

let createSystemJS
test.before(() => {
  delete require.cache[require.resolve('systemjs')]
  jsdomify.create(`<!DOCTYPE html><html><base href="file://${process.cwd()}/index.html"></html>`)
  createSystemJS = require('./createSystemJS').createSystemJS
})

test.after(() => {
  jsdomify.destroy()
})

test.only(async _t => {
  const sys = createSystemJS('npm-module')
  console.log(sys.getConfig())
  await sys.import('npm-module')
})
```

And the error message:
```sh
  Loading file:///Users/hwong/github/unional/some-issues/plugins/npm-module/package.json
  Unable to fetch package configuration file file:///Users/hwong/github/unional/some-issues/plugins/npm-module/package.json
  Resolving npm-module
  Loading npm-module
    XMLHttpRequest.error (node_modules/systemjs/dist/system.src.js:1456:14)
    invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:210:27)
    EventTargetImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:130:9)
    EventTargetImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:91:17)
    XMLHttpRequest.dispatchEvent (node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:71:35)
    dispatchError (node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:915:9)
    validCORSHeaders (node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:930:7)
    receiveResponse (node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:805:12)
    EventEmitter.client.on.res (node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:626:38)
    process.nextTick (node_modules/jsdom/lib/jsdom/living/xhr-utils.js:96:35)
```

I have verified that when running with `jsdom`, it is calling XHR from there:
https://github.com/systemjs/systemjs/blob/master/src/fetch.js#L41-L92

So it seems like the issue is more likely to be in `jsdom` instead of `systemjs` (as the code work in browser that uses XHR -- tested with Safari).

So it is not related to https://github.com/tmpvar/jsdom/issues/1724
and the file does exists so it is also not related to https://github.com/tmpvar/jsdom/issues/1579

You can see the error in this repo:
https://github.com/unional/some-issues/tree/systemjs-jsdomify

I have created a branch to demo this:

```sh
git clone https://github.com/unional/some-issues.git
cd some-issues
git checkout systemjs-jsdomify
npm install
npm test

# to run the browser code
npm run serve
# and open http://localhost:3000 in the browser and open dev console.
# you should see the logs
```

Node that there is a bug in `systemjs` that preventing the correct error message to be printed (it's fixed and pending for release).
You need to edit `node_modules/systemjs/dist/systemjs.src.js` line 97:
https://github.com/systemjs/systemjs/blob/master/dist/system.src.js#L97

```js
// change
function throwResolveError () {
// to
function throwResolveError (relUrl, parentUrl) {
```

References:
https://github.com/systemjs/systemjs/issues/1581
https://github.com/dmatteo/jsdomify/issues/338

**Comment by Joris-van-der-Wel** [comment]
Sorry, we do not support jsdomify because it uses a hack that can not be made to work standards compliant (DOM spec, HTML spec, etc). Also see https://github.com/tmpvar/jsdom/wiki/Don't-stuff-jsdom-globals-onto-the-Node-global

Does this issue occur without jsdomify?

**Comment by unional** [comment]
Thanks.

Yes, I can reproduce it with just `jsdom`:
```ts
import test from 'ava'
import { readFileSync } from 'fs'
import { jsdom } from 'jsdom'

const systemJSContent = readFileSync(require.resolve('systemjs'), { encoding: 'utf-8' })

const createSystemJSContent = readFileSync(require.resolve('./createSystemJS'), { encoding: 'utf-8' })

let window
test.beforeEach(() => {
  const document = jsdom(`<!DOCTYPE html><html><base href="file://${process.cwd()}/index.html"></html>`)
  window = document.defaultView

  let scriptEl = document.createElement('script')
  scriptEl.textContent = systemJSContent
  document.body.appendChild(scriptEl)

  scriptEl = document.createElement('script')
  scriptEl.textContent = createSystemJSContent
  document.body.appendChild(scriptEl)
})

test(async _t => {
  const sys = window.createSystemJS('npm-module')
  console.log(sys.getConfig())
  await sys.import('npm-module')
})
```

```sh
Promise rejected with: { Error: XHR error:  loading file:///Users/hwong/github/unional/some-issues/plugins/npm-module/package.json
    at XMLHttpRequest.error (about:blank:1456:14)
    at invokeEventListeners (/Users/hwong/github/unional/some-issues/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:219:27)
    at EventTargetImpl._dispatch (/Users/hwong/github/unional/some-issues/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:126:9)
    at EventTargetImpl.dispatchEvent (/Users/hwong/github/unional/some-issues/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:87:17)
    at XMLHttpRequest.dispatchEvent (/Users/hwong/github/unional/some-issues/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:61:35)
    at dispatchError (/Users/hwong/github/unional/some-issues/node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:994:9)
    at validCORSHeaders (/Users/hwong/github/unional/some-issues/node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:1009:7)
    at receiveResponse (/Users/hwong/github/unional/some-issues/node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:871:12)
    at EventEmitter.client.on.res (/Users/hwong/github/unional/some-issues/node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:691:38)
    at emitOne (events.js:96:13)
  originalErr:
   Error: XHR error:  loading file:///Users/hwong/github/unional/some-issues/plugins/npm-module/package.json
       at XMLHttpRequest.error (about:blank:1456:14)
       at invokeEventListeners (/Users/hwong/github/unional/some-issues/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:219:27)
       at EventTargetImpl._dispatch (/Users/hwong/github/unional/some-issues/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:126:9)
       at EventTargetImpl.dispatchEvent (/Users/hwong/github/unional/some-issues/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:87:
17)
       at XMLHttpRequest.dispatchEvent (/Users/hwong/github/unional/some-issues/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:61:35)
       at dispatchError (/Users/hwong/github/unional/some-issues/node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:994:9)
       at validCORSHeaders (/Users/hwong/github/unional/some-issues/node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:1009:7)
       at receiveResponse (/Users/hwong/github/unional/some-issues/node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:871:12)
       at EventEmitter.client.on.res (/Users/hwong/github/unional/some-issues/node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:691:38)
       at emitOne (events.js:96:13) }
  invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:219:27)
  EventTargetImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:126:9)
  EventTargetImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:87:17)
  XMLHttpRequest.dispatchEvent (node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:61:35)
  dispatchError (node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:994:9)
  validCORSHeaders (node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:1009:7)
  receiveResponse (node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:871:12)
  EventEmitter.client.on.res (node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:691:38)
   Error: XHR error:  loading file://plugins/npm-module/package.json
     XMLHttpRequest.error (about:blank:1456:14)
     invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:219:27)
     EventTargetImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:126:9)
     EventTargetImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:87:17)
     XMLHttpRequest.dispatchEvent (node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:61:35)
     dispatchError (node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:994:9)
     validCORSHeaders (node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:1009:7)
     receiveResponse (node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:871:12)
     EventEmitter.client.on.res (node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:691:38)
     emitOne (events.js:96:13) }
```

On the other hand, I'm running my test with `ava`, which provide isolation per test file (it run each test file in separate child process, in parallel).
Would that make it a feasible to use `jsdomify` and `browser-env` as global pollution is less of an issue?
(of course, I 100% agree that global pollution is a bad thing. 🌷 )

**Comment by unional** [comment]
> Would that make it feasible to use jsdomify and browser-env as global pollution is less of an issue?

I ask this because if the test code has deep dependencies (i.e. target -> depA -> depB -> .... -> depN), then I have to add the `<script>` tag manually (or using `jsdom.env({ scripts , src })`) for the whole dependency chain, making the test code couple to dependencies and their dependencies, making the test code fragile.

One workaround for it is to use `systemjs` to load and resolve the dependencies:

```ts
const systemJSContent = readFileSync(require.resolve('systemjs'), { encoding: 'utf-8' })
const doc = jsdom.jsdom()
const window = document.defaultView
const scriptEl = doc.createElement('script')
scriptEl.textContent = systemJSContent
document.body.appendChild(scriptEl)

window.SystemJS.import('...')
```

Of course, that doesn't work on my specific scenario (I'm working on a plugin system that based on `systemjs`, which I do want to load the plugin system outside of `systemjs` to ensure it works correctly in any environment).

**Comment by dmatteo** [comment]
There's one thing I don't understand about your very strong aversion to putting JSOM globals in Node.

> This way, each test creates an entirely new window and document. This contrasts with the very bad approach of mashing various properties of window onto the Node.js global, which causes all these properties to be shared not only across all your tests, but across your entire Node.js process.

The main reason why `jsdomify` was created is because I can `create` and `destroy` the instance in between each test suite, or even in between each individual test.

Doesn't that invalidate your point of "properties to be shared not only across all your tests, but across your entire Node.js process."?

**Comment by Joris-van-der-Wel** [comment]
> The main reason why jsdomify was created is because I can create and destroy the instance in between each test suite, or even in between each individual test.

Well, I do not like to do this because it can be error prone, a library that I use might be caching objects. For example, I may have to muck around with the module cache to workaround this.

But a more important reason is that the method that jsdomify uses is not fully compatible with how the global object works in browsers. Internally jsdom uses the [vm](https://nodejs.org/api/vm.html ) module to get the correct behavior of the global object, although we still have some issues to work out.
(Previously we used contextify for this, which was a binary extension to node.js).

For example:
```javascript
document.body.insertAdjacentHTML('beforeend', '<div id="foo">hello!</div>');
foo.textContent = 'ehlo!';
```
```javascript
const isBrowser = this === this.window;
function sha256(str) {
  if (isBrowser) {
    return crypto.subtle.digest(...);
  }
  else {
    throw Error("TODO: Implement for node.js");
  } 
}
```


I am __not__ saying that jsdomify should never be used. But just that you are aware of the caveats when using it. And that if you submit an issue, to not use it in your test case. Because then we will first have to figure out if the issue was caused by one of these caveats.

**Comment by Joris-van-der-Wel** [comment]
> Yes, I can reproduce it with just jsdom

I think jsdom's cross origin checks are ruining your day. Try this:

```javascript
const document = jsdom(
  `<!DOCTYPE html><html><base href="file://${process.cwd()}/index.html"></html>`,
  {
    url: 'file://${process.cwd()}/index.html' 
  }
)
```

Also, you can use jsdom's virtual console to debug errors like this: 

```javascript
const virtualConsole = jsdom.createVirtualConsole().sendTo(console);
const window = jsdom.jsdom(..., { virtualConsole }).defaultView;
```

**Comment by domenic** [comment]
Note that the `<base>` line *should* be redundant if you've set the `url` option as above.

**Comment by unional** [comment]
Yes, it is cross origin.


> Note that the <base> line should be redundant if you've set the url option as above.

Yes too:

```ts
  const document = jsdom('',
    {
      url: `file://${process.cwd()}/index.html`
    })
```

And thanks for the `virtualConsole` tips.
