### ISSUE TITLE
9.11.0 offsetX work arounds

### ISSUE THREAD

**Issue by blainekasten** [tmpvar/jsdom#1736]
Hey guys, 9.11.0 created a problem with some of my tests. My code does math based on sizes of dom nodes. I was previously able to do something like

```js
node.offsetTop = 100;
```

Now, I'm just getting errors about not having setters. Is there way you are aware of me being able to work around this? For now I'm hard fixing to 9.10.0.

Thanks so much for this library. It is truly great!

**Comment by domenic** [comment]
How would you do this in browsers, where offsetTop is not settable?

**Comment by blainekasten** [comment]
In browsers I don't need to do this as they will have their real value. But this is specifically for unit tests around ReactComponents

**Comment by Sebmaster** [comment]
`Object.defineProperty` should be able to help you out in these cases.

**Comment by amannn** [comment]
What's the correct way to achieve this with `Object.defineProperty`?

I've tried the following, but it creates an infinite loop (which makes sense):

```js
const node = document.createElement('div');
Object.defineProperty(node, 'offsetTop', {
  set(value) {
    this.offsetTop = value;
  }
});
node.offsetTop = 100;
```

Hardcoding the property on the global `HTMLElement` is also not quite what I want.

**Comment by Sebmaster** [comment]
```js
Object.defineProperty(node, 'offsetTop', {
  value: 100
});
```
should work.
