### ISSUE TITLE
Is it possible to use `file://` URL without "index.html"?

### ISSUE THREAD

**Issue by unional** [tmpvar/jsdom#1738]
I want to use `file://` URL and currently this is what I'm doing:

```ts
import { env } from 'jsdom'

env({
  file: 'index.html',
  done(err, win) {
    ...
  }
})
```

This works but it requires to have an actual `index.html`.
Is it possible to make it work without the actual file?

I've created [`global-test-harness`](https://github.com/unional/global-test-harness) which I don't want the consuming code to create a dummy `index.html` for this purpose.

Thanks.

**Comment by Joris-van-der-Wel** [comment]
Try this:

```javascript
jsdom.env({
  html: `<div class="foo">hello world</div>`,
  url: 'file:///foo/bar',
  done(err, win) {
    ...
  }
})
```
In this example the `html` property is what ends up as being unserialized into DOM. And the `url` property is only used for things like `location.href`, resolving, relative urls, cross origin checks, etc.

**Comment by unional** [comment]
Thanks.

It error with `ENOENT: no cush file or directory, open 'file:///foo/bar'`

**Comment by unional** [comment]
Thanks.

That behaves differently and breaking some tests.
I use `systemjs` inside `jsdom` to load the files, and with this setting, it errors with: `ENOENT: no such file or directory, open '/foo/fixtures/...'`

What happens is when `url: file:///foo/var` is specified, `systemjs` resolves to do xhrFetch with url `file:///foo/<file path>`.

When using `file: 'index.html'`, `systemjs` call xhrFetch with url: `file::///Users/..../global-test-harness/<file path>`. i.e. it resolves to the absolute path.

**Comment by unional** [comment]
So the solution is:

```ts
env({
  html: '<div></div>'
  url: `file:///${process.cwd()}/`
  ...
})
```

Thanks!
