### ISSUE TITLE
Strange behavior setting properties on window

### ISSUE THREAD

**Issue by brandonweiss** [tmpvar/jsdom#1739]
A month or two ago I made a small [library](https://github.com/brandonweiss/sonar-js/) and used jsdom for the tests. I just went back to it today to make an improvement and noticed my tests were failing, which was really weird. I hadn't changed anything. The Node version is the same and all the dependencies are locked via yarn.

After stepping through everything I eventually figured out that one of the properties I'm setting on window (innerHeight) isn't being set anymore. I was doing this:

```javascript
let createWindow = (options = {}) => {
  let document = jsdom.jsdom("<html><body></body></html>")
  let window = document.defaultView

  window.document.body.offsetHeight = options.pageHeight
  window.innerHeight = options.windowHeight

  return window
}
```

In each test I pass in a `pageHeight` and a `windowHeight`. The page height gets set but the window height does not. It won't change from the default of `768`. I'm super confused. I have no idea how this could have worked before but not now, even though nothing has apparently changed?

**Comment by Sebmaster** [comment]
Try doing the assignment twice? You might be hitting a known node bug here.

**Comment by brandonweiss** [comment]
Wow. That might be it. If I set it once 3 of 8 tests fail. Set it twice and 2 of 8 fail. But setting it three times doesn't decrease the number of failures.

**Comment by domenic** [comment]
This was a Node.js bug that was fixed in recent versions, thankfully. Please try the latest Node.js; it should be better now.

**Comment by brandonweiss** [comment]
Thanks!
