### ISSUE TITLE
querySelectorAll fails with single character attributes

### ISSUE THREAD

**Issue by AStoker** [tmpvar/jsdom#1740]
I have a document fragment that I'm testing which contains the following code: 
``` html
<h1 t="construction.title">Pardon the potholes, site is under construction</h1>
```
I'm using the i18n plugin in my project, and therefore the `t` attribute is used to flag down the title of what we are going to translate (it's the key to use).  
When I use `window.document.querySelectorAll('[t]');`, I get an error 
```
SyntaxError
    at DocumentImpl.<anonymous> (/Users/astoker/Documents/Github/AStoker/astoker.github.io/node_modules/jsdom/lib/jsdom/living/nodes/ParentNode-impl.js:83:11)
    at DocumentImpl.querySelectorAll (/Users/astoker/Documents/Github/AStoker/astoker.github.io/node_modules/jsdom/lib/jsdom/utils.js:133:45)
    at Document.querySelectorAll (/Users/astoker/Documents/Github/AStoker/astoker.github.io/node_modules/jsdom/lib/jsdom/living/generated/ParentNode.js:39:62)
    at eval (eval at evaluate (:117:21), <anonymous>:1:22)
    at Object.done (/Users/astoker/Documents/Github/AStoker/astoker.github.io/aurelia_project/tasks/process-locales.js:54:57)
    at process.nextTick (/Users/astoker/Documents/Github/AStoker/astoker.github.io/node_modules/jsdom/lib/jsdom.js:320:18)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

This works fine when I use the `i18n` attribute `window.document.querySelectorAll('[i18n]');`. Not sure what is going on... 
What I'm doing. Using gulp to go through files, and the files are all html fragments wrapped in `<template>` tags.
``` javascript
jsdom.env(
                    `<html><body>${file.contents.toString()}</body></html>`, //Wrapping in html/body for fragments to be loaded
                    function(err, window) {
                        if (err) {
                            console.log('Trouble making the window for scraping');
                            console.log(err);
                        }
                        //Create "Template" in body
                        let t = window.document.querySelector('template');
                        let tInstance = window.document.importNode(t.content, true);
                        window.document.body.appendChild(tInstance);

                        //Other strange bug with querySelectorAll and passing multiple selectors (querySelectorAll('[i18n], [t]');). So we're going to make two seperate calls
                        let i18nElements = window.document.querySelectorAll('[i18n]'); //Works
                        let tElements = window.document.querySelectorAll('[t]'); //Fails
...
```

**Comment by AStoker** [comment]
Seems that the selector (`[t]`) when matched with the `reValidator` is returning an empty set, when it should be returning `t`...

**Comment by AStoker** [comment]
Bump, anybody see this issue/working on it?

**Comment by AStoker** [comment]
Additional details, it seems that any querySelectorAll with attributes with a single character return an empty string in the `reValidator` regex

**Comment by domenic** [comment]
https://twitter.com/slicknet/status/782274190451671040

**Comment by AStoker** [comment]
Appreciate it 😃 
That's why I asked if anybody else had even seen it too. Some people tend to see an issue work on it, and then comment back, so I was just probing. 
It's an annoying bug right now, and interpreting the massive regex is a pain, but it's probably just a regex change that needs to be made.

**Comment by domenic** [comment]
Yeah, a PR would definitely be welcome!

**Comment by AStoker** [comment]
As soon as I figure out what the heck kind of Regex this sucker is, and then manage to fix it, I'll make a PR for sure. Regex's aren't quite my forte though, so I was _hoping_ I wasn't the only one suffering, and someone could help out :P But I understand the time crunch and full plates of issues that repo managers have to deal with on open source projects.

**Comment by AStoker** [comment]
Looks like it's a bug on a dependency (nwmatcher) that doesn't allow single character attributes.

**Comment by dperini** [comment]
I will have a look into this asap to hunt the described problem in "nwmatcher".
Did you test this in a browser using "querySelector/querySelectorAll" ?
Does the same test work in Chrome and Firefox ?
Thank you for reporting !

**Comment by AStoker** [comment]
@dperini, it was tested using Node v6.9.0 (as that was the target platform for this plugin), so I'm not sure if it works in Chrome or Firefox. But from what I've seen in the regex, I'd imagine that it would be duplicated in all browsers. To test specifically the regex out a bit more thoroughly, I used an online tool called debuggex to test out how it would behave in browsers (tested in Safari and Chrome, both had the same problem).

**Comment by dperini** [comment]
@AStoker your testing and suggestion are correct. I already pushed a fix for this in "nwmatcher".
Next release will be 1.4.0, I just need to run all tests to ensure the change has no negative effects.
Thank you again for the help in hunting this bug.

Fixed issue #1740 here: https://github.com/dperini/nwmatcher/commit/7bd5c68

**Comment by AStoker** [comment]
@dperini perfect, thanks. Any idea on when 1.4.0 will be released?
Once it's released @domenic, it's probably worth while to update the `package.json` here to ensure that it has at least 1.4.0. If you're good with that, then I'll make a small PR to upgrade the package file once 1.4.0 is released, at which point when it's merged we can close this issue.

**Comment by dperini** [comment]
@AStoker I was trying to add a few other tweaks but failed ...
I will try once more with those tweaks next week.
 then I will release 1.4.0.

**Comment by AStoker** [comment]
@domenic, thanks to the update in nwmatcher, we should be good with just updating the package.json to bump up the minimum version. https://github.com/tmpvar/jsdom/pull/1869

**Comment by dperini** [comment]
This issue have been fixed ... should it be closed ?
