### ISSUE TITLE
Not working correctly with Mongoose and Jest

### ISSUE THREAD

**Issue by jozsi** [tmpvar/jsdom#1752]
I've created a repository to describe and reproduce the bug: https://github.com/jozsi/bug-jest-mongoose#bug

Briefly: if I try to run a specific method of `Mongoose`, it doesn't work if `Jest` is using it's default `jsdom` environment, however it does under the `node` environment`.

What could be the culprit of the inconsistency, `jsdom` or `Mongoose`?

See: https://github.com/facebook/jest/issues/3045

**Comment by i8-pi** [comment]
The [mongodb module](https://github.com/mongodb/node-mongodb-native/blob/V2.2.24/lib/utils.js#L208) tests if something is an object using
```javascript
'[object Object]' == toString.call(arg)
```
which is not always reliable

In browsers and jsdom, doing this to the global object gives `[object Window]`, which is causing the `parseIndexOptions` function just above that line of code to behave differently in jsdom and node

**Comment by vkarpov15** [comment]
Mongoose maintainer here, can confirm that @i8-pi is correct. I'll open up a PR in the mongodb driver to fix this :+1: wish I'd read your comment earlier, would've saved me 45 mins of debugging :)

**Comment by jozsi** [comment]
Thank you @vkarpov15 for fixing it. The fixed versions are:
- mongoose v4.9.1
- node-mongodb-native v2.2.25
