### ISSUE TITLE
rendering react-highcharts with mount enzyme and jsdom gives an InvalidCharacterError

### ISSUE THREAD

**Issue by hyalkaf** [tmpvar/jsdom#1753]
Sorry if this is not the right place to post about this but it seems that the error I'm getting is from jsdom. I have posted a question in [StackOverflow](http://stackoverflow.com/questions/42587215/rendering-react-highcharts-with-mount-enzyme-gives-an-invalidcharactererror) about this as I'm not sure where to look for help. The issue that I have happens when I try to render a component that has [react-highcharts](https://github.com/kirjs/react-highcharts) as a child using enzyme mount method. an Invalid Character Error is thrown. Here is a [repo](https://github.com/hyalkaf/react-highCharts-enzyme-issue). You will need to do `npm run test-mocha` to see the error.

Thank you.

**Comment by domenic** [comment]
Thanks for the report. However we don't generally have the time to debug interactions with third-party packages. If you can produce a small repro that doesn't have any external dependencies (e.g. no Mocha, no Enzyme, just loading scripts into jsdom) this will be something we can investigate.
