### ISSUE TITLE
construct jsdom with exists parse5 document

### ISSUE THREAD

**Issue by tugrul** [tmpvar/jsdom#1755]
http://inikulin.github.io/parse5/classes/parserstream.html

I wanted to pass document object by parser stream. 

Is there a way to push document object to jsdom environment?

**Comment by Sebmaster** [comment]
No, jsdom doesn't support he parse5 stream at all (yet), so it's nothing we could even easily add. You'll have to serialize the document and then provide the resulting string to jsdom.
