### ISSUE TITLE
Issues with iframes

### ISSUE THREAD

**Issue by sted** [tmpvar/jsdom#1758]
In my environment (macOS 10.12, node.js 7.4.0) I'm seeing problems with iframes.

In particular: 
- the event notification via the frame.onload doesn't work but it works with frame.addEventListener('load', ...)
- it does not seem that the correct chains from the loaded iframe window to parent, top and frameElement are set

The tests seem in some way to confirm this:

`window/frame.js: FF.....FFF.FF.
`

It is something known? 
Do you need that I investigate more on the issue?

**Comment by domenic** [comment]
I think this is a known issue with Node v7.4.0 that was fixed in Node v7.5.0. Can you try upgrading?

I wonder if there's a way we can warn about this. Maybe just in the readme if nothing else.

**Comment by sted** [comment]
Hello Domenic, just upgraded to 7.7.1 and everything works.
Out of curiosity, any ideas about what caused these very specific issues?
Thank you very much,
Stefano

**Comment by domenic** [comment]
It was https://github.com/nodejs/node/issues/10806
