### ISSUE TITLE
Option constructor support

### ISSUE THREAD

**Issue by NAlexPear** [tmpvar/jsdom#1759]
As far as I can tell, `jsdom` does not support the [Option constructor](https://html.spec.whatwg.org/#dom-option) as expected. The `document.createElement()` version seems to work fine, and is generally my preference anyway, but both should be available according to the WHATWG spec.

My expectation would be that the `Option` constructor would be available directly from the `window`, as it is in Chrome and Firefox latest. 

To test:
```
var window = jsdom.jsdom().defaultView;

console.log( window.Option ); // undefined, expect HTMLOptionElement constructor
```

I suspect that this issue might be fixed in #1723, as well, but I wanted to make sure that this was documented or addressed!

**Comment by domenic** [comment]
Good catch. This would be a fairly easy thing to fix as a PR if you're interested. You'd insert the code aronud https://github.com/tmpvar/jsdom/blob/2161116160f81d93c2891e9290fc74d6b5f6188b/lib/jsdom/browser/Window.js#L187 based on the spec at https://html.spec.whatwg.org/#the-option-element and https://html.spec.whatwg.org/#dom-option. You'd add to-upstream web platform tests as well.
