### ISSUE TITLE
Local scripts won't run at all on Mac

### ISSUE THREAD

**Issue by ramtinsoltani** [tmpvar/jsdom#1765]
I'm using the following code on both a Windows machine and a Macbook in Node.js environment (with no module loaders of any kind):

```
var jsdom = require('jsdom');

module.exports = function(url, inject, injectPath) {

  var jsdomConfig = {};

  jsdomConfig.url = url;
  jsdomConfig.scripts = [`${__root}lib/jquery.js`];

  if ( inject ) jsdomConfig.scripts.push(injectPath);

  jsdomConfig.done = function(error, window) {

    // Expecting all the scripts to be executed
    console.log(window.$ === undefined); // Prints true

  };

  jsdom.env(jsdomConfig);

};
```

`_root` resolves to the project path (example: `C:/myproject/`).

The code runs perfectly on my Windows machine and the console.log prints `false`. However, on my Macbook it prints `true`.

I've tried all the suggested fixes (waiting for `window` to finish loading, etc.) but as long as the scripts are local, they never run on my Macbook.

I tried using a URL to load jQuery and it works! When I change the 5th line to `jsdomConfig.scripts = ['https://code.jquery.com/jquery-3.1.1.min.js'];` the console.log prints `false` in both my Macbook and the Windows machine. So I came up with a workaround (since the code is part of an Express.js webservice) and added a route to serve my local files using `res.download()` method. So instead of adding the local path of jQuery, I used something like `http://localhost:8000/jquery` and got it loaded when `done()` is called. Used the same method for other scripts passed to the function and they all work too.

But this adds unnecessary time to the whole process and I assume the downloaded file should be saved temporarily somewhere, so it occupies unnecessary space.

> `window` will be a fully-loaded window, with all external resources downloaded and `<script>`s executed.

...quoting from the [documentation](https://github.com/tmpvar/jsdom#doneerror-window). Clearly that is not happening!

Any ideas why local scripts are not executed when `done()` is called as opposed to non-local scripts and why is it Mac specific?

**Comment by Sebmaster** [comment]
You need to provide a full URL to scripts. That includes the protocol.

**Comment by ramtinsoltani** [comment]
The exact same code works on Windows but it doesn't work on Mac. The file path when running on Mac resolves to something like this `/Users/ramtin/myproject/lib/jquery.js`. What am I doing wrong?

**Comment by Sebmaster** [comment]
> That includes the protocol.

scripts does not accept file paths. scripts only accepts URLs and you're not providing a URL to a file path, but a relative URL.

**Comment by ramtinsoltani** [comment]
But why does it work on Windows when I provide a local path? If I add `C:/myproject/lib/jquery.js` to `jsdomConfig.scripts` it works.

Would `file:///Users/ramtin/myproject/lib/jquery.js` work on Mac?

**Comment by Sebmaster** [comment]
> But why does it work on Windows when I provide a local path?

That might actually be a bug. It seems like we're assuming that the protocol in that URL is "C:" and the rest is a data-segment and then at a lower level we just check if a file on that path exists (which will return false for all http:// URLs). Haven't checked if that's actually the case though.

> Would file:///Users/ramtin/myproject/lib/jquery.js work on Mac?

Yes.

**Comment by ramtinsoltani** [comment]
This part of the documentation is a little bit misleading:
>`scripts`: a string or array of strings, containing file names or URLs that will be inserted as `<script>` tags
Since it says `file names or URLs` I assumed that I can just add local paths to it. If `file:///` would be included as a hint in the documentation it surely saves a lot of confusion.

Thanks for your help. I'll be using `file:///` to load local-hosted libraries/scripts.

**Comment by Sebmaster** [comment]
Ah I see. There's some logic to try to make it work with file paths, but that seems to only work for windows, I guess.

**Comment by ramtinsoltani** [comment]
Just tried the `file:///` approach on both Windows and Mac and it works perfectly. Thanks for the help @Sebmaster .

**Comment by domenic** [comment]
Be sure to try the new v10 API documented in the readme, which should make things much clearer! There you can inject script tags the normal way, using `document.createElement("script")` for example.
