### ISSUE TITLE
external scripts aren't executed

### ISSUE THREAD

**Issue by ccorcos** [tmpvar/jsdom#1770]
I'm trying to use jsdom for server-side rendering. I've been toying around all afternoon and I cant seem to get the external scripts to run.

Here's what I have so far:

```js
jsdom.env({
	html: fs.readFileSync(`${clientStaticDir}/index.html`, "utf-8"),
	headers: req.headers,
	features: {
		FetchExternalResources: ["script", "frame", "iframe", "link", "img"],
		ProcessExternalResources: ["script"],
		SkipExternalResources: false
	},
	resourceLoader: function (resource, callback) {
		if (resource.url.href.startsWith("/")) {
			callback(null, fs.readFileSync(`${clientStaticDir}${resource.url.href}`, "utf-8"))
		} else {
			resource.defaultFetch(callback)
		}
	},
	done: function (err, window) {
		if (err) {
			console.error(err)
			res.sendFile("index.html", { root: clientStaticDir })
		} else {
			const output = jsdom.serializeDocument(window.document)
			console.log("!SSR", output)
			res.sendFile("index.html", { root: clientStaticDir })
			window.close()
		}
	},
})
```

I've verified that the resourceLoader is working and returning the webpack bundle, but it doesnt seem to be executing the JavaScript.

I have no idea what else to try. I'd appreciate any help. Thanks

**Comment by domenic** [comment]
Can you create a small example we can run to reproduce the problem, preferably much smaller than this, and which actually works instead of referring to undefined variables like `clientStaticDir`?

**Comment by ccorcos** [comment]
Hey @domenic, it turns out that there were exceptions that were garbled up. I had to use the `virtualConsole` options to see them. Any reason these exceptions don't bubble up?

**Comment by domenic** [comment]
Well, we can't bubble them up since the calls should not throw an exception. But we could write them to the console. We thought it was a bad idea to write to peoples' consoles without being asked. But for v10 we will start doing so by default in the new API.

**Comment by ccorcos** [comment]
Here's my little miniature example: https://github.com/ccorcos/rURL

You'll notice that `rurl http://www.chetcorcos.com/cube/` works fine compared to `curl http://www.chetcorcos.com/cube/` which doesn't execute the JavaScript.

But when you try to use this on non-trivial applications, you get errors. For example:

- `rurl https://www.notion.so/Demo-a332b2ac58c040ce8f82422e95c99449`
- `rurl http://todomvc.com/examples/react/`

In regards to the original issue, the error was just getting garbled up, so this issue is solved. But I'm still curious if you have any input on this `rURL` demo and making it more robust.
