### ISSUE TITLE
Window.Uint8(Clamped)Array

### ISSUE THREAD

**Issue by Janggwan** [tmpvar/jsdom#1771]
I'm modifying 'jsmpeg' code to run on nodejs as well as browser.
But I got the following error.
```
/home/janggwan/Desktop/Dev/node-rtsp-stream-es6/node_modules/jsmpeg/jsmpg.js:765
        this.currentY = new MaybeClampedUint8Array(this.codedSize);
                        ^

TypeError: MaybeClampedUint8Array is not a constructor
    at module.exports.jsmpeg.initBuffers (/home/janggwan/Desktop/Dev/node-rtsp-stream-es6/node_modules/jsmpeg/jsmpg.js:765:18)
```

and the corresponding code is
``` 
        var MaybeClampedUint8Array = window.Uint8ClampedArray || window.Uint8Array;
        if (!window.Uint8ClampedArray) {
                this.copyBlockToDestination = this.copyBlockToDestinationClamp;
                this.addBlockToDestination = this.addBlockToDestinationClamp;
        }

        // Allocated buffers and resize the canvas
        this.currentY = new MaybeClampedUint8Array(this.codedSize);
```

It seems that both Window.Uint8ClampedArray and Window.Uint8Array are undefined? or something wrong.

I used jsdom in the following way.

```
var jsdom = require("jsdom").jsdom;
var document = jsdom("<html><canvas id='videoCanavs'></canvas></html>");
```

How can I proceed with this situation?

**Comment by domenic** [comment]
Can you provide a more complete repro? Something I can run with `node test.js`. Ideally it should not involve third party libraries, so if you could extract the portion of the jsmpeg code that doesn't work and inline that into the repro, that would be helpful.
