### ISSUE TITLE
Compiling Chromium implementations to WebAssembly

### ISSUE THREAD

**Issue by lastmjs** [tmpvar/jsdom#1772]
Eventually Node.js and all major browsers will support running WebAssembly code. What are the issues with compiling the relevant DOM and HTML C++ implementations already in Chromium to WebAssembly? If that is feasible, I see that as a much better alternative to continuing to implement the DOM and HTML specs in JavaScript. Why implement these things twice? 

With that future in mind, what if jsdom became the JavaScript interface to the WebAssembly compilation of all of the relevant APIs that jsdom wants to support? If code size is an issue, jsdom could support some kind of module or plugin system that easily allows compiled web APIs to be imported into your project, while jsdom itself would be the core interface to the basic HTML and DOM compilations.

**Comment by domenic** [comment]
Well, it would be tens of megabytes, for one, and require a bunch of platform specific APIs...

This is not a direction jsdom is interested in. If you're interested in starting your own project in that direction though, feel free!

**Comment by rjy7wb** [comment]
why not just compile the whole browser into webassembly, then run it within itself?

**Comment by Stvad** [comment]
Came here by searching for something like this (DOM implementation in WASM, to use in service workers for browser extension 😅). @lastmjs @rjy7wb lmk if you've seen some developments towards this anywhere else!
