### ISSUE TITLE
MutationEvent.js reference to not existing MutationEvent-impl.js Webpack compiler fails 9.12.0

### ISSUE THREAD

**Issue by saschal-j5int** [tmpvar/jsdom#1773]
Hello,

I use jsdom for svg generation and I compile it with webpack to one file. The webpack compiler fails with following error:

`ERROR in ./~/jsdom/lib/jsdom/living/generated/MutationEvent.js
    Module not found: Error: Cannot resolve 'file' or 'directory' ../events/MutationEvent-impl.js in /home/test/work/git/j5-framework/j5/src/webui/node_modules/jsdom/lib/jsdom/living/generated
     @ ./~/jsdom/lib/jsdom/living/generated/MutationEvent.js 174:13-55
`
I checked different versions of jsdom and until version 8.5.0 the missing MutationEvent-impl.js was still in the package. From version 9.0.0 it disappears. From version 9.0.0 MutationEvent.js is also not reference anymore in jsdom/living/index.js. But the file is still in the npm package under living/generated/MutationEvent.js

I assume it has been removed at some stage but the "npm run convert-idl" doesn't clean the "generated" folder?

In current version 9.12.0 the file ' MutationEvent.js' is still in the npm package.

**Comment by domenic** [comment]
Yeah, we probably have some leftover files in the package. You should probably use a bundler tool like browserify which determines the files by crawling the dependency graph, instead of one like webpack which apparently just looks at whatever is on the filesystem. That's a bad strategy which we don't support.

**Comment by saschal-j5int** [comment]
Hi thanks for the response.

Unfortunately it is currently not possible to switch to another bundler tool for me since I only contribute to a project. As far as I understood the webpack docs also tries to build the dependency graph. But if any of the used modules uses an expression in an import statement like require(var_name) then webpack tries to parse all files to insure that on runtime every possible module is available. 
I also got the following erros which probably caused the problem:

>     WARNING in ./~/jsdom/lib/jsdom/utils.js
>     Critical dependencies:
>     216:21-40 the request of a dependency is an expression
>      @ ./~/jsdom/lib/jsdom/utils.js 216:21-40
>     
>     WARNING in ./~/jsdom/lib/jsdom/living/xmlhttprequest.js
>     Critical dependencies:
>     20:23-30 require function is used in a way in which dependencies cannot be statically extracted
>      @ ./~/jsdom/lib/jsdom/living/xmlhttprequest.js 20:23-30

I found a working "fix" by running a plugin function before webpack compiles that deletes the file if existing. This is not the best solution but works for me.

In webpack.config.js
```
plugins: [
  function() {
      this.plugin("compile", function(stats) {
        var file = path.join(__dirname, 'node_modules/jsdom/lib/jsdom/living/generated/MutationEvent.js')
        if (fs.existsSync(file))
          fs.unlinkSync(file)
      })
    },
]
```

However I would recommend to run a clean up function before the release to insure that there are no leftovers which increases the size of the package unnecessary.

**Comment by saschal-j5int** [comment]
I even found a simpler solution. I am using the ignore-loader to ignore this file:

module: {
   loaders: [
       //...
       {test: /node_modules[\/\\]jsdom[\/\\]lib[\/\\]jsdom[\/\\]living[\/\\]generated[\/\\]MutationEvent\.js$/, 
        loader: "ignore-loader"},
  ]
}

see [npm ignore-loader](https://www.npmjs.com/package/ignore-loader)

**Comment by domenic** [comment]
Fixed now, and probably in a way that won't reoccur :)

**Comment by saschal-j5int** [comment]
Create thanks
