### ISSUE TITLE
document.implementation.createHTMLDocument behaves differently than browser

### ISSUE THREAD

**Issue by gavinwahl** [tmpvar/jsdom#1779]
draft-js has this code in it (paraphrased):

```javascript
function getSafeBodyFromHTML(html) {
  doc = document.implementation.createHTMLDocument('foo');
  doc.documentElement.innerHTML = html;
  return doc.getElementsByTagName('body')[0];
}
```

In Chrome 56 and Firefox 45, `getSafeBodyFromHTML('')` returns an HTMLBodyElement. In jsdom 9.12.0, it returns undefined. `getSafeBodyFromHTML('foo')` does return an HTMLBodyElement like it's supposed to.

You can reproduce this in node with this code:

```javascript
> var jsdom = require('jsdom').jsdom;
> var document = jsdom();
> function getSafeBodyFromHTML(html) {
...   doc = document.implementation.createHTMLDocument('foo');
...   doc.documentElement.innerHTML = html;
...   return doc.getElementsByTagName('body')[0];
... }
> getSafeBodyFromHTML('')
undefined
> getSafeBodyFromHTML('asdf')
HTMLBodyElement {}
```

**Comment by domenic** [comment]
Just wanted to say great catch, and thanks for the very small repro (this is a model of what we like to see, no external frameworks or anything). That makes it much more likely we can address this soon, although I am in Tokyo for the next couple weeks so my weekends are not as free for open source as usual. A PR would be much appreciated if you want to help dig into it.

**Comment by domenic** [comment]
Fixed by https://github.com/tmpvar/jsdom/pull/1787
