### ISSUE TITLE
jsdom.env HTML doesn't have access to window?

### ISSUE THREAD

**Issue by brunops** [tmpvar/jsdom#1785]
Sorry if this is a duplicate, but couldn't find this in open or closed issues.

This is the simplest example I could come with, seems like a very simple use case

```js
  // ...
  it('defines `window.foo`', done => {
      jsdom.env(
        '<script>window.foo = 123;</script>',
        [],
        (err, window) => {
          if (err) {
            return done(err)
          }

          assert.equal(window.foo, 123)
          done()
        }
      )
  })
```

This gives me `Uncaught AssertionError: expected undefined to equal 123`. I also tried playing with `onload`, `done` and `setTimeout`s to try to make this work but got the same error all the time.

Isn't this a valid use case?

**Comment by brunops** [comment]
Although I'd rather use the previous example code, I was able to make it work with a different signature:

```js
  it('defines `window.foo`', done => {
    jsdom.env({
      html: '',
      src: 'window.foo = 123;',
      done: (err, window) => {
        if (err) {
          return done(err)
        }

        assert.equal(window.foo, 123)
        done()
      }
    })
  })
```

Is that the expected behavior?

**Comment by Sebmaster** [comment]
jsdom.env has on-page scripting disabled by default. You'll need to use `features.ProcessExternalResources`.

**Comment by brunops** [comment]
This works too

```js
jsdom.env(
  '<script>window.foo = 123;</script>',
  { features: { ProcessExternalResources: [ 'script' ] } },
  (err, window) => {
    assert.equal(window.foo, 123)
    done()
  }
)
```

Seems to be as designed, so I'm closing this, thanks @Sebmaster
