### ISSUE TITLE
The implementation of properties.client.on("data", chunk) in xmlhttprequest.js may cause performance problem in some cases.

### ISSUE THREAD

**Issue by skygon** [tmpvar/jsdom#1786]
Currently, I have encountered some performance problem when using jsdom to load some plain data. Here is some code snippet about how I load data:
``` javascript
eventEmitter.on('doSomething', doSomething);

jsdom.env({
  url : http://somewhere.com,
    features : {
        FetchExternalResources : ['script'],
        ProcessExternalResources : ['script']
    },
    done : function (error, window) {
      eventEmitter.emit('doSomething', window);
    }
});

function doSomething(w){
   /*
   Here will invoke function from window, like w.fetchData().  
   */
    w.fetchData();
}
```
The function fetchData from http://somewhere.com basically just uses jquery to load a CSV file. like :
```javascript
var uri = "./files/test.csv";
$.get(uri,function(response){
   /*omit implementation*/
}
```
In my test, loading a 150MB csv file will cost about **6 minutes** and use **1.5GB** memory. By using the  node profiling options, --prof and --prof-process, I got the following information:
```
 ticks    parent    name
41381 89.3% C:\Program Files\nodejs\node.exe
37253 90.0%      C:\Program Files\nodejs\node.exe
31658 85.0%           LazyCompile: ~Buffer.concat buffer.js:293:25
29548 93.3%                 LazyCompile: *properties.client.on.chunk node_modules\jsdom\lib\jsdom\living\xmlhttprequest.js:879:34
```
The above section told us that in the active ticks of node.exe, Buffer.concat costs about 85% ticks,  which happens at ```jsdom\lib\jsdom\living\xmlhttprequest.js:879```.

Here is the code snippet  around line 879 in xmlhttprequest.js:
```javascript
properties.client.on("data", chunk => {
    properties.responseBuffer = Buffer.concat([properties.responseBuffer, chunk]);
    properties.responseCache = null;
```	

Every time chunk comes,  properties.responseBuffer will be replaced with a new buffer, which is composed by the old properties.responseBuffer and the new arrived chunk. And the old responseBuffer will be left as so called 'garbage'. In order to test how frequently Buffer.concat is invoked, I added the following debug log into the above code:
```javascript
properties.client.on("data", chunk => {
    properties.responseBuffer = Buffer.concat([properties.responseBuffer, chunk]);
    //debug log. properties.count is defined previously and initialized to 0.
    properties.count += 1; 
    console.log("Times of buffer.concat: ", properties.count);
    console.log("Current buffer size: ", properties.responseBuffer.length);
```
And tested to get a 50MB csv file, here are the last few records:
```
Times of buffer.concat: 1823
Current buffer size: 53290356
Times of buffer.concat: 1824
Current buffer size: 53322476
Times of buffer.concat: 1825
Current buffer size: 53331314
```
That means **1800+** times of Buffer.concat, which will create tremendous number of un-referenced buffers. The clean of those buffers only rely on garbage collection. If the run environment of node thinks there is no need to clean those buffers, then rss will keep growing. ***And another important thing is that so many buffers's creation will cost lots of time.***

I also simply tested the performance by using pre-allocate responseBuffer, and using copy instead of concat. Both time code and memory usage will be reduced a lot. Here is some code snippet:
```javascript
//properties.responseBuffer = new Buffer(0);
properties.responseBuffer = Buffer.alloc(properties.bufferSize);
```
Pre-allocate responseBuffer, in my test, properties.bufferSize is 100MB. 

Then, handle received chunks as :
```javascript
properties.client.on("data", chunk => {
//properties.responseBuffer = Buffer.concat([properties.responseBuffer, chunk]);
properties.totalChunkSize += chunk.length;

if (properties.totalChunkSize >= properties.bufferSize){
    properties.bufferSize *= 2;
  while(properties.totalChunkSize >= properties.bufferSize){
      properties.bufferSize *= 2; 
  }
    var tmp = Buffer.alloc(properties.bufferSize);
    properties.responseBuffer = Buffer.concat([properties.responseBuffer, chunk])
    tmp.copy(properties.responseBuffer, properties.responseBuffer.length);
    properties.responseBuffer = tmp;
}
else{
  chunk.copy(properties.responseBuffer, properties.totalChunkSize - chunk.length, 0, chunk.length);
}
```
Instead of Buffer.concat, use buffer.copy , which will not create new buffer. If received chunk size is large current buffer size, then re-allocate a new buffer with double length.

And slice the responseBuffer according to total chunk size when all chunks are received:
```javascript
properties.responseBuffer = properties.responseBuffer.slice(0, properties.totalChunkSize);
```
As buffer.sllice only make a weak reference to the original buffer, thus no buffer will be created here. 

After those modification, loading the same 150MB csv file only costs **3 seconds** and uses **680MB** memory.

**Comment by domenic** [comment]
Great investigation!

If I am to understand, the only downside of your proposed change is that it will immediately allocate the whole 150 MB, right? Whereas with the current code, if you abort after seeing 10 MB, only 10 MB will be downloaded. Is that correct?

If so I think that is a fair tradeoff to make, and a PR would be welcome.

Another optimization I can imagine is that instead of making slices every time, we only make slices in the responseText getter.

**Comment by skygon** [comment]
The buffer size will increase based on properties.bufferSize, in a quadratic manner. 
```javascript
properties.totalChunkSize += chunk.length;

if (properties.totalChunkSize >= properties.bufferSize){
    properties.bufferSize *= 2;
     ...
    var tmp = Buffer.alloc(properties.bufferSize); //Create new buffer here, with new length
    properties.responseBuffer = Buffer.concat([properties.responseBuffer, chunk])
    tmp.copy(properties.responseBuffer, properties.responseBuffer.length);
    properties.responseBuffer = tmp;
```
If total received chunk size bigger than current buffer size, then create a new buffer with double length. In my test, the init value is 100MB, we can set it to any other values. The ultimate goal is to reduce 'garbage' buffers. For example, if we set init value of properties.bufferSize to 10MB and to load 150MB file, there will only has log2(150/10) 'garbage' buffers.  And the tradeoff is the init value of properties.bufferSize.

**Comment by skygon** [comment]
Another interesting thing is that when properties.responseBuffer bigger than 256MB, then in ```xmlhttprequest.js : get responseText()```:
```javascript
const res = whatwgEncoding.decode(responseBuffer, fallbackEncoding);
properties.responseTextCache = res;
return res;
```
Here *res* will be greater than the V8 String length limitation, (process.binding('buffer').kStringMaxLength is 268435440 bytes, 256MB ), which will cause exception/ abort.

**Comment by domenic** [comment]
Hmm. On average I would expect most resources retrieved by XHR to be < 1 MB so I'm not sure 100 MB is a good tradeoff.

The string size limitation is interesting. I assume browsers also fail in that regard.
