### ISSUE TITLE
window.origin is undefined - was it supposed to be window.location.origin?

### ISSUE THREAD

**Issue by jmlopez-rod** [tmpvar/jsdom#1789]
I've been trying to get some of my previous karma tests to pass in node using jsdom and I finally found my issue. The file `/lib/jsdom/living/post-message.js` executes this in line 19:

```javascript
if (targetOrigin !== "*" && targetOrigin !== this.origin) {
```

Now keep in mind that `this` is the object that calls `postMessage` which means that we are dealing with the window object. When I change the second condition to

```javascript
targetOrigin !== this.location.origin
```

It works fine. I was trying to create a PR but I can't seem to be able to run the post-message tests to see if my fix would create any issues.

I stumbled upon https://html.spec.whatwg.org/#crossDocumentMessages and if you search for `location.origin` it will advice you to use `window.origin` which is why probably the code is written as it is. But consider this, if I try to see `window.origin` in chrome i get undefined.

![screen shot 2017-03-28 at 6 44 13 pm](https://cloud.githubusercontent.com/assets/1810397/24432380/59dccfac-13e7-11e7-8b24-10a5f2d61d49.png)

Would this work?

  ```javascript
targetOrigin !== (this.origin || this.location.origin)
```

**Comment by domenic** [comment]
Thanks, this is probably just a bug. We don't implement window.origin so attempts to compare against it are bogus. A PR fixing this to `this.location.origin` would be welcome.

Unfortunately this is not easy to write a test for since setting up cross-origin web platform tests is not supported in our current test runner. So the easiest thing to do will be a PR without a test for now.

**Comment by jmlopez-rod** [comment]
Good to hear, which solution should I go for? use `this.location.origin` or `(this.origin || this.location.origin`?

**Comment by domenic** [comment]
The former, since `this.origin` doesn't exist so it will always be falsy.
