### ISSUE TITLE
Not able to get rendered DOM markup

### ISSUE THREAD

**Issue by voidmonk** [tmpvar/jsdom#1794]
Hey guys, I'm trying to load a simple test page in jsdom, that prints the current date-time (via inline JS) after a 2 second delay, but I'm not able to get the rendered DOM markup with the printed date-time.

Here's the test page output: http://output.jsbin.com/cikahogoku
Here's the test page code: http://jsbin.com/cikahogoku/edit?html,js,output

In nodejs, I'm not able to see the date-time from the DOM output using `jsdom.serializeDocument(window.document)` which is triggered 10 seconds after the jsdom `done` event.

Any clues?!

**Comment by Zirro** [comment]
You can use `textContent` instead of `innerText`. innerText was only recently standardised, and is currently not implemented in jsdom since it requires a layout engine to behave as a regular browser would (see issue #1245).

**Comment by Zirro** [comment]
I believe this issue can be closed in favour of #1245.
