### ISSUE TITLE
newapi: Cannot find module './jsdom/living/generated/utils.js'

### ISSUE THREAD

**Issue by davidbielik** [tmpvar/jsdom#1797]
Getting an error when trying to require the newapi: 

> Cannot find module './jsdom/living/generated/utils.js'

Where can I find utils.js since my "generated" directory is empty?

I'm using commit: #28d08f5

**Comment by domenic** [comment]
You need to run npm run prepublish.

**Comment by davidbielik** [comment]
Thanks @domenic. I'm now getting errors that it can not find this module: `/jsdom/scripts/webidl/convert`

I get the feeling I've missed some important step beyond the usually simple `npm install`. Is some other global dependency required or do i just go error-by-error and install these dependencies which aren't part of this package?

> node v7.7.3 and npm v4.1.2

**Comment by domenic** [comment]
In general installing from git is not supported and I'm not sure how to get it to work.

**Comment by davidbielik** [comment]
Thanks @domenic! Got it working by cloning through git, not using npm anymore. 

For anyone that needs help with running this new branch:

git clone https://github.com/tmpvar/jsdom --branch newapi
cd jsdom;
npm install;
npm run prepublish;

then in your .js file

var jsdom = require('./jsdom/lib/api.js');
