### ISSUE TITLE
TypeError: Cannot read property '_location' of null

### ISSUE THREAD

**Issue by OscarBengtsson** [tmpvar/jsdom#1798]
I'm getting test failed when I test epic via redux-observable.
```
Test Failed
/.../node_modules/jsdom/lib/jsdom/browser/Window.js:148

return idlUtils.wrapperForImpl(idlUtils.implForWrapper(window._document)._location);

TypeError: Cannot read property '_location' of null
    at Window.get location [as location] (/.../node_modules/jsdom/lib/jsdom/browser/Window.js:148:79)
    at Timeout.callback [as _onTimeout] (/.../node_modules/jsdom/lib/jsdom/browser/Window.js:525:40)
    at ontimeout (timers.js:380:14)
    at tryOnTimeout (timers.js:244:5)
    at Timer.listOnTimeout (timers.js:214:5)
```
And here is some of my test codes. I used fetch() and promise in fetchCategoriesEpic
```
it('test epic', () => {
    ...
    const action$ = ActionsObservable.of({ type: FETCH_CATEGORIES })

    fetchCategoriesEpic(action$)
      .toArray() // collects everything in an array until our epic completes
      .subscribe((actions) => {
        expect(actions).toEqual([
          { type: FETCH_CATEGORIES },
          { type: FETCH_CATEGORIES_SUCCESS, payload: List(payload.data).map((category) => new Category(category)) }
        ])
      })
    ...
}
```
How to solve this?

**Comment by jayphelps** [comment]
StackOverflow: http://stackoverflow.com/questions/43190171/redux-observable-cannot-read-property-location-of-null/43190284#43190284

This doesn't appear related to redux-observable.

**Comment by OscarBengtsson** [comment]
Alright, this issue is related with jsdom only.

**Comment by domenic** [comment]
Please produce a repro we can run with node repro.js without installing any dependencies besides jsdom.

**Comment by AndrewHenderson** [comment]
I ran into this issue when attempting to use `document.documentElement` while testing in an environment that did not have document defined.

I added a conditional to that application code and my tests ran fine after that.

**Comment by Enverbalalic** [comment]
+1 on this issue.

**Comment by domenic** [comment]
I'm going to lock this issue as it is attracting useless +1 comments with nobody providing code that reproduces the problem. If people encounter this in the future, please file a new issue using the issue template (and being sure to follow all the instructions in it, especially the one about no third-party libraries).
