### ISSUE TITLE
Missing children when trying to select content inside a <b> tag 

### ISSUE THREAD

**Issue by odarino** [tmpvar/jsdom#1803]
<Image 1>
![1](https://cloud.githubusercontent.com/assets/11508039/24763150/bd322306-1b1a-11e7-939c-25ef04153e2c.PNG)

<Image 2>
![2](https://cloud.githubusercontent.com/assets/11508039/24763151/bd36cc94-1b1a-11e7-9bc5-2a70bc504e91.PNG)
When I tried to select content inside a tag, jsdom returns me 2 tags ( objects) <Image 1>, meanwhile, when Im trying to use with the same query in browser, it returns for me more than 2 tags ( objects) < Image 2>. 
Can you please tell me what problem is, and how to fix it ? 

Thank you.

**Comment by Sebmaster** [comment]
Without some reproduction steps we can't do anything.

**Comment by odarino** [comment]
Thank you for your reply. Here it is: 
Simply that I use `jsdom.env` to retrieve html then select what I want
And here is the code: 
`jsdom.env(`
      ` "http://chiasenhac.vn/mp3/us-uk/us-dance-remix/if-i-lose-myself~alesso-onerepublic~ts3vsmdqq248me_download.html",`
    `   ['https://code.jquery.com/jquery-3.2.0.min.js],`
     `  function (err,window){`
         `  var $ = window.jQuery;`
       `    var select = $($($($('downloadlink')[0]).children()[5]).children())[3].href //which is undefined because there are no 3rd children`
`}`
`);`

**Comment by odarino** [comment]
Any ideas ? 
Thanks.
