### ISSUE TITLE
JSDOM.jsdom in v5.0.0 vs v7+

### ISSUE THREAD

**Issue by jamesopti** [tmpvar/jsdom#1804]
Im upgrading a legacy package from v5 to a version that supports node.js (7+ i think?)

Our existing code works differently when using `jsdom.jsdom` than it did before.

What changes were made between these versions? And what is the equivalent now?

Sorry if this is the wrong forum but I didnt see any docs so I thought I'd start here.

Thanks!

**Comment by Sebmaster** [comment]
Our [changelog](https://github.com/tmpvar/jsdom/blob/master/Changelog.md) is quite complete. Try that.
