### ISSUE TITLE
Add support for Symbol.toStringTag

### ISSUE THREAD

**Issue by droooney** [tmpvar/jsdom#1809]
Could you add support for such a feature for all HTML elements and other Nodes in order that `{}.toString.call(node)` returns not `'[object Object]'`?

**Comment by domenic** [comment]
Now that we require Node v6, this should be a pretty easy feature to add to https://github.com/jsdom/webidl2js, which powers jsdom.

**Comment by domenic** [comment]
We need to remember before closing this to also set the toStringTag for non-webidl2js objects.
