### ISSUE TITLE
Error: Can't resolve 'child_process'

### ISSUE THREAD

**Issue by kaynz** [tmpvar/jsdom#1812]
Hey,

I can't get jsdom working.

I installed jsdom, canvas, canvas-prebuilt as dependency, required jsdom. But whenever I run my webpack task, I'm getting this error:

> ERROR in /jsdom/lib/jsdom/living/xmlhttprequest.js
> Module not found: Error: Can't resolve 'child_process' in 'node_modules/jsdom/lib/jsdom/living'
>  @ /jsdom/lib/jsdom/living/xmlhttprequest.js 4:18-42
>  @ /jsdom/lib/jsdom/browser/Window.js
>  @ /jsdom/lib/jsdom.js

My node version is v7.7.3.

**Comment by domenic** [comment]
I don't know much about webpack and it's not really supported with jsdom, so you're better off filing a bug on the webpack repo.

**Comment by nebulousdog** [comment]
I similarly have this issue

**Comment by omerdn1** [comment]
I've also encountered this issue

**Comment by domenic** [comment]
Deleting +1 comments as they only add noise. If they continue I will lock this thread.

**Comment by BbosaH** [comment]
i just added   option of   `target : 'node'`  in  webpack.config.test.js and all worked fine

**Comment by RomuloMilani** [comment]
I seted the modules with error (_child_process_,_fs_,_net_,_tls_)  with 'empty' in webpack.config.js. It is working here, the module.exports stayed like this:

`module.exports = {
    node: {
        child_process: 'empty',
        fs: 'empty',
        net: 'empty',
        tls: 'empty'
    }
}`

**Comment by mrded** [comment]
I'm facing the same problem. I understood that webpack isn't supported, however can anyone recommend how can I make an isomorphic (universal) implementation of `document.createElement` ?

**Comment by kkomelin** [comment]
> I'm facing the same problem. I understood that webpack isn't supported, however can anyone recommend how can I make an isomorphic (universal) implementation of `document.createElement` ?

Next.js, for example, supports dynamic imports with SSR disabled, so you can load non-isomorphic components this way:
```javascript
import dynamic from 'next/dynamic'

const DynamicComponentWithNoSSR = dynamic(
  () => import('../components/hello3'),
  { ssr: false }
)
```
Documentation is here https://nextjs.org/docs#with-no-ssr

**Comment by x5engine** [comment]
@domenic +1 ;)
