### ISSUE TITLE
Changelog could use some pointers on migrating from 9.x to 10.x

### ISSUE THREAD

**Issue by jharris4** [tmpvar/jsdom#1815]
I just updated to 10.0.0, and I was surprised that the change log didn't draw attention to the following:

`import { jsdom } from 'jsdom';` --> `import { JSDOM } from 'jsdom';`

`var document = jsdom('<html></html>')` --> `var dom = new JSDOM('<html></html>')`

Once I made these changes (and `var document = dom.window.document`), it was smooth sailing, nice work!

**Comment by jharris4** [comment]
The README certainly did tell me how to figure out the changes to the API. I didn't intend to sound critical.

I merely thought the content of my original comment in this issue might be helpful as a kind of TLDR to save people a few minutes when making the same migration :-)

**Comment by domenic** [comment]
Ah I see. Yeah, the problem is that the defaults have changed significantly between those two lines of code; I guess it might not matter to the majority of users, but I'd not want to suggest that they are equivalent.

**Comment by jharris4** [comment]
Ah good to know. For the various unit tests I use jsdom with that change just worked out of the box, but it sounds like maybe I was just lucky. Thanks for the heads up about the changed defaults...
