### ISSUE TITLE
`Image.onload` not fired after upgrading for 9.x to 10.x

### ISSUE THREAD

**Issue by EvNaverniouk** [tmpvar/jsdom#1816]
This code works fine in 9.x:

```javascript
import jsdom from 'jsdom';
const dom = new JSDOM('<!DOCTYPE html><html><body></body></html>');
global.document = dom.window.document;
global.window = dom.window;

const img = new window.Image();
img.onload = () => console.log('This is fired without issue');
img.src = 'data:image/gif;base64,R0lGODlhEAAQAMQAAORHHOVSKudfOulrSOp3WOyDZu6QdvCchPGolfO0o/XBs/fNwfjZ0frl3/zy7////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACH5BAkAABAALAAAAAAQABAAAAVVICSOZGlCQAosJ6mu7fiyZeKqNKToQGDsM8hBADgUXoGAiqhSvp5QAnQKGIgUhwFUYLCVDFCrKUE1lBavAViFIDlTImbKC5Gm2hB0SlBCBMQiB0UjIQA7';
```

However, the following code does NOT work in 10.x

```javascript
import {JSDOM} from 'jsdom';
const dom = new JSDOM('<!DOCTYPE html><html><body></body></html>');
global.document = dom.window.document;
global.window = dom.window;

const img = new window.Image();
img.onload = () => console.log('This is never fired');
img.src = 'data:image/gif;base64,R0lGODlhEAAQAMQAAORHHOVSKudfOulrSOp3WOyDZu6QdvCchPGolfO0o/XBs/fNwfjZ0frl3/zy7////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACH5BAkAABAALAAAAAAQABAAAAVVICSOZGlCQAosJ6mu7fiyZeKqNKToQGDsM8hBADgUXoGAiqhSvp5QAnQKGIgUhwFUYLCVDFCrKUE1lBavAViFIDlTImbKC5Gm2hB0SlBCBMQiB0UjIQA7';
```

It appears that `new Image().onload` is never executed in v10.x

**Comment by vsemozhetbyt** [comment]
If I get it right, this is reported in commit:

https://github.com/tmpvar/jsdom/commit/58a7028d0d5b6aacc5b435daee9fd8f9eacbb14c

but not in the changelog:

https://github.com/tmpvar/jsdom/blob/master/Changelog.md#1000

**Comment by domenic** [comment]
Ah yep, forgot that changelog entry. Can fix the changelog, but this is an intentional breaking change.

**Comment by EvNaverniouk** [comment]
Is the migration solution to call `onload` manually?

**Comment by domenic** [comment]
Sure, that'd work.

**Comment by lehni** [comment]
@domenic what was the reason for changing this? The new behavior is inconsistent with how browsers behave: They fire the `load` event in those cases. When I implemented support for `load` events on images, I intentionally modelled it after what I observed on browsers. This is also the behavior that we're expecting in `paper.js`, so this change blocks upgrading to `jsdom` v10+.

**Comment by lehni** [comment]
Also, is this test not executed anymore?

https://github.com/tmpvar/jsdom/blob/58a7028d0d5b6aacc5b435daee9fd8f9eacbb14c/test/to-port-to-wpts/htmlimageelement.js#L91

**Comment by lehni** [comment]
Ok, it's worse: This not only broke the `load` event for data URLs, it appears to not be fired for any URL. Here a test-case that works both on v9, v10 and v11. The load event fires on v9, not the others:

```js
var jsdom = require('jsdom');
var path = require('path');

var html = '<html><body></body></html>';
var options = {
    // Use the current working directory as the document's origin, so
    // requests to local files work correctly with CORS.
    url: 'file://' + process.cwd() + '/',
    features: {
        FetchExternalResources: ['img', 'script']
    }
};

var window;
if (jsdom.JSDOM) {
    var dom = new jsdom.JSDOM(html, options);
    window = dom.window;
} else {
    var document = jsdom.jsdom(html, options);
    window = document.defaultView;
}

var image = new window.Image();
image.onload = () => {
    console.log('loaded');
};

image.src = path.resolve('./test.jpg');
```

**Comment by domenic** [comment]
> what was the reason for changing this? The new behavior is inconsistent with how browsers behave: They fire the load event in those cases.

Browsers do not fire a load event when they are configured to not load images. jsdom is by default configured to not load any external resources, so it follows browsers in this regard. This brings images in line with other not-loaded resources (like video, audio, link rel=preload, etc.)

You can also switch into a mode where it loads "usable" external resources, which includes images only if you have the canvas package installed.

As you can see from a few lines above, that test is executed only if the canvas package is installed, in which case load events *do* fire.

**Comment by joscha** [comment]
Just in case someone lands on here because of failing tests in Jest 22, it can be fixed via:
```
"testEnvironmentOptions": { "resources": "usable" },
```
Note: `features: { FetchExternalResources: ["img"] }` doesn't work with Jest, yet, as they use the old API.

**Comment by soanvig** [comment]
@joscha 
It doesn't work (in Jest). I do use `canvas` lib. In code there is `new Image()`, but I get an error `TypeError: Canvas.Image is not a constructor` at that line (error comes from jsdom). Without `resources: 'usable'` nothing works, so it is some progress.

In jsdom docs canvas lib is mentioned, yes. And to make it work with images `canvas` is required (which I include anyway for testing other things).

Does this configuration works for you?

```
TypeError: Canvas.Image is not a constructor
      
      at HTMLImageElementImpl._attrModified (node_modules/jsdom/lib/jsdom/living/nodes/HTMLImageElement-impl.js:14:25)
      at Object.exports.appendAttribute (node_modules/jsdom/lib/jsdom/living/attributes.js:53:11)
      at HTMLImageElementImpl.setAttribute (node_modules/jsdom/lib/jsdom/living/nodes/Element-impl.js:258:18)
      at HTMLImageElementImpl.set src [as src] (node_modules/jsdom/lib/jsdom/living/nodes/HTMLImageElement-impl.js:48:10)
      at HTMLImageElement.set (node_modules/jsdom/lib/jsdom/living/generated/HTMLImageElement.js:67:23)
      at Resource._loadElement (node_modules/resource-loader/src/Resource.js:517:13)
      at Resource.load (node_modules/resource-loader/src/Resource.js:446:22)
      at node_modules/resource-loader/src/Loader.js:531:30
      at next (node_modules/resource-loader/src/async.js:22:17)
      at Object.eachSeries (node_modules/resource-loader/src/async.js:19:5)
```

**Comment by TimothyGu** [comment]
@joscha You got it backwards: `FetchExternalResources` is part of the old API, and `"resources": "usable"` is a new API :)

**Comment by joscha** [comment]
> @joscha You got it backwards: FetchExternalResources is part of the old API, and "resources": "usable" is a new API :)

:D fixed

**Comment by rileybracken** [comment]
@joscha can you provide an example where you are getting this to work? I cannot seem to get it to work, `Image.onload` never fires 😦 .

**Comment by joscha** [comment]
@rileybracken you just need to add:

```json
"testEnvironmentOptions": { "resources": "usable" },
```
to your `jestconfig.json` in order to make it work.

**Comment by unruffledBeaver** [comment]
I could not get the jest settings + canvas working but for anyone who comes here and has this issue you can do this

```
const LOAD_FAILURE_SRC = 'LOAD_FAILURE_SRC';
const LOAD_SUCCESS_SRC = 'LOAD_SUCCESS_SRC';

beforeAll(() => {
    Object.defineProperty(global.Image.prototype, 'src', {
        set(src) {
            if (src === LOAD_FAILURE_SRC) {
                setTimeout(() => this.onerror(new Error('mocked error')));
            } else if (src === LOAD_SUCCESS_SRC) {
                setTimeout(() => this.onload());
            }
        },
    });
});
```

and then just set you `src` to either `LOAD_SUCCESS_SRC` or `LOAD_SUCCESS_SRC` to trigger `onload` or `onerror`

**Comment by chenxeed** [comment]
Thank you for the solution!

If I want to add this only on my certain case, should I restore back the original behavior?

If so, I wonder how can I restore back the defineProperty of `src` to original. 🤔

**Comment by kleinfreund** [comment]
The following isolated test case doesn’t work for me:

```
describe(('Image.prototype.src') => {
  test('triggers load for valid data URL', async done => {
    // A 1x1 pixel, base64-encoded PNG with a white background
    const pngPixel = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+ip1sAAAAASUVORK5CYII='

    async function loadImage(src) {
      return new Promise((resolve, reject) => {
        const image = new Image()

        image.onload = event => resolve(true)
        image.onerror = error => reject(error)
        image.src = src
      })
    }

    return loadImage(pngPixel).then(result => {
      expect(result).toEqual(true)
      done()
    })
  })
})
```

I’ve tried it with setting `"testEnvironmentOptions": { "resources": "usable" }` in `jest.config.json` without the outcome changing.

I added the hacky workaround posted in https://github.com/jsdom/jsdom/issues/1816#issuecomment-432496573 which makes the test pass. But this only works if one uses old-style `image.onload` instead of `image.addEventListener('load', ...)`.

Am I doing something wrong?

**Comment by imjasonmiller** [comment]
> I added the hacky workaround posted in #1816 (comment) which makes the test pass. But this only works if one uses old-style image.onload instead of image.addEventListener('load', ...).

@kleinfreund if you are using `image.addEventListener("load", ...)` I think you would have to swap out `this.onload` for [`this.dispatchEvent(new Event("load"))`](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/dispatchEvent) instead.

**Comment by AlvinLaiPro** [comment]
Mark

**Comment by JeffreyJoumjian** [comment]
`element.dispatchEvent` works perfect for me. Simple and no worrying about mocking:
```ts
test("should call onError",  async () => {
	const {findByTestId} = render(<ComponentWithImage/>);

	// find your image in the document
	const img = await findByTestId("your-img-test-id");

	// dispatch HTML error event
	img.dispatchEvent("error");

	// validate that onError was called
	// do your validation
});
```
