### ISSUE TITLE
SyntaxError: Unexpected token {

### ISSUE THREAD

**Issue by izakkam** [tmpvar/jsdom#1817]
I had a working build of my dockerized nodejs app last night, and I rebuilt my app this morning and now I get this error:

npm info it worked if it ends with ok
npm info using npm@2.15.11
npm info using node@v4.6.2
npm info prestart mynodejscontainertest@1.0.0
npm info start mynodejscontainertest@1.0.0

> mynodejscontainertest@1.0.0 start /usr/src/app
> node index.js

/usr/src/app/node_modules/jsdom/lib/api.js:10
const { URL } = require("whatwg-url");
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/src/app/index.js:9:13)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:990:3

npm info mynodejscontainertest@1.0.0 Failed to exec start script
npm ERR! Linux 4.4.0-66-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.6.2
npm ERR! npm  v2.15.11
npm ERR! code ELIFECYCLE
npm ERR! mynodejscontainertest@1.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mynodejscontainertest@1.0.0 start script 'node index.js'.
npm ERR! This is most likely a problem with the mynodejscontainertest package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mynodejscontainertest
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls mynodejscontainertest
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/src/app/npm-debug.log

I reverted my repository to the same one I had last night and it still isn't working when I rebuild my app.

**Comment by Sebmaster** [comment]
jsdom@10 requires nodejs v6. Either upgrade your node version or downgrade jsdom to jsdom@9.
