### ISSUE TITLE
click event not firing in v10

### ISSUE THREAD

**Issue by Havunen** [tmpvar/jsdom#1819]
After updating to JSDOM v10 `div.click() ` no longer fires the onClick listener attached to that node.

Event listener was attached node using following syntax:
```
node['onclick'] = function () {/*not related*/}
```
same code works in browsers

You can reproduce this in InfernoJS repository:
https://github.com/infernojs/inferno/tree/dev

- update to JSDOM v10
- npm run test:server  => click related tests fail
- JSDOM 9.12 all works.

**Comment by vsemozhetbyt** [comment]
Did you check the new https://github.com/tmpvar/jsdom#executing-scripts ?

**Comment by domenic** [comment]
Closing since that is probably it, but happy to reopen if we missed something.
