### ISSUE TITLE
Element.attributes should be a NamedNodeMap

### ISSUE THREAD

**Issue by Frankusky** [tmpvar/jsdom#1824]
Related to https://github.com/tmpvar/jsdom/issues/853

I wasn't able to get NamedNodeMap, even using Object.prototype.toString.call(domElement.attributes) neither using domElement.attributes.toString(), both returns [object Object]

Im using the following code:
`let dom = new JSDOM("<!DOCTYPE html><div class="test"><script src="http://test.com/file.js" my-attribute="testing"></script>"); global.window = dom.window; global.document = dom.window.document; console.log(document.getElementsByTagName('script')[0].attributes.toString()); console.log(Object.prototype.toString.call(document.getElementsByTagName('script')[0].attributes));`

Excuse me if I shouldnt have to create a new issue about this.

**Comment by domenic** [comment]
Element.attributes is already a NamedNodeMap. The toString value is not correct, but that's already tracked in #1809.

**Comment by Frankusky** [comment]
How can I retrieve that the specified dom element attribute is NamedNodeMap type? I still seeing [object Object], or the fix isn't released yet?

**Comment by domenic** [comment]
It has all the methods and properties of a NamedNodeMap. As stated, its toString isn't working yet.
