### ISSUE TITLE
SyntaxError: Unexpected token {

### ISSUE THREAD

**Issue by techyrajeev** [tmpvar/jsdom#1825]
## Basic info:

- **Node.js version:** 6
- **jsdom version:** v10

### Error details

```
home/test/Development/api-test/node_modules/jsdom/lib/api.js:10
const { URL } = require("whatwg-url");
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Module._extensions..js (module.js:416:10)
    at Object.require.extensions.(anonymous function) [as .js] (/home/test/Development/api-test/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/test/Development/api-test/.setup.js:3:13)
    at Module._compile (module.js:409:26)
    at loader (/home/test/Development/api-test/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/test/Development/api-test/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at /home/test/Development/api-test/node_modules/mocha/lib/mocha.js:230:27
    at Array.forEach (native)
    at Mocha.loadFiles (/home/test/Development/api-test/node_modules/mocha/lib/mocha.js:227:14)
    at Mocha.run (/home/test/Development/api-test/node_modules/mocha/lib/mocha.js:495:10)
    at Object.<anonymous> (/home/test/Development/api-test/node_modules/mocha/bin/_mocha:460:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

```

```js
require('babel-register')();

var jsdom = require('jsdom').jsdom;

var exposedProperties = ['window', 'navigator', 'document'];

global.document = jsdom('');
global.window = document.defaultView;
Object.keys(document.defaultView).forEach((property) => {
  if (typeof global[property] === 'undefined') {
    exposedProperties.push(property);
    global[property] = document.defaultView[property];
  }
});

global.navigator = {
  userAgent: 'node.js'
};

documentRef = document;
```

If I remove jsdom and comment above code mocha runs the test cases fine.

**Comment by domenic** [comment]
Can you show me the output of `node --version`? This error should only occur in Node versions below v6.

**Comment by techyrajeev** [comment]
I had actually installed node 6.10.2 but project was actually using node version 4.4.7. 
When I fixed node path this issue was gone.
but was getting this issue now.

global.document = jsdom('');
                  ^

TypeError: jsdom is not a function
    at Object.<anonymous> (/home/test/Development/api-test/.setup.js:7:19)
    at Module._compile (module.js:570:32)
    at loader (/hom

**Comment by domenic** [comment]
Please see the readme for how the API works; there is indeed no `require('jsdom').jsdom` in v10.

**Comment by techyrajeev** [comment]
I have changed the above code to this one -
Is this correct way?
I am basically trying to setup jsdom for mocha test runner.
```
require('babel-register')();

const jsdom             = require('jsdom');
const { JSDOM }         = jsdom;
const exposedProperties = ['window', 'navigator', 'document'];
const d                 = new JSDOM('<!doctype html><html><body></body></html>');

global.window = (d).window;
global.document = (d).window.document;

Object.keys(document.defaultView).forEach((property) => {
  if (typeof global[property] === 'undefined') {
    exposedProperties.push(property);
    global[property] = document.defaultView[property];
  }
});

global.navigator = {
  userAgent: 'node.js'
};

```

**Comment by domenic** [comment]
Well, it now looks like you might be using the API correctly, but see https://github.com/tmpvar/jsdom/wiki/Don't-stuff-jsdom-globals-onto-the-Node-global.

**Comment by techyrajeev** [comment]
Wow that's quite informative link. It means rather than stuffing all things into nodejs globals I should use JSDOM only when needed. As suggested in the example may be in beforeEach of test suite.
Thanks a lot for your help.

**Comment by jedwards1211** [comment]
@domenic do you have an example of how to evaluate one module in the context of `window` without losing its ability to `require` other modules?  All of my code is written to work with Webpack but thus far I've been testing it without webpacking it because that would waste time unnecessarily.

**Comment by jedwards1211** [comment]
@domenic I haven't seen *a single example* of how to conveniently use `jsdom` with `mocha` that doesn't stuff jsdom globals onto the Node global.  I guess ideally one would run the code in each `it()` block in the window context.  Loading a script tag in each test ins't very satisfying...if you have any opinions on how to make it better, let me know.

**Comment by jedwards1211** [comment]
@domenic even Airbnb's enzyme advises stuffing jsdom globals onto the Node global:

https://github.com/airbnb/enzyme/blob/master/docs/guides/jsdom.md

**Comment by domenic** [comment]
Yes, there are third parties promoting bad practices. We can't do anything about that except produce our own counter-documentation.

You should webpack your code, just like you would in a browser. Since that's what jsdom is emulating.

**Comment by jedwards1211** [comment]
@domenic I understand your reasoning, but I think it's just not practical enough for many use cases. 
 In light of the awkwardness I've mentioned so far, I think it makes more sense to just embrace making a frankenstein mishmash of node and jsdom globals and use tools like ESLint to ensure the code isn't accessing any globals it shouldn't.

**Comment by domenic** [comment]
You can do whatever you want in your code. Just be warned it's not supported and we may break it in a patch release, and won't be able to help on the issue tracker if you run into issues.

**Comment by jedwards1211** [comment]
I assume the only way it would break is if in the future something in the node and browser namespaces conflicts, right?

**Comment by domenic** [comment]
No, there are lots of possibilities, e.g. stronger this value enforcement, changes to property descriptors, etc. This has already bitten people during upgrades in the past.

**Comment by Joris-van-der-Wel** [comment]
Not only that, some javascript libraries will _not_ function properly if you do not run it using jsdom's sandbox. There are many silly things in DOM such as this:

```HTML
<div id="foo"></div>
<script>
foo.textContent = "hello"; // window.foo
</script>
```

**Comment by jedwards1211** [comment]
@Joris-van-der-Wel yes of course.  Fortunately in all of the testing I've done with React I haven't needed to do something so silly :)
