### ISSUE TITLE
defaultView undefined or null

### ISSUE THREAD

**Issue by PiotrekPaprocki** [tmpvar/jsdom#1827]
### Basic info:

- **Node.js version:** 6.9.5
- **jsdom version:** 10

I'm follwing this [article](https://semaphoreci.com/community/tutorials/getting-started-with-tdd-in-react) where I have `setup.js` script as follows: 

```
require('babel-register')();

var jsdom = require('jsdom').jsdom;

var exposedProperties = ['window', 'navigator', 'document'];

global.document = jsdom('');
global.window = document.defaultView;
Object.keys(document.defaultView).forEach((property) => {
  if (typeof global[property] === 'undefined') {
    exposedProperties.push(property);
    global[property] = document.defaultView[property];
  }
});

global.navigator = {
  userAgent: 'node.js'
};
```

And after changing `jsdom` to `JSDOM` (btw, why did you decide to change it?) and add `new` before `jsdom('')` it breakes on  
`Object.keys(document.defaultView).forEach((property) => {`

with 
`
TypeError: Cannot convert undefined or null to object
`
Anyone know why / what should I do to fix it?

Everything's working with jsdom@9.12.0

Thanks

**Comment by vsemozhetbyt** [comment]
v10 has a new API. See:

https://github.com/tmpvar/jsdom/blob/master/Changelog.md#1000
https://github.com/tmpvar/jsdom/blob/master/README.md

**Comment by zhanwenchen** [comment]
The usage of `defaultView` is still unclear to me. What's the difference between `jsdomInstance.window.document` and `jsdomInstance.window.document.defaultView.document`?

**Comment by Sebmaster** [comment]
There is none. `jsdomInstance.window` gets you a window. At that point you're in a DOM `Window` with all the properties that entails. `Window.prototype.document` gets you a `Document`. `Document.prototype.defaultView` gets you back to a `Window`.

**Comment by zhanwenchen** [comment]
@Sebmaster can calling `.defaultView` on any child of `window.document` get you back to the `Window` instance? Right now I'm returning a form with `document.forms[0]`, but can I go back to the `window` from the `form` element?

**Comment by Sebmaster** [comment]
`Node.prototype.ownerDocument` gets you back to a `Document`.

**Comment by zhanwenchen** [comment]
@Sebmaster is there any way to get back to the `window`?

**Comment by vsemozhetbyt** [comment]
@zhanwenchen `Node.prototype.ownerDocument.defaultView`

**Comment by zhanwenchen** [comment]
@vsemozhetbyt thanks!

**Comment by smokinjoe** [comment]
@PiotrekPaprocki - you able to figure out a fix? I'm super new to jsdom and right now all I can find are apparently outdated tutorials and information. Not really sure what to make of what @vsemozhetbyt linked and how it pertains to your question.

**Comment by PiotrekPaprocki** [comment]
@smokinjoe Dude, I don't remember :| Really. 
Maybe in comments of the article I've mentioned you will find something useful? 
I might just stuck with 9.12.0 or dive deep into the jsdom code and figure sth out. Don't remember, sorry.

**Comment by smokinjoe** [comment]
No sweat, appreciate the reply!
