### ISSUE TITLE
Canvas getContext doesnt work

### ISSUE THREAD

**Issue by nagamanikandank** [tmpvar/jsdom#1834]
I dont know if this is a issue or I am doing something wrong.

I am using JSDOM to create a canvas element to test using mocha. The following is the code

```
let canvas = require('canvas-prebuilt');
let jsdom = require('jsdom');
let { JSDOM } = jsdom;
let dom= new JSDOM();
let mycanvas = dom.window.document.createElement("canvas");
console.log("canvas data mycanvas:"+mycanvas.getContext("2D") );
```

The console gets printed as null.

But if I print `mycanvas.getHeight` it gets printed as `150`.

Am I doing something wrong or missing anything here. Please help

**Comment by domenic** [comment]
I'm not sure but it might need to be `2d` instead of `2D` (capitalization).

The other issue that could be causing this is #1811; something about canvas-prebuilt not working on Linux?

**Comment by nagamanikandank** [comment]
`console.log("canvas data mycanvas:"+mycanvas.getContext("2d") ); ` worked. Thanks.

But, when I pass the  `mycanvas` object to the JS file which I am actually testing, I am getting following error

`ReferenceError: window is not defined`

**Comment by domenic** [comment]
You'll need to provide a complete repo case again.
