### ISSUE TITLE
window.location.href returning about:blank

### ISSUE THREAD

**Issue by scrpatlolla** [tmpvar/jsdom#1840]
I would like to get the current page URL, which we usually get by using window.location.href in javascript. Please Advise.

import http from 'http';
import React, { PropTypes } from 'react';
import $ from "jquery";
const jsdom = require("jsdom");
const { JSDOM } = jsdom;
const { window } = new JSDOM(`...`);

const SampleApp = ({ value, location}) => {
    const check = window.location.href;
    const prId = "12512" //We can make it dynamic
    const url = "http://localhost:8000/prId=" + prId; //window,location.href;
    const id = url.substring(url.lastIndexOf('/') + 1);
    const output = id.replace(/[a-zA-Z=]/g, '');
    return (
        <div>
            <h1>Hello {value}</h1>
            <hr />
            <h2>{output} took from prId</h2>
            <h2>{check} took from prId</h2>
            <hr />
            <h2><a className="redirect" href={'//www.example.com/prId/' + output} target="_blank">Click Here</a>
            </h2>
        </div>
    );
};

Reference:
https://github.com/scrpatlolla/react-amp-template/blob/master/examples/src/demo.js

**Comment by domenic** [comment]
This does not follow the issue template. It uses syntax which is not supported in Node.js, such as import, and uses third-party libraries, such as React. Happy to reopen if you edit your post to conform to the requirements.
