### ISSUE TITLE
Not implemented: window.alert

### ISSUE THREAD

**Issue by Igor-Vuk** [tmpvar/jsdom#1843]
Inside the code I have this line window.alert('Please try again'). When testing the code I get a warning `Not implemented: window.alert` How do I resolve this and test the code? I am runin the new v10 version of jsdom and nevest version of jsdom-global

**Comment by vsemozhetbyt** [comment]
@Igor-Vuk See https://github.com/tmpvar/jsdom#intervening-before-parsing
```js
'use strict';

const { JSDOM } = require('jsdom');

const options = {
  resources: 'usable',
  runScripts: 'dangerously',
  beforeParse(window) {
    window.alert = window.console.log.bind(window.console);
  }
};

const dom = new JSDOM(`
  <!doctype html>
  <html>
    <head>
      <meta charset="UTF-8">
      <title></title>
    </head>
    <body>
      <script>
        window.alert('Please try again');
      </script>
    </body>
  </html>
`, options);

dom.window.close();
```
```console
Please try again
```

**Comment by bochen2014** [comment]
I'm not sure how useful above info is, as must of the time, we don't config `jsdom` directly but rather leave it with `jest` or other test framework.

I followed `jest` [documentation](https://facebook.github.io/jest/docs/en/configuration.html#testenvironmentoptions-object) and created 
```js
//jest.config.js
module.exports={
 ......

 testEnvironmentOptions: {
    // only string values is supported??
    beforeParse (window) {
     console.log('------------------------------------------  log ')
      window.document.childNodes.length === 0;
      window.alert = (msg) => { console.log(msg); };
      window.matchMedia = () => ({});
      window.scrollTo = () => { };
    }
  }, 

......
}
```
but it seems to NOT work as I didn't see my log info;

to get it work, I have to 
1. create my own testEnv in `jest.config.js`
```json
testEnvironment: '<rootDir>/script_preprocessor/customizedJsdomEnv.js',
```
2. inside my test env
```js
// https://github.com/facebook/jest/issues/5124#issuecomment-352650274
const JSDOMEnvironment = require('jest-environment-jsdom');

module.exports = class CustomizedJSDomEnvironment extends JSDOMEnvironment {
  constructor (config) {
    const _config = Object.assign(config, {
      testEnvironmentOptions: {
        beforeParse (window) {
          console.log(`^^^^^^^^^^^^^$$$$$$$$^^^^^^^^^^^^^$$$$$$$$^^^^^^^^^^^^^$$$$$$$$`);
          window.document.childNodes.length === 0;
          window.alert = (msg) => { console.log(msg); };
          window.matchMedia = () => ({});
          window.scrollTo = () => { };
        }
      }});
    super(_config);
    this.global.jsdom = this.dom;
  }

  teardown () {
    this.global.jsdom = null;
    return super.teardown();
  }
};

```

3. now run `yarn jest` and I can see my log info, which indicates `beforeParse` is wired up to `jsdom` that jest is using;

NOTE: this is probably an overkill as you can simply do 
1. setupFiles
```js
//jest.config.js
{
   setupFiles: [ '<rootDir>'/test/setup.js]
}
```
2. in your setup.js
```js
 window.alert = (msg) => { console.log(msg); };
          window.matchMedia = () => ({});
          window.scrollTo = () => { };
```
the downside is that it mutate your global object directly, but, practically, it's not a big deal

**Comment by debasishshanti** [comment]
@bochen2014 Try setting the alert function to undefined first and then assign your function to it. This is what solved the issue for me

**Comment by richardmyu** [comment]
@bochen2014  thanks, it work

**Comment by Krumpet** [comment]
@bochen2014 This works, but when I try to debug my test I get this error:

`TypeError: Cannot assign to read only property 'testEnvironmentOptions' of object '#<Object>'`

**Comment by codelovesme** [comment]
@bochen2014 second solution worked for me!
