### ISSUE TITLE
Basic questions about extracting modified HTML content

### ISSUE THREAD

**Issue by rehierl** [tmpvar/jsdom#1850]
Node.js version: 7.10.0
jsdom version: 10.1.0

I am using jsdom similar to the following lines:

```js
const userContent1 = "HTML soup";
const userContent2 = "<DOCTYPE html><html><head></head><body>HTML soup ...";
const userContent = userContent2;

const dom = new JSDOM(userContent);
const doc = dom.window.document;

//- use doc to modify userContent

let result1 = doc.documentElement.innerHTML;
let result2 = doc.documentElement.outerHTML;
let result3 = doc.body.innerHTML;
return (result1 | result2 | result3);
```

**(Question 1)** How do I extract the whole content?

In case of "userContent = userContent2" neither result1, nor result2 will start with DOCTYPE. In other words: Some information from the user's input is lost.

Is there another way to extract the whole content I am unaware of?

**(Question 2)** How can I determine which result to return?

In case of "userContent = userContent1" I get to work with only part of an HTML document; i.e. no &lt;html&gt; tags. Therefore I should return result3. And in case of "userContent = userContent2" I get to work with a fully specified HTML document and should return result1 or result2.

Now the question is, without prior knowledge of what exactly the user provided, does jsdom allow me to query some property in order to determine which result I need to return?

**Comment by vsemozhetbyt** [comment]
You can use `serialize()` to get the whole HTML: https://github.com/tmpvar/jsdom#serializing-the-document-with-serialize

**Comment by rehierl** [comment]
Ok, thanks. I'll use 'serialize()' instead of 'doc.documentElement.inner/outerHTML'.

serialize() on the other hand will add '&lt;head&gt;&lt;/head&gt;' even if userContent didn't have these tags. Is there any way to disable this behavior? I guess I could live with these additional tags, so this shouldn't be too bad.

Maybe I should be more clear on what I am trying to achieve: I'm trying to write code that searches for heading tags (&lt;h1&gt; through &lt;h6&gt;) and adds 'id' attributes if necessary. And because that code may only assume that userContent might contain some heading tags, it shouldn't change userContent in any other way.

So I also still need to figure out whether to return the result of 'dom.serialize()' or 'doc.body.innerHTML'. Does jsdom allow to determine if userContent was a fully specified HTML file, or just some tag soup?

Of course I could try to examine the beginning of userContent to make that decision myself. I just wondered if jsdom had some properties/functions to answer this question.

**Comment by rehierl** [comment]
I have decided to use 'dom.nodeLocation(doc.body)' to determine which result to return.
Thanks for your hint.
