### ISSUE TITLE
Loading script files

### ISSUE THREAD

**Issue by john-doherty** [tmpvar/jsdom#1867]
### Basic info:

- **Node.js version:** v6.10.2
- **jsdom version:** 10.1.0

Can someone please give a quick example of how to load a script file from disk. I ideally wanted to use `JSDOM.fromFile` method, and have script tags in the page. 

I've trawled the documentation and tried lots of variations but nothing works.

**Comment by vsemozhetbyt** [comment]
@john-doherty How do you check if it works? Maybe your script have not enough time to be loaded and executed? See https://github.com/tmpvar/jsdom#asynchronous-script-loading

Example:
`test.html`:
```html
<!doctype html>
<html>
  <head>
    <meta charset="UTF-8">
    <title></title>
  </head>
  <body>
    abc
    <script src='script.js'></script>
  </body>
</html>
```
`script.js` (in the same folder with `test.html`):
```js
document.body.textContent = 123;
```
`test.js`:
```js
'use strict';

const { JSDOM } = require('jsdom');

const options = {
  resources: 'usable',
  runScripts: 'dangerously',
};

JSDOM.fromFile('test.html', options).then((dom) => {
  console.log(dom.window.document.body.textContent.trim());

  setTimeout(() => {
    console.log(dom.window.document.body.textContent.trim());
  }, 5000);
});
```
Output:
```console
abc
123
```

**Comment by john-doherty** [comment]
Thank you for the quick response @vsemozhetbyt

I figured it was either a path issue or async problem, so I worked around it by reading all scripts into a variable and then adding them to the DOM using:

```js
var scriptEl = document.createElement('script');
scriptEl.textContent = script;
document.head.appendChild(scriptEl);
```

Appears to be working fine for the moment.

**Comment by joetidee** [comment]
If I have the following application structure:

```
/site/some.js
/test/test.js
```

then how do I get JSDom to include some.js, for instance:

`<script src="../site/some.js"></script>`

**Comment by vsemozhetbyt** [comment]
@joetidee Do the ways from the previous examples not work for you?

**Comment by joetidee** [comment]
In the end I just ended up passing the `document` to my tests, so linking to the files became irrelevant.
