### ISSUE TITLE
[xhr]validCORSHeaders throws cors error when origin is "null" (null but type is string)

### ISSUE THREAD

**Issue by yosuke-furukawa** [tmpvar/jsdom#1868]
### Basic info:

- **Node.js version:** 
v7.10.0

- **jsdom version:** 
v9.10.2

### Minimal reproduction case

Sorry I could not describe reproduction code.
My reproduction code uses `jest` and `axios`, I don't catch the detail reason.
I have got `Cross Origin null forbidden` error in my test case.

```javascript
  function validCORSHeaders(xhr, response, flag, properties, origin) {
    const acaoStr = response.headers["access-control-allow-origin"];
    const acao = acaoStr ? acaoStr.trim() : null;

   // ----- debug code ----
    console.log(typeof origin) // string "null"
    console.log(typeof acao) // object null
    // throw error because acao !== origin is truthy!!

    if (acao !== "*" && acao !== origin) {
      properties.error = "Cross origin " + origin + " forbidden";
      dispatchError(xhr);
      return false;
    }
   // ....
    return true;
  }
```

I don't know why this `origin` prop is string, but I found the `origin = "null"` code is here.

https://github.com/tmpvar/jsdom/blob/master/lib/jsdom/living/xmlhttprequest.js#L690

# Question

- is this a known issue? 
- which origin value is correct? "null" or null.

**Comment by domenic** [comment]
Sorry, without a reproduction case, I don't think we can work on this. It sounds like it's working as intended. It's possible to have an origin of `"null"` (e.g. any opaque origin serializes as null) and to not have an ACAO header (thus `acao` is null). In which case it's correct to dispatch an error.

Happy to reopen if you can create a minimal reproduction case that works different in browsers.

**Comment by jpgilchrist** [comment]
@tly1980 you're a life saver. 👍

**Comment by jamesrusso** [comment]
@tly1980 thanks. You just saved my morning!  👍

**Comment by Niceplace** [comment]
@tly1980 I have no idea how you found this, but you put an end to hours of pain and suffering.
Thank you so much.

**Comment by siemiatj** [comment]
When using `nock`, you can fix easily by adding response headers : 

```javascript
      nock('http://api.test.url')
      .defaultReplyHeaders({ 'access-control-allow-origin': '*' })
     .get('/foo').reply(200, 'bar');
```

**Comment by jamonholmgren** [comment]
@tly1980 I owe you a :beer:

**Comment by tly1980** [comment]
Hi Folks,

I would love to take the credits, however, I am not the first one who solve this out:

I solved it by reading this (SO thread) [https://stackoverflow.com/questions/42677387/jest-returns-network-error-when-doing-an-authenticated-request-with-axios]
Credits goes to this (buddy: Daniele Dellafiore )  [https://stackoverflow.com/users/510671/daniele-dellafiore]

**Comment by muyu66** [comment]
@tly1980 you're a life saver. 👍

**Comment by andreshg112** [comment]
I'm using Mocha, how can I change my test environment for it?

**Comment by andreshg112** [comment]
Solved with Mocha (not really Mocha at all but Axios). This is what I did.
https://github.com/jsdom/jsdom/issues/2319#issuecomment-410362266

**Comment by SG5** [comment]
@tly1980 do you have solution for mocha?
