### ISSUE TITLE
window.eval doesn't finish and doesn't log errors either

### ISSUE THREAD

**Issue by TitanNano** [tmpvar/jsdom#1871]
### Basic info:

- **Node.js version:** v7.9.0
- **jsdom version:** v11.0.0

When loading a webpack bundle and executing it via dom.window.eval() the code runs to a certain degree. The problem is, it doesn't finish. I assume at some point an error occurs but isn't shown in the console. I attached my html and js files incase someone want's to reproduce this problem.

Module 17 is the entry module. I therefore placed `console.log('running main Script');` in there to check if the module is executed. The line appears in my console. 

[html_and_js.zip](https://github.com/tmpvar/jsdom/files/1033466/html_and_js.zip)

### Minimal reproduction case

```js
const { JSDOM, VirtualConsole } = require("jsdom");
const fs = require('fs');
const virtualConsole = new VirtualConsole();

virtualConsole.sendTo(console);

const options = {
    virtualConsole: virtualConsole,
    runScripts: 'outside-only'
};
JSDOM.fromFile('./index.html', options).then(dom => {
	const source = fs.readFileSync('./app.js', 'utf8');
	global.dom = dom;

	dom.window.eval(source);
});
```

### How does similar code behave in browsers?
The bundle runs without any error in the browser.

**Comment by Sebmaster** [comment]
You're not passing the virtualConsole to jsdom, so you won't see any logs from it.

**Comment by TitanNano** [comment]
@Sebmaster sorry I see, I missed that in the example. I definitely passed it in my tests, since I got errors for some of the css.

**Comment by Sebmaster** [comment]
You'll have to give a better repro then. One we can actually execute.

**Comment by TitanNano** [comment]
@Sebmaster well I updated my initial comment. If the zipped files don't work for you, it'd be good if you can tell me what I can provide instead. At the moment I can't create any minimal eval code, since I don't know where it stops executing.

**Comment by Sebmaster** [comment]
If I open your index file in the browser I get a blank page, so I'm not sure what you're expecting jsdom to do. However, I see you're using custom elements and chances are that's not going to run (even with the shim, there are some issues).

**Comment by TitanNano** [comment]
@Sebmaster yes, many of the stylesheets are missing and custom elements also won't work, thus the blank page. What I'm trying to achieve is to run the bundle in order to get the dom transformation. 

But thank you for mentioning custom elements. I was totally oblivious to the fact that of course the WebComponentsReady event never fired! 🙈

Well sorry for wasting your time :/
