### ISSUE TITLE
React issue onScroll

### ISSUE THREAD

**Issue by hammer65** [tmpvar/jsdom#1874]
### Basic info:

7.1.0
10.1.0

This warning appears because of the following in React code but is only supposed to trigger for old versions of IE. unfortunately it triggers for JSDOM because of what JSDOM returns in this scenario.
*called here*
https://github.com/facebook/react/pull/6678/files#diff-5574f655d491348f422bca600ff6711dR221
*ran here and fails here*
https://github.com/facebook/react/blob/b1768b5a48d1f82e4ef4150e0036c5f846d3758a/src/renderers/dom/shared/utils/isEventSupported.js#L51

### Minimal reproduction case

```javascript
  const { window: win } = new JSDOM(
  '<!doctype html><html><body></body></html>',
  {
    runscripts: 'dangerously',
    beforeParse: (window) => {
      const eventName = 'scroll';
      const element = window.document.createElement('div');
      element.setAttribute(eventName, 'return;');
      const isSupported = typeof element[eventName] === 'function';
      console.log('####', typeof element[eventName]);
    }
  }
);
```
Console will show `undefined` not `function`

### How does similar code behave in browsers?

no errors in browser

**Comment by domenic** [comment]
`eventName` should be `onscroll`, not `scroll`, right?

**Comment by hammer65** [comment]
correct. Not camel case

**Comment by hammer65** [comment]
Okay my mistake but then I have no idea where this error is coming from

**Comment by Zirro** [comment]
You've written `runscripts` rather than `runScripts`. Replacing it (and `scroll` with `onscroll`) resolves the issue in your reproduction case.

**Comment by domenic** [comment]
Great find, thanks @Zirro!
