### ISSUE TITLE
XHR implementation corrupts download when resizing buffer (at 1MB boundary)

### ISSUE THREAD

**Issue by metamatt** [tmpvar/jsdom#1875]
### Basic info:

- **Node.js version:** 6.10
- **jsdom version:** 11.0

### Minimal reproduction case

Dunno about minimal. You need to be serving a file above 1MB and try to GET it via XHR. I noticed this while trying to get jsdom to run an app that uses systemjs and traceur, and traceur.js is about 1.3MB, and systemjs throws a SyntaxError trying to `eval` the (corrupted) content of traceur.js.

I think this patch fixes it:

```
diff --git a/node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js b/node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js
index 3884d1d..2b6b00d 100644
--- a/node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js
+++ b/node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js
@@ -909,12 +909,10 @@ module.exports = function createXMLHttpRequest(window) {
           properties.bufferStepSize *= 2;
         }
         const tmpBuf = Buffer.alloc(properties.bufferStepSize);
-        properties.responseBuffer = Buffer.concat([properties.responseBuffer, chunk]);
         properties.responseBuffer.copy(tmpBuf, 0, 0, properties.responseBuffer.length);
         properties.responseBuffer = tmpBuf;
-      } else {
-        chunk.copy(properties.responseBuffer, properties.totalReceivedChunkSize - chunk.length, 0, chunk.length);
       }
+      chunk.copy(properties.responseBuffer, properties.totalReceivedChunkSize - chunk.length, 0, chunk.length);
       properties.responseCache = null;
       properties.responseTextCache = null;
       properties.responseXMLCache = null;
```

Seems like there should be a test case for this in https://github.com/tmpvar/jsdom/tree/master/test/web-platform-tests/to-upstream/XMLHttpRequest but I'm not quite sure how to write that.

I confirmed that

- without the above patch, the original manifestation I saw (corrupt content of traceur.js) goes away if I set the initial buffer size to 2*1024*1024 instead of 1*1024*1024
- with the above patch, things seem to work fine end to end in a few cases I tried even if I stress the buffer resize behavior more aggressively by setting the initial buffer size to 1K instead of 1MB

**Comment by metamatt** [comment]
I think the actual bug is this: for terminology, let's say the physical buffer is the allocated size and the logical buffer is the prefix of that accounted for by `totalReceivedChunkSize` (in practice, the rest of the physical buffer is 0-filled at allocation time and remains that way until the logical buffer grows to fill it). The [`Buffer.concat` call at line 912](https://github.com/tmpvar/jsdom/blob/b1b7f230132806617c53b076f521b4b0ab854226/lib/jsdom/living/xmlhttprequest.js#L912) concats the chunk to the end of the physical buffer, not the logical buffer, that is, ignoring the `totalReceivedChunkSize`. This results in the remaining 0-padding (the difference between the logical buffer and the physical buffer) getting spliced into the data, pushing the new chunk later in the combined buffer, then the `Buffer.copy` call at line 913 truncates the new buffer to the right length, which truncates the new chunk.

So if we get 2 chunks of length 5 and an original allocation size of 8:

- we want AAAAA + BBBBB = AAAAABBBBB,
- instead we have AAAAA000 (but we know the receivedChunkSize is 5)
- then concat AAAAA000 + BBBBB = AAAAA000BBBBB
- but we know the receivedChunkSize is 10 so we truncate and now we have AAAAA000BB

The patch I proposed above fixes this problem by avoiding the `Buffer.concat` call which doesn't know about the logical size of the buffer, but also avoids an extra copy (we just put the bytes directly where they belong in the new buffer), and makes the code more uniform (we always handle the new chunk with the same `chunk.copy` call).

**Comment by domenic** [comment]
Can you provide the file? I tried generating one via `"abcd".repeat(260)` and it didn't get corrupted, hmm.

**Comment by domenic** [comment]
Oh, duh, I was a few orderes of magnitude off in how many repeats I need...
