### ISSUE TITLE
Constructing JSDOM with a URL doesn't update the origin to reflect that URL

### ISSUE THREAD

**Issue by shirakaba** [tmpvar/jsdom#1883]
### Basic info:

- **Node.js version:** v7.8.0
- **jsdom version:** 11.0.0

#### jsdom_setup.js

```js
/* from: https://github.com/airbnb/enzyme/blob/master/docs/guides/jsdom.md */
"use strict";
const { JSDOM } = require('jsdom');
const DEFAULT_HTML = '<html><body></body></html>';
const jsdom = new JSDOM(DEFAULT_HTML, {
    url: "http://www.bbc.co.uk",
    referrer: "http://www.bbc.co.uk",
    contentType: "text/html",
    userAgent: "node.js",
    includeNodeLocations: true
});
const { window } = jsdom;

global.window = window;
global.document = window.document;
global.navigator = {
    userAgent: 'node.js'
};

const props = Object.getOwnPropertyNames(window)
    .filter(prop => typeof global[prop] === 'undefined')
    .map(prop => Object.getOwnPropertyDescriptor(window, prop));
Object.defineProperties(global, props);
```

#### Test.ts (this is TypeScript, but the built javascript is identical)
```js
import {JSDOM} from 'jsdom';

it("Should set origin, preventing CORS complaints.", function(done){
    expect(window.location.href).to.equal("http://www.bbc.co.uk/"); // This assertion passes.
    expect(location.origin).to.equal("http://www.bbc.co.uk"); // This assertion fails. Equals: null

    let xhr = new XMLHttpRequest();
    xhr.onreadystatechange = () => {
        if(xhr.readyState !== XMLHttpRequest.DONE) return;
        xhr.onreadystatechange = null;
        if(xhr.status === 0) return done(new Error("HTTP status 0."));
        done();
    };
    xhr.open("GET", "http://www.bbc.co.uk", true);
    xhr.onerror = (e) => done(new Error("The fetch failed."));
    xhr.send(null);
});
```

The assertion that the origin matches that of the requested URL fails:
`AssertionError: expected 'null' to equal 'http://www.bbc.co.uk'`

If we comment out that line and allow the XHR to proceed, we get the following errors:
* `Error: Cross origin null forbidden` – The origin was null at the time of request, just like the assertion showed previously.
* `Error: The fetch failed.` – The error message I chose here reflects [whatwg diagnosis](https://xhr.spec.whatwg.org/#events) for an error firing on the `XMLHttpRequest.onerror` event handler.
* `Error: HTTP status 0.` – Symptomatic of a CORS issue.

#### mocha.opts
```
--compilers ts:ts-node/register
--require tsconfig-paths/register
--require jsdom-global/register
--require jsdom_setup.js
```

### node & mocha invocation
`/usr/local/bin/node /Users/shirakaba/Sites/node_modules/mocha/bin/_mocha --require ts-node/register --ui bdd --reporter /Applications/WebStorm.app/Contents/plugins/NodeJS/js/mocha-intellij/lib/mochaIntellijReporter.js /Users/shirakaba/Sites/test/Test.ts --grep "XHR Should set origin, preventing CORS complaints\.$"`

### How does similar code behave in browsers?

Have tried very hard, but I can't figure out how to set up my already monstrous Webpack-Typescript-Karma-Mocha-Chai stack with a browser instead of JSDOM, sorry! I would be very interested to learn how.

**Comment by domenic** [comment]
Sorry, I'm not able to debug your issue as I don't have TypeScript installed. Additionally, I need a minimal repro that does not use third-party frameworks like Mocha, or put things on the global (see https://github.com/tmpvar/jsdom/wiki/Don't-stuff-jsdom-globals-onto-the-Node-global. Please see the issue template for how to create a minimal repro.

Happy to reopen if you edit your post to conform to the issue reporting guidelines.

**Comment by shirakaba** [comment]
@domenic Thank you very much for directing me to that; my singleton jsdom setup (achieved through use of the `jsdom-global` library and the `jsdom-setup.js` configuration file) did appear to be the root of the problem, and with some refactoring, I was able to remove both. Now my setup instantiates a jsdom specifically for each test case.

For the benefit of other users, here is my resulting working setup. I think we can call it a *TypeScript-Mocha-Chai-Node-JSDOM* stack; although I additionally have files for Webpack and Karma floating around, I don't think that they are ultimately involved:

#### `${PROJECT_ROOT}/test/Test.ts`

Note: I've tried to keep this Typescript code 100% Javascript-compatible. Older versions of Javascript lack `let`, `const`, and arrow functions, but this TypeScript code should work as Javascript without any changes as long as the Javascript environment's version is modern enough.

```js
import { expect } from 'chai';
import {JSDOM} from 'jsdom'; // IMPORTANT: we will be using jsdom version 11, using the jsdom version 10+ API.
/* If you are not using commonJS-style module-loading, try this syntax instead: */
// const { expect } = require("chai").expect;
// const { JSDOM } = require("jsdom");

describe("JSDOM test", function () {
    let TARGET_ORIGIN = "http://www.bbc.co.uk";
    let window;
    let document;
    let XMLHttpRequest;
    before(() => {
        let dom = new JSDOM("<html><body></body></html>", {
            url: TARGET_ORIGIN,
            referrer: TARGET_ORIGIN,
            contentType: "text/html",
            userAgent: "node.js",
            includeNodeLocations: true
        });
        window = dom.window;
        document = window.document;
        XMLHttpRequest = window.XMLHttpRequest;

        const div = document.createElement("div");
        div.id = "confidenceDiv";
        document.body.appendChild(div);
    });

    it("Tests should use JSDOM's global variables", () => {
        expect(typeof XMLHttpRequest).to.equal("function");
        expect(window.location.origin).to.equal(TARGET_ORIGIN);
        expect(typeof document).not.to.equal("undefined");
    });

    it("The jsdom's state set up during before() should persist for each test", () => {
        expect(document.getElementById('confidenceDiv')).not.to.equal(null);
    });

    it("Should not run into CORS issues during XHR to the URL used for JSDOM's construction", (done) => {
        expect(window.location.origin).to.equal(TARGET_ORIGIN);

        let xhr = new XMLHttpRequest();
        xhr.onreadystatechange = () => {
            if(xhr.readyState !== XMLHttpRequest.DONE) return;
            xhr.onreadystatechange = null;
            if(xhr.status === 0) return done(new Error("HTTP status 0, likely indicating CORS issue."));
            if(xhr.status !== 200) return done(new Error("HTTP status " + xhr.status + "; expected 200."));
            // console.log(xhr.responseText);
            done();
        };
        xhr.open("GET", "http://www.bbc.co.uk", true);
        xhr.onerror = (e) => done(new Error("The fetch failed."));
        xhr.send(null);
    });

    after(() => {
       // May be good practice in case something we end up using something like setInterval that tries to keep jsdom alive.
       window.close();
    });
});
```

The tests all pass :)

#### `${PROJECT_ROOT}/test/mocha.opts`

This is the default location that Mocha expects to find the `mocha.opts` configuration file (I haven't investigated how to change it).

```
--compilers ts:ts-node/register
--require tsconfig-paths/register
```

* I am using `ts:ts-node/register` to compile the TypeScript automatically to Javascript (you will need to do `npm install --save-dev ts-node/register` to get this library).
* I am using `tsconfig-paths/register` because my project involves import paths starting from `src/` rather than always using relative import paths. If you are using relative import paths, you won't need this line.

---

I can run any test from my IDE (WebStorm) by clicking the 'play' button next to a test (in this case, the top-level one labelled 'JSDOM test'). This automatically runs the following bash script, which one could type out in the command line manually if one doesn't have an IDE with Mocha integration:
`/usr/local/bin/node /Users/shirakaba/Sites/example_project/node_modules/mocha/bin/_mocha --require ts-node/register --ui bdd --reporter /Applications/WebStorm.app/Contents/plugins/NodeJS/js/mocha-intellij/lib/mochaIntellijReporter.js /Users/shirakaba/Sites/example_project/test/JSDOMTest.ts --grep "JSDOM test "`

**Comment by warmans** [comment]
I ran into this issue and was able to fix it by just importing a specific XMLHttpRequest instead of falling back to what presumably added to the globals by `jsdom-global/register`.

Might be useful info for somebody.

e.g.
```
import { XMLHttpRequest } from "xmlhttprequest";

class NodeXhrFactory extends XhrFactory {
    build(): XMLHttpRequest {
        return new XMLHttpRequest();
    }
}
``

**Comment by jasdeep-compro** [comment]
Hi @shirakaba ,

I'm trying to set up a MOCHA-Typescript-Node-JSDOM environment. I tried executing your test file, the first and the third test passes. But the second test fails ("The jsdom's state set up during before() should persist for each test"). I can't find a solution to check for a particular id set for an element.

**Comment by shirakaba** [comment]
@jasdeep-compro Now that I look back on the code I submitted here, it appears that the element with id "confidenceDiv" was never appended into the DOM in the first place. Replace my original `before()` block with this:

```js
before(() => {
    // jsdom-global, when invoked as below, creates a jsdom according to params and sets its document and window as NodeJS's.
    cleanup = require('jsdom-global')("<html><body></body></html>", {
        url: TARGET_ORIGIN,
        referrer: TARGET_ORIGIN,
        contentType: "text/html",
        userAgent: "node.js",
        includeNodeLocations: true
    });

    // Referencing 'document' and 'window' now directly references those of NodeJS.
    // Adding these three lines to hopefully fix my second test:
    const div = document.createElement('div');
    div.id = "confidenceDiv";
    document.body.appendChild(div);
});
```

Does the second test now pass?

**Comment by jasdeep-compro** [comment]
@shirakaba Thanks for your reply. Yes it passes now. 

Is there a way to assert for a particular ID in the Target Location ?

For example in Target Location = "http://www.bbc.co.uk" , can we check If a particular id is present or not.

**Comment by shirakaba** [comment]
@jasdeep-compro Do you mean something like this?

```js
it("A certain element id should be present depending on the origin that has been set.", () => {
    if(TARGET_ORIGIN === "http://www.bbc.co.uk"){
        expect(document.getElementById('bbcDiv')).not.to.equal(null);
    } else if (TARGET_ORIGIN === "https://www.cadbury.co.uk"){
        expect(document.getElementById('cadburyDiv')).not.to.equal(null);
    } else {
        throw new Error("Unexpected origin: " + TARGET_ORIGIN);
    }
});
```

**Note:** even if you set your `url` as www.bbc.co.uk, the content of JSDOM's DOM will *not* match that of www.bbc.co.uk, because you've only initialised the DOM content as `<html><body></body></html>`. The `url` field has the [following purpose](https://github.com/jsdom/jsdom#customizing-jsdom):

> `url` sets the value returned by `window.location`, `document.URL`, and `document.documentURI`, and affects things like resolution of relative URLs within the document and the same-origin restrictions and referrer used while fetching subresources. It defaults to `"about:blank"`.

If you want to initialise the DOM so that it has the same contents as the page that you've set your url as, you'll need to refer to JSDOM's [documentation](https://github.com/jsdom/jsdom#convenience-apis) (see the `fromURL()` and `fromFile()` methods).
