### ISSUE TITLE
Testing with jsdom crashes on Object.assign (Object undefined)

### ISSUE THREAD

**Issue by haf** [tmpvar/jsdom#1884]
JSDOM v11.0

```
node_modules/rxjs/util/assign.js:22
    return root.Object.assign || assignImpl;
                      ^
TypeError: Cannot read property 'assign' of undefined
```

**Code to reproduce:** `import { Observable } from 'rxjs/Rx';` with 

setup.js

```
require('babel-register')();
import chai from 'chai';
chai.config.includeStack = true;

/* In case we want to use JSDOM */

const { JSDOM } = require('jsdom');
const jsdom = new JSDOM('<!doctype html><html><body></body></html>');
const { window } = jsdom;

function copyProps(src, target) {
    const props = Object.getOwnPropertyNames(src)
        .filter(prop => typeof target[prop] === 'undefined')
            .map(prop => Object.getOwnPropertyDescriptor(src, prop));
              Object.defineProperties(target, props);
}

global.window = window;
global.document = window.document;
global.navigator = {
    userAgent: 'node.js'
};
copyProps(window, global);
```

Command line:

`cross-env BABEL_ENV=test mocha --harmony --compilers js:babel-register --require tests/helpers/nullCompiler.js --require intl tests/helpers/setup.js $(find app -name '*.test.js')`

Similar to http://jamesknelson.com/testing-in-es6-with-mocha-and-babel-6/

**Expected behavior:** Object should exist, because we fill it in.

**Actual behavior:** Object is `undefined`.

**Additional information:**

**Comment by domenic** [comment]
Sorry, this did not follow the issue template. I cannot run that code in Node.js because of the nonstandard `import` syntax. It also uses several third party dependencies, which we cannot be responsible for debugging fo you.

**Comment by haf** [comment]
Better?

Yes, the point of jsdom is to test third party dependencies. I understand you cannot support arbitrary 3rd party thingies, but is `Object` supposed to be undefined?

**Comment by domenic** [comment]
No, but who knows, maybe one of the third parties messed it up. We can't debug until you can provide code showing it's a jsdom problem, by giving a sample without any third-party dependencies.

**Comment by jonknowles** [comment]
This issue seems to be caused in Node by JSDOM creating a window object in globalJSDom, which rxjs then tries to use as it's root element. Rsjx then thinks it's running in the browser, not node, so it tries to use properties on the window object that aren't there.  I fixed similar issues in my project by adding window.Object = Object and window.Math = Math right after globalJSDom() was called.
