### ISSUE TITLE
CustomEvent is not inspectable (but is in normal browser implementation)

### ISSUE THREAD

**Issue by msumme** [tmpvar/jsdom#1888]
### Basic info:

- **Node.js version: 8.0** 
- **jsdom version: 10** 

I can't check CustomEvent type, or detail.

From a jest test
```
const event = new CustomEvent('customevent', {detail: {propName: 'value'}});
expect(event.type).toEqual('customevent');
expect(event.detail).toEqual({propName: 'value'});
```
You can definitely access those properties in the Chrome version of custom events, and I believe others.

When logging it in the node console: 
```
 [ CustomEvent {
          isTrusted: [Getter],
          [Symbol(impl)]: 
           CustomEventImpl {
             type: 'pushstate',
             bubbles: false,
             cancelable: false,
             detail: [Object],
             target: null,
             currentTarget: null,
             eventPhase: 0,
             _initializedFlag: true,
             _stopPropagationFlag: false,
             _stopImmediatePropagationFlag: false,
             _canceledFlag: false,
             _dispatchFlag: false,
             isTrusted: false,
             timeStamp: 1497310636702,
             [Symbol(wrapper)]: [Circular] } } ]

```

It looks like the interesting details are hidden behind a Symbol and can't be accessed?  I don't think that's how it should work, since target, detail, and type are all normally needed to do event processing.

**Comment by Sebmaster** [comment]
Have you actually tried that test? `event.type` is an accessor and definitely accessible.

**Comment by domenic** [comment]
Closing as this does not provide a repro case we can run in pure Node. Happy to reopen if such a case is provided.

**Comment by msumme** [comment]
Ah shoot, I misread my console output.  That is the real output, but the test had a step in the middle, and it was wrapped in an extra unexpected array.  Sorry!
