### ISSUE TITLE
Setting src on image should kick off request

### ISSUE THREAD

**Issue by stevvooe** [tmpvar/jsdom#189]
If I load the following with jsdom, I expect that a request for the image should be kicked off when 

    <html>
      <head>
      </head>
      <body>
        <script src="http://code.jquery.com/jquery-1.5.min.js"></script>
        <script language="javascript">
          i = new Image();
          i.src = 'http://localhost/favicon.ico';
          console.log(i);
        </script>
      </body>
    </html>

I am attempting this with following features:

    {features:
        {
          FetchExternalResources: [ 'script', 'img' ],
          ProcessExternalResources: [ 'script', 'img' ],
          MutationEvents: '2.0',
          QuerySelector: false } }

I am not sure if this is the correct behavior or not, but I would expect this work like it works in a browser.

**Comment by toddpi314** [comment]
mitar's solution worked me.
Also, it is pretty easy to just create a class that implements src, onload, onerror and is impl. with an underlying request.

**Comment by Cristy94** [comment]
@mitar 

I too need to use a functional new Image() because I need to get image width/height.

What exactly did you change? Do you use node-canvas, or you just copied that source code form image.js ? Because I can not use node-canvas (failed to install it).

Is there a better way now to create a new Image() ?

**Comment by mitar** [comment]
I use node-canvas.

**Comment by lehni** [comment]
This is now possible, since #1366 has been merged (closing #1365).

You need the `node-canvas` module and set `FetchExternalResources: ["img"]` for it to work.

I suggest that this issue here can be closed now, too. What do you think, @tmpvar?

**Comment by domenic** [comment]
Yep, agreed.

**Comment by aaani** [comment]
So I added 
```
var Canvas = require("canvas");
```
and then later in my code
```
jsdom.env({
             ...
            FetchExternalResources: ["img"],
```

But that doesn't fix the issue. Am I missing anything? @lehni @domenic

**Comment by domenic** [comment]
Did you properly nest `FetchExternalResources` inside a `features` option?

(Sorry about how horrible the API is; [newapi](https://github.com/tmpvar/jsdom/blob/newapi/lib/newapi1.md) is coming...)

**Comment by aaani** [comment]
I added it in inside jsdom.env. This is what my config looks like:
```
        jsdom.env({
            //Seed html so that this it doesn't try to load url
            html:'<html></html>',
            //workaround to set window.Location
            url: 'https://localhost',
            FetchExternalResources: ["img"],
            //load all dependencies
            src: [
                fs.readFileSync('dist/myfile.min.js', 'utf-8'),
            ],

            done(err, createdWindow) {
                if (err) return done(err);
                window = createdWindow;
                //forward browser logs to node logs
                window.console = global.console;
                done();
            }
        });
```

**Comment by aaani** [comment]
NVM. I nested FetchExternalResources  inside features and now it works fine. 
BTW I am really excited for the new API. Thanks!
