### ISSUE TITLE
TypeError: Cannot read property '_location' of null

### ISSUE THREAD

**Issue by Enverbalalic** [tmpvar/jsdom#1893]
### Basic info:

NodeJS version: v6.10.3
jsdom version: jsdom@11.0.0

### Minimal reproduction case

```js
const jsdom = require("jsdom");
const { JSDOM } = jsdom;
const window = (new JSDOM(``, { runScripts: "outside-only" })).window;

window.setTimeout(function() {
        window.close();
        window.setTimeout(function () {
                window.location.href = "hello";
        }, 300);
}, 1000);
```
In browsers after window.close(); all pending timeouts are cleared and new ones are not set up.

**Comment by domenic** [comment]
Great repro code, thanks! I will investigate this as soon as I am able to.
