### ISSUE TITLE
RequestError: Error: unable to verify the first certificate

### ISSUE THREAD

**Issue by magician11** [tmpvar/jsdom#1897]
### Basic info:

Using Node `v7.9.0`

```
{
  "dependencies": {
    "jsdom": "^11.0.0"
  }
}
```

### Minimal reproduction case

```js
const { JSDOM } = require('jsdom');

JSDOM.fromURL('https://www.sfcinemacity.com/showtime/cinema/9936').then(dom => {
  console.log(dom.serialize());
});
```

This URL works in a browser, but I get the above error running it in Node.js. Any idea how to get this to work?

Thanks.

**Comment by TimothyGu** [comment]
This error is coming from Node.js, not jsdom:

```js
https.get('https://www.sfcinemacity.com/showtime/cinema/9936', (err) => console.log(err))
```

results in

```
Error: unable to verify the first certificate
    at TLSSocket.<anonymous> (_tls_wrap.js:1098:38)
    at emitNone (events.js:105:13)
    at TLSSocket.emit (events.js:207:7)
    at TLSSocket._finishInit (_tls_wrap.js:628:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:458:38)
```

An [SSL Test](https://www.ssllabs.com/ssltest/analyze.html?d=www.sfcinemacity.com&latest) reveals that the server has an incomplete certificate chain, which Chrome ignores, but not Firefox:

![screenshot from 2017-06-27 11-54-39](https://user-images.githubusercontent.com/1538624/27570266-6aa6240c-5b2f-11e7-91f0-d5e5a28814e3.png)

**Comment by magician11** [comment]
Interesting, I just ran it again and it worked. Guess they just fixed their certs.

Thanks for looking into it. Just a coincidence that the first time I tried jsdom they had cert issues.
