### ISSUE TITLE
customElements is not defined

### ISSUE THREAD

**Issue by snuggs** [tmpvar/jsdom#1900]
### Basic info:

- **Node.js version:** 7.8.0 
- **jsdom version:** 11.0.0 

### Minimal reproduction case

```js
const { JSDOM } = require("jsdom");

const options = { runScripts: 'dangerously' };
const dom = new JSDOM(``, options);

customElements.define ('foo-bar', ...);
window.customElements.define ('foo-bar', ...);

```

Am getting `customElements is not defined` and `Cannot read property 'define' of undefined`
![capture d ecran 2017-06-27 a 19 19 54](https://user-images.githubusercontent.com/38223/27614152-d551cfac-5b6d-11e7-9e02-f479660c69e3.png)
![capture d ecran 2017-06-27 a 19 16 39](https://user-images.githubusercontent.com/38223/27614153-d5557206-5b6d-11e7-90f2-0ef3fbc672a9.png)

**Comment by Sebmaster** [comment]
Yes, web components ar enot supported. There's already an issue for this: #1030.

**Comment by snuggs** [comment]
Thanks @Sebmaster
