### ISSUE TITLE
Move location implementation into separate module

### ISSUE THREAD

**Issue by ForbesLindesay** [tmpvar/jsdom#1901]
I'm attempting to build a full browser on top of jsdom (currently taxi-driver on top of zombie.js) and I'm doing my best not to mess to mess too much with the internals of jsdom, so I can more easily upgrade in the future.  The first difficulty I'm hitting is that I have to have my own implementation of the "location" object.  It would be really helpful if we could have a proper spec compliant location implementation that just required you to pass in the url of the document and an implementation of "locationObjectNavigate" and then it could handle everything else.

**Comment by domenic** [comment]
I don't think moving it into a separate module is the way to go here, but we could certainly work on hooks that improve the ability to intercept navigation.

However, we'd ideally prefer such improvements to be contributed to jsdom itself.

**Comment by ForbesLindesay** [comment]
In retrospect, I don't think this would help anyway.  Replacing the implementation of `window.location` is super-hard because it's unforgeable or whatever. Upstreaming stuff has always been my preferred solution.  Unfortunately updating zombie to work on the latest jsdom would be pretty difficult, so I think the right solution is to upstream enough stuff that zombie becomes mostly un-necessary.
