### ISSUE TITLE
How do you load external scripts?

### ISSUE THREAD

**Issue by cg433n** [tmpvar/jsdom#1914]
jsdom can run scripts which are inline inside of the document's `<head>` tag, but how do you make it run scripts which are linked to in the document head via `<script src="">`?

For options I'm using:

```js
{
    url: url,
    resources: 'usable',
    runScripts: 'dangerously',
}
```

### Basic info:

- **Node.js version: 8.1.2**
- **jsdom version: 11.1.0**

### Minimal reproduction case:

```js
// index.js
const request = require('request')
const jsdom = require('jsdom')
const {JSDOM} = jsdom
const url = 'http://localhost:8000'

request(url, (error, response, body) => {
  const options = {
    url: url,
    resources: 'usable',
    runScripts: 'dangerously',
  }
  
  const dom = new JSDOM(body, options)
  
  console.log(dom.window.document.body.children.length) // Expecting to see `1`
  console.log(dom.window.document.body.innerHTML) // Expecting to see `<h1>Hello world</h1>`
})
```

```js
// external.js
document.addEventListener('DOMContentLoaded', () => {
  document.write('<h1>Hello world!</h1>')
})
```

```html
<!-- index.html -->
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>JSDOM test</title>
    <script src="external.js"></script>
  </head>
  <body>
  </body>
</html>
```

Complete minimum working example: https://github.com/cg433n/jsdom-test

**Comment by domenic** [comment]
The issue here is that `DOMContentLoaded` is an asynchronous event. You're logging before it has a chance to happen. You need to wait for it to fire; only then will your `document.write()` happen.

Something like this should probably work:

```js
const dom = new JSDOM(body, options)

dom.window.document.addEventListener('DOMContentLoaded', () => {
  // We need to delay one extra turn because we are the first DOMContentLoaded listener,
  // but we want to execute this code only after the second DOMContentLoaded listener
  // (added by external.js) fires.
  setImmediate(() => {
    console.log(dom.window.document.body.children.length) // Expecting to see `1`
    console.log(dom.window.document.body.innerHTML) // Expecting to see `<h1>Hello world</h1>`
  });
});
```

**Comment by cg433n** [comment]
I see! You guys are fantastic - keep up the good work!

**Comment by hugolpz** [comment]
`setImmediate` [is risky on the long run](https://developer.mozilla.org/en-US/docs/Web/API/Window/setImmediate).
![Screenshot_2020-09-02_18-46-34](https://user-images.githubusercontent.com/1420189/92012400-af25aa00-ed4c-11ea-8937-f47c5cb85d79.png)
