### ISSUE TITLE
Getting cookies from documents

### ISSUE THREAD

**Issue by ymetalnikov** [tmpvar/jsdom#1918]
### Basic info:

- **Node.js version:** v8.1.3
- **jsdom version:** 11.1.0

### Minimal reproduction case

```js
// my.test.js
const jsdom = require("jsdom");
const JSDOM = jsdom.JSDOM;

const dom = new JSDOM(`<body>
    <script>document.cookie = 'name1=xx;name2=yy;'</script>
</body>`, { runScripts: "dangerously" });

// name1=xx
console.log( dom.window.document.cookie);
```

run: $ node my.test.js

Could you help me?
I try set cookie in JSDOM, but when i check it in documents i receive only first part of it.

Expected result: name1=xx;name2=yy;
Got result: name1=xx

How to get it all? 

thanks in advance

**Comment by Sebmaster** [comment]
You're using document.cookie wrong. That's not how it works in browsers. If you want to set multiple cookies, you need to set it multiple times.
