### ISSUE TITLE
Is jsdom extendable in such a way that I can start making a JS-based browser?

### ISSUE THREAD

**Issue by trusktr** [tmpvar/jsdom#1923]
Can I use jsdom to (theoretically) start making a purely JS-based browser. So when HTML is parsed, have it start running logic, for example to make an `<img>` element actually fetch an image, etc. I would have to make a renderer, and connect it to that, etc. Does the API allow such a thing to be possible (even if it would be super much work to recreate a browser, but just theoretically)?

**Comment by TimothyGu** [comment]
A headless browser based on jsdom has in fact already been created: https://github.com/assaf/zombie zombie uses a very old version of jsdom currently, and upgrading to latest jsdom requires nontrivial work. Its maintainer @ForbesLindesay is trying to [upstream the changes necessary](https://github.com/tmpvar/jsdom/pulls/ForbesLindesay) for jsdom itself to be navigable.

Rendering, however, is a much bigger beast. I *assume* it technically could be done, but it would be a huge amount of work.

**Comment by domenic** [comment]
Closing, as @TimothyGu's answer covers it :)
