### ISSUE TITLE
Can't load external js

### ISSUE THREAD

**Issue by dwqs** [tmpvar/jsdom#1924]
### Basic info:

- **Node.js version:** v8.1.3
- **jsdom version:** v 11.1.0

### Minimal reproduction case

```js
const { JSDOM } = require("jsdom");

const options = {
    runScripts: "dangerously",
    resources: "usable"
};
const dom = new JSDOM(`
  <!DOCTYPE html><html><body><div id="test"></div><script src="http://cdn.bootcss.com/jquery/2.1.1/jquery.min.js"></script></body></html>
`, options);

console.log(dom.window.jQuery, dom.window.$)
```
The output in terminal is `undefined`. And if load external js from a relative path, will get error:

```
Error: Could not load script: "./vv.js"
    at /Users/pomy/git/vue-mobx/node_modules/jsdom/lib/jsdom/browser/resource-loader.js:44:23
    at Object.check (/Users/pomy/git/vue-mobx/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:91:11)
    at ReadStream.<anonymous> (/Users/pomy/git/vue-mobx/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:110:12)
    at ReadStream.wrappedEnqueued (/Users/pomy/git/vue-mobx/node_modules/jsdom/lib/jsdom/browser/resource-loader.js:255:16)
    at emitOne (events.js:115:13)
    at ReadStream.emit (events.js:210:7)
    at fs.js:1942:12
    at FSReqWrap.oncomplete (fs.js:135:15) { Error: ENOENT: no such file or directory, open './vv.js' errno: -2, code: 'ENOENT', syscall: 'open', path: './vv.js' }
```
For `vv.js`:
```
var a =1;
```
I've trawled the documentation and tried lots of variations but nothing works.

**Comment by vsemozhetbyt** [comment]
I may be wrong, but it seems the case of https://github.com/tmpvar/jsdom#asynchronous-script-loading
Yor script may not be loaded and executed yet when you try to get `dom.window.jQuery`.

**Comment by TimothyGu** [comment]
http://cdn.bootcss.com/jquery/ returns a 404 here.

**Comment by dwqs** [comment]
Here is the link: [http://cdn.bootcss.com/jquery/2.1.1/jquery.min.js](http://cdn.bootcss.com/jquery/2.1.1/jquery.min.js) @TimothyGu

**Comment by dwqs** [comment]
I will be try, thanks. @vsemozhetbyt

**Comment by dwqs** [comment]
Hi @vsemozhetbyt , I change my code according to the document:

```
let {JSDOM} = require('jsdom')

const options = {
    runScripts: "dangerously",
    resources: "usable"
};
const dom = new JSDOM(`
  <!DOCTYPE html><html><body><div id="test"></div><script src="http://cdn.bootcss.com/jquery/2.1.1/jquery.min.js"></script></body></html>
`, options);

console.log(dom.window)

dom.window.onModulesLoaded = () => {
  console.log("ready to roll!");
};
```
The code can print `window` object in the terminal, but the second log can't be print. It seems doesn't work.

**Comment by vsemozhetbyt** [comment]
@dwqs I think this is not your case:

> The best way, **if you control the page in question**, is to use whatever mechanisms are given by the script loader to detect when loading is done.

You do not control jquery lib here, so way to fix it is posibly this:

> If you do not control the page, you could try workarounds such as polling for the presence of a specific element.

> For more details, see the discussion in #640, especially @matthewkastor's [insightful comment](https://github.com/tmpvar/jsdom/issues/640#issuecomment-22216965).

**Comment by dwqs** [comment]
Thanks very much!!!

**Comment by yairEO** [comment]
I can't seem to find what happened to `jsdom.jQueryify` .... there's NOTHING in the WIKI or issues :(
