### ISSUE TITLE
Clicking <label> causes disabled checkbox to become checked

### ISSUE THREAD

**Issue by schreifels** [tmpvar/jsdom#1925]
### Basic info:

- **Node.js version:** 6.11.1
- **jsdom version:** 11.1.0

It appears that if you trigger a click on a `<label>` that wraps a disabled `<input type="checkbox">`, jsdom will change the `checked` property. This does not occur if you trigger the click on the `<input>` directly. This is not the behavior in Chrome.

### Minimal reproduction case

```js
const { JSDOM } = require('jsdom');

const dom = new JSDOM('\
  <!DOCTYPE html>\
  <html>\
    <body>\
      <label><input type="checkbox"></label>\
    </body>\
  </html>\
');

const label = dom.window.document.querySelector('label');
const input = dom.window.document.querySelector('input');

label.click();
console.log('expecting true, actual', input.checked); // actual = true

input.click();
console.log('expecting false, actual', input.checked); // actual = false

input.disabled = true;

input.click();
console.log('expecting false, actual', input.checked); // actual = false

label.click();
console.log('expecting false, actual', input.checked); // actual = true (UNEXPECTED)
```

Output:

```
expecting true, actual true
expecting false, actual false
expecting false, actual false
expecting false, actual true (UNEXPECTED)
```

### How does similar code behave in browsers?

In OSX/Chrome 59:

```
expecting true, actual true
expecting false, actual false
expecting false, actual false
expecting false, actual false
```

https://jsfiddle.net/cja7cpng/

**Comment by domenic** [comment]
Great catch, thank you! It looks like the spec is kind of vague on this, so it's understandable that we got it wrong. But it should be a pretty easy fix. Are you interested in submitting a pull request?

The implementation code to modify would be at https://github.com/tmpvar/jsdom/blob/master/lib/jsdom/living/nodes/HTMLLabelElement-impl.js , and we'd want to write a test in web-platform-test format as per https://github.com/tmpvar/jsdom/blob/master/Contributing.md#web-platform-feature-tests

**Comment by schreifels** [comment]
@domenic Thanks for the quick reply! The code seems pretty straightforward -- thanks for pointing me in the right direction. I should have some time in the next few days to look at it. I will take a crack at a pull request.
