### ISSUE TITLE
set Timezone for jsdom

### ISSUE THREAD

**Issue by hoangtrongphuc** [tmpvar/jsdom#1936]
How can I set Timezone for jsdom ?
I requested to many pages and html return based on timezone of browser.
So I need to solution to get timezone is +0

**Comment by domenic** [comment]
jsdom doesn't really deal with timezones. So it's the same as any other software on your computer, I guess.

**Comment by hoangtrongphuc** [comment]
My computer timezones is +7, but when I crawler webpage, html returned based on timezone +2.
I think jsdom use other timezone when access web page

**Comment by domenic** [comment]
Can you provide a reproduction case? Please follow the new issue template.

**Comment by hoangtrongphuc** [comment]
Sry but my code is complex.
I will describe my situation: 
- I crawler with soccerway web page, and datetime are converted to your local PC time
- When I open browser in my local, I see datetime for match in +7
- When I crawler with node, I get data with time zone +2 in my database

**Comment by domenic** [comment]
OK. Without a code example, we cannot debug this situation, so I will close this issue. Happy to reopen if you can provide code we can use to debug.

**Comment by john-doherty** [comment]
You can do this with the [timezoned-date](https://github.com/thorn0/timezoned-date) module.
