### ISSUE TITLE
Error: Not implemented: HTMLFormElement.prototype.submit

### ISSUE THREAD

**Issue by runbb** [tmpvar/jsdom#1937]
Error
```php
HTMLInputElement {} HTMLInputElement {}
Error: Not implemented: HTMLFormElement.prototype.submit
    at module.exports (/home/xlmnxp/Documents/Nodejs/DownFrom99/node_modules/jsdom/lib/jsdom/browser/not-implemented.js:9:17)
    at HTMLFormElementImpl.submit (/home/xlmnxp/Documents/Nodejs/DownFrom99/node_modules/jsdom/lib/jsdom/living/nodes/HTMLFormElement-impl.js:68:5)
    at HTMLFormElement.submit (/home/xlmnxp/Documents/Nodejs/DownFrom99/node_modules/jsdom/lib/jsdom/living/generated/HTMLFormElement.js:18:21)
    at /home/xlmnxp/Documents/Nodejs/DownFrom99/app.js:12:10
    at process._tickCallback (internal/process/next_tick.js:109:7) undefined
```
```typescript
import { JSDOM } from "jsdom";

JSDOM.fromURL("http://localhost/").then((dom:JSDOM) => {
    let document = dom.window.document;
    let window = dom.window;

    let form = <HTMLFormElement> document.querySelector("form");
    let urlField = <HTMLInputElement> document.querySelector("input[name='formvalue']");
    let submitButton = <HTMLInputElement> document.querySelector("input[type='submit']");

    console.log(submitButton,urlField)
    
    urlField.value = "https://www.youtube.com/watch?v=RWjDLfx8Lww";

    form.submit()
    
})
```

**Comment by domenic** [comment]
Yes, indeed, form submission is not implemented. This is working as expected.

**Comment by StevenDewey** [comment]
@runbb did you find another solution for this? I am trying to do the same thing.

**Comment by StevenDewey** [comment]
@domenic do you have any ideas on how to accomplish this functionality? Perhaps another library?

**Comment by runbb** [comment]
@stefanbuck no :(

**Comment by islazh** [comment]
@domenic is there a reason why this has been unimplemented? Would you be open to a pull request to implement this?

**Comment by domenic** [comment]
See https://github.com/jsdom/jsdom#unimplemented-parts-of-the-web-platform. This is about navigation, and thus a huge undertaking. You're welcome to try, but please understand you'd need to be implementing basically all of https://html.spec.whatwg.org/multipage/browsing-the-web.html.

**Comment by maksymddd** [comment]
@domenic it would be nice to disable this error message.

**Comment by domenic** [comment]
You can do so; see the readme on jsdomErrors.

**Comment by YoruNoHikage** [comment]
Is it still possible to implement the handling of the inputs when the form is submitted?
`event.target[name]` are not defined.

**Comment by ssolders** [comment]
Ran into this when writing tests using Jest.
My workaround:

```
window.HTMLFormElement.prototype.submit = () => {}
```

Added this before I mount my component in the test case.
At least it keeps my console clean.

**Comment by janjaap** [comment]
I managed to silence the errors by doing:
```js
describe('submit', () => {
  let emit;

  beforeAll(() => {
    ({ emit } = window._virtualConsole);
  });

  beforeEach(() => {
    window._virtualConsole.emit = jest.fn();
  });

  afterAll(() => {
    window._virtualConsole.emit = emit;
  });

  it('should handle submit ', () => {
    ...
  });
});
```

**Comment by dlrice** [comment]
There is a nice workaround here https://kula.blog/posts/test_on_submit_in_react_testing_library/

**Comment by raquelhortab** [comment]
> Ran into this when writing tests using Jest.
> My workaround:
> 
> ```
> window.HTMLFormElement.prototype.submit = () => {}
> ```
> 
> Added this before I mount my component in the test case.
> At least it keeps my console clean.

Hi! I like your workaround but I am not sure where to do that, you thing you could help maybe? I have  the following code: (see I added your "fix" as the first statement in main())

```
const jsdom = require("jsdom");
const { JSDOM } = jsdom;

JSDOM.fromFile("index.html", null).then(dom => {
    main(dom.window);
});

function main(window){

  window.HTMLFormElement.prototype.submit = () => {}

  var oldAlert = window.alert;
  window.alert = function() {
    console.log("Alert fired with arguments: " + arguments);
    oldAlert.apply(window, arguments);
  };

  window.document.getElementsByTagName("button")[0].click();

}

```

but it is still raising the same `Error: Not implemented: HTMLFormElement.prototype.submit`

**Comment by bogem** [comment]
Solution that works for us:
```js
let origErrorConsole;

// Following code replaces the original window.console.error
// to ignore the "Not implemented: HTMLFormElement.prototype.submit".
//
// We use "form.onsubmit" event listener in some tests,
// but HTMLFormElement.prototype.submit is not implemented in JSDOM,
// although the tests are passing and handler is fired.
//
// More:
// https://github.com/jsdom/jsdom/issues/1937
// https://github.com/facebook/jest/issues/5223#issuecomment-489422244
beforeEach(() => {
  origErrorConsole = window.console.error;

  window.console.error = (...args: unknown[]) => {
    const firstArg = args.length > 0 && args[0];

    const shouldBeIgnored =
      firstArg &&
      typeof firstArg === 'string' &&
      firstArg.includes('Not implemented: HTMLFormElement.prototype.submit');

    if (!shouldBeIgnored) {
      origErrorConsole(...args);
    }
  }
})

afterEach(() => {
  window.console.error = origErrorConsole;
})
```

**Comment by forelabs** [comment]
If you don't care about the `submit` you can also disable submitting the form with
```html
<form onsubmit="return false;">
```

No more error message

**Comment by pahan35** [comment]
@domenic, could you please show us how to use a virtual console from the test file itself?

Let's suggest that the test file is next
```
import React from 'react'

import {render} from '@testing-library/react'

import ComponentWithSubmit from './ComponentWithSubmit'

test('Component with form', () => {
  const {getByText} = render(<ComponentWithSubmit />)
  expect(getByText('I am inside form')).toBeInTheDocument()
})
```

P.S: there is jest as a test runner

**Comment by domenic** [comment]
Sorry, you'll need to ask Jest for support on how to use Jest. The jsdom is only able to provide support for jsdom itself, not for any package that uses jsdom as a dependency.

**Comment by bl-JonathanRys** [comment]
I had a component using a form but not using submit on the form and was still seeing this error.  I solved it by adding type="button" to my other buttons within the form.

**Comment by brunogarcia** [comment]
Workaround:

Create a `jest.warnings.js` file at the root of your project.

```js
// jest.warnings.js
global.originalLogError = global.console.error;

global.console.error = (...args) => {
  /**
   * Avoid jsdom error message after submit a form
   * https://github.com/jsdom/jsdom/issues/1937
   */
  const errorMessage = "Not implemented: HTMLFormElement.prototype.submit";
  if (args && args[0].includes(errorMessage)) {
    return false;
  }

  global.originalLogError(...args);

  return true;
};
```

Add to your `jest.config.js` file this new line:
```js
// jest.config.js
module.exports = {
  setupFiles: ["./jest.warnings.js"]
};

```

**Comment by fantapop** [comment]
It would be great to add form submission specifically to the list of unimplemented features. I read this list before picking this library and did not associate navigation with form submission. Everything is great besides that!

**Comment by chrys-exaucet** [comment]
comibining  @bogem's lifecycle tips  and @brunogarcia  file separation  works just fine.


```js

// jest.warnings.ts

// see https://github.com/jsdom/jsdom/issues/1937
// @ts-ignore
let origErrorConsole: any;

beforeEach(() => {
  origErrorConsole = window.console.error;

  window.console.error = (...args: any []) => {
    const firstArg = args.length > 0 && args[0];

    const shouldBeIgnored =
      firstArg &&
      typeof firstArg === 'string' &&
      firstArg.includes('Not implemented: HTMLFormElement.prototype.submit');

    if (!shouldBeIgnored) {
      origErrorConsole(...args);
    }
  };
});

afterEach(() => {
  window.console.error = origErrorConsole;
});
```




````js

// jest.config.ts

const jestConfig = {
  preset: 'ts-jest',
  globals: {
    'ts-jest': {
      tsconfig: '<rootDir>/tsconfig.spec.json',
    },
  },
  setupFilesAfterEnv: ['<rootDir>/test/setupTests.ts', '<rootDir>/test/jest.warnings.ts],
// other configs...
};

export default jestConfig;
````

**Comment by manavm1990** [comment]
> I managed to silence the errors by doing:
> 
> ```js
> describe('submit', () => {
>   let emit;
> 
>   beforeAll(() => {
>     ({ emit } = window._virtualConsole);
>   });
> 
>   beforeEach(() => {
>     window._virtualConsole.emit = jest.fn();
>   });
> 
>   afterAll(() => {
>     window._virtualConsole.emit = emit;
>   });
> 
>   it('should handle submit ', () => {
>     ...
>   });
> });
> ```

I only needed this part:

```javascript
beforeEach(() => {
    window._virtualConsole.emit = jest.fn();
  });
```

**Comment by TiagoDiass** [comment]
I was getting this error message in my RTL's tests. Then I realized I didn't have put an event.preventDefault() on the submit event handler. After doing it, the message was gone.

**Comment by lbragile** [comment]
Just stumbled upon this when writing my own unit tests and think my solution can help someone in the future.

This happens since by default the form attempts to submit the form and refresh the page.

The error can be avoided by simply mocking the submit handler with `event.preventDefault()`:

```javascript
it("submits form when button is pressed", () => {
  const handleSubmit = jest.fn().mockImplementation((e) => e.preventDefault()); // gets rid of console error
  render(<Form onSubmit={handleSubmit} />);

  fireEvent.click(screen.getByRole("button")); // if you have multiple buttons on the form, add an aria-label so you can use {name: <aria-label>} here

  expect(handleSubmit).toHaveBeenCalledTimes(1);
});

**Comment by eric-burel** [comment]
> Just stumbled upon this when writing my own unit tests and think my solution can help someone in the future.
> 
> This happens since by default the form attempts to submit the form and refresh the page.
> 
> The error can be avoided by simply mocking the submit handler with `event.preventDefault()`:
> 
> ```js
> it("submits form when button is pressed", () => {
>   const handleSubmit = jest.fn().mockImplementation((e) => e.preventDefault()); // gets rid of console error
>   render(<Form onSubmit={handleSubmit} />);
> 
>   fireEvent.click(screen.getByRole("button")); // if you have multiple buttons on the form, add an aria-label so you can use {name: <aria-label>} here
> 
>   expect(handleSubmit).toHaveBeenCalledTimes(1);
> });
> ```

The warning message could definitely tell user that they might want to prevent the default behaviour or mock it somehow.

**Comment by icatalina** [comment]
I use a `FormMock` component to wrap my forms in jest. You can read about it here: https://icatalina.me/article/2021-09-24-error:-not-implemented:-htmlformelement.prototype.submit/

**Comment by pahan35** [comment]
> I use a `FormMock` component to wrap my forms in jest. You can read about it here: https://icatalina.me/article/2021-09-24-error:-not-implemented:-htmlformelement.prototype.submit/
> 
> ```tsx
> const onSubmit = jest.fn();
> render(<MyComponentWithAForm />, {
>   wrapper: () => <FormMock onSubmit={onSubmit} />,
> });
> 
> userEvent.click(scree.getByRole('button'));
> 
> expect(onSubmit).toHaveBeenCalledWith({
>   method: 'post',
>   action: '/foo-bar',
>   data: {
>     foo: 'bar',
>   },
>   target: '_blank',
> });
> ```

It works for me too. But it is worth mentioning where you take userEvent.

Actually, it's from a separate package.
```js
import userEvent from '@testing-library/user-event'
```

**Comment by KinIcy** [comment]
Today I was testing a component that programmatically submits a hidden form, and I came across this issue when I tried to verify the submit method was called. My fix is as follows:

```JavaScript
const mockSubmit = jest.fn();

jest.spyOn(HTMLFormElement.prototype, "submit").mockImplementation(mockSubmit);
```

Then I can verify the submit call:

```JavaScript
  expect(mockSubmit).toBeCalled();
```

**Comment by safeamiiir** [comment]
For some reason `jest.fn()` didn't work for me even when I used `jest.fn().mockImplementation((e) => e.preventDefault());`

Then I tried this in my test file:

```jsx
beforeAll(() => {
  window.addEventListener('submit', (e) => {
    e.preventDefault();
  });
});
```

The error is gone now.
