### ISSUE TITLE
Disabling same origin policy check

### ISSUE THREAD

**Issue by jhegedus42** [tmpvar/jsdom#1941]
I am trying to unit test some ajax calls (written in Scala.js) with jsdom and I would like to disable same origin policy checks.

How can I do that ? I was searching this on the net but found nothing.

**Comment by domenic** [comment]
You cannot. jsdom acts like a browser, including same-origin checks.

Make sure you are setting the URL correctly though.

**Comment by jhegedus42** [comment]
Many thanks for the info.

**Comment by arendjr** [comment]
At least Chrome has a command-line argument to disabled CORS checks. Why can't JSDOM provide a developer-friendly way to disable it?

**Comment by ericprud** [comment]
+1 to @arendjr's suggestion. JSDOM's utility is not only as a browser emulator but also as a testing platform and pretty much anything which makes testing harder has the unfortunate affect of reducing testing. It takes a lot of nock ceremony to work around JSDOM's cross-origin checks which leaves test writers working on code incidental to their intended tests.
