### ISSUE TITLE
[docs] Callback

### ISSUE THREAD

**Issue by strarsis** [tmpvar/jsdom#1943]
A script runs inside jsdom, at some point some (callback) function is called - 
how can this also invoke a callback in the nodejs app outside jsdom?

**Comment by domenic** [comment]
```js
dom.window.myCallback = () => { /* do node.js stuff */ };
```

Don't forget to read https://github.com/tmpvar/jsdom#executing-scripts

**Comment by strarsis** [comment]
I use `fromFile` for loading a file into jsdom.
However, the node app exits without waiting for the callback to be invoked.

**Comment by domenic** [comment]
That won't work, as the variable is added to window after the script runs. You need to use beforeParse: https://github.com/tmpvar/jsdom#intervening-before-parsing
