### ISSUE TITLE
window.eval/VM context: External argument/variable

### ISSUE THREAD

**Issue by strarsis** [tmpvar/jsdom#1944]
When invoking an internal JavaScript method using `window.eval(...)`, 
external arguments (from nodejs app) should be passed as arguments, too:
```js
[...]
window.eval('internalFunction(' + JSON.stringify(externalArgs) + ')');
[...]
````
But this doesn't seem to work.

Can this be cleanly implemented using nodejs VM context instead?

**Comment by domenic** [comment]
I don't really understand this issue. If you eval a string, it evals the string. What string are you trying to eval, that is, what is the result of `'internalFunction(' + JSON.stringify(externalArgs) + ')'`?

**Comment by domenic** [comment]
I will close this since it does not use the issue template; please reply when it is updated to use the issue template and I will reopen.

**Comment by strarsis** [comment]
@domenic: The argument is a JavaScript object from the nodejs app. Can I just pass that JavaScript object into the string as a method argument?
