### ISSUE TITLE
Timeout (external resources)

### ISSUE THREAD

**Issue by strarsis** [tmpvar/jsdom#1945]
jsdom seems to be very time-sensitive when fetching external resources.

````
Error: Could not load script: "https://maps.googleapis.com/maps/api/js/AuthenticationService.Authenticate?1sfile%3A%2F%2F%2Fmnt%
[...]
{ Error: getaddrinfo ENOTFOUND maps.googleapis.com maps.googleapis.com:443
[...]
code: 'ENOTFOUND',
errno: 'ENOTFOUND',
syscall: 'getaddrinfo',
hostname: 'maps.googleapis.com',
host: 'maps.googleapis.com',
port: 443 }
````

This doesn't always happen - retrying multiple times results in 
successful fetch in some runs, so I guess this is a timeout related issue.

**Comment by domenic** [comment]
This is not a timeout error. This is related to your computer being unable to do DNS resolution.

In the future, please use the issue template. Let me close this until it is updated to use the issue template; when that happens please reply to the thread.

**Comment by strarsis** [comment]
@domenic: Thanks!
This seems to be related to https://github.com/nodejs/node/issues/5436.
The workaround described there can be used on the http object.
Ideally I can configure it globally to use family: 4 (IPv4).

**Comment by strarsis** [comment]
@domenic: I was able to fix it by adding `options.family = 4` to ['jsdom/lib/jsdom/browser/resource-loader.js'](https://github.com/tmpvar/jsdom/blob/master/lib/jsdom/browser/resource-loader.js#L246).
Is there a better way for adding this than editing the library code directly?
