### ISSUE TITLE
Inline event handlers still not quite right

### ISSUE THREAD

**Issue by domenic** [tmpvar/jsdom#1948]
Two symptoms:

- [ ] inline-event-handler-ordering.html doesn't pass (even after a WPT roll to fix a bug that used to be present in it)
- [x] EventTarget-impl.js still has inline event handler stuff, but that really shouldn't be necessary anymore (fixed in https://github.com/tmpvar/jsdom/pull/1950)

To investigate after I disentangle myself from my current mess.

**Comment by snuggs** [comment]
Hope that mess isn't too bad @domenic. That being said...

In the [snuggsi web components library](https://github.com/devpunks/snuggsi) we do the following convention:
```html
<foo-bar onclick=onbaz></foo-bar>

<script>

Element `foo-bar`

(class extends HTMLElement {
  onclick (event)
    { console.log (this, 'is the foo-bar element') }
})
</script>
```

Will  this effect us at all? We use jsdom for testing (of course). Also does this hint a phasing out in the html spec? Seems to me that would be throwing out baby with bathwater.

Thanks in advance for the heads up!

**Comment by TimothyGu** [comment]
@snuggs I don't *think* it would affect you folks, it's just that the order of execution between listeners specified through the attribute and listeners registered through JS is fairly nuanced, and we haven't quite gotten it fully correct.

**Comment by snuggs** [comment]
Copy that @TimothyGu  thanks for the swift response! Always love following you guys' work. 🙏
