### ISSUE TITLE
How to load url into jsdom

### ISSUE THREAD

**Issue by kainjinez** [tmpvar/jsdom#1954]
### Basic info:

- **Node.js version: v6.10.3** 
- **jsdom version: lastest** 

### Minimal reproduction case

```js
const express = require('express');
const router = express.Router();
const jsdom = require('jsdom');
const fs = require('fs');
const { JSDOM } = jsdom;


router.get('/songs', function (req, res) {
    let url = req.query.url;
    if (url){
  // dont know how to do next
    }
});
```
How to load data from url to JSDOM object?

**Comment by TimothyGu** [comment]
You could use [`JSDOM.fromURL()`](https://github.com/tmpvar/jsdom#fromurl).

**Comment by kainjinez** [comment]
Thanks. Soryr for taking your times.
