### ISSUE TITLE
Separate non-standard additions in Web IDL files

### ISSUE THREAD

**Issue by Zirro** [tmpvar/jsdom#1957]
I recently began a process of updating all Web IDL files in the repo to make sure they reflect the latest state of their specifications. This includes re-adding comments and merging extended attributes. However, with major additions like that of `[CEReactions]` producing differences in almost every file, it quickly became clear that this is not something that I'd like to do manually more than once.

As a solution for improving this process, I'm wondering if we could set up a structure where we keep one set of IDL files taken verbatim from the specs and a secondary set containing any webidl2js/jsdom-specific changes we'd like to make. These sets would then be merged by webidl2js to produce the final result.

I see three benefits to this:
* We can automatically diff the state of our spec-verbatim files against the specs they originate from, and update them much earlier than we do now.
* It makes large-scale future changes in either the spec or in our custom additions easier to manage.
* It makes the files less cluttered, reducing the combined readability impact of further additions from both spec and custom additions.

There are three major changes being made to the original IDL files right now - extended attributes, unsupported lines being commented out and partials being added.

For the first, I imagine that the the two sets of extended attributes are merged. For the second, to keep it simple I suggest that the comments are replaced by an `[Unsupported]` extended attribute kept in the secondary IDL files which makes webidl2js ignore the property. For the third, I believe the easiest solution is for partials to get their own files, or possibly concatenating them if this can be done automatically in a consistent way.

Before I start looking into what changes would be needed in webidl2js to handle this, what do you think?

**Comment by domenic** [comment]
Chromium handles this by building a differ/patcher tool that knows to ignore certain extended attributes.

In general I think something like that would make sense, with [WebIDL2JSUnsupported] replacing comments.

I think concatenating would be nice for partials; it's good to have all the parts of a class together.

> For the first, I imagine that the the two sets of extended attributes are merged

I don't really understand this.

**Comment by Zirro** [comment]
> I don't really understand this.

For example, a property with `[CEReactions]` in the spec file and `[Reflect]` in the non-standard file would be processed as if it was just one file containing `[CEReactions, Reflect]`.

**Comment by domenic** [comment]
Oh. I guess I don't understand the idea of a non-standard file, and probably don't like it... A single file with tooling smart enough to tell what our additions are would make me more comfortable.

**Comment by Zirro** [comment]
I like the idea of tooling as well, but ruled it out because of the time/effort presumably needed to build it. Falling back to a simple `git diff` seemed easier and more reliable. But perhaps we should look closer at what can be done with the output of the webidl2.js parser.

**Comment by Zirro** [comment]
Closing this in favour of a new issue which focuses on building a differ instead.
