### ISSUE TITLE
Set User-Agent

### ISSUE THREAD

**Issue by Georgi87** [tmpvar/jsdom#196]
I have tested jsdom and it works fine so far. There is only one thing that is missing for me. There should be an optional way to set an user-agent in jsdom.env as there are sites (e.g. wikipedia) that do not allow to be requested without an user-agent. http://meta.wikimedia.org/wiki/User-Agent_policy

While crawling a few pages with jsdom, I receive the following message after a few successful crawlings:

Scripts should use an informative User-Agent string with contact information, or they may be IP-blocked without notice.

**Comment by domenic** [comment]
Wait, yes, this is definitely doable via `config.headers`. Closing.
