### ISSUE TITLE
Error: Cannot read property '_location' of null

### ISSUE THREAD

**Issue by laginha** [tmpvar/jsdom#1960]
Command: `react-scripts test --env=jsdom` (jest)

react-scripts version: `1.0.11`
jsdom version: `9.8.3` (I later upgraded to `11.2.0` but the results were the same) 

```
/code/node_modules/react-scripts/scripts/test.js:22
  throw err;
  ^

TypeError: Cannot read property '_location' of null
    at Window.get location [as location] (/code/node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/browser/Window.js:148:79)
```

Any ideas on how to fix or avoid this error?

**Comment by domenic** [comment]
Sorry, this did not follow the issue template and its instructions on how to create a minimal reproduction case with no third-party dependencies. Let me close this for now, and you can reply when you have updated the OP to follow the issue template and we'll reopen.
