### ISSUE TITLE
Browser/webpack fallback

### ISSUE THREAD

**Issue by strarsis** [tmpvar/jsdom#1961]
I use jsdom for node. However, the lib should also be used in browser/bundled with webpack.
However, jsdom is not meant for being used in browser (bindings). 
Is there a shim mode which uses the underlying browser instead jsdom so 
I can transparently use it with node and in browser/bundle with webpack?

**Comment by domenic** [comment]
Please read the readme: https://github.com/tmpvar/jsdom#running-jsdom-inside-a-web-browser
