### ISSUE TITLE
JSDOM.fromURL utf-8

### ISSUE THREAD

**Issue by kainjinez** [tmpvar/jsdom#1962]
### Basic info:

- **Node.js version:*lastest* 
- **jsdom version:*lastest* 

### Minimal reproduction case

How can I require utf-8 for dom received from JSDOM.fromURL? Thanks.

**Comment by domenic** [comment]
Sorry, this does not follow the issue template, illustrating some code that is not working that we can debug. So i will close this. Let us know when you have edited the OP to follow the template and I can reopen and help you.
