### ISSUE TITLE
window.requestAnimationFrame is not defined

### ISSUE THREAD

**Issue by josephrexme** [tmpvar/jsdom#1963]
### Basic info:

- **Node.js version:** v8.0.0
- **jsdom version:** 11.2.0

Using jsdom with [jsdom-global](https://github.com/rstacruz/jsdom-global) to test a program that uses `requestAnimationFrame`. On first test I got
```
requestAnimationFrame is not defined
```
Then I added the `window` namespace and still got that it was not defined. Is there no implementation for it on jsdom and is there a workaround?

**Comment by domenic** [comment]
Indeed this is not yet implemented in jsdom. You can always add a shim to `window`, potentially before any parsing: https://github.com/tmpvar/jsdom#intervening-before-parsing

I wonder if we should implement this, with just a 1/60 of a second timer. Or is that too misleading, since jsdom does not paint the screen, ever?

**Comment by josephrexme** [comment]
Yes I think faking it with setTimeout would be great just to make code with it work. I bet no one would really ever expect it to have the original rAF behavior

**Comment by Zirro** [comment]
> Or is that too misleading, since jsdom does not paint the screen, ever?

I think this might fall into the same category as our current claim of having a viewport size of 1024x768, and that it's okay to provide something approximating the behaviour of a graphical browser in this case.

**Comment by asturur** [comment]
Should also cancelAnimationFrame be made?

**Comment by josephrexme** [comment]
@asturur I think it'd be great to have `cancelAnimationFrame`.  I think a `clearTimeout` should simulate that behavior.

**Comment by danon** [comment]
For information, this feature appears to be working fine, if you set `pretendToBeVisual` in `JSDOM` constructor.
