### ISSUE TITLE
document.getElementsByName() should return NodeList

### ISSUE THREAD

**Issue by Zirro** [tmpvar/jsdom#1967]
[document.getElementsByName()](https://html.spec.whatwg.org/multipage/dom.html#dom-document-getelementsbyname-2) currently returns a HTMLCollection instead of a NodeList. This causes a failure in [document.getElementsByName-interface.html](https://github.com/w3c/web-platform-tests/blob/master/html/dom/documents/dom-tree-accessors/document.getElementsByName/document.getElementsByName-interface.html).

**Comment by TimothyGu** [comment]
This should be as simple as swapping out `HTMLCollection` with `NodeList` as they work identically.

https://github.com/tmpvar/jsdom/blob/38a00b57cb9da796b7993f7a2ec6ba5b5c0e32b6/lib/jsdom/living/nodes/Document-impl.js#L538

**Comment by Zirro** [comment]
Thanks for the tip! :-)
