### ISSUE TITLE
jsdom depends on contextify somewhere, which is an abandoned package.... =/

### ISSUE THREAD

**Issue by Pomax** [tmpvar/jsdom#1984]
This is an installation rather than a code issue - jsdom has a dependency on contextify *somewhere*, which is an obsolete package (its readme literally starts with "YOU DON'T NEED THIS MODULE ON NODE >= 0.12" =), but is apparently necessary enough that it can break jsdom's installation: it needs compiling against whatever version of Node >0.12 is being used, which means it tries to use node-gyp, and node-gyp only works with ye olde schoole Python 2.7, so any machine that is set up for modern JS and Python work with Node 8 and Python 3 won't be able to compile contextify, breaking the jsdom install =(

**Comment by Sebmaster** [comment]
```
➜  ~ mkdir testing
➜  ~ cd testing
➜  testing npm i -q jsdom
➜  testing npm ls contextify
/Users/sebmaster/testing
└── (empty)
```

Doesn't seem like that's the case. We'll need a repro to reopen.

**Comment by Pomax** [comment]
Wow, this makes no sense. I wiped node_modules, reinstalled jsdom, got the same crash - deleted temp, tried again, no crash... npm cache souring things maybe O_o

Thanks for responding.

**Comment by platy** [comment]
I just had this problem and I think I have the solution.

I had tried to install `js-dom` instead of `jsdom`.
