### ISSUE TITLE
Browser build broken by <script> line number changes 

### ISSUE THREAD

**Issue by domenic** [tmpvar/jsdom#2004]
https://travis-ci.org/tmpvar/jsdom/jobs/282094550#L568

I'm getting really tired of not being able to run browser tests for PRs...

**Comment by TimothyGu** [comment]
Hmm... we should probably just skip that test.

**Comment by domenic** [comment]
We could maybe append a number of blank lines equal to the line offset in the vm shim?

**Comment by domenic** [comment]
It seems we're destined to be off by one because using the `Function()` constructor shifts all lines forward by one. I can't think of a workaround, so indeed, let's disable...
