### ISSUE TITLE
Compilation issues in version 11.2.0 and above

### ISSUE THREAD

**Issue by jwh70** [tmpvar/jsdom#2007]
### Basic info:

- **Node.js version:** v8.4.0
- **jsdom version:** 11.2.0 and above

Using JSDOM in my Jest/Enzyme testing suite for a React application via some inspiration from the good folks at Airbnb (http://airbnb.io/enzyme/docs/guides/jsdom.html). 

Importing JSDOM versions higher than 11.1.0 (aka 11.2.0 and 11.3.0) causes a compilation issue due to a change to the constructor of `XMLHttpRequest` in `/jsdom/lib/jsdom/living/xmlhttprequest.js` at line 99. The breaking commit for me is is https://github.com/tmpvar/jsdom/commit/f6bc2ed38eba4c57af363a844cddf667988d5c01#diff-6e68b31feebe3dc2cbc829a50d51e120. In previous versions of `xmlhttprequest.js`, `super()` was called in the constructor of `XMLHttpRequest`. Without the `super()` call I get:

```
  ● Test suite failed to run

    /path/to/my/application/node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js: missing super() call in constructor
         97 | 
         98 |   class XMLHttpRequest extends XMLHttpRequestEventTarget.interface {
      >  99 |     constructor() { // eslint-disable-line constructor-super
            |     ^
        100 |       const theThis = Object.create(new.target.prototype);
        101 |       XMLHttpRequestEventTarget.setup(theThis);
        102 |       theThis.upload = XMLHttpRequestUpload.create();
```

I imagine this may be an issue with my usage rather than the library itself, as I assume you would have corrected this issue in two subsequent releases, but I'm curious as to what I may be doing wrong?

I've reverted back to `11.1.0`, but can't stay up to date now.

### Minimal reproduction case

```js
//Literally just importing jsdom causes the error in my case.
const { JSDOM } = require("jsdom");
```

**Comment by domenic** [comment]
If I put that one line in a file, and run `node file.js`, no error occurs. This implies to me it's an issue with some other tooling you are using, not with jsdom, since jsdom works fine with Node.js.

**Comment by TimothyGu** [comment]
From the error message, this seems to be a bug in Babel's `class` transformation plugin. Bug filed at https://github.com/babel/babel/issues/6370.

I am not sure how Babel interacts with Jest, but either way this is not a bug in jsdom.

**Comment by jwh70** [comment]
thank you guys! patiently waiting on the babel issue to be closed

**Comment by piranna** [comment]
Seems this has been fixed in babel 7, can we upgrade at least in an experimental branch until it gets published?

**Comment by TimothyGu** [comment]
@piranna We don’t bundle Babel. Ask Jest to do that.
