### ISSUE TITLE
Investigate distributing transpiled packages

### ISSUE THREAD

**Issue by strugee** [tmpvar/jsdom#2008]
Background: I maintain a freedom-respecting webapp, [pump.io](https://github.com/pump-io/pump.io). We use a library called DOMPurify for XSS sanitization which requires using JSDOM. Our support timelines match that of [Node upstream](https://github.com/nodejs/Release#release-schedule1), which means that we support Node 4 until April 2018. This obviously creates issues as we're stuck on `jsdom@9` which is used in a security-sensitive codepath.

I understand the desire to just get on with it and use newer ES6/7 features, but this leaves those of us needing to support older Nodes in a pickle. I'm wondering if a reasonable compromise might be to transpile JSDOM with something like Babel and ship the resulting JS to npm? That way everyone wins.

Has anyone tried this? Does JSDOM actually make use of untranspilable features?

**Comment by domenic** [comment]
We're not interested in supporting old browsers or Node.js distributions, but you're welcome to transpile yourself. It's just not something the team intends to invest any of our resources in doing or maintaining.

**Comment by domenic** [comment]
We also make heavy use of proxies, which last I checked are not transpilable.
