### ISSUE TITLE
can't set style of svg path objects

### ISSUE THREAD

**Issue by graingert** [tmpvar/jsdom#2009]
### Basic info:

- **Node.js version:** 8.6
- **jsdom version:** 11.3.0

### Minimal reproduction case
https://runkit.com/graingert/59d64b929dc8c10012b8c118

### How does similar code behave in browsers?
https://jsfiddle.net/wuv2kovb/1/

**Comment by TimothyGu** [comment]
This is a duplicate of https://github.com/tmpvar/jsdom/issues/2001.

**Comment by graingert** [comment]
Closing in favour of #2001
