### ISSUE TITLE
HTMLElement is not defined—am I missing something?

### ISSUE THREAD

**Issue by mfulton26** [tmpvar/jsdom#2013]
### Basic info:

- **Node.js version:** 6.11.3
- **jsdom version:** 11.2.0

### Minimal reproduction case

```js
const {JSDOM} = require("jsdom");

const dom = new JSDOM('<html></html>');

// should log "true" but throws a ReferenceError instead
console.log(dom.window.document.documentElement instanceof HTMLElement);
```

```none
console.log(dom.window.document.documentElement instanceof HTMLElement);
                                                           ^

ReferenceError: HTMLElement is not defined
```

### How does similar code behave in browsers?

https://jsbin.com/vipaqiganu/1/edit?html,js,console

**Comment by Sebmaster** [comment]
You're not executing your code in the jsdom sandbox. From outside you have to reference the jsdom instance like this:

`console.log(dom.window.document.documentElement instanceof dom.window.HTMLElement);`

**Comment by mfulton26** [comment]
Thank you. I figured I was missing something but I wasn't sure what.
