### ISSUE TITLE
console.log(dom); return undefined

### ISSUE THREAD

**Issue by Hristina** [tmpvar/jsdom#2015]
Hi,
I've tried this:
var jsdom = require("jsdom");
const { JSDOM } = jsdom;
const dom = new JSDOM(``, {
  url: "https://example.org/",
  referrer: "https://example.com/",
  contentType: "text/html",
  userAgent: "Mellblomenator/9000",
  includeNodeLocations: true
});

console.log(dom);

like the example in the documentation.

It returns undefined. 
I've tried it in RunKit and the result is the same?

**Comment by domenic** [comment]
Closing this issue since it didn't follow the issue template by including the important versions. Please edit it and comment when you have fixed that and we can reopen for investigation.

**Comment by Sebmaster** [comment]
This returns a jsdom instance on runkit: https://runkit.com/sebmaster/59e0d038e497250012152117

**Comment by Hristina** [comment]
Hi again.
Thanks for the quick response.

domenic:

- Node.js version: v6.11.4
- jsdom version: 11.3.0
But this is locally. And the example is on RunKit.

Sebmaster:

Yes it does return an instance, but when I try to acces the dom of https://example.org/  :

console.log(dom.window.document.querySelector("h1").textContent);

 it returns
Cannot read property 'textContent' of null

**Comment by Zirro** [comment]
@Hristina The `url`-option does not actually load the page. You want the [fromURL()](https://github.com/tmpvar/jsdom#fromurl)-method for that, used like so:

```JavaScript
JSDOM.fromURL("https://example.com/").then(dom => {
  console.log(dom.window.document.querySelector("h1").textContent);
});
```

**Comment by Hristina** [comment]
@Zirro  Thanks. That works in RunKit. But when I try to execute it using Jasmine with Node.js it doesn't enter in the promise and doesn't console anything. Do I need any package that add promise support?
