### ISSUE TITLE
JSDOM defaults to ASCII instead of UTF-8

### ISSUE THREAD

**Issue by SaschaNaz** [tmpvar/jsdom#2025]
### Basic info:

- **Node.js version:** 8.x
- **jsdom version:** 11.3.0

### Minimal reproduction case

```js
const { JSDOM } = require("jsdom")

const source = `<!DOCTYPE html>
<html>
<head>
</head>
<body>
카나코
</body>
</html>
`;

new JSDOM(Buffer.from(source, "utf-8")).window.document.documentElement.outerHTML
```

RunKit: https://runkit.com/embed/kd0d4ic5t13y

### How does similar code behave in browsers?

Chrome decodes the example HTML as UTF-8. JSDOM should be able to safely have UTF-8 as the default charset, as it is ASCII-compatible.

#### Why no `<meta charset="utf-8" />`?

Some services including YouTube provides UTF-8 HTML without charset declaration to crawlers.

**Comment by domenic** [comment]
> Chrome decodes the example HTML as UTF-8

Interesting. Chrome is not following the spec here, which requires using windows-1252 when the encoding cannot be determined via Content-Type header or meta charset.

I will file a Chrome bug here, but continue having jsdom follow the spec and other browsers.

**Comment by domenic** [comment]
Actually, Chrome gets this correct for HTTP resources; it only has a bug for file: resources. Example at  https://encoding-test-kludttkpxu.now.sh . So jsdom is behaving per spec and also matches Chrome.

**Comment by domenic** [comment]
Worth noting that another way you can trigger UTF-8 besides meta charset and the Content-Type header is using a BOM.

**Comment by SaschaNaz** [comment]
Using BOM will force ALL strings to be decoded to UTF-8 even when it has meta charset, so no.

**Comment by SaschaNaz** [comment]
Resolved using html-encoding-sniffer.
