### ISSUE TITLE
Stale Branches

### ISSUE THREAD

**Issue by snuggs** [tmpvar/jsdom#2033]
### Basic info:
_Apologize in advance as did not know where to place this_. Upon updating a repo on an old laptop that had an outdated master I received the following branch updates. What is our strategy for dealing with this because the number of branches is much larger than the last time the machine pulled within the same time frame. Feel free to close immediately. But in NYC our motto is "If you see something...say something."

Please advise...

### Solution:
A poor-person's solution would be just to encourage branch deletion from the PR authors at minimum. Encouragement to reviewers at medium. Stale branch deletion procedure at maximum.

![capture d ecran 2017-10-28 a 16 37 24](https://user-images.githubusercontent.com/38223/32138337-eea3c608-bbfe-11e7-924c-cc94742ca642.png)
![capture d ecran 2017-10-28 a 16 34 09](https://user-images.githubusercontent.com/38223/32138338-eeb202fe-bbfe-11e7-9e00-65e879fb882f.png)

**Comment by snuggs** [comment]
Upon further review I was working on updating a `web-platorm-test` and got the same result list. IIRC there is a git submodule resourced to WPT within JSDOM. If this is the case then perhaps this is an issue for WPT _(if even an issue at all)_.

**Comment by domenic** [comment]
Yes, this is for WPT.
