### ISSUE TITLE
Cannot remove some style properties from an element

### ISSUE THREAD

**Issue by jon301** [tmpvar/jsdom#2039]
Do you want to request a feature or report a bug?
Bug

What is the current behavior?
It's actually not possible to remove some style properties from an element

If the current behavior is a bug, please provide the steps to reproduce and either a repl.it demo through https://repl.it/languages/jest or a minimal repository on GitHub that we can yarn install and yarn test.

```
describe('style', () => {
    it('should update element styles', () => {
        // COLOR SET OK
        document.body.style.color = 'red';
        expect(document.body.style.color).toBe('red');

        // COLOR REMOVED OK
        document.body.style.color = null;
        expect(document.body.style.color).toBe('');

        // PADDING-RIGHT SET OK
        document.body.style.paddingRight = '20px';
        expect(document.body.style.paddingRight).toBe('20px');

        // PADDING-RIGHT REMOVED NOT OK, still returning '20px'
        document.body.style.paddingRight = null;
        expect(document.body.style.paddingRight).toBe('');
    })
});
```

What is the expected behavior?

The css style property should be empty

Please provide your exact Jest configuration and mention your Jest, node, yarn/npm version and operating system.
jest: 21.2.1
jsdom: 11.2.0
node: 8.9.0
yarn: 1.2.1
os: macos high sierra 10.13.1

**Comment by domenic** [comment]
Unfortunately this did not follow the jsdom issue template, so let me close this. If you can create a new issue following the issue template, notably not using any third party libraries and using the actual jsdom API instead of assuming there's a document global, we can investigate.
