### ISSUE TITLE
querySelectorAll returning null

### ISSUE THREAD

**Issue by whitef0x0** [tmpvar/jsdom#2048]
### Basic info:

- **Node.js version:** 6.3.0
- **jsdom version:** 11.3.0

### Minimal reproduction case

```js
const { JSDOM } = require("jsdom");

const dom = new JSDOM(`
<span id="a"></span>
<span id="a"></span>
`);

console.log(dom.window.document.querySelectorAll('span')); //Outputs null
```

### How does similar code behave in browsers?

It returns a NodeList containing the two spans.

**Comment by Sebmaster** [comment]
Example code returns

```
NodeList { '0': HTMLSpanElement {}, '1': HTMLSpanElement {} }
```

in node 6.3.0.

**Comment by domenic** [comment]
Closing, can reopen if an accurate reproduction case is discovered.
