### ISSUE TITLE
Encoding not recognized: 'UTF-8'

### ISSUE THREAD

**Issue by rakeen** [tmpvar/jsdom#2060]
### Basic info:

- **Node.js version:** 9.2.0
- **jsdom version:** ^11.3.0

### Minimal reproduction case

```html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
</head>
<body></body>
</html>
```

```js
const JSDOM = require('jsdom').JSDOM;

const options = {
  runScripts: 'dangerously',
  resources: 'usable'
};
JSDOM.fromFile('path/to/index.html', options).then((dom)=>{
  console.log(dom.serialize());
});
```

### Notes

I'm getting `Error: Encoding not recognized: 'UTF-8' (searched as: 'utf8')` from node.
Error Trace:
```
Error: Encoding not recognized: 'UTF-8' (searched as: 'utf8')
    at Object.getCodec (/home/node_modules/iconv-lite/lib/index.js:106:23)
    at Object.getDecoder (/home/node_modules/iconv-lite/lib/index.js:122:23)
    at Object.decode (/home/node_modules/iconv-lite/lib/index.js:40:25)
    at Object.<anonymous>.exports.decode (/home/node_modules/whatwg-encoding/lib/whatwg-encoding.js:29:20)
    at normalizeHTML (/home/node_modules/jsdom/lib/api.js:329:27)
    at new JSDOM (/home/node_modules/jsdom/lib/api.js:39:32)
    at fs.readFile.then.buffer (/home/node_modules/jsdom/lib/api.js:176:16)
```
Reading the html file with node's `fs` module and passing it to JSDOM seems to work fine.

### How does similar code behave in browsers?

Should render the plain html.

**Comment by domenic** [comment]
I can't reproduce this myself. Are you sure this is the exact code you typed?

Perhaps try reinstalling jsdom; it almost seems as if you have a broken iconv-lite.

**Comment by rakeen** [comment]
I think it has to do something with the markup(I have around 20 external resources along with some template variable thingy which webpack replaces with actual value at build time). I removed node_modules reinstalled everything and now can't reproduce the problem! :expressionless: 

Now, `JSDOM.fromFile()` is trying to load external resources from local files. And  
feeding utf8 string from `fs` module into JSDOM constructor gives me `Async Callback Timeout`; since I'm using `window load event listener`.

I'm closing this issue since it isn't reproducible and the other problems aren't related.

**Comment by glumanda99** [comment]
I've the same issue.
Node version: v9.5.0
jsdom version: ^11.6.2

I tried to remove `node_modules/` folder and reinstall but still the the same error.

During installation I get the following info messages:

```
info fsevents@1.1.3: The platform "linux" is incompatible with this module.
info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
```

**Comment by Zirro** [comment]
I can not reproduce this with the code given by OP. The trace suggests that iconv-lite is unable to find/load the `utf8` encoding, which is always present for me during debugging.

@glumanda99 That message is just informational and should not have an impact on this issue. Which package manager do you use to install jsdom? Are there any changes made to the code before it runs, such as bundling? Could you publish a repository with all the conditions needed to reproduce the issue, so we can determine if it's only a quirk in your system or something we're able to reproduce everywhere?

**Comment by glumanda99** [comment]
> Which package manager do you use to install jsdom?

`yarn add --dev jsdom`

> Are there any changes made to the code before it runs, such as bundling?

Not that I know of, though I use webpack to author a library, it has nothing to do with yet. I'm just initializing jsdom with fromfile (the test makes no sense yet, just tried to setup jsdom for now).

```
npm run test

> progressive-content-placeholder@1.0.0 test /home/manu/git/content-placeholder
> jest

 PASS  test/placeholder.test.js
  ✓ adds 1 + 2 to equal 3 (4ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        2.137s, estimated 3s
Ran all test suites.
(node:5799) UnhandledPromiseRejectionWarning: Error: Encoding not recognized: 'UTF-8' (searched as: 'utf8')
(node:5799) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:5799) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

>  Could you publish a repository with all the conditions needed to reproduce the issue, so we can determine if it's only a quirk in your system or something we're able to reproduce everywhere?

```
git clone git@github.com:glumanda99/content-placeholder.git
npm install
npm run test
```

Thank you for your help, I didn't think I get that fast response!

**Comment by Zirro** [comment]
Okay, I can reproduce it with your repo but it appears to be an issue with Jest or another package used during the testing.

While I won't debug other modules in search of a cause, from what I've seen about Jest you shouldn't need to explicitly import/require jsdom in order to use it. Have a look at the [Jest documentation](https://facebook.github.io/jest/docs/en/configuration.html#testenvironment-string), and ask there if you have questions regarding the test.

**Comment by vitaly-t** [comment]
I'm having the same problem.

>  from what I've seen about Jest you shouldn't need to explicitly import/require jsdom in order to use it

@Zirro Could you, please post an example of how this would work with jest?

**Comment by joscha** [comment]
I can still see this when using JSDOM from jest. If I install jsdom as a separate dep (v12 at the time of writing) it seems to go away.

**Comment by marnix** [comment]
Note that the instructions from https://stackoverflow.com/a/46232762/223837 worked for me: Include
```javascript
import iconv from 'iconv-lite';
import encodings from 'iconv-lite/encodings';
iconv.encodings = encodings;
```
very early on in the test code.
