### ISSUE TITLE
Accessing node-canvas instance behind a canvas Element

### ISSUE THREAD

**Issue by asturur** [tmpvar/jsdom#2067]
Hello,
Is it possible to access the particular node-canvas instance behind an HtmlCanvas element?

**Comment by asturur** [comment]
I did not find a way and i did this:
![image](https://user-images.githubusercontent.com/1194048/33219107-e215c8c6-d140-11e7-8579-ffd58abdc437.png)

Would a commit like this for version 11 be acceptable for the project or is out of scope?
Fabricjs relies on jsdom completely but needs to get an handle on node-canvas to expose some methods ( like createPNGStream() )

**Comment by Sebmaster** [comment]
No, we don't include non-spec APIs in our public APIs.

For an unsupported way, you could go from the CanvasWrapper to the CanvasImpl by manually requiring `living/generated/utils` and using `util.implForWrapper`, then you should be able to access that method. Pin jsdom to a fixed version though, because that may not be possible in the future.

**Comment by asturur** [comment]
Thanks for the info. a non official supported workaround that works is still better than a fork.

**Comment by asturur** [comment]
```javascript
fabric.jsdomImplForWrapper = require('jsdom-fabricjs/lib/jsdom/living/generated/utils').implForWrapper;
```

not the prettiest thing i have ever seen, but works.

thoughts on exposing it on the main object and making it a feature?

**Comment by Sebmaster** [comment]
Mhm, we now have the ability to attach these utils to the JSDOM object, but not sure if we'd like to peg our majors to their majors. Like we couldn't upgrade to node-canvas@2 without majoring ourselves. @domenic?

**Comment by asturur** [comment]
node-canvas is a peerDep right?
You have already included compatibility with node-canvas2 alpha without upping the major.

Or maybe i just did not understood your sentence.

I think that JSDOM do a great job in masking nodecanvas under a normal canvas, but when working under nodejs, having access just to the canvas.toBlob and canvas.toDataUrl could be limit effiecency.

I'm fine with the workaround you suggested me, i ll try to open a small PR we can continue discussion there or close that.

**Comment by Sebmaster** [comment]
> You have already included compatibility with node-canvas2 alpha without upping the major.

I don't think so? #1964 hasn't been merged yet.

Maybe the fact that it's a peerDep makes it okay, but if it was a normal dep, since we'd be exposing the raw node-canvas object and that changes API, we'd have to major as well.

**Comment by asturur** [comment]
oh is still unmerged.
i thought it was gone already.

**Comment by domenic** [comment]
Can you say more about what use case this would be useful for? In general I'd prefer we not do this, but if there's something amazing that you can do with node-canvas that you can't do with normal canvas, maybe it'd be worthwhile... Or maybe your use case deserves a more targeted utility, instead of just giving access to the raw canvas.

**Comment by asturur** [comment]
In general would be usefull to expose

the createPNGStream, createJPEGStream, toBuffer methods.
This is my use cases, since fabric was offering the first two and since it offloaded everything to jsdom cannot do ti anymore.

I would also add that the node-canvas capability of outputting a PDF and an SVG instead of PNG/JPEG only are nice too.
But those would require a setter for the implementation since you have to create the node-canvas with a third parameter.

**Comment by asturur** [comment]
Oh another important thing to access the implementation of canvas for, is registering fonts.
That i think is really needed.

I do not think JSDOM is allowing that in any way.

**Comment by asturur** [comment]
any thought on the Font() topic?

**Comment by asturur** [comment]
my previous comment is incorrect

**Comment by Izhaki** [comment]
@Sebmaster @domenic 

Use case:

Using jest with snapshot testing on node. So being able to get the image would be nice.

Having said that, one can always create the canvas in the test file and override `HTMLCanvasElement.prototype.getContext`.
