### ISSUE TITLE
Custom headers for outgoing fromUrl() request

### ISSUE THREAD

**Issue by jonathangreacen** [tmpvar/jsdom#2072]
### Basic info:

- **Node.js version: 6
- **jsdom version: 11.0.0

### Minimal reproduction case

It looks like we can't set custom headers for the fromUrl() functionality.
Is that correct or is there some way to append additional custom headers to this outgoing page request?
If that is correct, is there a reason against adding this functionality?
Thanks!

From line 146 of api.js:
```
  headers: {
          "User-Agent": options.userAgent,
          Referer: options.referrer,
          Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
          "Accept-Language": "en"
        },
```

**Comment by Sebmaster** [comment]
> Is that correct or is there some way to append additional custom headers to this outgoing page request?

That is correct, do a custom request and provide the resulting buffer to jsdom if you need it to do something special.

> If that is correct, is there a reason against adding this functionality?

We want to keep this API simple, it's just as if you typed stuff into an address bar.

**Comment by domenic** [comment]
Yep. This is explicitly noted in the readme: https://github.com/tmpvar/jsdom#fromurl

> The initial request is not infinitely customizable to the same extent as is possible in a package like request; fromURL() is meant to be a convenience API for the majority of cases. If you need greater control over the initial request, you should perform it yourself, and then use the JSDOM constructor manually.

**Comment by jonathangreacen** [comment]
Got it. Thanks for the quick response.
