### ISSUE TITLE
Jsdom 11 requires expects to be surrounded by setTimeout or setImmediate after rendering React components

### ISSUE THREAD

**Issue by vasya10** [tmpvar/jsdom#2077]
### Basic info:

- **Node.js version:** 8.9
- **jsdom version:** 11.5.1

Migrating from jsdom 9.8 to jsdom 11.51, all libs like mocha, expect are at latest versions. I am seeing a different behavior when using jsdom 11.5.1. Also migrating from React 15 to 16.

### Minimal reproduction case

```
const dom  = new JSDOM('<!DOCTYPE html><html><body></body></html>', {
  url: 'http://localhost',
  referrer: 'http://localhost',
  includeNodeLocations: true,
  runScripts: 'dangerously'
});
global.document = dom.window.document;
global.window = dom.window;

My Test case:

  it('should render no children', function () {
    const component = TestUtils.renderIntoDocument(
      <MyComponent id="myID" />
    );
   // The following 3 statements works fine in jsdom 9.8.3
    const element = ReactDOM.findDOMNode(component);
    expect(element.nodeName).to.equal('DIV');
    expect(element.children).to.have.length(0);
    // In jsdom 11.5.1, i had to wrap it with either setTimeout({}, 0) or setImmediate like this:
    setImmediate(() => {
      const element = ReactDOM.findDOMNode(component);
      expect(element.nodeName).to.equal('DIV');
      expect(element.children).to.have.length(0);
    })
  });
```
I would like to understand if this behavior is expected in the new jsdom. I have to change in many places to make this work and was wondering if there was a setting to get the former behavior. I could isolate this by switching jsdom to 11.5.1, keep other libs same.

Any help appreciated.

**Comment by Sebmaster** [comment]
You'll have to reduce this more to native DOM methods, we can't chase down third party library behaviour.

**Comment by domenic** [comment]
Closing since this did not follow the issue template, in particular in that it uses third party libraries. Happy to reopen if an isolated example of some DOM code is provided.
