### ISSUE TITLE
Hide messages for not implemented functionalities

### ISSUE THREAD

**Issue by Aftabnack** [tmpvar/jsdom#2105]
### Basic info:

- **Node.js version:** 8.6.0
- **jsdom version:** Using Jest 22.0.4

### Issue

* Currently I am getting not implemented warnings from JSDOM.

![screenshot from 2018-01-09 19-12-28](https://user-images.githubusercontent.com/15635777/34723562-186dd6b2-f571-11e7-9dda-d736df63124c.png)

* How do I hide these messages? This is cluttering my test run console.

![screenshot from 2018-01-09 19-14-10](https://user-images.githubusercontent.com/15635777/34723627-4f0f98ae-f571-11e7-882c-6a4bd5868b5a.png)

**Comment by domenic** [comment]
https://github.com/tmpvar/jsdom#virtual-consoles

**Comment by Aftabnack** [comment]
Okay! I will look at how it is implemented in Jest, and see if they have exposed this in their usage of JSDOM. Thanks!
