### ISSUE TITLE
New "ws" dependency breaks browser bundling

### ISSUE THREAD

**Issue by domenic** [tmpvar/jsdom#2113]
Example: https://travis-ci.org/tmpvar/jsdom/jobs/329344759

Not sure whether to fix this by just stubbing it out (so you get a bunch of errors in the browser), or actually using the browser's WebSocket API to create the appropriate stub, or just using the browsers WebSocket API in place of our implementation...

**Comment by Zirro** [comment]
Hmm, depending too much on builtins could create compatibility issues and limit the environments where the code (at least in bundled form) can run. I think we should avoid it if we can.

Since the troublesome dependencies are optional, an alternative might be to use browserify's `exclude` option when bundling which should cause ws to use JavaScript fallback code instead.

**Comment by TimothyGu** [comment]
We are already using browser builtins for e.g. XMLHttpRequest, through the browserify `http` shim. `WebSocket` is supported [pretty much everywhere](https://caniuse.com/#feat=websockets), and I think we should make an attempt to support it.

**Comment by Zirro** [comment]
I was thinking of environments where it can be desirable to use a bundled version of jsdom such as Web Workers (though I see that all browsers do expose WebSocket there now) and other engines without a CommonJS environment.

But you're right that we already have an implicit dependency on browser builtins through the shims, so I suppose making it explicit with WebSocket isn't that much of a stretch. With the `exclude` option it might still be possible to only use the ws dependency by excluding the optional dependencies, but I'm not sure if that's preferable to using browser builtins in this case.

**Comment by lpinca** [comment]
If are planning to use a browserified version of ws you are out of luck. As far as I know there is no way to get access to a raw TCP socket in the browser with JavaScript.

**Comment by Zirro** [comment]
@lpinca Ah, that settles it then. I was under the impression that people had managed to use it in the browser from looking through issues such as https://github.com/websockets/ws/pull/661, but I suppose their use case might have been different.

**Comment by graingert** [comment]
fyi you can use `ws-browserify` as a shim here.

**Comment by TimothyGu** [comment]
We use some fairly `ws`-specific features, so `ws-browserify` probably wouldn't really work. Simply creating a new browser-specific `WebSocket-impl.js` file that forwards all method calls to the underlying `WebSocket` object should be enough.

**Comment by domenic** [comment]
I guess we shouldn't release a new version until this is fixed, urgh :-/.
