### ISSUE TITLE
SVGPathElement (and similars) not implemented

### ISSUE THREAD

**Issue by marinho** [tmpvar/jsdom#2126]
(I've open this issue before in https://github.com/facebook/jest/issues/5379 but was advised to open it here instead)

### Basic info:

- **Node.js version:** v8.9.0
- **jsdom version:** 11.6.1
- **TypeScript version:** 2.6.2

**What is the current behavior?**

When running **Jest** with jsdom, it complains `ReferenceError: SVGPathElement is not defined`.

I'm using [path-data-polyfill.js](https://www.npmjs.com/package/path-data-polyfill.js), it uses `SVGPathElement.prototype` to add methods that were removed from SVG API in Chrome (i.e. `getPathData`, `setPathData` and others).

I made a quick search in jsdom source code and couldn't find any mention to `SVGPathElement`

Not only `SVGPathElement` is missing but also `SVGRectElement`, `SVGCircleElement`, `SVGEllipseElement`, `SVGLineElement`, `SVGPolylineElement` and `SVGPolygonElement`.

**What is the expected behavior?**

I would expect any SVG basic element class to be present when running tests with Jest and jsdom.

I'm using jsdom only for running Jest tests.

In my specific case, I solved my problem it by monkey-patching the classes into global myself, but I would like to contribute and implement them partially in jsdom.

**Question:** as it seems these classes aren't implemented at all, following https://github.com/tmpvar/jsdom/issues/1423 and https://github.com/tmpvar/jsdom/pull/1445, **is it acceptable if I file a PR implementing such classes but not fully implemented?**.

**Comment by domenic** [comment]
Thanks, but unfortunately we cannot accept issues that do not follow the issue template. This seems very entangled with Jest, and we cannot take time to debug such issues. Please find a way to isolate this to code only involving jsdom, and we can reopen the issue.

**Comment by TimothyGu** [comment]
> is it acceptable if I file a PR implementing such classes but not fully implemented?.

Yes! I didn’t include them in the initial PR as I just wanted to unbreak a lot of people’s exist scripts, but a patch that includes only stubs for SVG\*Element would be entirely welcome.

@Domenic this issue isn’t really related to Jest at all

**Comment by TimothyGu** [comment]
Also, the current SVG implementation is actually from #2011, not either of the tickets you mentioned

**Comment by marinho** [comment]
@domenic I gave my Jest example because that's the circumstance where it appeared, but as @TimothyGu said, it's a feature request for jsdom only.

I will rewrite it following the template soon, but not today, as I need time to learn how jsdom works on other scenarios different than Jest-based tests.

Thanks, @TimothyGu, I will work it out soon and bring a PR.

**Comment by TaqBostan** [comment]
I had this problem, and it went away after migrating from jsdom to happy-dom.
