### ISSUE TITLE
Cookie/Session Data

### ISSUE THREAD

**Issue by ses1984** [tmpvar/jsdom#310]
Hi, first I would like to say thanks for this awesome project. I love the idea of it. I also have to say that my skill level is not high. I've done some useful front and back end web development but I lack a lot of under-the-hood knowledge that would facilitate being able to hack on projects that are not my own.

I tried searching this page for 'cookie' or 'session' and found no results so I figured that it wouldn't hurt to share my problem here.

I also have to say that I'm not sure if using jsdom is the best approach to this problem. I went for jsdom first because I know how to poke the DOM with javascript and I was a little scared of trying to parse the output of the printer's web server in another language.

I am trying to automate a task that I have to do at my job that requires going through our main copier/printer's web interface. In short, I physically scan a document at the machine, then I want to get the scanned document from the printer's web interface and into a queue on a server for processing.

It was quite difficult trying to figure out exactly what was going on as most of the web interface is composed of nasty nested frames and links to javascript functions that build cgi request strings. After some effort I was finally able to specify what my script needs to do:
* Visit the printer's main page to set a cookie that gives me permission to access other pages
* Visit a page that has the ID number of the document I want to process
* Visit  the document's page to get the ID numbers corresponding to the document images (one image file per page)
* For each image ID found, request that image and put it in my processing queue

Despite the fact that there is no password protection or security of any kind, you have to visit the printer's main page first, and some kind of certificate is assigned to your session, I think in the form of a cookie that stores a number; if the cookie is cleared then it's back to error pages until you go back to the printer's home page.

I need some way for jsdom to set this cookie otherwise it seems like my problem is not really meant to be covered under jsdom.

Thanks for your help.

**Comment by domenic** [comment]
document.cookie works as of 5.0.0!
