### ISSUE TITLE
Parser is shared among all documents

### ISSUE THREAD

**Issue by TomiBelan** [tmpvar/jsdom#322]
Given this code:

    doc1 = jsdom.jsdom(null, null, { parser: html5 })
    doc2 = jsdom.jsdom(null, null, { parser: htmlparser2 })

both doc1 and doc2 will use the same parser (in this case html5). The first call to `jsdom.jsdom` sets the parser program-wide for the rest of its execution. This breaks module isolation etc.

The parser is initialized in `jsdom.browserAugmentation`, but that function only executes once (or perhaps once per DOM level, but doc1 and doc2 both use `jsdom.defaultLevel`).

Of the options that can be passed to `jsdom.jsdom`, `browserAugmentation` uses only `parser`. However, the same problem might apply to other parts of `jsdom` code that 'augment' objects in a similar way. (For example, I'm not sure whether `windowAugmentation` is affected.)

**Comment by domenic** [comment]
Fixed in 4.0.0!
