### ISSUE TITLE
Expose Event constructor

### ISSUE THREAD

**Issue by jreinke** [tmpvar/jsdom#445]
I have an error when I want to include prototype.js 1.7 (version 1.6 is ok)
I use zombie for test but the bug seems to come from jsdom.

node v0.6.16 / npm v1.1.19 / zombie v0.13.6 / jsdom v0.2.14

```html
<html>
<head>
	<title>prototype.js 1.7</title>
	<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/prototype/1.7.0.0/prototype.js"></script>
</head>
<body>
	<p>Just included prototype.js 1.7</p>
</body>
</html>
```

```javascript
var zombie = require("zombie");
zombie.visit("http://localhost/prototype.html", {debug: true}, function(err, browser) {
  if (err) {
    console.log(err.message);
  } else {
    console.log(browser.html());
  }
});
```

Zombie: GET http://localhost/prototype.html => 200
Zombie: GET https://ajax.googleapis.com/ajax/libs/prototype/1.7.0.0/prototype.js => 200
/ajax/libs/prototype/1.7.0.0/prototype.js:5545: TypeError: Cannot read property 'prototype' of undefined
    Event.prototype = window.Event.prototype || document.createEvent('HTMLEven
                                  ^
TypeError: Cannot read property 'prototype' of undefined
    at /ajax/libs/prototype/1.7.0.0/prototype.js:5545:35
    at /ajax/libs/prototype/1.7.0.0/prototype.js:5808:2
    at Object.run (/usr/local/lib/node_modules/zombie/node_modules/jsdom/node_modules/contextify/lib/contextify.js:10:24)
    at /usr/local/lib/node_modules/zombie/lib/zombie/browser.js:166:26
    at Object.javascript (/usr/local/lib/node_modules/zombie/lib/zombie/scripts.js:17:21)
    at Object._eval (/usr/local/lib/node_modules/zombie/node_modules/jsdom/lib/jsdom/level2/html.js:1282:46)
    at Object.<anonymous> (/usr/local/lib/node_modules/zombie/lib/zombie/jsdom_patches.js:49:29)
    at /usr/local/lib/node_modules/zombie/node_modules/jsdom/lib/jsdom/level2/html.js:48:20
    at Object.check (/usr/local/lib/node_modules/zombie/node_modules/jsdom/lib/jsdom/level2/html.js:277:11)
    at /usr/local/lib/node_modules/zombie/node_modules/jsdom/lib/jsdom/level2/html.js:295:12
Zombie: Cannot read property 'prototype' of undefined TypeError: Cannot read property 'prototype' of undefined
    at /ajax/libs/prototype/1.7.0.0/prototype.js:5545:35
    at /ajax/libs/prototype/1.7.0.0/prototype.js:5808:2
    at Object.run (/usr/local/lib/node_modules/zombie/node_modules/jsdom/node_modules/contextify/lib/contextify.js:10:24)
    at /usr/local/lib/node_modules/zombie/lib/zombie/browser.js:166:26
    in /ajax/libs/prototype/1.7.0.0/prototype.js
Cannot read property 'prototype' of undefined

**Comment by domenic** [comment]
Works these days!
