### ISSUE TITLE
classList

### ISSUE THREAD

**Issue by medikoo** [tmpvar/jsdom#510]
It would be great to have support for classList. It has support in most browsers

http://caniuse.com/classlist
http://dom.spec.whatwg.org/#dom-element-classlist

**Comment by pemrouz** [comment]
+1 for classList

**Comment by Joris-van-der-Wel** [comment]
This is way down somewhere on my personal todo. If someone else is going to implement it, note that the polyfill mentioned earlier is not a complete implementation. For example its index properties are not live and it is violating reference equality `foo.classList === foo.classList`

**Comment by aurelienappere** [comment]
+1 for classList
would be awesome :+1:

**Comment by domenic** [comment]
This thread has unfortunately become a +1 magnet, so I am locking it. If someone is interested in implementing, please open a pull request.

**Comment by domenic** [comment]
Fixed in #1213 and going to be released in 6.2.0 in a few minutes!

**Comment by medikoo** [comment]
That's great news. Thank you!

**Comment by flipstewart** [comment]
This is fixed, and that's amazing, but I'm using a version of Jest that requires an old version of jsdom.

I simply needed `classList` to be present on `document.body` and to have a working `toggle` method.

```js
// The version of jsdom we're using doesn't have classLists, so...
document.body.classList = [];
Object.defineProperty(document.body.classList, 'toggle', {
  enumerable: false,
  writable: true,
  value(className) {
    let index = this.indexOf(className);
    index > -1
      ? this.splice(index, 1)
      : this.push(className);
    return !(index > -1);
  }
});
```

Adding this code into my test took care of things, so maybe a similar solution will help folks in similar situations :smile:
