### ISSUE TITLE
Add events to el.focus() and el.blur()

### ISSUE THREAD

**Issue by tmpvar** [tmpvar/jsdom#533]
Right now we are just changing the `document.activeElement`, but I believe we need to emit events as well.

Also, tests.

**Comment by nylen** [comment]
It looks like this is still an issue.  I have some code that needs to read `document.activeElement` in a `blur` event handler (since nobody told IE11 about `relatedTarget`).  In order to test this code using `jsdom`, we have to use an extra step:

```js
// 1. Reset document.activeElement (pick one, these are equivalent)
myElement.blur();
document.activeElement = document.body;

// 2. Send an event to call handlers
myElement.dispatchEvent( new Event( 'blur' ) );
```
