### ISSUE TITLE
Setting proxy doesn't seem to work with scripts

### ISSUE THREAD

**Issue by pvencill** [tmpvar/jsdom#567]
So, trying to use jsdom from behind a proxy.  Doing this:

j.env({ html: 'http://www.google.com/', scripts : ['http://code.jquery.com/jquery.js'], done : console.log, proxy: process.env.http_proxy});

works as expected.  Trying to parse the document instead using jquery:

j.env({ html: 'http://www.google.com/', scripts : ['http://code.jquery.com/jquery.js'], done : function(e,w){ w.$('a[href]').each(function(l){ console.log(l.attr('href'));}); }, proxy: process.env.http_proxy});

results in an error :  

repl:1
pts : ['http://code.jquery.com/jquery.js'], done : function(e,w){ w.$('a[href]
                                                                    ^
TypeError: Object #<Object> has no method '$'

which leads me to believe the jquery library isn't downloading and being used by the document.  Thoughts?

**Comment by glennschler** [comment]
There is a working option now for downloading script resources when behind a proxy.

As @vesse mentioned above, the [Controlling proxy behaviour using environment variables](https://github.com/request/request/blob/4455e53c535609746465775f78e958b94e560b2f/README.md#controlling-proxy-behaviour-using-environment-variables) should be a resolution. This now does work when using jsdom version 7.0.1. Seems the latest [browser/resource-loader.js](https://github.com/tmpvar/jsdom/blob/master/lib/jsdom/browser/resource-loader.js#L91) does not hard set the proxy option, so the Request module is able to follow it's native rules.
