### ISSUE TITLE
request.setTimeout

### ISSUE THREAD

**Issue by silentroach** [tmpvar/jsdom#596]
Hi!

It will be great if you will implement some timeout support for jsdom requests.
Thank you for package!

**Comment by aggied** [comment]
Is this resolved then? Can't find any reference, and if the feature is enabled I'm not sure how to access it

**Comment by domenic** [comment]
One way you can implement this is by using a custom resource loader: https://github.com/tmpvar/jsdom#custom-external-resource-loader

**Comment by aggied** [comment]
thanks for the quick response @domenic ! I need to be able to control the timeout for the original request that gets the `url` I supply to `jsdom.env`. I'll keep in mind the custom resource loader for any of the resulting resources, but do you know how I can manage the timeout for the original request?

**Comment by domenic** [comment]
The best way is to make the request yourself, then feed the resulting HTML to jsdom.
