### ISSUE TITLE
Support for CustomEvent (and the general plan for Level 3 support)

### ISSUE THREAD

**Issue by rprieto** [tmpvar/jsdom#611]
Hi,

I noticed `jsdom` doesn't support Level 3 [custom events](https://developer.mozilla.org/en-US/docs/DOM/Event/CustomEvent), so the following code crashes:

```
var tap = document.createEvent('CustomEvent');
tap.initCustomEvent('tap', true, true, {});
```

It would be relatively trivial to add a basic empty implementation in the level 2 folder (baaaaad), but I wouldn't know where to start with Level 3 (everything is commented-out). What's the plan in that area?

On a related topic, the new standard seems to be [using event constructors instead of initCustomEvent](http://www.w3.org/TR/domcore/#constructing-events). Does that fit into Level 4 support?

```
var event = new Event('focus', {bubbles:false,cancelable:true});
document.querySelector('input').dispatchEvent(event);
```

**Comment by treshugart** [comment]
@rprieto I found that doing something like the following worked for my purposes:

```js
let opts = { bubbles: true, cancelable: true, detail: null };
let e = document.createEvent('HTMLEvents');
e.detail = opts.detail;
e.initEvent(name, opts.bubbles, opts.cancelable);
```

**Comment by sjungwirth** [comment]
I'm running into an issue here as well with the lack of CustomEvent support.

**Comment by Sebmaster** [comment]
It's currently being implemented here: https://github.com/tmpvar/jsdom/pull/1258 follow there for updates, but we need to get some basic infrastructure down before we can merge it.

**Comment by domenic** [comment]
Fixed by https://github.com/tmpvar/jsdom/commit/5459bec38660658e4e18642265f61c3d79e984dd
