### ISSUE TITLE
Crash on jsdom window.close() when adding jquery when lots of extant windows

### ISSUE THREAD

**Issue by cdent** [tmpvar/jsdom#614]
Under load a node process using jsdom + jquery to make and process many windows can crash and dump core:

```
#
# Fatal error in ../deps/v8/src/api.h, line 297
# CHECK(allow_empty_handle || that != __null) failed
#
```

The backtrace of the core file is not very helpful (presumably due to lack of available symbols):

```
#0  0x00007fff96302212 in __pthread_kill ()
```

[this gist](https://gist.github.com/cdent/5459753) will demonstrate the bug. Running the same setup without jsdom and jquery or with just jsdom but not jquery (`act2` and `act3` respectively) does not tickle the bug. Note that the setup, though bizarre with its random timeouts, manages to mirror the real use case from which this more minimal test case is extracted. In that real situation fewer jsdom windows need to exist before the problem shows up. The `1382` number was the lowest number on my machine that would tweak the problem, but on different machines I would expect it to be different. I presume the problem is not the number of windows themselves, but their state.

I assume this is a problem with contextify so /cc @brianmcd but didn't want to report there as my data doesn't actually point there in any direct way.

Note also that the problem shows up (in the real world code) whether the jquery is done via `jquery.create` or `jsdom.jQueryify`. I have not had a chance to test with some other script, but I guess that would be a good way to validate the contextify theory.

Happy to provide whatever additional info or testing is useful.

Current setup:

```
$ uname -a
Darwin rust.local 12.3.0 Darwin Kernel Version 12.3.0: Sun Jan  6 22:37:10 PST 2013; root:xnu-2050.22.13~1/RELEASE_X86_64 x86_64
$ node -v
v0.10.5
$ npm list
npm WARN package.json test@0.0.1 No README.md file found!
test@0.0.1 /private/tmp/cun/testnode
├─┬ jquery@1.8.3
│ ├─┬ contextify@0.1.5
│ │ └── bindings@1.1.0
│ ├── htmlparser@1.7.6
│ ├─┬ jsdom@0.2.19
│ │ ├── cssom@0.2.5
│ │ ├── cssstyle@0.2.3
│ │ └─┬ request@2.20.0
│ │   ├── aws-sign@0.3.0
│ │   ├── cookie-jar@0.3.0
│ │   ├── forever-agent@0.3.0
│ │   ├─┬ form-data@0.0.8
│ │   │ ├── async@0.2.7
│ │   │ └─┬ combined-stream@0.0.4
│ │   │   └── delayed-stream@0.0.5
│ │   ├─┬ hawk@0.10.2
│ │   │ ├── boom@0.3.8
│ │   │ ├── cryptiles@0.1.3
│ │   │ ├── hoek@0.7.6
│ │   │ └── sntp@0.1.4
│ │   ├─┬ http-signature@0.9.11
│ │   │ ├── asn1@0.1.11
│ │   │ ├── assert-plus@0.1.2
│ │   │ └── ctype@0.5.2
│ │   ├── json-stringify-safe@3.0.0
│ │   ├── mime@1.2.9
│ │   ├── node-uuid@1.4.0
│ │   ├── oauth-sign@0.3.0
│ │   ├── qs@0.5.6
│ │   └── tunnel-agent@0.3.0
│ ├── location@0.0.1
│ ├── navigator@1.0.1
│ └── xmlhttprequest@1.4.2
└─┬ jsdom@0.6.0
  ├─┬ contextify@0.1.5
  │ └── bindings@1.1.0
  ├── cssom@0.2.5
  ├── cssstyle@0.2.3
  ├─┬ htmlparser2@3.0.5
  │ ├── domelementtype@1.1.1
  │ ├── domhandler@2.0.3
  │ ├── domutils@1.1.2
  │ └── readable-stream@1.0.2
  ├── nwmatcher@1.3.1
  └─┬ request@2.20.0
    ├── aws-sign@0.3.0
    ├── cookie-jar@0.3.0
    ├── forever-agent@0.3.0
    ├─┬ form-data@0.0.8
    │ ├── async@0.2.7
    │ └─┬ combined-stream@0.0.4
    │   └── delayed-stream@0.0.5
    ├─┬ hawk@0.10.2
    │ ├── boom@0.3.8
    │ ├── cryptiles@0.1.3
    │ ├── hoek@0.7.6
    │ └── sntp@0.1.4
    ├─┬ http-signature@0.9.11
    │ ├── asn1@0.1.11
    │ ├── assert-plus@0.1.2
    │ └── ctype@0.5.2
    ├── json-stringify-safe@3.0.0
    ├── mime@1.2.9
    ├── node-uuid@1.4.0
    ├── oauth-sign@0.3.0
    ├── qs@0.5.6
    └── tunnel-agent@0.3.0
```

**Comment by domenic** [comment]
I am almost sure this is fixed given the removal of contextify in jsdom 4.0.0. Certainly will reopen if anyone has a repro.
