### ISSUE TITLE
Canvas element fails "instanceof HTMLElement"

### ISSUE THREAD

**Issue by mitar** [tmpvar/jsdom#649]
At least the canvas element (I have not tested other) returns false on "element instanceof HTMLElement". It should return true.

**Comment by rgbkrk** [comment]
Is there a way to get access to the `HTMLElement` class directly from jsdom, to be extended in es6 contexts?

**Comment by domenic** [comment]
`window.HTMLElement` works. Not sure what that has to do with this issue though.

**Comment by domenic** [comment]
Confirmed this is still broken as of 6.1.0.
