### ISSUE TITLE
CSS parsing errors show up in the jsdom.env errors array.

### ISSUE THREAD

**Issue by TravelingTechGuy** [tmpvar/jsdom#687]
I'm using the latest JSDom (0.8.5)to scrape Amazon reviews:
```
var url = 'http://www.amazon.com/product-reviews/B002RLR0EY/?ie=UTF8&showViewpoints=0&pageNumber=1&sortBy=bySubmissionDateDescending';
require('jsdom').env(url, ["http://code.jquery.com/jquery.js"], function(errors, window) {
    console.log(errors);
    var $ = window.$;
    console.log('product name:', $('#productSummary').parent().find('a:first').text());
    window.close();
});
```

I'm getting this error, consistently, from every page I scrape, even though I get all the results properly:

```
[ { type: 'error',
    message: 'Dispatching event \'DOMNodeInsertedIntoDocument\' failed',
    data: { error: [Object], event: [Object] } } ]
```

I'm at the point where I actually have code in place to ignore this specific error. But that feels unsafe (even dirty :)) somehow.

Any idea what's causing this and how to avoid this error? I saw a similar issues from 2 years ago, marked **closed**, though no explanation provided.

**Comment by domenic** [comment]
6.0.0 fixed this by changing the error-reporting structure pretty drastically.
