### ISSUE TITLE
WHATWG HTML requires appending event attributes to event queue

### ISSUE THREAD

**Issue by terinjokes** [tmpvar/jsdom#696]
In the current WHATWG HTML spec, handlers added via the "traditional" event attributes on a DOM element should be appended to the same queue as events added via the DOM spec.
#### 7.1.6.1 Event handlers

> […]
> 
> When an event handler H of an element or object T implementing the EventTarget interface is first set to a non-null value, the user agent must append an event listener to the list of event listeners associated with T with type set to the event handler event type corresponding to H, capture set to false, and listener set to the event handler processing algorithm defined below.
> 
> […]
> 
> This example demonstrates the order in which event listeners are invoked. If the button in this example is clicked by the user, the page will show four alerts, with the text "ONE", "TWO", "THREE", and "FOUR" respectively.
> 
> ```
> <button id="test">Start Demo</button>
> <script>
>  var button = document.getElementById('test');
>  button.addEventListener('click', function () { alert('ONE') }, false);
>  button.setAttribute('onclick', "alert('NOT CALLED')"); // event handler listener is registered here
>  button.addEventListener('click', function () { alert('THREE') }, false);
>  button.onclick = function () { alert('TWO'); };
>  button.addEventListener('click', function () { alert('FOUR') }, false);
> </script>
> ```
> 
> […]

**Comment by Sebmaster** [comment]
Fixed in 5f3cbd6.
