### ISSUE TITLE
namespaceURI property missing?

### ISSUE THREAD

**Issue by Pomax** [tmpvar/jsdom#705]
I'm doing some DOM validation work using html
```
var html = "<html><body><p>test</p><svg width='100' height='100' viewbox='0 0 100 100'><path d='"+d+"'/></svg><p>test</p></body></html>";
```

and it appears that HTML nodes are not given their correct namespaceURI property. This, for instance, returns `null`:  `console.error("DOM: ", require("jsdom").jsdom(html).childNodes[0].namespaceURI);`

in browsers this will return "http://www.w3.org/1999/xhtml" (even if under HTML5 rules that namespace is technically irrelevant).

The same goes for SVG elements inside HTML, although they should report "http://www.w3.org/2000/svg" (but be parsed according to the HTML5 rules, which treats the SVG element as properly part of HTML)

**Comment by domenic** [comment]
Works these days!
