### ISSUE TITLE
Fixing the wrong document error

### ISSUE THREAD

**Issue by mkschreder** [tmpvar/jsdom#717]
What is the purpose of these lines in level1/core.js file?

line 514:
if (newChild._ownerDocument !== this._ownerDocument) {
      throw new core.DOMException(WRONG_DOCUMENT_ERR);
    }

These lines come in the way of using local node-jquery for manipulating the document. In particular doing $("some selector").append($("<newelement>")) generates wrong document error if $ represents a custom jquery ie $ = require("jquery") instead of window.$. 

I have today successfully been using local jquery after commenting out these lines.

My question is: can commenting out these lines lead to any unexpected results down the road?

**Comment by dmethvin** [comment]
@domenic maybe that was true in an older spec? The current spec says that nodes are auto-adopted (search for "adopt" or "adopting steps") and browsers seem to apply this algorithm. There are only a couple of obscure methods that throw WrongDocumentError.

**Comment by dmethvin** [comment]
BTW let me know if I can help with something here, I'd rather move jsdom forward than move jQuery back to its old method of creating elements. Is [this](https://github.com/tmpvar/jsdom/blob/3cee6eea9b480da76624f8f3cac15a2f9b7b4068/lib/jsdom/living/nodes/Node-impl.js#L184-L187) the right area? Seems like it would need to change to call `adoptNode` which [isn't currently implemented](https://github.com/tmpvar/jsdom/blob/9dd9069354e36c077032f4cbcb1616a7d9e6f0c4/lib/jsdom/living/nodes/Document.idl#L28).

**Comment by domenic** [comment]
Oh cool, yeah! That is the right area indeed. I'm happy to accept a quick-patch of that area for now with a small test and worry about the larger spec-compliance issue later. insertBefore needs to be rewritten to follow the modern DOM spec in general; see also #1349.

**Comment by rlgomes** [comment]
Having the same problem, @dmethvin any chance you'll put up a patch ? I can futz about to figure out how to solve this but not familiar enough with the jsdom project to get this done in a reasonable amount of time. I can although help test out a patch on a few local tests that I wanted to use jsdom to avoid using phantom to unit test some code, which is where I hit this same issue.

**Comment by rlgomes** [comment]
Another scenario that just triggerd the `WrongDocumentError` for me was when using jQuery (again) to create a document fragment like so: `$('<span>some text</span>')` where internally jQuery builds a document fragment and then creates a TextNode and attempts to append it but since the ownerDocument isn't of the type *core.Document* we hit this same `WrongDocumentError`.

**Comment by dmethvin** [comment]
Yes, pretty much any HTML-to-DOM conversion in jQuery 2.2+ will run into this issue with jsdom. One workaround would be to explicitly pass `document` as the context , but that is most likely impractical for a lot of scenarios.

There are some [security reasons](https://github.com/jquery/jquery/blob/fe05cf37ffd4795988f9b2343df2182e108728ca/src/core/parseHTML.js#L24-L28) why we want to keep this, although we [can't fix older Safaris](https://github.com/jquery/jquery/blob/fe05cf37ffd4795988f9b2343df2182e108728ca/src/core/support.js). If you can modify your local copy of jQuery you could just set `support.createHTMLDocument = false` where it's being assigned and use it only for jsdom testing.

I'll see if I can figure out jsdom well enough to write a patch in the next week.
