### ISSUE TITLE
Why are file paths and their exports in code convoluted?

### ISSUE THREAD

**Issue by moll** [tmpvar/jsdom#718]
Hello!

1. Why is everything in a separate `lib/jsdom` directory? It makes sense in Ruby because it adds everything in `lib` to the global load path, but in Node it doesn't. It's unnecessary nesting.

2. Why are individual files exporting so deeply nested structures instead of just their own concern? Seeing `require("./lib/jsdom/level2/core").dom.level2.core` is ridiculous. ;)

3. This is a criticism unrelated to nesting, but why are individual files with concerns changing globals, rather than the globals requiring and combining things themselves? The immediate example is `level2/style.js` that, rather than returning its concerns to its caller, attaches them to the DOM core and returns a weird nested structure again.

Just out of curiosity, are any of the JSDOM's architects Ruby or Java guys that come up with such deep nesting? :-)

**Comment by domenic** [comment]
See README at https://github.com/tmpvar/jsdom/tree/master/lib
