### ISSUE TITLE
JSDOM error handling

### ISSUE THREAD

**Issue by JacksonGariety** [tmpvar/jsdom#726]
Is there any way to make JSDOM forward script errors to Node.js?

I assumed the following would log `undefined has no method 'toString'` but the errors are null:

    jsdom.env(
      '<html><script>nonExistentVariable.toString()</script></html>'
    , []
    , function (errors, window) {
        console.log(errors)
      }
    )

**Comment by domenic** [comment]
This should all be fixed in 6.0.0, especially when using a virtual console :)

**Comment by SystemParadox** [comment]
In case this helps anyone else, in 3.1.1 I had to add the following to forward errors from event scripts (otherwise they go silently unnoticed):

```
document.raise = function (type, message, data) {
    if (data.error) {
        throw data.error;
    } else {
        console.error('ERROR', message);
    }
};
```

**Comment by nodejsdevs** [comment]
Help me, i already checked this  https://nodeer.space/questions/what-is-the-best-way-to-handle-errors-generated-by-my-jsdomjqueryify-callback-function
