### ISSUE TITLE
Keyboard events

### ISSUE THREAD

**Issue by JacksonGariety** [tmpvar/jsdom#730]
I see the commented-out DOM source includes keyboard events.

Assuming they aren't already implemented, how would I go about adding them to JSDOM? Is there any reason they haven't been implemented already? Would this be trivial for me to add myself?

**Comment by dbrans** [comment]
+1

**Comment by domenic** [comment]
Fixed by https://github.com/tmpvar/jsdom/commit/5459bec38660658e4e18642265f61c3d79e984dd

**Comment by edrpls** [comment]
Hi, unfortunately I'm stuck on an older Node version, is there any other way to trigger keyboard events?

**Comment by Sebmaster** [comment]
No, `KeyboardEvent`s were never implemented before this change.

**Comment by edrpls** [comment]
Okay, thanks for your response.

**Comment by Joris-van-der-Wel** [comment]
Have you tried using [nvm](https://github.com/creationix/nvm) to install the latest node? (you do not need root)

**Comment by edrpls** [comment]
Thanks for the suggestion, but the problem is that it will run on a corp machine with a specific version that can't be modified from the outside.
