### ISSUE TITLE
canvas id ignored when using node-canvas

### ISSUE THREAD

**Issue by Bjvanminnen** [tmpvar/jsdom#737]
I have the following code.  When I run without node-canvas installed, I can find both the div and canvas by id.  When I run with node-canvas installed, I can no longer find the canvas by id.

```
var jsdom = require('jsdom').jsdom;

var html = '<div id="mydiv"></div>';
var dom = jsdom(html);
console.log(dom.getElementById('mydiv') !== null);

html = '<canvas id="mycanvas"></canvas>';
dom = jsdom(html);
console.log(dom.getElementById("mycanvas") !== null);
```

**Comment by jpswade** [comment]
+1
Over 12 months since this issue was opened.

@domenic perhaps you could point us in the right direction as to what is blocking this?

**Comment by domenic** [comment]
@jpswade what's blocking this is that you haven't submitted a pull request to fix this.

**Comment by jpswade** [comment]
@domenic I haven't submitted a pull request because I am not versed in this project. Please advise.

**Comment by domenic** [comment]
@jpswade you know about as much about the canvas code as I do. Otherwise, for general guidelines, please read CONTRIBUTING.md.

**Comment by robertjustjones** [comment]
@jpswade Take a look or try #1025.  It very well may fix your issue.
@domenic I'm still watching for node-canvas to release an update so that we can close that.
