### ISSUE TITLE
jsdom.env with document.referrer doesn't seem to send the header

### ISSUE THREAD

**Issue by mblakele** [tmpvar/jsdom#745]
I'm new to jsdom so I may be doing something wrong here, but it seems like referrer headers aren't being sent over the wire. First, I notice that the `README.md ` says "referer" but the code seems to expect `referrer` (usual confusion over spelling, which dates back to the original RFE). But either way, `tcpdump` shows the request going out without any extra headers.

This code is a simplified version of what I'm doing. In this example I'm setting both referer and referrer, just to be on the safe side.

        jsdom.env({
            url: "http://example.com",
            document: {
                referer: "http://example.com",
                referrer: "http://example.com" },
            scripts: ["http://code.jquery.com/jquery.js"],
            done: function (errors, window) {
                console.log('errors', errors);
                console.log('referrer', window.document.referrer); } });

The log shows that the response object thinks referrer has been set, and that's all the test case at `test/jsdom/env.js` checks. But according to `tcpdump` there is no Referrer or Referer header on the actual request. So if a site requires a Referer header, the request fails.

I've done a little hacking around and I think the problem might be in the way `http.request` is used. I can set the Referer header using `http.get` directly. That gives me a workaround, since I should be able to slurp the response directly and then use it with jsdom as needed.

            http.get({
                host: 'example.com',
                path: '/',
                headers: {
                    'Referer': "http://example.com" } },
                     function(res) { ...

I'm using jsdom 0.10.1 from npm and node 0.10.25, running on OSX.

**Comment by domenic** [comment]
I guess we have a `headers` option now.
