### ISSUE TITLE
HTML5 Video Tag Problem

### ISSUE THREAD

**Issue by flavioribeiro** [tmpvar/jsdom#754]
Hi, I'm facing an issue with html5 video tag and play() method. It seems jsdom doesn't support it:

```
> jsdom.env("<video src=test.mp4>", ["http://code.jquery.com/jquery.js"], function (err, window) { window.$('video')[0].play(); } );
undefined
>
repl:1
uery.com/jquery.js"], function (err, window) { window.$('video')[0].play(); }
                                                                    ^
TypeError: Object [ VIDEO ] has no method 'play'
    at repl:1:146
    at /Users/flavio.barbosa/Development/player/node_modules/jsdom/lib/jsdom.js:255:9
    at process._tickCallback (node.js:415:13)
```

This call is a side effect of another test I'm writing, and I imagine that jsdom shouldn't break. At least for me, it would be better to just silence play/pause/stop method calls to video tag.

**Comment by stephenhandley** [comment]
Any update on this?

**Comment by piranna** [comment]
I'm also interested on this for testing purposses. Is there any update?

**Comment by marcemira** [comment]
Also interested on this feature

**Comment by domenic** [comment]
A reasonable stub was added in 6.1.0. Let's open new issues for anything in particular that needs to be added.
