### ISSUE TITLE
Support the HTML5 form attribute for inputs

### ISSUE THREAD

**Issue by stof** [tmpvar/jsdom#765]
In HTML5, input elements can have a ``form`` attribute, to associate them with the form tag with the corresponding id rather than to their closest form ancestor. But this is not supported currently.
This impacts 2 places:

- the implementation of the ``form`` getter for all field elements (input, select, textarea and button)
- the retrieval of elements of a form element

**Comment by stof** [comment]
@domenic any news about this ?

**Comment by domenic** [comment]
PR welcome!

**Comment by domenic** [comment]
This seems to be implemented these days.

**Comment by jamietre** [comment]
@domenic  not sure if this is a regression or it never was, but this does not exist in current release of jsdom, so requesting this be reopened.

Repro:

https://github.com/jamietre/jsdom-form-attribute

**Comment by domenic** [comment]
Submit events are unrelated to `form=""` attributes. If you could file a new issue following the template that'd be helpful. In particular not using any third-party testing frameworks, but just using jsdom itself.

**Comment by jamietre** [comment]
Not sure I understand the assertion that they aren't related; the existence of `form="foo"` on a button is what associates is with `<form id="foo">` and results in its `submit` event being triggered when the button is clicked. For example, https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button

> form HTML5
> The form element that the button is associated with (its form owner). The value of the attribute must be the id attribute of a `form` element in the same document. If this attribute is not specified, the <button> element will be associated to an ancestor `form` element, if one exists. This attribute enables you to associate `button` elements to `form` elements anywhere within a document, not just as descendants of `form` elements.

But I'm happy to revise the repo to not use mocha & file a new issue.
