### ISSUE TITLE
DOMNodeInserted not firing when `useCapture` is `true`

### ISSUE THREAD

**Issue by STRd6** [tmpvar/jsdom#768]
DOMNodeInserted doesn't fire when `useCapture` is `true`, though it does fire when `useCapture` is `false` or not set.

In Google Chrome all three tests pass.

In jsdom the first one fails and the other two pass.

    describe "jsdom DOMNodeInserted", ->
      it "should fire DOMNodeInserted when inserting a node into the DOM (use capture true)", (done) -> # FAILS!
        div = document.createElement "div"

        div.addEventListener "DOMNodeInserted", ->
          done()
        , true

        document.body.appendChild div

      it "should fire DOMNodeInserted when inserting a node into the DOM (use capture false)", (done) -> # Passes
        div = document.createElement "div"

        div.addEventListener "DOMNodeInserted", ->
          done()
        , false

        document.body.appendChild div

      it "should fire DOMNodeInserted when inserting a node into the DOM (use capture undefined)", (done) -> # Passes
        div = document.createElement "div"

        div.addEventListener "DOMNodeInserted", ->
          done()

        document.body.appendChild div

**Comment by domenic** [comment]
We got rid of mutation events, so I guess we should close this.
