### ISSUE TITLE
XMLHttpRequest is not using globalAgent so it's easy to exhaust available fds

### ISSUE THREAD

**Issue by kapouer** [tmpvar/jsdom#790]
Since there is no pooling for xhr requests in jsdom, a client can easily exhaust available file descriptors, leading to errors like `getaddrinfo ENOTFOUND in dns.js`.
This typically happen when rendering tiled json maps (and i'm doing that kind of thing).
The fix is to make XMLHttpRequest use a custom agent (or at least globalAgent), but that's not possible because https://github.com/driverdan/node-XMLHttpRequest/issues/44 was never solved.
[Here's a merged repository](https://github.com/kapouer/node-XMLHttpRequest) with fixed version 1.5.1.
This module looks unmaintained, maybe it would be good to jsdom to maintain its own fork of it.

**Comment by domenic** [comment]
This should be fixed by 2c8933905e9b81436843fe8d429918876a277e54!!
