### ISSUE TITLE
input.selectionStart is undefined

### ISSUE THREAD

**Issue by STRd6** [tmpvar/jsdom#799]
In the Chrome console I can get the selectionStart attribute of an input element, but in jsdom it is always undefined. 

Expected (Chrome Version 35.0.1916.114)

    input = document.createElement("input")
    input.selectionStart // => 0

Actual (jsdom 0.10.5)

    input = document.createElement("input")
    input.selectionStart // => undefined

**Comment by yaycmyk** [comment]
And now https://github.com/tmpvar/jsdom/pull/1305! :)

**Comment by domenic** [comment]
Merged! 7.2.0 coming out shortly!!
