### ISSUE TITLE
Performance Regression?

### ISSUE THREAD

**Issue by btakita** [tmpvar/jsdom#805]
From my test suite, it seems like there are some performance regressions between v0.8.10 and v0.11.0. In every test, a new dom is constructed. There is also heavy client-side rendering and interaction with DOM events. I'm using jQuery, backbonejs, & handlebars.

The run times of my test suites are the following:

v0.8.10 - 290 seconds
v0.11.0 - 500 seconds

**Comment by domenic** [comment]
Performance has massively improved recently. I'm going to close this for now in favor of more specific bugs people can open, preferably with test code.
