### ISSUE TITLE
HTML id and global variable

### ISSUE THREAD

**Issue by Mickael-van-der-Beek** [tmpvar/jsdom#822]
In normal browsers, if you have a DOM node containing an ```id```, the value of that ```id``` will be used as a key on the ```window``` object and the value will be a reference to the DOM node. e.g:

```<div id="testy">Hello World!</div>```

in this example, the ```window``` object will have a property called ```testy```.

Now, ```window['testy']``` will return the reference to the ```<div>``` we created earlier.

This is not the case in JSDOM.

**Comment by domenic** [comment]
Fixed by #1116!
