### ISSUE TITLE
NodeList should not have a length setter

### ISSUE THREAD

**Issue by lawnsea** [tmpvar/jsdom#859]
Several `NodeList` methods use `Array.prototype.slice` and `Array.prototype.splice`. Unfortunately, both Firefox and Chrome expect to be able to set the `length` of arrays that are `slice`d or `splice`d. To work around this problem for #849, I added a `length` setter to `NodeList` that ignores the new value and uses `_length`.

This is not ok in the long run, however, as we want `NodeList` to look like the real thing, which exposes a read-only `length` property.

See https://github.com/TreehouseJS/jsdom/commit/15e3c4fa91d70ea803074aa21d61f36667db1b63 and tmpvar/jsdom#850 for details.

**Comment by domenic** [comment]
Fixed in master, yay
