### ISSUE TITLE
AttributeList._$reserved generates error during Mocha testing

### ISSUE THREAD

**Issue by johntitus** [tmpvar/jsdom#867]
I use jsdom to do some automated testing along with Mocha, and ran into a strange error. I have a folder of about a dozen test files. If I execute the one that uses JSDOM like this:

**mocha -R spec -t 45000 accesscontrol.test.js --server=serverA**

The test runs fine. If I try and execute all of the test files in the local directory, like this:

**mocha -R spec -t 45000 *.test.js --server=scott**

I get the following error:

**TypeError: Property 'valueOf' of object object is not a function**

I traced this error to this line, in jsdom/lib/level1/core.js:

**reserved = reserved.concat(Object.getOwnPropertyNames(prototype));**

If I put that line in a try/catch block, and just ignore the error, the tests proceed fine. I decided to console.log(prototype), along with the "LOGGING PROTOTYPE" header, just to see what happens. This is the output:
LOGGING PROTOTYPE
{ '_$reserved': [],
  '$getNoNS': [Function],
  '$getNode': [Function],
  '$setNoNS': [Function],
  '$set': [Function],
  '$setNode': [Function],
  '$removeNoNS': [Function],
  '$remove': [Function],
  '_$onlyRemoveNode': [Function],
  '$removeNode': [Function],
  getNamedItem: [Function],
  removeNamedItem: [Function],
  item: [Function],
  getNamedItemNS: [Function],
  removeNamedItemNS: [Function],
  setNamedItem: [Function],
  setNamedItemNS: [Function] }
LOGGING PROTOTYPE
{}

I honestly have no idea what this section of the code does, so I can't narrow it down much further.

Node: 0.10.26
Mocha: 1.12.0
JSDOM: 1.0.0-pre.3

**Comment by domenic** [comment]
As of 5.4.0 _$reserved no longer exists, so this should no longer be an issue :)
