### ISSUE TITLE
Improve X(HT)ML support

### ISSUE THREAD

**Issue by domenic** [tmpvar/jsdom#885]
Our goal is to be as good as browsers, but no better. In particular, we are not an arbitrary XML DOM. But, we do need to switch parsing modes, produce XmlDocuments, etc. Lots of work to do. @Sebmaster has been leading the charge on this.

**Comment by felixfbecker** [comment]
This would be very nice. Currently the only option for parsing XML in Node is xml2js, which is a pain to work with. I would much rather work with true [Nodes](https://developer.mozilla.org/en-US/docs/Web/API/Node) like defined in the DOM standard.

**Comment by Sebmaster** [comment]
@felixfbecker We don't have proper XHTML support, but if you only need to get XML into a DOM-like structure to be able to query it, you can set `parsingMode: "xml"`, which should work - there might be XML features we don't (yet) support though.

**Comment by domenic** [comment]
With the addition of strict XHTML parsing, I am going to consider this closed. Other bugs in the x(h)tml tag track specific issues; there definitely are some left.
