### ISSUE TITLE
onreadystatechange not in document -- breaks MooTools 1.5.1

### ISSUE THREAD

**Issue by si13b** [tmpvar/jsdom#931]
Hello,

We are having issues with running the MooTools 1.5.1 library within JSDOM/contextify.

We use a 1.5.1 version of the library built at the following location: http://mootools.net/core/367e0590290c2a3e76fbb5c455d9ebc5

We get the following error when executing `mootools-core.js`:
```
"TypeError: Cannot call method 'addEvent' of null"
```

The problematic line of code seems to be the following, which is inside an IIFE with window and document passed in as parameters. For some reason window is null, as per the error above?:
```
window.addEvent('load', function () {
	loaded = true;
});
```

Removing this statement in a modified version of mootools-core.js allows us to continue and the library works for the most part, but I don't understand why it isn't working in the first place.

**Comment by domenic** [comment]
Subsuming into #1063.
