### ISSUE TITLE
Using Contextify's createScript in association with jsdom's window

### ISSUE THREAD

**Issue by tolmasky** [tmpvar/jsdom#938]
I'm wondering if caching out a compiled script using Contextify's createScript is a viable strategy to address two possible performance issues in some jsdom stuff that I am running repeatedly:

1. Reparsing a very large script
2. Avoiding network chatter of loading it over and over

Something along these lines:

```javascript
var script_string;
var compiled_script = Contextify.createScript(script_string)
jsdom.env(html_string, { done: function(errors, window) { compiled_script.runInContext(window); });
```

**Comment by domenic** [comment]
No longer using Contextify, so, we're good.
