### ISSUE TITLE
Include a readme example of fragment parsing using <template>

### ISSUE THREAD

**Issue by domenic** [tmpvar/jsdom#941]

**Comment by RickyChien** [comment]
Hi, @domenic, Are there any special usages in using <template>? 
I just invoked ```var doc = jsdom(myTemplateHTMLString);``` but got ```TypeError: Cannot call method 'toLowerCase' of undefined```

myTemplateHTMLString is like:

```
<element>
  <template>

      <div>
      </div>

  </template>
</element>
```
Would you mind to take a look at it? Thanks

**Comment by domenic** [comment]
This is built in to newapi.
