### ISSUE TITLE
jQuery .val() method on a cloned form element doesn't update its value attribute

### ISSUE THREAD

**Issue by dr-nick** [tmpvar/jsdom#946]
I had a weird problem using zombie.js for a functional test of some production cloning script. It seems that using jQuery's `val()` on a cloned, unattached element doesn't work as it would in-browser. Here's a stripped-down scenario to reproduce it:

```html
<html><body>
<form>
	<input type="text" id="sourceField" name="field" value="should not expose this">
</form>

<script>
(function($) {
	var $template = $('#sourceField').clone();
	$template.val('');
	var $new = $template.clone();
	// in production code, would rename and append here
	console.log($new.prop('name') + ': ' + $new.val());
})(jQuery);
</script>
</body></html>
```

Running this in a browser console, you see:

    field:

In zombie.js, the console shows:

    field: should not expose this

If I replace the `$template.val('');` with `$template.attr('value', '');`then the code works consistently in both. It seems that the `.val()` method doesn't update the value attribute of the cloned node, which allows its content to persist across further clone operations.

I see it using jQuery 1.8 through 1.11.1. Looking at the [jQuery code](https://github.com/jquery/jquery/blob/1.x-master/src/attributes/val.js) it seems that it should be a pretty straightforward assignment. I'd welcome someone with better knowledge of jsdom taking a quick look to see if it's an obvious bug in how it's handled.

**Comment by domenic** [comment]
#1143 adds "cloning steps" so this should be a much easier fix after that lands.

**Comment by matthewp** [comment]
I'd like to take this one on. It looks like all that's needed is to add a cloningSteps hook in the input element and make sure _value is copied over?

**Comment by domenic** [comment]
Awesome! Yeah, I think that's the main part. It would also be good to also propagate the other things mentioned in the spec; I believe our impl has direct counterparts of all of them.

**Comment by matthewp** [comment]
I assume you mean this part:

> The cloning steps for input elements must propagate the value, dirty value flag, checkedness, and dirty checkedness flag from the node being cloned to the copy.

Will do! Going to see if there are any WPT for this, otherwise will create a new one in to-upstream.

**Comment by matthewp** [comment]
I think this is the place to put it, but there isn't a test for the input element currently: https://github.com/w3c/web-platform-tests/blob/master/dom/nodes/Node-cloneNode.html

What is the process for upstreaming a test, should I write the test in WPT first and try to get them to accept it, or add it to jsdom first and worry about WPT later?  I don't mind either way, would rather do it the "right way" even if it's a little slower.

**Comment by domenic** [comment]
Either option seems like the "right way" to me :). So whichever you prefer.

Personally, what I would do is put it in jsdom as Node-cloneNode-inputs.html. In general I kind of would prefer things more broken up into multiple files than the existing web platform tests structure, so when I contribute tests I try to keep them more separated. (This is probably just a side effect of jsdom's inability to mark failures on a per-test basis instead of a per-file basis, though.)

**Comment by domenic** [comment]
Fixed by https://github.com/tmpvar/jsdom/pull/1547, yay!
