### ISSUE TITLE
mac fail 

### ISSUE THREAD

**Issue by nousacademy** [tmpvar/jsdom#947]
output: 
    gyp: /Users/nrajlich/node/common.gypi not found (cwd: /Users/alexelkan/NetBeansProjects/myproject/app/node_modules/jsdom/node_modules/contextify) while reading includes of binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:337:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Darwin 13.1.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/alexelkan/NetBeansProjects/myproject/app/node_modules/jsdom/node_modules/contextify
gyp ERR! node -v v0.10.26
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok 
npm http 304 https://registry.npmjs.org/domhandler
npm http 304 https://registry.npmjs.org/domutils
npm http 304 https://registry.npmjs.org/domelementtype
npm ERR! error rolling back Error: ENOTEMPTY, rmdir '/Users/alexelkan/NetBeansProjects/myproject/app/node_modules/jsdom/node_modules/htmlparser2/node_modules/domhandler/test/cases'
npm ERR! error rolling back  jsdom@1.2.1 { [Error: ENOTEMPTY, rmdir '/Users/alexelkan/NetBeansProjects/myproject/app/node_modules/jsdom/node_modules/htmlparser2/node_modules/domhandler/test/cases']
npm ERR! error rolling back   errno: 53,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   path: '/Users/alexelkan/NetBeansProjects/myproject/app/node_modules/jsdom/node_modules/htmlparser2/node_modules/domhandler/test/cases' }
npm ERR! contextify@0.1.9 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the contextify@0.1.9 install script.
npm ERR! This is most likely a problem with the contextify package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls contextify
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 13.1.0
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "jsdom"
npm ERR! cwd /Users/alexelkan/NetBeansProjects/myproject/app/node_modules
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! code ELIFECYCLE
npm ERR! Error: ENOENT, lstat '/Users/alexelkan/NetBeansProjects/myproject/app/node_modules/jsdom/node_modules/htmlparser2/node_modules/readable-stream/lib/_stream_writable.js'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 13.1.0
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "jsdom"
npm ERR! cwd /Users/alexelkan/NetBeansProjects/myproject/app/node_modules
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! path /Users/alexelkan/NetBeansProjects/myproject/app/node_modules/jsdom/node_modules/htmlparser2/node_modules/readable-stream/lib/_stream_writable.js
npm ERR! fstream_path /Users/alexelkan/NetBeansProjects/myproject/app/node_modules/jsdom/node_modules/htmlparser2/node_modules/readable-stream/lib/_stream_writable.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/alexelkan/NetBeansProjects/myproject/app/node_modules/npm-debug.log
npm ERR! not ok code 0

**Comment by domenic** [comment]
Sorry for the lag time. I just noticed you had not updated your version of npm. That is the key ingredient here: you need to have npm 2.5.0.

**Comment by domenic** [comment]
No longer using contextify anyway.
