### ISSUE TITLE
Add support for HTMLElement.dataset

### ISSUE THREAD

**Issue by isakb** [tmpvar/jsdom#961]
Currently it seems like elements returned from document.createElement() do not have any .dataset property, which is unexpected (https://html.spec.whatwg.org/#dom-dataset).

**Comment by ericdum** [comment]
+1

**Comment by cctuan** [comment]
+1

**Comment by RickyChien** [comment]
+1

**Comment by domenic** [comment]
Please see discussion in #963; this is not possible until V8 supports proxies (and not the nonstandard `Proxy.create`, but `new Proxy`).

**Comment by kevinpeno** [comment]
Looks like it's coming! https://twitter.com/s3ththompson/status/687301453761806336

**Comment by rwu823** [comment]
+1

**Comment by ngerritsen** [comment]
+1 Really need this feature

**Comment by JohnMealy23** [comment]
Very surprised this hasn't made it in the spec, yet.

**Comment by artemgurzhii** [comment]
Why [/lib/jsdom/browser/not-implemented.js](https://github.com/tmpvar/jsdom/blob/master/lib/jsdom/browser/not-implemented.js) doesn't throwing error?

**Comment by joetidee** [comment]
For those wanting this, use _element_.setAttribute("data-foo","bar");

**Comment by izhaknys** [comment]
Any updates on this?

**Comment by domenic** [comment]
https://twitter.com/slicknet/status/782274190451671040

**Comment by timwis** [comment]
Boy, I just spent an hour debugging this ghost of an issue whose symptom was that node was running out of memory. Turned out to be caused by using `dataset` instead of `getAttribute`. Perhaps a helper warning in the meantime would save folks from the same experience? :-/

**Comment by idanen** [comment]
@domenic according to [this](http://node.green/), `Proxy` is supported since Node 6.
Do you have some guidelines on how you want to implement this so it'll be easier to contribute?

**Comment by TimothyGu** [comment]
@idanen You will want to first implement the [`DOMStringMap`](https://html.spec.whatwg.org/#domstringmap) interface, which requires changes in [`webidl2js`](https://github.com/jsdom/webidl2js) to support legacy platform objects (as defined in [Web IDL](https://heycam.github.io/webidl/#es-legacy-platform-objects)) through Proxies. The Web IDL spec contains detailed instructions on what each internal method should do exactly.

**Comment by idanen** [comment]
@TimothyGu Something like [dom-token-list](jsdom/lib/jsdom/living/dom-token-list.js) ?

**Comment by TimothyGu** [comment]
@idanen, no that's something entirely different.

**Comment by schreifels** [comment]
We ran into this issue when migrating our test suite to jsdom. If it is helpful, here is the codemod I wrote to convert `dataset` getters and setters to use `getAttribute` and `setAttribute`: https://gist.github.com/schreifels/eb6764b0435d9d830652cee7cb1132c1.
