### ISSUE TITLE
Hiding an element using jQuery does not respect :visible selector 

### ISSUE THREAD

**Issue by jamescookie** [tmpvar/jsdom#982]
I am trying to hide an element using jQuery, and then want to be able to check it is not visible using the ':visible' selector, but it does not see to work. Is this a bug?

Here is my test:

    it('should hide elements', function() {
        document.body.innerHTML = '<div class="one"><div class="inner">hello</div></div>' +
                    '<div class="two"><div class="inner">hello</div></div>';

        $('.one').hide();
        expect($('div.one').css('display')).to.equal('none');
        expect($('div.two').css('display')).to.equal('');
        expect($('div:visible').length).to.equal(2); // fails, reports 4
    });

**Comment by Joris-van-der-Wel** [comment]
jquery uses `offsetWidth` and `offsetHeight` for that. If both of those are 0, an element is `:hidden` and not `:visible`.

So #135 would have to be resolved

**Comment by domenic** [comment]
Rolling into #1048.
