### ISSUE TITLE
Implement charset prescanner

### ISSUE THREAD

**Issue by domenic** [tmpvar/jsdom#986]
See all the fun stuff at https://html.spec.whatwg.org/multipage/syntax.html#the-input-byte-stream

It seems like this is a series of operations on the raw byte stream, and could be done as a separate npm package.

If anyone thinks this would be fun ... all yours!

**Comment by inikulin** [comment]
It require some parser feedback and imho should be done on parse5 level

**Comment by domenic** [comment]
This was actually done by the amazing @nicolashenry in https://github.com/tmpvar/jsdom/commit/8e8f333e2b9bffc45f5f53a156f64d8b60bfe061. There's no way to really trigger it except using `jsdom.env` with a URL (or using XHR) for now, but in newapi when we allow you to pass in a buffer it will become extra-useful.
