### ISSUE TITLE
Support for `event.defaultPrevented`

### ISSUE THREAD

**Issue by jarofghosts** [tmpvar/jsdom#989]
Adding support for [event.defaultPrevented](https://developer.mozilla.org/en-US/docs/Web/API/event.defaultPrevented) would be nice, especially for test cases and such.

Further specification [here](http://www.w3.org/TR/2006/WD-DOM-Level-3-Events-20060413/events.html#Events-Event-defaultPrevented), as linked from MDN. It is simply a boolean property of an event that indicated whether `preventDefault()` has been called on it.

**Comment by brandon-bethke-neudesic** [comment]
Feature is implemented in Pull Request: https://github.com/tmpvar/jsdom/pull/1080
Please code review and merge. Thank you.
