### ISSUE TITLE
Showing element with jQuery does not update display style

### ISSUE THREAD

**Issue by jamescookie** [tmpvar/jsdom#994]
I cannot 'show' an element with jQuery?

    it('should show elements', function() {
        document.body.innerHTML = '<style>.one {display: none;} </style><div class="one"><div class="inner">hello</div></div>';

        expect($('div.one').css('display')).to.equal('none');
        $('.one').show();
        expect($('div.one').css('display')).to.equal('block'); // fails, reports 'none'
    });

**Comment by domenic** [comment]
Wow, nice find @Sebmaster in root-causing the bugs in play here.

I wonder how we can do this. There will presumably be some trickery involved in making cssstyle aware of default style sheets, without having to insert them into the document (which causes observably different results).

See also https://github.com/domenic/html-as-custom-elements/issues/27

**Comment by akhaku** [comment]
Ran into this issue today myself. How about adding a <style> element to the head of the generated document, which has a set of rules that emulate the default style sheet used by common implementations? What do you think?

**Comment by domenic** [comment]
No, that would break any code that looks at e.g. `document.styleSheets[0]` (or `document.styleSheets` in general, really).

Someone needs to test whether default stylesheets affect the results of `getPropertyValue` (in which case we should introduce this into cssstyle) or whether they're handled at a higher level and only show up in `getComputedStyle` (in which case we'll need to handle this in jsdom).

**Comment by akhaku** [comment]
Thanks for clarifying, sorry for my clueless response above. Tried it out in chrome, safari and FF on OSX 
```javascript
var a = document.getElementById('foo')
window.getComputedStyle(a).getPropertyValue('display')
>> "block"
a.style.getPropertyValue('display')
>> null
```
so it looks like it shows up in getComputedStyle. I'll pull down the source and mess around with it for a bit, will send up a pull request if I can get it working. Thanks!
