### ISSUE TITLE
Make Contextify an optional dependency for the io.js

### ISSUE THREAD

**Issue by inikulin** [tmpvar/jsdom#995]
Many people encountering issues with contextify build. In io.js vm module is based on the Contextify (see [changelog](https://github.com/iojs/io.js/blob/v1.x/CHANGELOG.md#vm)). It would be cool to have a Contextify  as an optional dependency for this platform, so jsdom will not have any native dependencies.

**Comment by Sebmaster** [comment]
I already tried to build a [branch](https://github.com/Sebmaster/jsdom/tree/feature/vm) for this some time ago (at the time for node 0.11), however it failed a test which checked the global context as far as I remember.

**Comment by domenic** [comment]
The plan is to finish up some outstanding pull requests, release v3.0 as the last Node.js-compatible version, then work on a v4.0 that is io.js-only and has no contextify dependency.

**Comment by tmpvar** [comment]
@domenic :+1:

**Comment by Joris-van-der-Wel** [comment]
I'm not that up to speed on io.js, but they still call themselves "unstable". Would that not be something to wait for first?

**Comment by domenic** [comment]
Nah.

**Comment by rstacruz** [comment]
Not anymore... io.js 1.1.0 is considered stable.

**Comment by Joris-van-der-Wel** [comment]
I am happy as long as I can install io.js using `apt-get install` ;)

**Comment by domenic** [comment]
Done!
